### ISSUE TITLE
Bug: Reinstalation of any cached archive fails

### ISSUE THREAD

**Issue by marc0der** [sdkman/sdkman-cli#1005]
**Bug report**

Reinstallation of a previously installed version of Java fails. This always occurs when a cached artefact is already found in the `archives` folder.

**To reproduce**

```
❯ sdk install scala 3.1.0

...

❯ sdk rm scala 3.1.0

Deselecting scala 3.1.0...

Uninstalling scala 3.1.0...
 
❯ sdk install scala       

Found a previously downloaded scala 3.1.0 archive. Not downloading it again...
__sdkman_checksum_zip:15: no such file or directory: 

```

**System info**

Manjaro Linux
SDKMAN latest+4bf5b70
zsh 5.8 (x86_64-ubuntu-linux-gnu)

**Comment by MLNW** [comment]
I'm experience the same issue.

**Comment by marc0der** [comment]
@hgeraldino is currently working on this feature, so perhaps he can take a look.

**Comment by hgeraldino** [comment]
Yes, I'll submit a patch to fix this bug shortly...

**Comment by hgeraldino** [comment]
This has been addressed, I'll close this issue.
