### ISSUE TITLE
I am receiving a zip file not found when downloading SDKMAN

### ISSUE THREAD

**Issue by paynet1** [sdkman/sdkman-cli#1006]
To download I type:   curl -s "https://get.sdkman.io" | bash
Getting this error:   "Looking for a previous installation of SDKMAN...
Looking for unzip...
Looking for zip...
Not found.
======================================================================================================
 Please install zip on your system using your favourite package manager.

 Restart after installing zip."

I have downloaded a couple zip programs but nothing works.  Which "zip" program is SDKMAN looking for?

**Comment by helpermethod** [comment]
Hi @paynet1, if you have any more questions feel free to reach out to us on [Slack](https://slack.sdkman.io).
