### ISSUE TITLE
Bug: When 'sdk' is invoked from a non-login shell, it gives 'command not found' error

### ISSUE THREAD

**Issue by Mehdzor** [sdkman/sdkman-cli#1008]
**Bug report**

When `bash -c 'sdk version'` is run it gives 'command not found error'

**To reproduce**

`bash -c 'sdk version'`

**System info**

**Comment by Philzen** [comment]
@Mehdzor @marc0der nevertheless it would be very helpful to know why this is not working and if a recommended workaround is available.

I checked the documentation, but couldn't find anything on this.

**Comment by marc0der** [comment]
Hi @Philzen, the reason is that `sdk` is actually a shell function, not a binary executable. The declaration of that function lives in `sdkman-main.sh`. Hope this helps.
