### ISSUE TITLE
Feature: copy install

### ISSUE THREAD

**Issue by oraluben** [sdkman/sdkman-cli#1010]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**

I would love to have the option to copy the to-be-installed package to a sdkman-managed folder (e.g. just `.sdkman/candidates`).

This feature woule be helpful for someone who is working on a repo that has multiple branches, like me.
I need to build artifacts for each branch and switch between branches (and rebuild) very often, and I would need to install the artifact somewhere outside the repo. sdkman will not only help me to manage those installations but also get rid of `make install` if there's something like `sdk install --copy`.

**Risk**
There's some package that relies on their installed prefix, e.g. cpython, so this feature won't work for all packages.

**Comment by marc0der** [comment]
Hi @oraluben. I'm not sure I entirely understand your request. Could you give us some more examples of what you mean? What repo are you referring to, and what kind of artefacts do you mean to copy/install?

But then again, perhaps I misunderstood what you asked of us. Perhaps it's worth clarifying the sole purpose of SDKMAN: it is an SDK manager, i.e. it helps you install SDKs on your machine in the most frictionless way possible. 

Unless your repo is building an SDK archive for distribution, I don't think we are the best fit to copy or install your build artefacts. Feel free to drop in on our Slack to discuss this further if you like.

**Comment by oraluben** [comment]
Thanks for your reply! I just found a solution for my case and want to elaborate more before closing this issue, just for a record.

I'm working on GraalVM with various branches of OpenJDK. Basically, I need to checkout branches and rebuild OpenJDK, which will overwrite previous artifacts. Furthermore, GraalVM depends on a non-default make target that is out of the scope of `make install`, so I cannot install them in different locations.
What I was thinking is SDKMAN could do the copying and I can use a `make <target> && sdkman install --copy <artifact>`.
Finally, it turns out that OpenJDK already has a mechanism for this situation. There's a `CONF` environment variable that can help you not overwrite artifacts from different branches.

**Comment by marc0der** [comment]
That's great news, thanks for the explanation @oraluben. I'm glad that you found an easy solution that works for you.
