### ISSUE TITLE
Pointing SDKMan to Existing Installed Java Version

### ISSUE THREAD

**Issue by lalik77** [sdkman/sdkman-cli#1016]
Hello everybody , can someone help me with this , before installing SDKMAN, i had my local version of JDK . After installing SDKMAN , when i wanted to point sdkman to my local Java version , information from this [article](https://dzone.com/articles/how-to-install-multiple-versions-of-java-on-the-sa)
====>

`$ ln -s /Library/Java/JavaVirtualMachines/<java-folder> ~/.sdkman/candidates/java/<java-folder>`

`$ sudo ln -s /Library/Java/JavaVirtualMachines/<java-folder>/Contents/Home/bin ~/.sdkman/candidates/java/<java-folder>/bin`

then the command on second line give me an error
-> `ln: /Users/username/.sdkman/candidates/java/jdk1.8.0_271.jdk/bin: No such file or directory`

sdk list java give me the next -> at the bottom i have my local version

<img width="989" alt="141976418-b676093b-133f-4605-8a99-b40706a379f4" src="https://user-images.githubusercontent.com/45859153/142207333-a38f9a16-3284-44c9-9c94-eb15993ca260.png">

After that i tell to sdk to use my local version.
<img width="1104" alt="141976658-16805df1-639a-4e5d-b05a-f178a4013943" src="https://user-images.githubusercontent.com/45859153/142207492-859fcf14-140f-44fd-a5c5-17c011f76c38.png">

What i am doing wrong ?
When a switch back to java installed with sdkman in my case "java versio 16..." , all seems be ok .

<img width="1131" alt="141977796-3d360a3d-bcdb-4482-a5f8-309b117658bd" src="https://user-images.githubusercontent.com/45859153/142207621-f05e1281-144d-4a55-8175-2d94ab347c10.png">

How finally point SDK MAN to my local version of JAVA ?

Thank YOU

**Comment by marc0der** [comment]
Hi @lalik77, you can install local versions by following [these instructions](https://sdkman.io/usage#localversion) on our website.

**Comment by lalik77** [comment]
Thank u @marc0der . 
I have tried but i have still some troubles , when a say to sdk to use my local version , it doesn't accept .
When i try to install it again , it says that it's already installed .


<img width="888" alt="Снимок экрана 2021-11-18 в 1 14 26" src="https://user-images.githubusercontent.com/45859153/142291476-be1ac70e-72a7-465d-89d9-0e82bdf03b24.png">

maybe i have to uninstall sdk and install it again ?

**Comment by mattwelke** [comment]
Local install instructions worked well for me.

I found a build on https://jdk.java.net/loom/ that I was interested in. I ran the following commands:

```
wget https://download.java.net/java/early_access/loom/7/openjdk-18-loom+7-288_linux-x64_bin.tar.gz
tar -xf openjdk-18-loom+7-288_linux-x64_bin.tar.gz
mv jdk-18/ 18-loom
sdk install java 18-loom $(realpath 18-loom/)
sdk default 18-loom
```

And it appears I have a JDK I can use just like the other ones I installed using the normal way where you install one from the list:

```
~/javas > which java
/home/matt/.sdkman/candidates/java/current/bin/java
~/javas > java --version
openjdk 18-loom 2022-03-15
OpenJDK Runtime Environment (build 18-loom+7-288)
OpenJDK 64-Bit Server VM (build 18-loom+7-288, mixed mode, sharing)
```

**Comment by gadget78** [comment]
thankyou for this step by step ! .. 
i needed java version 16, for a maven build ...
used steps and links above to download, unpack, install local version... 

oddly under `sudo mvn clean install` it used the older version, but if i used just `mvn clean install` it did then use the v16 from sdk install ??

**Comment by mattwelke** [comment]
@gadget78 If I recall, `sudo` will execute a command in a different way, which can involve it using a completely different binary. For a long time now, I've just avoided using `sudo` in general when doing software development. Basically, I keep all my tools and dependencies scoped to my Linux user account. I've been doing it that way with Ruby (using rbenv), Node.js (using n), Python (using pyenv), and Java (using SDKMAN!).

**Comment by eddumelendez** [comment]
Closing due to original question was already answered. Feel free to open a new issue if there is any issue.
