### ISSUE TITLE
Question: [Short summary]

### ISSUE THREAD

**Issue by aluedt** [sdkman/sdkman-cli#1017]
**Question**
With a JDK installed using sdkman on Mac, when I right-click on an executable jar file and choose to open it with the "Java Launcher" it results in an error "Unable to locate a Java Runtime". Is there any workaround?

**System info**
Mac OS Big Sur 11.6.1 (20G224)

**Comment by marc0der** [comment]
SDKMAN is a command line tool. Please refer to our website [usage page](https://sdkman.io/usage) for instructions.
