### ISSUE TITLE
Feature: suggest installed candidates when you type 'sdk use' pointing to a non-existing candidate

### ISSUE THREAD

**Issue by nicoloboschi** [sdkman/sdkman-cli#1021]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
When you use multiple candidates for different projects, you use `sdk use [candidate] [version]` for switching context.

I usually type a wrong version and then I need to run `sdk list [candidate]` in order to get the right version. It seems stupid but having a listing of already installed identifiers in the output command would be very useful for me.

For example:

Current:
```
user@mac % sdk use java 17.0.1

Stop! Candidate version is not installed.
```

Suggested output:
```
user@mac % sdk use java 17.0.1

Stop! Candidate version is not installed. Maybe you meant one of the followings: [... listing installed 
identifiers]
```

**Comment by marc0der** [comment]
That would be good, but in the meanwhile, why not use tab completion for everything. It works for all the subcommands and their associated parameters. It also works for bash and ZSH.

Give this a try:
```
sdk u[TAB] j[TAB] 17[TAB]
```

**Comment by helpermethod** [comment]
If it's not enabled, type `sdk config` and set the `sdkman_auto_complete` to `true` to enable tab completion.

**Comment by nicoloboschi** [comment]
great, it works well with zsh, I haven't thought about using tab completion. Thank you

I'll let you decide to close or not this issue
