### ISSUE TITLE
Feature: Support for customized JDKs

### ISSUE THREAD

**Issue by rcsilva83** [sdkman/sdkman-cli#1024]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
In my organization, we have an internal Maven repository which runs under HTTPS and the certificate used is emitted by our internal CA. For that reason, on all our JDK installations we need to add the Root CA certificate to the truststore, so Maven is able to connect to the repository.

So we need support for downloading customized JDKs from an internal repository or support for a "post installation script" to execute the `keytool -import` command against each JDK installation.

**Comment by marc0der** [comment]
Hi @rcsilva83, this sort of setup is only possible if you have a dedicated cloud installation or your own on-prem installation of SDKMAN. The cloud hosted installation that you are currently using only supports the standard JDKs.

Provisioning one of the above options is certainly possible. Please feel free to contact me directly on Slack if this is of interest to you.

**Comment by rcsilva83** [comment]
Hi @marc0der, thanks for your answer!

As SDKMAN is a CLI, what do you mean by "a dedicated cloud installation"? And by "your own on-prem installation of SDKMAN" do you mean a custom version of SDKMAN?

**Comment by marc0der** [comment]
SDKMAN is client-server software. The bash CLI is but the tip of the iceberg. Most of the heavy lifting happens on the serverside. Your CLI interacts with upto 5 microservices backed by MongoDB. Hope it makes more sense now 😄

**Comment by rcsilva83** [comment]
Oh, it makes much more sense! Sorry for the newbie question. I'll contact you on Slack. Thank you very much.
