### ISSUE TITLE
Feature: Show the detected platform in the CLI tool

### ISSUE THREAD

**Issue by FDelporte** [sdkman/sdkman-cli#1028]
**Feature request**
It would be great to show the detected platform in SDK. That would make it easy to detect why for instance currently no Java versions are listed on Raspberry Pi 32bit versions as discussed on https://github.com/sdkman/sdkman-cli/issues/836

Or when the "list" command has no results, show a message e.g. `SDKMAN has no Java versions listed for platform 'LinuxARM32SF'.`

**Comment by marc0der** [comment]
Awesome ideas! 😎

**Comment by marc0der** [comment]
I've rolled something out for the Java list view, mind giving that a try @FDelporte?

**Comment by tonygermano** [comment]
@marc0der Looks good to me. I actually just pieced together some api query strings because I wanted to see which java candidates were available for x86-64 and arm64 macos, but I am running sdkman from Ubuntu. I saw that it had the architecture at the top before I even noticed this issue and assumed it was always there :smiley:

**Comment by tonygermano** [comment]
When I did try to use an unsupported architecture (I used `macos` before I knew to use `DarwinX64`) It just says the following with no indication of arch type
> Available Java Versions for Universal
> ---------------------------------------------
> No versions available for your platform at this time.

**Comment by marc0der** [comment]
@tonygermano yeah, the API isn't really intended to be used in that way.

If you use macOS arm64, you can use the Rosetta 2 compatibility mode if you aren't happy with the amount of available JDKs. Otherwise you can just go with what's there as the list will certainly grow over time.

**Comment by marc0der** [comment]
@FDelporte I'm closing this feature request for now as I believe it is working. Please let me know if you had anything else in mind.

**Comment by FDelporte** [comment]
thanks @marc0der ! will check asap, have to catch up after a short holiday break ;-)

**Comment by FDelporte** [comment]
asap being now ;-)

pi@crowpi:~ $ uname -a
Linux crowpi 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux
pi@crowpi:~ $ sdk version
SDKMAN 5.13.1

Shows indeed a message that no versions are available, would be great to see the detected platform, but can understand if that's more difficult to implement

```
================================================================================
Available Java Versions for Universal
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
No versions available for your platform at this time.
================================================================================

```

**Comment by marc0der** [comment]
@FDelporte This will appear instead of `Universal` in the header as soon as the new backend changes are deployed. You should be seeing something along the lines of `Linux ARM 32bit Soft Float`. Let's verify this when all the changes are deployed.
