### ISSUE TITLE
Bug: command not found post installation hook for ARM 32Bit Soft (and Hard) Float

### ISSUE THREAD

**Issue by retrodaredevil** [sdkman/sdkman-cli#1030]
**Bug report**
I believe this bug was introduced with one of the changes from #836. I'm making a separate issue because I think that issue can be used to talk about the correct versions that need to show up and this can be used to talk about the command not found error.

This bug is also the same as #593, but that looks like an old bug, so I'm making a new one.

The bug report and reproduction can be shown in one block of text:

```
joshua@batterypi:~ $ sdk list java | cat
================================================================================
Available Java Versions for Linux ARM 32bit Hard Float
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
 Zulu          |     | 11.0.13      | zulu    |            | 11.0.13-zulu        
               |     | 8.0.312      | zulu    |            | 8.0.312-zulu        
================================================================================
Omit Identifier to install default version 17.0.1-tem:
    $ sdk install java
Use TAB completion to discover available versions
    $ sdk install java [TAB]
Or install a specific version by Identifier:
    $ sdk install java 17.0.1-tem
Hit Q to exit this list view
================================================================================
joshua@batterypi:~ $ sdk install java 11.0.13-zulu

Downloading: java 11.0.13-zulu

In progress...

########################################################################################################################## 100.0%
-bash: __sdkman_post_installation_hook: command not found
joshua@batterypi:~ $ sdk version

SDKMAN 5.13.1
joshua@batterypi:~ $ uname -a
Linux batterypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
joshua@batterypi:~ $
```

**To reproduce**
Run an install command for java as shown above on a system that has ARM 32Bit Soft Float.

**System info**
I reproduced on RPi0, RPi1, RPi3.

It's worth noting that this error did not occur on my 64Bit system that I use regularly. It too is running 5.13.1.

**Comment by eddumelendez** [comment]
I think this is related to [this](https://github.com/sdkman/sdkman-hooks/blob/80fd5e199d0a13373bce729aed03a08d9db0fbec/app/domain/domain.scala#L31)

I have created https://github.com/sdkman/sdkman-hooks/pull/41

**Comment by retrodaredevil** [comment]
I'll go ahead and close this then. Feel free to reopen if this issue can be useful.

**Comment by marc0der** [comment]
@retrodaredevil I've merged @eddumelendez's fix, would you mind testing it now?
