### ISSUE TITLE
How do I determine if it is a vendored release and where to report issues?

### ISSUE THREAD

**Issue by sdavids** [sdkman/sdkman-cli#1034]
I had the following issue:

```
$ sdk install tomcat 8.5.73

Downloading: tomcat 8.5.73

In progress…

#### 100.0%

Installing: tomcat 8.5.73
Done installing!


Setting tomcat 8.5.73 as default.
$ find $SDKMAN_DIR/candidates/tomcat/8.5.73/bin/*.sh | xargs stat -f '%Lp %N'
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/catalina.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/ciphers.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/configtest.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/daemon.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/digest.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/setclasspath.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/shutdown.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/startup.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/tool-wrapper.sh
644 /Users/dev/Library/sdkman/candidates/tomcat/8.5.73/bin/version.sh
```

Notice the permissions are wrong: `644` instead of `744` or `755` (depending on if the umask is taken into account or not). -- *Note*: This is not what this issue is about!

I was unsure where to report an issue:

- https://github.com/sdkman/sdkman-cli
  did not seem right if it was a vendored release
- https://github.com/sdkman/vendor-release 
  does not seem right either
- https://sdkman.io/vendors
   does not state how to report issues with vendored releases
- https://github.com/apache/tomcat
  I am not sure if they have been ones doing the vendoring 
- `$ sdk list`
   does not state whether it is vendored or not, neither where to report issues

**Comment by hgeraldino** [comment]
This seems related to https://github.com/sdkman/sdkman-cli/issues/974

BTW, artifacts for all candidates/versions are hosted by their vendors (Apache in this particular case)

**Comment by marc0der** [comment]
@sdavids, that's right, just as @hgeraldino says. These binaries are downloaded directly from Apache archives, and we redirect curl to their download location. 

The problem has been reported numerous times before and should be reported directly to the Tomcat team. Hopefully, if enough people complain about this, they will do something about it. Feel free to mention me on the issue if you report this on Github.

I'll close this issue for now. In future, please follow the contributor guidelines and use the provided template.

**Comment by sdavids** [comment]
> Notice the permissions are wrong: `644` instead of `744` or `755` (depending on if the umask is taken into account or not). -- _Note_: This is not what this issue is about!
> 
> `$ sdk list`
>   does not state whether it is vendored or not, neither where to report issues

Why is this issue being closed?

This issue is about improving `sdk list` or having something like `sdk describe`.

The output would at least state that this is a vendored release.

Ideally it would state where it has been vendored from and/or a link to their homepage/GitHub/GitLab page.

**Comment by marc0der** [comment]
@sdavids please read the [contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/77fe23a758bfcc01fc8b06547e6e95e4a9ff1ea6/CONTRIBUTING.md) which will tell you all you need to know about the process we follow. This process was put in place to help us triage real issues and feature requests, which means we have to spend less time working through a stack of GH issues over weekends. Hope that makes more sense now.

**Comment by sdavids** [comment]
I have updated the title and added the 
```
- [ ] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
```

In front of my existing text.

This is according to your template:

```
<!-- Thank you for suggesting a new feature. Please consider discussing your idea in our Slack channel before requesting a new feature. -->

- [ ] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
<!-- A clear and precise description of what new or changed feature you want. Please include the reason, why you would need the feature. E.g. what problem does it solve? Or which workflow is currently frustrating and will be improved by this? -->
```

I hope you are happy now.

Thank you for considering my request.

**Comment by marc0der** [comment]
@sdavids my intention is not to sound rude, and sorry if I came across abrupt in any way. 

The problem here is that I see no distinct feature request, just an observation, question, and a dump about some permissions issues.

In order to formulate a proper feature request, let's discuss it on Slack (as per our guidelines) so we can help distil this into something concrete and deliverable.

**Comment by sdavids** [comment]
I understand your sentiment but please update your template(s) if it is required:

> In particular, we require a conversation to happen on our community Slack before opening GH issues here.
> 
> ```
> 
> ```

"Please consider" ... is different from ... "we require"

But no point in arguing, `sdkman` is a useful tool.

Opinions differ.

Communication is hard.

**Comment by marc0der** [comment]
Indeed, very hard :smile: 

Point taken and I've updated the feature request template as per your suggestion.
