### ISSUE TITLE
Feature: support ki: The Next Interactive Shell for Kotlin

### ISSUE THREAD

**Issue by benjishults** [sdkman/sdkman-cli#1035]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**

Please consider including ki: The Next Interactive Shell for Kotlin.

https://blog.jetbrains.com/kotlin/2021/04/ki-the-next-interactive-shell-for-kotlin/

**Comment by helpermethod** [comment]
`ki` is supported for quite a while now. Closing the issue.
