### ISSUE TITLE
Bug: `___sdkman_check_version_cache()` should not be called if `$SDKMAN_OFFLINE_MODE` is "true"`

### ISSUE THREAD

**Issue by JohanLorenzo** [sdkman/sdkman-cli#1043]
Thank you for creating and maintaining sdkman! We at https://github.com/maltcommunity use it to control/update which JDK and maven version we run. It's super handy! 

**Bug report**
`___sdkman_check_version_cache()` should not be called if `$SDKMAN_OFFLINE_MODE` is `"true"`

**To reproduce**

1. On a docker image with `sdkman` installed but not `curl`, `source ~/.bashrc` to let sdkman be initialized.
2. Wait 24 hours after the image got built.

Results:

```sh
+++ __sdkman_echo_debug 'Version cache needs updating...'
+++ [[ false == \t\r\u\e ]]
+++ [[ false == \t\r\u\e ]]
+++ __sdkman_echo_debug 'Refreshing version cache with STABLE version.'
+++ [[ false == \t\r\u\e ]]
+++ version_url=https://api.sdkman.io/2/broker/download/sdkman/version/stable
++++ __sdkman_secure_curl_with_timeouts https://api.sdkman.io/2/broker/download/sdkman/version/stable
++++ [[ false == \t\r\u\e ]]
++++ curl --silent --location --connect-timeout 7 --max-time 10 https://api.sdkman.io/2/broker/download/sdkman/version/stable
~/sdkman/src/sdkman-utils.sh: line 64: curl: command not found
```

More verbose logs: [sdkman.log](https://github.com/sdkman/sdkman-cli/files/7988170/sdkman.log)

**System info**

The docker image is used within a CI pipeline. It's based on debian (testing) and sdkman is installed regularly (`curl` is indeed present in the image at this time). While the docker image is built, we use sdkman to install precise maven and JDK versions. Thus, for the sake of reproducibility, we put sdkman in offline mode afterwards. We also strip unneeded binaries (like `curl`) off the image. That's how we ended up noticing this bug. 

OS:  Debian testing
```sh
bash --version
GNU bash, version 5.1.12(1)-release (x86_64-pc-linux-gnu)
```
```sh
sdk version
bash: curl: command not found

SDKMAN 5.13.1
```

I'm happy to provide any further details 🙂 

**Potential fix**

I believe this call[1] should be conditioned by the state of `$SDKMAN_OFFLINE_MODE`

[1] https://github.com/sdkman/sdkman-cli/blob/f7ffc9c2e63821942549074b6ee580e82a737a4e/src/main/bash/sdkman-main.sh#L82

**Comment by marc0der** [comment]
Hi @JohanLorenzo, very glad to hear that you find our tool useful!

Sorry that it's not working for you in the way you expected. However, SDKMAN can't be installed without curl. We actually enforce that it is present on installation; if not present, we abort the installation process. Since curl is core to just about everything SDKMAN does, it's a mandatory dependency, as are zip and unzip (and tar for Java).

Another point is that the offline mode is horribly broken, and is actually slated for complete removal. So even if you are using this to work around your current hack, it will disappear in the near future.

My recommendation for you would be to use a base docker image that has all the prerequisites for SDKMAN installed. That way you won't have to do any hacks to make things work in your environment.

Hoping this helps some!

**Comment by JohanLorenzo** [comment]
Thank you very much for your thorough answer @marc0der! I understand the rationale. Removing the offline mode makes sense to me, then 🙂 I'm closing this issue since it's not something worth fixing. 

Just before we end this conversation, I have a question. For our specific use case, it seems the best option is to: 

1. Install `sdkman` with all its dependencies (like `curl`)
2. Install the target JDK and maven versions
3. Purge any existing cache (to keep the Docker image as light as possible)
4. Uninstall `sdkman` alongside its dependencies
5. Make the installed JDK/maven binaries available in `$PATH`

Do you think I might be missing a step? I'd be happy to write some documentation in case someone has a similar use case (once I validate it works, of course 🙂).

**Comment by marc0der** [comment]
Once again, two options here for me:
* I would have a separate build for the Docker image, and it would contain any tools that I need to get the work done (in your case curl, zip, unzip, tar, gzip). I would publish that image to a Docker registry. I would then use that image in any builds that require Java/Maven.
* An even better option, why not just use the [Adoptium Docker images](https://hub.docker.com/_/adoptopenjdk) that already have the latest Java installed? That would mean that you could always use their latest Java, and only need to install Maven in your container as part of your build.

Option two would be how I would approach it and would result in the following workflow:
1. Run your build with the [Maven Wrapper](https://maven.apache.org/wrapper/)(!)

No need for installing SDKMAN, Java or Maven!

**Comment by JohanLorenzo** [comment]
Sounds good. Thank you for the pointers!
