### ISSUE TITLE
Bug: GNOME 3 on Linux: screen locking seems to freeze downloads.

### ISSUE THREAD

**Issue by ascopes** [sdkman/sdkman-cli#1049]
**Bug report**

Running under Linux with a fresh install of SDKMAN, if something is installing (in my case Maven), when GNOME 3 locks the screen due to inactivity, it appears to cause the transfer to freeze.

Not sure if this is a red herring, but I have been able to replicate this three times in a row now on the same device. Preventing the screen locking seems to prevent the issue from occurring.

Killing the job with CTRL-C then reports that the archive is corrupt and I have to purge the install to try again.

**To reproduce**

1. Start a download for Maven
2. Let the system lock the screen through inactivity while the download runs.
3. Unlock the screen.
4. The download has frozen.

**System info**

```console
[ashley@dell ~]$ sdk v
SDKMAN 5.13.1

[ashley@dell ~]$ uname -a
Linux dell 5.16.7-200.fc35.x86_64 #1 SMP PREEMPT Sun Feb 6 19:53:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[ashley@dell ~]$ cat /etc/*release
Fedora release 35 (Thirty Five)
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 35 (Thirty Five)
Fedora release 35 (Thirty Five)

[ashley@dell ~]$ ${SHELL} --version
GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by marc0der** [comment]
Hi @ascopes,

This sounds like a problem with Fedora. I use Arch Linux and have never had such an issue. Also, keep in mind that we are simply using curl for file transfers, nothing fancy.

It would be interesting to see the result if you repeat the procedure using curl directly to download a large file.

**Comment by ascopes** [comment]
Hmm, I don't seem to be able to replicate it with cURL directly.

Perhaps it was a red herring and something else was causing the connection to hang at the same time, by coincidence.

Will close for now and reopen if I can get any further with working this out.

Thanks!
