### ISSUE TITLE
Bug: sdk upgrade offers to install an older java version as the one installed

### ISSUE THREAD

**Issue by martinborgman** [sdkman/sdkman-cli#1053]
**Bug report**

I have java 17.0.2-tem installed and it is the current and the default jdk, but if I do a `sdk upgrade java`, sdkman offers to install java 17.0.1-tem.

**To reproduce**

```
$ sdk upgrade

Available defaults:
java (local: 17.0.2-tem; default: 17.0.1-tem)

Use prescribed default version(s)? (Y/n):
```
**System info**

- MacOS 11.6.4
- zsh 5.8 (x86_64-apple-darwin20.0)
- SDKMAN 5.13.1

**Comment by marc0der** [comment]
@martinborgman Thanks for reporting this. This isn't as much a bug as it is a mere data issue. I've updated this in our database, so now everything should be fine.

@eddumelendez Just wondering, but is there something we can put in place to ensure that the default Java version is updated in the future?

**Comment by martinborgman** [comment]
@eddumelendez I think this question is related to issue #1014.

I think that changing the java group into java-<dist> groups is a fairly simple solution and it would allow users to have several different distributions installed and be updated separately. The question then becomes do we still allow `sdk list java` to list all java distributions?

**Comment by eddumelendez** [comment]
@marc0der I would see if I can done something on the current implementation. Otherwise, I can take it into account for the new implementation

**Comment by marc0der** [comment]
@martinborgman this problem will be addressed in a new feature called _version pinning_. Here you will be able to pin a version series, or series and vendor distribution.

Of course, this is not related to the data issue you reported here so closing this for now.
