### ISSUE TITLE
install script

### ISSUE THREAD

**Issue by tonycody** [sdkman/sdkman-cli#1056]
https://get.sdkman.io/

Where is this script?

<img width="724" alt="image" src="https://user-images.githubusercontent.com/6773121/156149348-e627fc86-9e2b-490b-bee9-0d7b4835e6a5.png">

Would you consider executing this command for the user after installation?
The user installation to use always need to execute this command, why not help the user to do this after the installation?

**Comment by marc0der** [comment]
@tonycody Unfortunately it isn't possible to source this as it runs in a subshell.

Let's use Slack as suggested in the [contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/65ee538d57f227577e16fe698be98d004669f7ea/CONTRIBUTING.md) for such discussions/questions in the future. You can drop a message in the #cli-developement channel.
