### ISSUE TITLE
Feature: [How to configure sdkman to mirror Web sites around the world?]

### ISSUE THREAD

**Issue by qwfys** [sdkman/sdkman-cli#1059]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] #1060

**Feature request**

After using the sdk, I feel that the sdk is very good, but sometimes the network is not very powerful. If the web mirror site of the sdk can be configured, this problem should be better solved. So, I just want to know, how to build and configure a Web mirror site?

**Comment by marc0der** [comment]
Hi @qwfys, we do not employ mirror sites in SDKMAN and will always redirect you to the origin of the binary. If you are experiencing download issues, it will be due to connectivity to those origin sites.
