### ISSUE TITLE
Question: Install x86 JDK on M1 Mac

### ISSUE THREAD

**Issue by IljaR** [sdkman/sdkman-cli#1068]
Hi all,

for a specific project I need an x86 JDK (version 11 or 13 prefered) installed on my M1 MacBookPro. More precisely I need nd4j and javacpp which are not available for Arm64 yet and maven tries to retrieve macosx-arm64 versions that are not available.

I tried the sdkman_rosetta2_compatible switch as described here (https://itnext.io/how-to-install-x86-and-arm-jdks-on-the-mac-m1-apple-silicon-using-sdkman-872a5adc050d) but the list of available java versions is the same with switch set to true and false.

Is there a x86 version? It does not show in list. And it not how can I find a x86 version to be installed via sdkman.

cheers and best
Ilja

**Comment by PaulLiang1** [comment]
this should work

```
❯ sdk install java 17.0.3.fx-zulu
java 17.0.3.fx-zulu is already installed.

❯ cat `which java` | file -
/dev/stdin: Mach-O 64-bit executable x86_64
```

**Comment by hpopov** [comment]
> Hi all,
> 
> for a specific project I need an x86 JDK (version 11 or 13 prefered) installed on my M1 MacBookPro. More precisely I need nd4j and javacpp which are not available for Arm64 yet and maven tries to retrieve macosx-arm64 versions that are not available.
> 
> I tried the sdkman_rosetta2_compatible switch as described here (https://itnext.io/how-to-install-x86-and-arm-jdks-on-the-mac-m1-apple-silicon-using-sdkman-872a5adc050d) but the list of available java versions is the same with switch set to true and false.
> 
> Is there a x86 version? It does not show in list. And it not how can I find a x86 version to be installed via sdkman.
> 
> cheers and best Ilja

Hello, Ilja
I has been following the same article. The reason it may not be working for you is that when SDKman! is installed locally, it stores its configuration in the user folder, starting at ~/
So try to edit the same property using `sdk config` command (for me it opens vim editor with actual settings loaded from user home directory (i.e. ~/.sdkman/...)

**Comment by eddumelendez** [comment]
Do you open your terminal with rosetta compatibility? You should be able to download from it. I had the same case and use to download using it like that

**Comment by eddumelendez** [comment]
Closing because the last comment mentions how to proceed in this case.
