### ISSUE TITLE
Bug: Conflict with hstr application when set sdkman_auto_env=true

### ISSUE THREAD

**Issue by speedlog** [sdkman/sdkman-cli#1087]
**Bug report**
When i have installed hstr (https://github.com/dvorka/hstr) and sdkman with sdkman_auto_env=true

Every command i get message "bash: PROMPT_COMMAND: line X: `history -a; history -n; ;sdkman_auto_env'"

```
hstr version "2.3.0" (2020-11-19T07:41:00)

bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 0: `history -a; history -n; ;sdkman_auto_env'

user:~/Downloads/test-sdk-env/car-app$ java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
bash: PROMPT_COMMAND: line 1: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 1: `history -a; history -n; ;sdkman_auto_env'

user:~/Downloads/test-sdk-env/car-app$ cd ..
bash: PROMPT_COMMAND: line 2: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 2: `history -a; history -n; ;sdkman_auto_env'
```

There is a resolution.
Despite of warning comment ("THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!") i need to set hstr fragment in `.bashrc` after sdkman fragment.
Something like that:

```
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/user/.sdkman"
[[ -s "/home/user/.sdkman/bin/sdkman-init.sh" ]] && source "/home/user/.sdkman/bin/sdkman-init.sh"

# HSTR configuration - add this to ~/.bashrc
alias hh=hstr                    # hh to be alias for hstr
export HSTR_CONFIG=hicolor       # get more colors
shopt -s histappend              # append new history items to .bash_history
export HISTCONTROL=ignorespace   # leading space hides commands from history
export HISTFILESIZE=10000        # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
# ensure synchronization between bash memory and history file
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
# if this is interactive shell, then bind hstr to Ctrl-r (for Vi mode check doc)
if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hstr -- \C-j"'; fi
# if this is interactive shell, then bind 'kill last command' to Ctrl-x k
if [[ $- =~ .*i.* ]]; then bind '"\C-xk": "\C-a hstr -k \C-j"'; fi
```

**To reproduce**
1. Install https://github.com/dvorka/hstr
2. Add config for hstr `hstr --show-configuration >> ~/.bashrc`
3. Install sdkman
4. Set sdkman_auto_env=true

**System info**

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

SDKMAN 5.15.0

hstr version "2.3.0" (2020-11-19T07:41:00)

**Comment by marc0der** [comment]
Hi @speedlog, I don't think this is a bug but rather an incompatibility between the two tools. Not sure if there is much we can do about this.

**Comment by speedlog** [comment]
I agree, but maybe warning comment "THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!" is unnecessary?
When i changed order in .bashrc sdkman still works :)

**Comment by marc0der** [comment]
For the vast majority of our users, this statement is true and important. I don't think I want to change it any time soon.

**Comment by speedlog** [comment]
Thanks for explanation. I tried to figure out why SDKMAN should be in the end of file.

I dig a little and found cause of this problem.
It's more general than conflict with hstr.
When i would have an environment variable PROMPT_COMMAND that ends with ";"  the problem will occur.

hstr add `export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"`
it effectivly means `export PROMPT_COMMAND="history -a; history -n; "`, because my env `PROMPT_COMMAND` is empty.

I will try to propose a change to SDKMAN in a while.

**Comment by helpermethod** [comment]
Hi@speedlog!

Why do you add a space before `${PROMPT_COMMAND}`?

```
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
```

SDKMAN! assumes that the existing PROMPT_COMMAND ends on a `;`, in which case it's stripped away, or a command (w/o space).

I guess SDKMAN! could also strip trailing whitespace before, but I'd rather not add two much special casing for handling `PROMPT_COMMAND`, which is a hack anyway (zsh doesn't have all those problems).

**Comment by speedlog** [comment]
@helpermethod 
This fragment with space after semicolon is from hstr application.

I have not noticed there is solution removing double semicolon. So the problem is just space at the end.
I've changed my commit and trim PROMPT_COMMAND

**Comment by marc0der** [comment]
@speedlog That is now available for testing in the beta channel. Could you please confirm that it works for you?

**Comment by speedlog** [comment]
@marc0der SDKMAN latest+0906561 works perfectly :-)
I've also tried manual change in sdkman-init.sh before my commit.

**Comment by helpermethod** [comment]
@speedlog Thanks for bringing the issue up and providing a PR!
