### ISSUE TITLE
Feature: Corretto JDK 11 for M1 Mac

### ISSUE THREAD

**Issue by charlie-harvey** [sdkman/sdkman-cli#1090]
Most of the JDK Vendors were waiting on OpenJDK to publish the backport of JDK 11 for M1 Mac. They have finally done so and the others have followed.

Amazon has theirs as GA. Not having a hard time finding the links for the others.

https://github.com/corretto/corretto-11/releases/tag/11.0.15.9.1

**Comment by eddumelendez** [comment]
it has been available for some weeks already.
