### ISSUE TITLE
now the sdkman-cli command execution is 504 bad gateway

### ISSUE THREAD

**Issue by RealForce1024** [sdkman/sdkman-cli#1094]
**Bug report**

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.1</center>
</body>
</html>

```
(END)

**To reproduce**

1. $~: sdk list java
2. $~:  the shell returns
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.1</center>
</body>
</html>
(END)
```

**System info**
mac studio m1 ultra(2022) and macbook pro(2018)

**Comment by VladislavFetisov** [comment]
Do you also cant successfully execute any command in sdkman-cli? I have same problem right now

**Comment by RealForce1024** [comment]
> Do you also cant successfully execute any command in sdkman-cli? I have same problem right now

Yes, It return the nginx error code 504 bad gateway!

**Comment by VladislavFetisov** [comment]
Thank you, because i thought that is problem on my side
