### ISSUE TITLE
Feature: Provide a way to switch to the default version of an SDK

### ISSUE THREAD

**Issue by donalmurtagh** [sdkman/sdkman-cli#1099]
- [X] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] I've had a conversation on the [#cli-development](https://sdkman.slack.com/app_redirect?channel=cli-development) Slack channel about this request.

**Feature request**

I'm trying to write a script which uses sdkman to switch to a specific version of java, then switches back to the user's default version, but it doesn't seem there's any way to accomplish the latter. One possible solution is to extend the `sdk u` command such that if a version isn't provided, the default version is used, e.g. `sdk u java` would switch to the default java version.

**Comment by xtovski** [comment]
Do you mean "current" version by default version?

**Comment by helpermethod** [comment]
Hi @donalmurtagh,

you can do something like that using `sdk env`.

Add an `.sdkmanrc` where you put your in your SDK version of choice, e.g.  `java=22.2.r17-grl`.
Then type `sdk config` to open SDKMAN!'s config and set `sdkman_auto_env=true`.

Now, whenever you enter the directory, SDKMAN! automatically switched to the version set in the `.sdkmanrc` file, and switches back to the default as soon as you exit that directory. Works both for Bash and zsh.

**Comment by helpermethod** [comment]
Closing this one as there has been no more feedback.
