### ISSUE TITLE
Bug: INTERNET NOT REACHABLE! when I connected to internet using by WIFI Direct Hotspot.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [sdkman/sdkman-cli#1100]
**Bug report**

[PdaNet+](http://pdanet.co/install/)
[NetShare](https://netshare.app/)
I've tested those two apps.
I can use internet but sdkman says `INTERNET NOT REACHABLE`.

**To reproduce**

1. install required apps on your phone(Android).
2. open app, turn on `WIFI Direct Hotspot` from your phone.
3. connect to this wifi from mac.
4. use sdk command that needs internet connection like `sdk list java`.

**System info**
 macOS Monterey 12.4
zsh 5.8.1 (x86_64-apple-darwin21.0)
SDKMAN 5.15.0

**Comment by marc0der** [comment]
Hi @luceat-lux-vestra,

I suspect that what you are seeing here is not a bug with SDKMAN but rather a connectivity issue when using `curl`. Could you confirm that you are able to make the following call from the command line?

```bash
curl -vvv https://api.sdkman.io/2/candidates/alive
```

**Comment by helpermethod** [comment]
@marc0der According to 
https://sdkman.slack.com/archives/C014YJCLJAW/p1655993955949219
there was a partial outage. Could that be the problem?

**Comment by luceat-lux-vestra** [comment]
Here's curl result.
I think @marc0der you are right.

❯ curl -vvv https://api.sdkman.io/2/candidates/alive
* Could not resolve host: api.sdkman.io
* Closing connection 0
curl: (6) Could not resolve host: api.sdkman.io

> Hi @luceat-lux-vestra,
> 
> I suspect that what you are seeing here is not a bug with SDKMAN but rather a connectivity issue when using `curl`. Could you confirm that you are able to make the following call from the command line?
> 
> ```shell
> curl -vvv https://api.sdkman.io/2/candidates/alive
> ```

**Comment by tlunsfordCXP** [comment]
I had this problem with zscaler. Had to copy public zscaler cert files (3 of them) to /usr/local/share/ca-certificates and then run `update-ca-certificates`. Should fix it for approximately two weeks, since zscaler changes one of the two intermediate certs ever two weeks.
