### ISSUE TITLE
Bug: [I can't download some versions of java and other candidates]

### ISSUE THREAD

**Issue by ahton005** [sdkman/sdkman-cli#1101]
**Bug report**
Also I can't do selfupdate, I can't download scala for example, although some java versions are downloaded. It seems to me that the problem is that for some reason the candidates cannot download, I find archives with a size of 0 bytes.

> $ sdk i scala
> 
> Downloading: scala 3.1.3
> 
> In progress...
> 
> 
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of /c/Users/azyablov/.sdkman/tmp/scala-3.1.3.zip or
>         /c/Users/azyablov/.sdkman/tmp/scala-3.1.3.zip.zip, and cannot find /c/Users/azyablov/.sdkman/tmp/scala-3.1.3.zip.ZIP, period.
> 
> Stop! The archive was corrupt and has been removed! Please try installing again.

I'm new to programming, maybe I wrote something wrong in the environment variables.
I have been solving this for several days, I would be very grateful if you could help.
**To reproduce**
sdk i scala
sdk i sbt
for example

**System info**

**Comment by marc0der** [comment]
Hi @ahton005, I'm pretty confident this isn't a bug but an environmental issue on your machine or your network.

Please follow the [contributing guidelines](https://github.com/sdkman/sdkman-cli/blob/9f86a554692e41406e880d7db122df71006afa09/CONTRIBUTING.md) before opening a bug report here.

As per the guidelines, please feel free to chat with us on Slack where we can help you resolve this. I am closing this for now.
