### ISSUE TITLE
Feature: Hope to support downloading ruby

### ISSUE THREAD

**Issue by GGGGGHT** [sdkman/sdkman-cli#1109]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] I've had a conversation on the [#cli-development](https://sdkman.slack.com/app_redirect?channel=cli-development) Slack channel about this request.

**Feature request**

As described in the title. I hope sdk support download ruby. If the sdk supports downloading ruby, it can reduce my cost of installing ruby.

**Comment by marc0der** [comment]
Hi @GGGGGHT, SDKMAN is predominantly focused on JVM technology. We have considered hosting JRuby in the past, but AFAIK we didn't go ahead because of the distribution's packaging.

Please feel free to ask such questions on our community slack.
