### ISSUE TITLE
Prevent leakage of shell variables

### ISSUE THREAD

**Issue by pledbrook** [sdkman/sdkman-cli#111]
Because the gvm scripts are now sourced, variables leak into the shell. Even if they aren't visible with the `env` command (they need to be explicitly exported for that), a user can still use them in shell commands, e.g. `echo $CURRENT`.

As discussed previously, lower casing the variable names, namespacing them and perhaps clearing the variables themselves at every opportunity should probably be done.

**Comment by marc0der** [comment]
This was all taken care of during the refractor last year. Variable scoping was introduced using local variables (all lower case now), and only the most essential variables are exposed in the shell.
