### ISSUE TITLE
Feature: Disable update prompt (for CI/CD operations)

### ISSUE THREAD

**Issue by igrigorov** [sdkman/sdkman-cli#1113]
This is something in the spirit of #515 & #499 - there should be an option to disable the update prompt when running simple SDKMAN commands, as it breaks batch processes and, in particular, CI/CD pipelines.

I'm using SDKMAN on a Gitlab worker machine, changing the JDK version for a specific project build. It stopped working when the latest minor release came out, with the following behavior:

```
$ sdk use java 17.0.3-tem 00:02
Using java version 17.0.3-tem in this shell.
ATTENTION: A new version of SDKMAN is available...
The current version is 5.16.0, but you have 5.15.0.
Would you like to upgrade now? (Y/n): 
ERROR: Job failed: exit status 1
```

I decided that enabling offline mode on the machine would resolve the issue, and indeed it did for 3 days. But apparently this is just a temporary solution, as written in the docs:

> The offline mode will also be disabled/enabled automatically when the internet becomes available/unavailable. Naturally, commands that require internet connectivity will not function but give a warning. 

So I decided to put the enable offline command in the cicd script, just to find the issue described in #499...

Finally, I tried the workaround described in https://github.com/sdkman/sdkman-cli/issues/515#issuecomment-601572687, which worked... _somehow_.  
It looks that the command `n | sdk use java 17.0.3-tem || true` ignores the 'n' answer under Gitlab worker and the update was executed normally - not the desired behavior.

```
$ n | sdk use java 17.0.3-tem || true
bash: line 100: n: command not found
Using java version 17.0.3-tem in this shell.
ATTENTION: A new version of SDKMAN is available...
The current version is 5.16.0, but you have 5.15.0.
Would you like to upgrade now? (Y/n): 
Updating SDKMAN...
Installing script cli archive...
* Downloading...
######################################################################## 100.0%
* Checking archive integrity...
* Extracting archive...
* Copying archive contents...
* Cleaning up...
Updating config file...
```

**Comment by marc0der** [comment]
Hi @igrigorov,

Out of interest, have you tried using the `sdkman_selfupdate_enable` config setting as described on our website [usage page](https://sdkman.io/usage#config)? If I understand your issue right, this should solve your problems.

**Comment by igrigorov** [comment]
Thank you, @marc0der, you are right!  
I must have mistaken it for `sdkman_auto_answer` when trying to find the right configuration and thus omitted it. In this case, the feature I asked for doesn't make much sense, I guess - please feel free to close it.

**Comment by marc0der** [comment]
Great, glad it works for you!

**Comment by rubensa** [comment]
@marc0der  Have **sdkman_selfupdate_enable** be changed by **sdkman_selfupdate_feature**?
