### ISSUE TITLE
Bug: sdk selfupdate command invalid

### ISSUE THREAD

**Issue by ben-wing** [sdkman/sdkman-cli#1121]
**Bug report**

[Documentation states](https://sdkman.io/usage#selfupdate) that to update SDKMAN! itself that the command `sdk selfupdate` should be used. when I execute that command it reports "Invalid command:  selfupdate" and Usage does not include the selfupdate command as an option.

**To reproduce**

1. install the latest SDKMAN! 
2. run `sdk selfupdate`
```
$ sdk selfupdate

Invalid command: selfupdate


Usage: sdk <command> [candidate] [version]
       sdk offline <enable|disable>

   commands:
       install   or i    <candidate> [version] [local-path]
       uninstall or rm   <candidate> <version>
       list      or ls   [candidate]
       use       or u    <candidate> <version>
       config
       default   or d    <candidate> [version]
       home      or h    <candidate> <version>
       env       or e    [init|install|clear]
       current   or c    [candidate]
       upgrade   or ug   [candidate]
       version   or v
       broadcast or b
       help
       offline           [enable|disable]
       update
       flush             [tmp|broadcast|metadata|version]

   candidate  :  the SDK to install: groovy, scala, grails, gradle, kotlin, etc.
                 use list command for comprehensive list of candidates
                 eg: $ sdk list
   version    :  where optional, defaults to latest stable if not provided
                 eg: $ sdk install groovy
   local-path :  optional path to an existing local installation
                 eg: $ sdk install groovy 2.4.13-local /opt/groovy-2.4.13
```
**System info**

- OS
-- OS Name:                   Microsoft Windows 10 Enterprise
-- Version:                10.0.19044 N/A Build 19044
- Shell (git-bash)
-- GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
- sdk version
-- SDKMAN 5.16.0

**Comment by OothecaPickle** [comment]
adding `sdkman_selfupdate_feature=true` to `$HOME/.sdkman/etc/config` fixed it for me

**Comment by marc0der** [comment]
@ben-wing just curious, but how did you install SDKMAN? We have a feature flag in SDKMAN that disables selfupdate if it is installed by package managers such as brew. In cases like that, the package manager will handle any updates.

**Comment by ben-wing** [comment]
the way i installed SDKMAN was
`bash <(curl -sSL "https://get.sdkman.io")` 

followed pretty much immediately by 
```
mkdir -p $SDKMAN_DIR/etc \
  && echo 'sdkman_auto_answer=true' > $SDKMAN_DIR/etc/config \
  && source $SDKMAN_DIR/bin/sdkman-init.sh \
  && sdk selfupdate force
```

part of a script that my work provided to install their standard corporate development environment.

it appears that i should suggest we add
```
  && echo 'sdkman_selfupdate_feature=true' >> $SDKMAN_DIR/etc/config \
```

**Comment by marc0der** [comment]
Okay, right. The problem is in your second line:
```
  && echo 'sdkman_auto_answer=true' > $SDKMAN_DIR/etc/config \
```

You are overwriting the `etc/config` file using `>`.
This effectively clears out all the default configs, including this entry:

```
sdkman_selfupdate_feature=true
```
If this value is not set, it defaults to `false` and the `selfupdate` subcommand and all its references disappear.

Hope this helps!

**Comment by marc0der** [comment]
I'm removing the bug label because this is a usage issue.
