### ISSUE TITLE
IDEA 2020.3 cannot detect java sdk installed by sdkman (installed through brew)

### ISSUE THREAD

**Issue by vicq23** [sdkman/sdkman-cli#1136]
**Bug report**
When I installed sdkman through brew command, I successfully installed several java sdk, but my installed java sdk could not be detected in IDEA 2020.3
The root cause of the issue:
When I installed sdkman through brew command，all installed sdk will be in the "/opt/homebrew/opt/sdkman-cli/libexec/candidates" directory, But IDEA detects java sdk from the "~/.sdkman" directory.
My solution：
Point to the /opt/homebrew/opt/sdkman-cli/libexec/candidates directory by creating a soft connection in ~/.sdkman, So that IDEA can detect java sdk in ~/.sdkman directory
`ln -s /opt/homebrew/opt/sdkman-cli/libexec/candidates ～/.sdkman`

**To reproduce**
1. Run `brew install sdkman-cli`
2. Run `sdk install java`
3. Open java project in IDEA
4. Go to Meun: File >> Project Structure >> Project >> Project SDK, you cannot see the Java SDK installed by sdkman after clicking the drop-down box.

**System info**

**Comment by marc0der** [comment]
I think this bug should be filed with the IntelliJ team, not SDKMAN. We have no control over where they detect their JDKs.

Closing this issue for now as it isn't a bug in SDKMAN.
