### ISSUE TITLE
Bug: Tests fail on macs because of a bad platform string

### ISSUE THREAD

**Issue by xyzzy-plugh-plover** [sdkman/sdkman-cli#1137]
**Bug report**

Many tests fail on macs because the string used in `UnixUtils.inferPlatform(String, String)` as a lookup key for `UnixUtils.platforms` was changed a while ago (in commit 06fd0436a6b9ac79ba2b28125637cfde2b3c9a3b) to be obtained from `uname -s` instead of from `System.getProperty("os.name")`; the value of `uname -s` for macs is `Darwin`, so the hardcoded mac platform  key must be correspondingly changed.

**To reproduce**

Run tests on a mac.

**System info**

macOS 12.6
zsh 5.9
SDKMAN 5.16.0

**Comment by marc0der** [comment]
@helpermethod @hgeraldino are either of you able to confirm that this is broken? It works on Linux 🤷‍♂️ 😄

**Comment by hgeraldino** [comment]
It fails indeed. Submitted a small PR to have it fixed.
