### ISSUE TITLE
Bug: Setting `sdkman_rosetta2_compatible=true` does not affect `sdk list java` on macOS+Apple Silicon

### ISSUE THREAD

**Issue by esmail** [sdkman/sdkman-cli#1145]
**Bug report**

As mentioned in #1068, setting `sdkman_rosetta2_compatible=true` does not result in x64 JDKs being shown by `sdk list java` when executing in macOS with an Apple Silicon CPU.

**To reproduce**

On a Apple Silicon machine running macOS
1. Execute `sdk list java` and note that only JDKs built for native execution are listed
2. Set `sdkman_rosetta2_compatible=true` e.g. via `sdk config`
3. Execute `sdk list java` and note that the same list of JDKs is displayed (i.e. no x64 versions are shown)

**System info**

macOS 12.6, Apple M1 Pro CPU
zsh 5.8.1 (x86_64-apple-darwin21.0)
SDKMAN 5.16.0

**Comment by marc0der** [comment]
Hi @esmail, can you confirm that you opened a new terminal? Can you also confirm that `sdkman_rosetta2_compatible=true` was set successfully by echoing it out to the terminal?

Even though we still have this flag, there really is no reason to use anymore as we now support the arm architecture on Mac fully.

**Comment by esmail** [comment]
Actually, manually pulling up https://api.sdkman.io/2/candidates/java/darwinx64/versions/list?installed= manually I see that it does indeed match what I see running `sdk list java`, so this was a mistake on my part. Some company documentation led me to to expect Java 15 JDKs in the list.

Curiously though, I am able to install versions that aren't showing in the list which you can see available for download in the API e.g. at https://api.sdkman.io/2/broker/download/java/15.0.2.hs-adpt/darwinx64 .
