### ISSUE TITLE
Feature: Could we list jetbrains jdks in sdkman?

### ISSUE THREAD

**Issue by zifnab87** [sdkman/sdkman-cli#1146]
- [X] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] I've had a conversation on the [#cli-development](https://sdkman.slack.com/app_redirect?channel=cli-development) Slack channel about this request.

**Feature request**
Jetbrains provides hotswapping and some other interesting features on top of other openjdks.. it would be nice to have its jdks listed in sdkman:

http://hotswapagent.org/mydoc_quickstart-jdk17.html 
xpost: https://github.com/JetBrains/JetBrainsRuntime/issues/186

Thank you

**Comment by mkurz** [comment]
:+1: Yeah that would be nice, specially if they release new JBR versions with fixes at sometimes takes a while until that reaches IntelliJ. That way we could easily use sdkman to download the latest version and make Intellij use it.

**Comment by marc0der** [comment]
This all depends on whether our upstream API (Foojay DISCO) provides the JB JDKs. @eddumelendez will probably know best.

**Comment by Mugenor** [comment]
Looks like they support it:
https://github.com/foojayio/discoapi#at-the-moment-the-following-distributions-are-supported-by-the-api
