### ISSUE TITLE
Bug: install fails behind proxy

### ISSUE THREAD

**Issue by taringamberini** [sdkman/sdkman-cli#1147]
**Bug report**
The installation curl command fails when I run Git Bash behind my company proxy.

**To reproduce**
When I open Git Bash and I run the installation command `curl -s "https://get.sdkman.io" | bash` than nothing seems happen.

So I've run again the curl installation without the silent mode option `-s`, running `curl "https://get.sdkman.io" | bash` then I get the error `curl: (35) OpenSSL SSL_connect: Connection was reset in connection to get.sdkman.io:443`

**System info**

- Microsoft Windows 10 Enterprise, version 10.0.19042 N/D build 19042
- Git Bash installed with git version 2.37.3.windows.1

**A partial solution**

Before  running the curl installation command I've run `export https_proxy="user:password@proxyhost:proxyport"`

Clearly, every time I open Git Bash I have to run `export https_proxy="user:password@proxyhost:proxyport"` before any sdkmen command.

Best regards,
taringamberini

**Comment by marc0der** [comment]
Hi @taringamberini,

This isn't a bug, but rather a limitation of your corporate proxy and how curl works.

In future, please follow the contributing guidelines before opening a bug report here.

**Comment by taringamberini** [comment]
> In future, please follow the contributing guidelines before opening a bug report here.
Sorry, in the future I'll do.

Best regards
