### ISSUE TITLE
Failed to install grails 2.3.11

### ISSUE THREAD

**Issue by josenicomaia** [sdkman/sdkman-cli#1149]
mario@dell:~/.sdkman/tmp$ sdk install grails 2.3.11

Downloading: grails 2.3.11

In progress...

-=O=-                                                                   #         #        #        #                          
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/mario/.sdkman/tmp/grails-2.3.11.zip or
        /home/mario/.sdkman/tmp/grails-2.3.11.zip.zip, and cannot find /home/mario/.sdkman/tmp/grails-2.3.11.zip.ZIP, period.

Stop! The archive was corrupt and has been removed! Please try installing again.

**Comment by marc0der** [comment]
Please read our contributing guidelines below 👇
