### ISSUE TITLE
Bug: scala-cli now provides aarch64 Linux binary, but sdkman does not install it

### ISSUE THREAD

**Issue by mkurz** [sdkman/sdkman-cli#1159]
**Bug report**
Yesterdays scala-cli release provides a binary for aarch64 Linux, see https://github.com/VirtusLab/scala-cli/releases/tag/v0.1.19:

> We are happy to announce that there is a new dedicated launcher for the Linux Aarch64. You can find it [here](https://github.com/VirtusLab/scala-cli/releases/download/v0.1.19/scala-cli-aarch64-pc-linux.gz).

However sdkman does not install it.

**To reproduce**
```sh
$ sdk install scalacli

Stop! scalacli 0.1.19 is not available. Possible causes:
 * 0.1.19 is an invalid version
 * scalacli binaries are incompatible with your platform
 * scalacli has not been released yet

Tip: see all available versions for your platform:
```

**System info**
- Up to date [Arch Linux ARM](https://archlinuxarm.org/), running on MacBook Pro (Asahi Linux)

```sh
$ sdk version
SDKMAN 5.16.0

$ bash --version
GNU bash, version 5.1.16(1)-release (aarch64-unknown-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ uname -a
Linux mkurz-macbook-pro 6.1.0-asahi-2-1-edge-ARCH #2 SMP PREEMPT_DYNAMIC Wed, 14 Dec 2022 14:33:17 +0000 aarch64 GNU/Linux

$ uname -m
aarch64
```

**Comment by marc0der** [comment]
@mkurz, this is not an SDKMAN CLI bug. Please read and abide by the [contributing guidelines](https://github.com/sdkman/sdkman-cli/blob/65b95fb8e18dbdfbc71ae4600d8fa2efb22bed40/CONTRIBUTING.md) and ask any usage related questions on our **Slack user-issues channel** as stipulated.
