### ISSUE TITLE
Bug: The requested URL returned error: 504

### ISSUE THREAD

**Issue by nakhodkin** [sdkman/sdkman-cli#1169]
**Bug report**
<img width="1074" alt="Screenshot 2023-02-03 at 01 17 11" src="https://user-images.githubusercontent.com/14351638/216474185-8d09acaa-9a09-48e3-9a59-34553a01c722.png">

Unable to install the software. 

Once entered
```shell
$ curl -s "https://get.sdkman.io" | bash
```

the command errors out with exit code of `22`.

**Log output**
 ```
                                                                Now attempting installation...


Looking for a previous installation of SDKMAN...
Looking for unzip...
Looking for zip...
Looking for curl...
Looking for sed...
Installing SDKMAN scripts...
Create distribution directories...
Getting available candidates...
Prime the config file...
Installing script cli archive...
* Downloading...
curl: (22) The requested URL returned error: 504    #     #    #   #          

'curl --fail --location --progress-bar "$download_url" > "$sdkman_zip_file"': command failed with exit code 22.
```

**To reproduce**
```shell
$ curl -s "https://get.sdkman.io" | bash
```

**System info**
Mac OS Ventura 13.1
zsh 5.8.1 (x86_64-apple-darwin22.0)

**Comment by beverlyRoadGoose** [comment]
jumping to add that I am facing the same issue

**Comment by marlowww** [comment]
Today I found similar problem while doing `sdk list`.

`curl` call to `https://api.sdkman.io/2/candidates/list` returns with:
`<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.10</center>
</body>
</html>`

**Comment by PatrM** [comment]
Also jumping in just for visibility, I face the same problem as @marlowww.

```noformat
❯ sdk version  

SDKMAN!
script: 5.16.1
native: 0.1.0
```

Running OSX 13.1 in case that's relevant

**Comment by talonx** [comment]
Does anybody have any visibility into when this might get fixed? The Slack channel seems to be restricted to sdkman devs.

**Comment by stranljip** [comment]
> Does anybody have any visibility into when this might get fixed? The Slack channel seems to be restricted to sdkman devs.

You can generate your own invite: https://slack.sdkman.io/

**Comment by talonx** [comment]
> > Does anybody have any visibility into when this might get fixed? The Slack channel seems to be restricted to sdkman devs.
> 
> You can generate your own invite: https://slack.sdkman.io/

Thanks!

**Comment by marc0der** [comment]
Service has now been restored.
