### ISSUE TITLE
Bug: Stop! java is not a valid candidate while running sdk list java

### ISSUE THREAD

**Issue by manitgupta** [sdkman/sdkman-cli#1173]
**Bug report**
My `sdkman` installation used to work perfectly before. After updating to the latest version, I am no longer able to use it.

```
❯ sdk list java

Stop! java is not a valid candidate.

❯ sdk version

SDKMAN!
script: 5.16.1
native: 0.1.0
```

For any command that I run - `sdk list`, `sdk use` and `sdk default` return the same output. I have tried to uninstall and install but the problem still persists.
I have also tried `sdk flush candidates` but it did not help.

Other languages such as `sdk list scala`, `sdk list gradle` etc also do not work.

**To reproduce**
Install the latest release of SDKMAN. Try to run `sdk list java`.

**System info**
MacOS Ventura 13.2
Fish Terminal
M1 Pro
SDKMAN: 5.16.1

**Comment by marlowww** [comment]
Looks like API is down, same problem as https://github.com/sdkman/sdkman-cli/issues/1169#issuecomment-1429260567

**Comment by imyxiao** [comment]
same

**Comment by tplive** [comment]
> Looks like API is down, same problem as [#1169 (comment)](https://github.com/sdkman/sdkman-cli/issues/1169#issuecomment-1429260567)

It's been down for two weeks? 😱

**Comment by marlowww** [comment]
> > Looks like API is down, same problem as [#1169 (comment)](https://github.com/sdkman/sdkman-cli/issues/1169#issuecomment-1429260567)
> 
> It's been down for two weeks? 😱

Nope, its probably another URL/endpoint than old issue

**Comment by andersenleo** [comment]
Same here, fwiw..

**Comment by UBessle** [comment]
Same here

**Comment by luongvo** [comment]
Same here, we just got the issue today.

```
All done!


You are subscribed to the STABLE channel.

Please open a new terminal, or run the following in the existing one:

    source "/home/runner/.sdkman/bin/sdkman-init.sh"

Then issue the following command:

    sdk help

Enjoy!!!
==== BROADCAST =================================================================
* 2023-02-13: grails 5.2.6 available on SDKMAN!
* 2023-02-13: gradle 8.0 available on SDKMAN!
* 2023-02-12: skeletal 0.15.0 available on SDKMAN! https://github.com/cbmarcum/skeletal/releases/tag/v0.15.0
================================================================================

Stop! kotlin is not a valid candidate.
Error: Process completed with exit code 1.
```

**Comment by Kaishley** [comment]
Same here.

**Comment by stranljip** [comment]
Parallel discussion in Slack: https://sdkman.slack.com/archives/CJTNQA94M/p1676359041313729

**Comment by juliaBriadis** [comment]
Experiencing same issue with grails. "Stop! grails is not a valid candidate." sdk list command gives back 504 Gateway Time-out.

**Comment by talonx** [comment]
Same issue with installing java and gradle.

**Comment by Glecun** [comment]
Same issue, `sdk list java` returns me 504

**Comment by marttp** [comment]
Same issues, I thought I have faced this from my end.
After updating to `5.16.1`, I faced the same problem with `sdk list java`

```html
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.10</center>
</body>
</html>
```

Actually, before I updated to `5.16.1`, my previous version is `5.16.0` and still able to use `sdk list java`

**Comment by ptschack** [comment]
This problem is currently present on system which I maintain:
```$ sdk version

SDKMAN!
script: 5.16.1
native: 0.1.0`

**Comment by schallerala** [comment]
In some cases, it might help a few people to [enable the `offline`](https://sdkman.io/usage#offline) mode of _sdkman_ to allow using an already installed candidate.
Small thing that might come in handy in the time being.

**Comment by manish2aug** [comment]
If debug logging is enabled in the config, it can be seen on even startup of the terminal that it cannot connect

**Comment by manish2aug** [comment]
It seems that the beta channel is also not working https://beta.sdkman.io/2 giving 404

**Comment by alexei-28** [comment]
I also has this problem:

Linux Mint 20.3

Sdkman :
SDKMAN!
script: 5.16.1
native: 0.1.0
In terminal I try simple command:

sdk list java 
but get error

Stop! java is not a valid candidate.
This also not working:

sdk install java

Stop! java is not a valid candidate.
How can I fix this error?

P.S. this not help

sdk flush candidates

**Comment by mley** [comment]
This is pretty frustrating. Offline mode also does not work for me. 
```
$ sdk offline enable
Offline mode enabled.
$ sdk ls java

Stop! java is not a valid candidate.
```

Would it be possible to make basic usage possible without the usage of the API in the next version?

**Comment by gcwiak** [comment]
Same for me.
`SDKMAN 5.16.1.`, `sdk list java` results in 504.

**Comment by ingo-1492** [comment]
same here, SDKMAN 5.16.1., sdk list java results in "Stop! java is not a valid candidate."

**Comment by vanta** [comment]
Works for me now.

**Comment by alexei-28** [comment]
sdk update.

Now, it's work. Thanks

**Comment by ryan-williams-esure** [comment]
Still dead here. Still 404 on https://api.sdkman.io/2/candidates/list/ - seems I missed the brief window of it working.

**Comment by marc0der** [comment]
@ryan-williams-esure Remove the forward slash on the end of the URL. All services are up and running and haven't gone down again since the outage earlier.

**Comment by Tuubz** [comment]
@marc0der It's returning a different error response now:

`<head><title>503 Service Temporarily Unavailable</title></head>`

Reference: https://github.com/nimblehq/android-templates/actions/runs/4172007998/jobs/7243910588

**Comment by marc0der** [comment]
Hey @Tuubz, this was due to the initial rate-limiting that I imposed on the API. It was a bit aggressive at first, but I've relaxed it to 10 r/s per IP. Let me know on our community slack if you still see this issue.

**Comment by stefumies** [comment]
Have the same issue, here we are, December 2024

**Comment by marc0der** [comment]
Hi @stefumies, that comment isn't very helpful. What are you trying to install

This condition sometimes occurs when vendors remove a link to a resource on the web, effectively leaving an orphan in our database. It would be helpful if you provide the detail so we can correct the problem.

**Comment by stefumies** [comment]
Sorry, what was not helpful? I mentioned I have the same issue, that is referring to the same issue in this entire thread. Regardless, thank you for your reply, I have gone with a different version manager that suits my needs.

**Comment by marc0der** [comment]
Can you explain what you are seeing? Is it on CI? What are you installing?

**Comment by marc0der** [comment]
FWIW, we've had zero outages over the past 30 days, so I'm really not sure what you are referring to.
![2024-12-04T08:17:13,910505144+00:00](https://github.com/user-attachments/assets/693455c3-4305-4bd0-96a1-edc9f3a1ee0a)

**Comment by stefumies** [comment]
As I said, many thanks for your help, but I am no longer using sdkman.
