### ISSUE TITLE
Bug: Offers Quarkus 3.0.0.Alpha4 as default version

### ISSUE THREAD

**Issue by ksilz** [sdkman/sdkman-cli#1175]
**Bug report**

Today, SDKMAN! offered an alpha version of Quarkus as the default. It shouldn't.

**To reproduce**

1. Run these commands with Quarkus installed already:
```shell
sdk selfupdate
sdk update
sdk ug
```
2. SDKMAN! offers the alpha version 3.0.0.Alpha4 as the default:
```shell
Available defaults:
-e quarkus (local: 2.16.1.Final, 2.16.2.Final; default: 3.0.0.Alpha4)

-e -n Use prescribed default version(s)? (Y/n):
```

**System info**

- macOS Ventura 13.2.1
- zsh 5.8.1 (x86_64-apple-darwin22.0)
- The output of `sdk version`
```shell
SDKMAN!
script: 5.16.1
native: 0.1.0
```

**Comment by marc0der** [comment]
Hi @ksilz, this isn't really a bug but a data issue so let's close this. The vendors are responsible for publishing their own versions on SDKMAN, so this should probably be taken up with the likes of @maxanderson. Feel free to chat with us (or Max) on our community slack as per the [contributing guidelines](https://github.com/sdkman/sdkman-cli/blob/47fd6c42d806498e443157b68bf956bbc100f8cd/CONTRIBUTING.md)
