### ISSUE TITLE
Bug: SDK list <candidate> is not working on version 5.16.1

### ISSUE THREAD

**Issue by nabeel-ahmed-sp** [sdkman/sdkman-cli#1177]
**Bug report**
 SDKMAN is buggy on version 5.16.1

**To reproduce**
`sdk list java` is returning `Stop! java is not a valid candidate.` after upgrading sdkman to 5.16.1

**System info**
MacOS M1 Pro

**Comment by helpermethod** [comment]
Hi @nabeel-ahmed-sp,

just performed the upgrade, works fine for me. What happens when you just type `sdk list`?

**Comment by Limess** [comment]
We're seeing similar issues:

`sdk list` returns as expected

But:

```
sdk list java

Stop! java is not a valid candidate.
```

**Comment by nabeel-ahmed-sp** [comment]
Yes as mentioned by @Limess I am facing exact same issue at my end.

**Comment by Limess** [comment]
Running `sdk offline enable` restores functionality with pre-installed versions as a temporary workaround.

**Comment by nabeel-ahmed-sp** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/118155733/219002848-8648542b-56c5-47bd-af7f-387851052c47.png">

> Running `sdk offline enable` restores functionality with pre-installed versions as a temporary workaround.

I tried this. It didn't work for me.

**Comment by helpermethod** [comment]
How did you install SDKMAN!? Via Homebrew or curl?

**Comment by marc0der** [comment]
Hi @nabeel-ahmed-sp, could you try running `sdk update`, then opening a new terminal? I think this should solve your issue.

**Comment by marc0der** [comment]
@nabeel-ahmed-sp did this work for you? If so please feel free to close the issue.

**Comment by nabeel-ahmed-sp** [comment]
Yes this solved my issue. Thanks alot!
