### ISSUE TITLE
Bug: sdk selfupdate fails at line 92 when tmp directory does not exist

### ISSUE THREAD

**Issue by travisfw** [sdkman/sdkman-cli#1178]
### Bug report
sdkman should check that the tmp directory exists before writing to it
#### output
```
Updating SDKMAN...
Installing script cli archive...
* Downloading...
bash: line 92: ~/.sdkman/tmp/sdkman-5.16.1.zip: No such file or directory
'curl --fail --location --progress-bar "$download_url" > "$sdkman_zip_file"': command failed with exit code 1.
```

### To reproduce
delete the `tmp` directory in `~/.sdkman/` and run `sdk selfupdate`
#### easy work-around
`mkdir ~/.sdkman/tmp`
and then rerun.

Users should not have to do this, though. The cause of the error is not obvious, and creating the tmp directory was just a guess. `tmp` directory and files in it should be managed, and should not be assumed to exist. This occurred for me after restoring from a backup which excluded tmp directories.

### System info
- OS: Fedora 37
- Shell: `GNU bash, version 5.2.15(1)-release (x86_64-redhat-linux-gnu)`
- The output of `sdk version`
  - script: 5.16.1
    native: 0.1.0

**Comment by marc0der** [comment]
Hi @travisfw,

I honestly don't think this is a bug. In short, never delete folders or change files in the sdkman directory. If you do, you do so at your own risk. If you want to clear out the temp folder, be sure to read the help we provide here:

```
sdk help flush
```

**Comment by travisfw** [comment]
> In short, never delete folders or change files in the sdkman directory.

You misunderstand.
I have had no need for flushing the temp files on demand.
It's really quite reasonable for backup and sync systems to skip tmp dirs and caches.

**Comment by marc0der** [comment]
I recommend not deleting that folder, since it isn't a cache but a temporary workspace. This is much like the `/tmp` or `/var/tmp` directories that would cause huge issue on your Linux distro if they were removed. Everything in the `.sdkman` folder should be backed up. We never leave large files hanging around here so it is perfectly safe.
