### ISSUE TITLE
The installation command 

### ISSUE THREAD

**Issue by Preet-Govind** [sdkman/sdkman-cli#1186]
`$ curl -s get.gvmtool.net | bash `
is no more valid , kindly update the readme ,  reference https://github.com/sdkman/sdkman-cli/issues/641

Thanks

**Comment by marc0der** [comment]
Hi @Preet-Govind, could you please point me to the readme you are referring to? Wasn't aware that it was still referred to as gvmtool anywhere. For the best reference to installation, please refer to Https://sdkman.io/install

**Comment by Preet-Govind** [comment]
I was point in the readme file referenced below.


https://github.com/sdkman/sdkman-cli#installation


### Installation

Open your favourite terminal and enter the following:

`$ curl -s https://get.sdkman.io | bash`

**_this instruction in the "Installation" section of readme_**


_Sorry if referring a bit improperly , i'm quite new to git._

**Comment by marc0der** [comment]
That is the right command and it works perfectly. I don't see any reference to gvmtool in there.

**Comment by Preet-Govind** [comment]
edited above comment , it was having wrong link earlier.

*EDIT : i came from that readme of "flofreud" , i went to issue tracker and landed up on SDKMAN ,here its definitely clear. Its there in "forked" project of "flofreud" user.

I got upto his repo from google search for git link of gvm , spring-docs mentions use of GVM .

https://docs.spring.io/spring-boot/docs/1.2.0.M2/reference/html/getting-started-installing-spring-boot.html#getting-started-gvm-cli-installation

Thanks for helping :)

**Comment by marc0der** [comment]
Okay, if you look at the domain, that's the Spring website. It is for a very early version of Spring Boot. I'm pretty sure they aren't maintaining the docs for 1.2.0 M2 anymore.

In future, please follow the guidelines as requested in the issue template and the contributing guidelines below.
