### ISSUE TITLE
Bug: Error on install

### ISSUE THREAD

**Issue by BubbaJoe** [sdkman/sdkman-cli#1188]
**Bug report**
when i try to install sdkman, i get the error below
```
* Downloading...
######################################################################## 100.0%
* Checking archive integrity...
* Extracting archive...
* Copying archive contents...
* Cleaning up...

Set version to latest+00538c2 ...
Set native version to 0.1.3 ...
touch: /Users/joe/.bash_profile: Permission denied
'touch "$sdkman_bash_profile"': command failed with exit code 1.
```

**To reproduce**
curl -s "https://get.sdkman.io" | bash

**System info**
MacOS M1 Max - Ventura
zsh 5.8.1 (x86_64-apple-darwin22.0)

**Comment by marc0der** [comment]
This looks like a permissions issue, not a bug. Please feel free to chat with us on slack if the problem persists on your machine. All details can be found in the contributing guidelines.
