### ISSUE TITLE
Bug: JAVA_HOME for Zulu JDK doesn't match location for JDK found by Gradle

### ISSUE THREAD

**Issue by kenyee** [sdkman/sdkman-cli#1203]
**To reproduce**
This is something specific to the Zulu JDK in how it sets up symbolic links.  This causes Gradle to start up multiple daemons and waste memory because it thinks the JDK is different (because of the different paths).
The long discussion in a Gradle thread: https://github.com/gradle/gradle/issues/24521
Workaround is to use another JDK...e.g. Temurin.  
The Gradle folks have tried to work around the symlink quirks in Zulu multiple times w/o luck (see linked issues).

I guess the question is whether this is a bug in the Zulu JDK packaging for sdkman and if there are guidelines for them and something that can be done to fix the packaging?

**System info**
- OS: Mac
- Shell and version: zsh 5.9 (x86_64-apple-darwin22.0)
- The output of `sdk version`:
SDKMAN!
script: 5.18.1
native: 0.1.3

**Comment by marc0der** [comment]
Hi @kenyee, we don't alter the binary that is unpacked on your machine in any way. We simply download the binary from it's origin source, unpack it and add the location where it was unpacked to the path. Any problems with Zulu should be reported directly to Azul.

**Comment by kenyee** [comment]
Thanks..will ask the Azul folks.

I thought sdkman might have used the homebrew model of repackaging :-)
