### ISSUE TITLE
Feature: I hope I can use sdkman in nushell.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [sdkman/sdkman-cli#1211]
- [ ] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] I've had a conversation on the [#cli-development](https://sdkman.slack.com/app_redirect?channel=cli-development) Slack channel about this request.

**Feature request**

Can run in nushell.

**Comment by marc0der** [comment]
Closed. Please follow the contributing guidelines.

**Comment by nathanlisabio** [comment]
since this is the only issue abt nushell that i can find, here are some options worth checking out for future finders:

1) https://github.com/mikolas/nu_plugin_sdkman
2) from AI, to be placed in your config.nu:
```
def sdk [...args: string] {
  run-bash 'source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk "$@"' ...$args
}
...
def run-bash [script: string, ...args: string] {
  ^bash -lc $script bash ...$args
}
```
