### ISSUE TITLE
Add Gant support

### ISSUE THREAD

**Issue by bavobbr** [sdkman/sdkman-cli#122]
Gant is used in our project to launch certain tasks

"Gant is a tool for scripting Ant tasks using Groovy instead of XML to specify the logic. A Gant specification is a Groovy script and so can bring all the power of Groovy to bear directly, something not possible with Ant scripts."
(http://gant.codehaus.org/)

Gvmtool currently supports our requirement to install Groovy, Grails and Gradle, but it doesn't install Gant. It would be very clean to have this supported as well, that would make setting up the environment a trivial task instead of a page-long guide.

**Comment by erasche** [comment]
Seconding this, would make our life much easier.

**Comment by marc0der** [comment]
Anyone still using Gant or can we close this?

**Comment by erasche** [comment]
Not me.

**Comment by bavobbr** [comment]
I have migrated to Gradle now :) Thanks

**Comment by marc0der** [comment]
Awesome! Great choice ;-)

Closing this issue.
