### ISSUE TITLE
Bug: No available java versions

### ISSUE THREAD

**Issue by MtFBella109** [sdkman/sdkman-cli#1220]
**Bug report**
If I enter "sdk list java", I get not a single version o java listed and if I do "sdk install java", I get the following Message:
`Stop! java 17.0.7-tem is not available. Possible causes:
 * 17.0.7-tem is an invalid version
 * java binaries are incompatible with your platform
 * java has not been released yet

Tip: see all available versions for your platform:

  $ sdk list java`
If I type sdk list maven, I get all Versions of maven, so it's only with java, exactly like in the Issue of empty "sdk list java" on Windows 10. But I don't use Windows, I'm using GhostBSD

**To reproduce**
I installed it with the command ` curl -s "https://get.sdkman.io" | bash ` and the first thing I tried was sdk java list

**System info**
- OS: GhosdstBSD 13.2
- Shell: bash 5.2.15
- sdkman version: 5.18.2

**Comment by marc0der** [comment]
Hi @MtFBella109, unfortunately we do not support any BSD variants. We support, Linux, macOS and to a limited extent, Windows through MSYS and WSL.
