### ISSUE TITLE
Bug: All Springboot 1.X Versions fail to install

### ISSUE THREAD

**Issue by codeconsole** [sdkman/sdkman-cli#1221]
**Bug report**
Unable to install all Spring Boot 1.X versions.  Seems to be an issue with the download repository 

Perhaps change it to the following:
https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-cli/1.5.9.RELEASE/

instead of 
http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.5.9.RELEASE/ (broken)

**To reproduce**
```
% sdk install springboot 1.5.22.RELEASE 

Downloading: springboot 1.5.22.RELEASE

In progress...

-=O=#    #      #        #                                                                                                                                        
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/user/.sdkman/tmp/springboot-1.5.22.RELEASE.zip or
        /Users/user/.sdkman/tmp/springboot-1.5.22.RELEASE.zip.zip, and cannot find /Users/user/.sdkman/tmp/springboot-1.5.22.RELEASE.zip.ZIP, period.
```

**System info**
OSX 13.3.1 (a) (22E772610a)
```
% sdk version
SDKMAN!
script: 5.18.1
native: 0.2.2

% zsh --version
zsh 5.9 (x86_64-apple-darwin22.0)
```

**Comment by W-Lawless** [comment]
Same issue. Please fix this, it's an easy switch of a dead url that would make managing old spring versions much easier. As it stands, trying to download the versions manually doesn't seem to work for me; they fail build tests during compilation.

**Comment by marc0der** [comment]
We don't have any knowledge of the URLs that are persisted for Spring Boot. This candidate is actually managed by the Spring team themselves. It would be best to notify them on their own bug tracker.

**Comment by codeconsole** [comment]
@marc0der the only files they have access to on maven central are `tar.gz` files.  There is no way to have sdkman install a `tar.gz` instead of a zip?  

Also, is it possible to remove old versions? Versions prior to [1.3.7.RELEASE](https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-cli/1.3.7.RELEASE/spring-boot-cli-1.3.7.RELEASE-bin.tar.gz) will just be broken installations and should be removed somehow.

**Comment by philwebb** [comment]
We've managed to fix this on our end. No need to remove any older releases.

I think this issue can be closed now.
