### ISSUE TITLE
Bug: (Cygwin) Sdkman platform is defined as exotic causing empty java candidates list

### ISSUE THREAD

**Issue by aerfus** [sdkman/sdkman-cli#1223]
**Bug report**
Unable to list java candidates under Cygwin as SDKMAN_PLATFORM is exotic when should be windowsx64

**To reproduce**
1. open a new ternimal
2. Install Cygwin
3. Install Sdkman
4. enter `sdk list java`

**System info**
- OS
  - Windows 11 x64
- Shell and version
  - GNU bash, version 5.2.15(3)-release (x86_64-pc-cygwin)
- The output of `sdk version`
  - SDKMAN 5.18.2
- The output of `uname -a`
  - CYGWIN_NT-10.0-22621 Inazuma 3.4.7-1.x86_64 2023-06-16 14:04 UTC x86_64 Cygwin

**Additional info**
Might be related to #1216, #1219

**Comment by jmaasing** [comment]
Same issue here. Cygwin says: 
`$ uname -s
CYGWIN_NT-10.0-22621`
but sdkman says
`$ cat .sdkman/var/platform
exotic`

**Comment by marc0der** [comment]
Hi @aerfus and @jmaasing,

Unfortunately, we can no longer support Cygwin as it expects Windows `.exe` binaries to behave like Linux binaries when working with file paths. Our new native extensions are Windows binaries that behave as expected on Windows. For this reason, I have chosen to stop supporting Cygwin altogether. The only compatible shell that works with our binaries and that we do support is Git Bash with MINGW. Alternatively, most users prefer using WSL, which is guaranteed to work.

Hope this helps!

**Comment by aerfus** [comment]
Hi [marc0der](https://github.com/marc0der)!
Thank you for the answer.
