### ISSUE TITLE
Bug: sdkman under fish freezes output

### ISSUE THREAD

**Issue by teras** [sdkman/sdkman-cli#1225]
**Bug report**
When I use fish as my shell, sdkman seems not to be able to refresh the display. The command runs, but won't update the display. It looks as if the output is stored in a temporary place, and is displayed only when the command exits. This wouldn't be a problem , until a command that needs user input is required. Then the system waits for the user input, but the user doesn't know that he has to type at all, waiting there forever.

**To reproduce**

When in fish shell, type any sdk command that needs user input. I.e if `java 20.0.1.fx-zulu` is not installed, a command like 
`sdk install java 20.0.1.fx-zulu`. If you let it rest a bit and then type `[ENTER]` all output is displayed at once and you see that the reason of waiting was this line;

```Do you want java 20.0.1.fx-zulu to be set as default? (Y/n):```

**System info**

Linux aura 6.1.39-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 17:58:31 +0000 x86_64 GNU/Linux

fish, version 3.6.1

SDKMAN!
script: 5.18.2
native: 0.2.9

**Comment by helpermethod** [comment]
Hi @teras!

We don't officially support fish (yet), but there is a community-driven project which enables the use of SDKMAN! with fish

https://github.com/reitzig/sdkman-for-fish

**Comment by helpermethod** [comment]
It seems that fish's `echo` command buffers its output

https://stackoverflow.com/questions/27475097/why-does-fishs-echo-builtin-behave-differently-from-bashs-builtin
