### ISSUE TITLE
Feature: Please include zig lang in the sdk supported

### ISSUE THREAD

**Issue by sirlordt** [sdkman/sdkman-cli#1226]
**Feature request**
Please include zig lang in the supported sdk.

[Zig lang](https://ziglang.org)

Thanks!!!.

**Comment by marc0der** [comment]
@sirlordt please correct me if I'm wrong but I don't think that Zig is a JVM language. All SDKs hosted on SDKMAN are JVM related.

**Comment by sirlordt** [comment]
> @sirlordt please correct me if I'm wrong but I don't think that Zig is a JVM language. All SDKs hosted on SDKMAN are JVM related.

Yes is correct. Zig lang is not jvm related.

I saw the repo  [sdkman-cli-native](https://github.com/sdkman/sdkman-cli-native.git) in rust lang. And think SDKMAN is opening to another tools not related with the jvm.

**Comment by marc0der** [comment]
Sure, that's the implementation language, but all the candidates we host are targeted at JVM users.
