### ISSUE TITLE
Bug: /lib64/libc.so.6: version `GLIBC_2.18' (and others) not found

### ISSUE THREAD

**Issue by marc-guenther** [sdkman/sdkman-cli#1227]
**Bug report**

I'm on OracleLinux 7.9. After successfully installing with:
```
curl -s "https://get.sdkman.io" | bash
source "/root/.sdkman/bin/sdkman-init.sh"
```
I then get this error:
```
[root@oraclelinux79 ~]# sdk help
/root/.sdkman/libexec/help: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /root/.sdkman/libexec/help)
/root/.sdkman/libexec/help: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/.sdkman/libexec/help)
```

**System info**
- OS: OracleLinux 7.9
- The output of `sdk version`:
    ```
    [root@oraclelinux79 ~]# sdk version
    /root/.sdkman/libexec/version: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/.sdkman/libexec/version)
    /root/.sdkman/libexec/version: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /root/.sdkman/libexec/version)
    /root/.sdkman/libexec/version: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/.sdkman/libexec/version)
    ```
- Version of `glibc`:
    ```
    [root@oraclelinux79 ~]# yum info glibc
    Installed Packages
    Name        : glibc
    Arch        : x86_64
    Version     : 2.17
    Release     : 326.0.9.el7_9
    Size        : 13 M
    Repo        : installed
    From repo   : ol7_latest
    ...
    ```

**Comment by danuvian** [comment]
It is also broken with Centos 7. The app install fines but when I run 'sdk -version', I get the following error:
...sdkman/libexec/help: /lib64/libc.so.6: version 'GLIBC_2.28' not found (required by .../libexec/help)
...sdkman/libexec/help: /lib64/libc.so.6: version 'GLIBC_2.18' not found (required by .../libexec/help)

Would be nice if we had an easy way to install an older version of sdkman.

**Comment by helpermethod** [comment]
@marc0der According to this blog post, the best bet would be to stick to GLIB 2.17 for the forseeable future

https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html

**Comment by marc0der** [comment]
I've got an outstanding task to downgrade the Ubuntu LTS version we use to build our targets in the matrix build. We'd have to go as low as 18.04 I think.

**Comment by oraluben** [comment]
If I want to build from source to workaround this, is that possible? The `./gradlew install` command in readme seems not working since https://github.com/sdkman/sdkman-cli/commit/b02a937d8a06b29ed0c52f5b26e93f1efbabe9d8

**Comment by bbossola** [comment]
Broken also in Ubuntu 18.04.6 LTS. Is it possible to downgrade to a previous version?

**Comment by bbossola** [comment]
Ah I manage to get it working by executing:
```
sdk selfupdate force
````

See also:
https://github.com/sdkman/sdkman-cli-native/issues/152

**Comment by marc0der** [comment]
This is definitely working on older versions of Linux now. I just installed it on a docker container running Ubuntu 18.04 and it works perfectly.

**Comment by marc0der** [comment]
Closing this issue as it was fixed on the native extensions project.
