### ISSUE TITLE
Bug: [platform dir not found and sdk list not working]

### ISSUE THREAD

**Issue by biscuithx** [sdkman/sdkman-cli#1228]
**Bug report**

after running 'sdk update'
i got some error when open a new shell
![image](https://github.com/sdkman/sdkman-cli/assets/24818359/788e26eb-acaf-4115-9b7f-bd369ceae192)

i checked the the directory and it certainly doesn't exist in my computer
this is my ~/.zshrc
![image](https://github.com/sdkman/sdkman-cli/assets/24818359/8a81044f-a0ec-4cbf-839e-95b1a38d7630)

i found the shell command in '~/.sdkman/bin/sdkman-init.sh' using the platform dir
![image](https://github.com/sdkman/sdkman-cli/assets/24818359/4bafa9aa-6892-4b5a-8512-498d181d3d2e)

another things wrong is when i run 'sdk list java', i got an error like a web page which tells me something not found
![image](https://github.com/sdkman/sdkman-cli/assets/24818359/54c13fb7-d64b-42e1-8cfd-d12b9a1a261a)

**To reproduce**

run 'sdk update'

**System info**

- OS: CYGWIN_NT-10.0-19044 pc-010502 3.3.6-341.x86_64 2022-09-05 11:15 UTC x86_64 Cygwin
- Shell and version: zsh 5.8 (x86_64-pc-cygwin)
- The output of `sdk version`: SDKMAN 5.18.2

**Comment by yangchunze** [comment]
Is the problem solved?I have the same problem
