### ISSUE TITLE
Bug: Downloading SDKMAN. No such file or directory

### ISSUE THREAD

**Issue by hpbcrowe** [sdkman/sdkman-cli#1239]
**Bug report**

I am trying to install SDKMAN on a mac MacBook Pro. I run the curl `curl -s “https://get.sdkman.io/” | zsh`. It looks like it is downloaded ok. But then, I get the message: 
                                                                 Now attempting installation...

Looking for a previous installation of SDKMAN...
Looking for unzip...
Looking for zip...
Looking for curl...
Looking for sed...
Installing SDKMAN scripts...
Create distribution directories...
Getting available candidates...
Prime platform file...
Prime the config file...
Installing script cli archive...
* Downloading...
######################################################################## 100.0%
* Checking archive integrity...
* Extracting archive...
* Copying archive contents...
zsh: no matches found: /Users/hpbcrowe/.sdkman/src/*
'': command failed with exit code 1.

The installation fails. If I run `source "$HOME/.sdkman/bin/sdkman-init.sh"` It says no such file or directory. 
source: no such file or directory: /Users/hpbcrowe/.sdkman/bin/sdkman-init.sh
If I look at the downloaded file it doesn't have the same structure path:
![Screenshot 2023-09-15 at 3 19 56 PM](https://github.com/sdkman/sdkman-cli/assets/51143614/b0950faa-70c0-4581-9111-a4599a356e83)

**To reproduce**

1. Open a zsh terminal
2.  run curl -s "https://get.sdkman.io" | zsh

**System info**

OS: Mac OS Ventura version 13.5.2
Shell: zsh zsh 5.9 (x86_64-apple-darwin22.0)
Output of 'sdk version':
Invalid command: version

Usage: sdk <command> [candidate] [version]
       sdk offline <enable|disable>

   commands:
       install   or i    <candidate> [version] [local-path]
       uninstall or rm   <candidate> <version>
       list      or ls   [candidate]
       use       or u    <candidate> <version>
       config
       default   or d    <candidate> [version]
       home      or h    <candidate> <version>
       env       or e    [init|install|clear]
       current   or c    [candidate]
       upgrade   or ug   [candidate]
       version   or v
       help
       offline           [enable|disable]
       selfupdate        [force]
       update
       flush             [tmp|metadata|version]

   candidate  :  the SDK to install: groovy, scala, grails, gradle, kotlin, etc.
                 use list command for comprehensive list of candidates
                 eg: $ sdk list
   version    :  where optional, defaults to latest stable if not provided
                 eg: $ sdk install groovy
   local-path :  optional path to an existing local installation
                 eg: $ sdk install groovy 2.4.13-local /opt/groovy-2.4.13

**Comment by marc0der** [comment]
Hi @hpbcrowe, please follow the installation instructions as per our website. Installation as follows by running:

```
curl -s https:://get.sdkman.io | bash
```

In future, please follow the contributing guidelines linked below, starting with a conversation on our community slack user issues channel.

**Comment by hpbcrowe** [comment]
Sorry I don't understand. I'm not using bash, I use zsh. I ran that command with zsh and it didn't work.Thank you.On Sep 15, 2023 3:57 PM, Marco Vermeulen ***@***.***> wrote:
Hi @hpbcrowe, please follow the installation instructions as per our website. Installation as follows by running:
curl -s https:://get.sdkman.io | bash

In future, please follow the contributing guidelines linked below, starting with a conversation on our community slack user issues channel.
