### ISSUE TITLE
Bug: Graal Java SDK incorrectly tagged as "Unclassified"

### ISSUE THREAD

**Issue by dondonz** [sdkman/sdkman-cli#1257]
Hi team,

First up, thanks for building a great tool that I get a lot of use and enjoyment out of!

I noticed a very small thing about some Java SDKs being incorrectly tagged as "Unclassified".

I updated sdkman 
```
sdk update
```
then ran
```
sdk list java
```

I was expecting to see a 22.3.3 version of Graal as it's the latest version on their website's release notes: https://www.graalvm.org/release-notes/22_3/

But instead I saw only up to version 21 from these two vendors, but nothing starting with version 22.
```
GraalVM CE    |     | 21           | graalce |            | 21-graalce
               |     | 21.0.1       | graalce |            | 21.0.1-graalce
               |     | 20.0.2       | graalce |            | 20.0.2-graalce
               |     | 20.0.1       | graalce |            | 20.0.1-graalce
               |     | 17.0.9       | graalce |            | 17.0.9-graalce
               |     | 17.0.8       | graalce |            | 17.0.8-graalce
               |     | 17.0.7       | graalce |            | 17.0.7-graalce
 GraalVM Oracle|     | 21           | graal   |            | 21-graal
               |     | 21.0.1       | graal   |            | 21.0.1-graal
               |     | 20.0.2       | graal   |            | 20.0.2-graal
               |     | 20.0.1       | graal   |            | 20.0.1-graal
               |     | 17.0.9       | graal   |            | 17.0.9-graal
               |     | 17.0.8       | graal   |            | 17.0.8-graal
               |     | 17.0.7       | graal   |            | 17.0.7-graal
```

Scrolling down I can see these "Unclassified" vendors but these versions have the ending `grl`, which is what I was expecting from the right Graal version. Also the numbers line up with the release notes: 22.3.3. https://www.graalvm.org/release-notes/22_3/
```
 Unclassified|     | 22.3.3.r17   | grl     |            | 22.3.3.r17-grl
 Unclassified|     | 22.3.3.r17   | grl     |            | 22.3.3.r17-grl
```

Hopefully the issue is caused by a missing tag or name. In case it matters, I'm on a Mac and I use ZSH.

Thanks!

**Comment by jifbrodeur** [comment]
@dondonz Hi, I don't think this is a but, if you look at the Graal site, Oracle changed its versionning for Graal to match the JDK version, 17.x for jdk 17 and 21 for JDK 21.
Thanks
Jean-François

**Comment by dondonz** [comment]
That's great thanks
