### ISSUE TITLE
Bug: sdk install java 17.0.9-graal fails on macOS Sonoma 14.1.2 corrupt archive error, job table full on zsh

### ISSUE THREAD

**Issue by jifbrodeur** [sdkman/sdkman-cli#1261]
**Bug report**

running sdk install java 17.0.9-graal gives an error message: extract:11: job table full or recursion limit exceeded and
Stop! The archive was corrupt and has been removed! Please try installing again.

**To reproduce**

running sdk install java 17.0.9-graal 

**System info**
 macOS Sonoma 14.1.2, on intel, zsh 5.9 (x86_64-apple-darwin23.0), SDKMAN! script: 5.18.2, native: 0.4.3

**Comment by helpermethod** [comment]
Hi @jifbrodeur!

The error message `job table full or recursion limit exceeded` suggests that ZSH is performing some recursive call.

As SDKMAN! never calls something recursively, I wonder if maybe some alias or an Oh My Zsh could be responsible for this?

Maybe there is an alias defined for `tar`, `zip`, `unzip`? You can get the list of aliases by typing `alias` in your shell of choice.

**Comment by jifbrodeur** [comment]
@helpermethod  you are 100% correct there was one alias defined for unzip='extract $*' I removed it from my alias.zsh script and voilà! Maybe a check for alias or an addition to the error message would be great, just a thought.
Thanks

**Comment by helpermethod** [comment]
> @helpermethod you are 100% correct there was one alias defined for unzip='extract $*' I removed it from my alias.zsh script and voilà! Maybe a check for alias or an addition to the error message would be great, just a thought. Thanks

Hi @jifbrodeur!

Checking for aliases sounds like a good idea, as this is a quite common problem. Maybe we could issue a warning if aliases are defined for `tar/zip/unzip/curl` @marc0der?

**Comment by marc0der** [comment]
Sounds like a great idea!
