### ISSUE TITLE
Feature: [why can't configuration download path?]

### ISSUE THREAD

**Issue by falser101** [sdkman/sdkman-cli#1263]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] I've had a conversation on the [#cli-development](https://sdkman.slack.com/app_redirect?channel=cli-development) Slack channel about this request.

**Feature request**
because my linux path /root/ space isn't enough,i want sdkman can custom configuration the storage path

**Comment by marc0der** [comment]
Please read the section _Installing in a custom location_ on our installation page.
