### ISSUE TITLE
Bug: Can't update Quarkus to 3.6.8

### ISSUE THREAD

**Issue by vanuatoo** [sdkman/sdkman-cli#1275]
**Bug report**
sdk selfupdate
No update available at this time

sdk update

No new candidates found at this time.

sdk upgrade

All candidates are up-to-date

sdk list quarkus

shows that 3.6.8 is available and 3.6.7 is installed
<img width="732" alt="Screenshot 2024-01-31 at 11 24 31" src="https://github.com/sdkman/sdkman-cli/assets/6188902/2ef02274-e6fd-4287-ba71-9ca72d8d651e">

**System info**
macOS Sonoma Version 14.2.1 on M1

zsh --version
zsh 5.9 (x86_64-apple-darwin23.0)

sdk version
SDKMAN!
script: 5.18.2
native: 0.4.6

**Comment by marc0der** [comment]
Hi @vanuatoo, it seems that the Quarkus team forgot to update the default version. Please raise this directly with the Quarkus team as they publish their own versions to our platform.

A temporary workaround is to install the latest version and set it as default when asked.

```
sdk install quarkus 3.6.8
```
