### ISSUE TITLE
`.sdkmanrc` file is tracked in git

### ISSUE THREAD

**Issue by mdxabu** [sdkman/sdkman-cli#1283]
Dear Maintainers,

I am currently using sdkman for Java. I have noticed that when I use git the  `.sdkmanrc`, this file is tracked in git. This is because open-source contributors do not merge this file.

Best,
@mdxabu

**Comment by marc0der** [comment]
Hi @mdxabu, whether you track the `.sdkmanrc` file in Git is completely up to you. I personally always check mine in so my entire team gets the benefit of a fixed Java version.

In future, please ask usage questions on our community Slack as stipulated the contributing guidelines.
