### ISSUE TITLE
Bug: `./gradlew install` doesn't work 

### ISSUE THREAD

**Issue by hp77-creator** [sdkman/sdkman-cli#1286]
**Bug report**

I tried to install sdkman locally as mentioned in the README, I ran `./gradlew install` but since there is no `install` task explicitly defined, it failed.

**To reproduce**

1. clone the repo
2. run `./gradlew install`

**System info**

OS -> macOS 14.4
Shell -> zsh 5.9

**Comment by marc0der** [comment]
Hi @hp77-creator, thanks for making us aware of this. The README was out of date as we no longer support installing sdkman in this way. I've now removed all parts of the file that are no longer relevant.
