### ISSUE TITLE
Make it possible to run individual features from build

### ISSUE THREAD

**Issue by pledbrook** [sdkman/sdkman-cli#129]
It's not possible at the moment to run a single Cucumber feature from the build. To allow that, we can create a JUnit test per feature annotated with `@Feature` and then use the `-Dsingle.test` Gradle property.

Unless there is a another way to control which features are executed. Unfortunately, the annotations seem to be the only way when using the JUnit support.

**Comment by marc0der** [comment]
Yes, AFAIK this all works. Also, even easier is the ability to run features directly from within IDEA now that we use wiremock test fixtures. Closing this one for now.
