### ISSUE TITLE
Bug: Fails to upgrade Java to 21.0.5-tem on M1 Mac

### ISSUE THREAD

**Issue by ksilz** [sdkman/sdkman-cli#1320]
**Bug report**
SDKMAN! wants to upgrade my Java 21 but fails to do so.

**To reproduce**
I run this and press `[Enter]` when prompted:

```shell
sdk ug
```

Here's the output:

```shell
Available defaults:
java (local: 11.0.24-tem, 17.0.12-tem, 8.0.422-zulu, 21.0.4-tem; default: 21.0.5-tem)


Use prescribed default version(s)? (Y/n):
Stop! java 21.0.5-tem is not available. Possible causes:
 * 21.0.5-tem is an invalid version
 * java binaries are incompatible with your platform
 * java has not been released yet

Tip: see all available versions for your platform:

  $ sdk list java
```

**System info**
- M1 macOS Sonoma 14.7
- zsh 5.9 (x86_64-apple-darwin23.0)
- SDKMAN!: script: 5.18.2, native: 0.4.6

**Comment by ellisboddington** [comment]
Same issue here. Same versions of sdkman and zsh, macOS 15.0.1 on an M1 Max machine.

**Comment by marc0der** [comment]
Hi, this is not a bug but a data issue. @eddumelendez could this be bad data that we are getting upstream from the disco API?

In future, please talk to us on Discord as per the contribution guidelines linked below. It saves time in trying to triage issues here.

**Comment by eddumelendez** [comment]
Temurin doesn't publish all artifact at once. This morning the artifact for mac arm was not available and now it is, so, in sdkman as well after running the migration process.

Btw, for windows is not available yet.
