### ISSUE TITLE
OS-generated files ends up as local version in list of available candidate versions

### ISSUE THREAD

**Issue by rlovtangen** [sdkman/sdkman-cli#163]
Some common OS-generated files could probably be filtered from the list of available candidate versions.
Here .DS_Store ends up in the list because Finder created a .DS_Store under ~/.gvm/grails:

```
$ gvm list grails

============================================================
Available Grails Versions
============================================================
   + dev
   + .DS_Store
   * 2.2.2
   * 2.2.1
 > * 2.2.0
     2.1.5
     2.1.4
```

**Comment by bpieber** [comment]
I also have this problem with .DS_Store

**Comment by McPringle** [comment]
This is still an annoying bug…

**Comment by marc0der** [comment]
Sure, it would be easy to fix too. Want to submit a PR?

**Comment by marc0der** [comment]
Re-opening issue due to warnings in the console:

    find: warning: you have specified the -maxdepth option after a non-option argument (, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

**Comment by McPringle** [comment]
Do you have a context, please? Which OS version? Maybe the `find` command behaves a little bit different. I'll investigate tomorrow.

**Comment by marc0der** [comment]
Sure no probs, here is the archey dump:

```
               +                
               #                
              ###               
             #####              
             ######             
            ; #####;            User: marco
           +##.#####            Hostname: scopuli
          +##########           Distro: Arch Linux
         #############;         Kernel: 4.14.4-1-ARCH
        ###############+        Uptime: 1 day, 10:49
       #######   #######        Window Manager: 
     .######;     ;###;`".      Desktop Environment: 
    .#######;     ;#####.       Shell: /bin/zsh
    #########.   .########`     Terminal: xterm-256color
   ######'           '######    Packages: 870
  ;####                 ####;   CPU: Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
  ##'                     '##   RAM: 6343 MB / 15771 MB 
 #'                         `#  Disk: 97GB / 493GB
```

**Comment by McPringle** [comment]
I don't have ArchLinux but I have a VM running Ubuntu. I was able to reproduce the warning of the `find` command on Ubuntu and fixed it by swapping the parameters.

**Comment by marc0der** [comment]
@McPringle Okay, I've tested this on all platforms and send to work well now. I've releases this on stable as 5.5.15. Thanks for the great work!
