### ISSUE TITLE
Integrating with user's BASH set up

### ISSUE THREAD

**Issue by russel** [sdkman/sdkman-cli#187]
Users may wish to use GVM for default implementations and then manage their own Bash environment variables for some specific systems. Currently I install Groovy for myself and use GVM for Gradle, Griffon, and Grails. Currently GVM assumes it is in sole charge of the *_HOME and PATH environment variables and puts it's paths first. Since the default is to execute the GVM initialization last this overwrites any settings the user may have set up, in my case GROOVY_HOME and PATH are set as I need them then GVM overwrites the settings.

Thus currently GVM does not "play nice" with a sophisticated users' set up.

Whilst all the variables were hard coded it was easy to use a different start up script and comment things out. The new (and improved) approach in 1.3.0 does not allow for this so easily.

I am trying the experiment of using a non-standard version of the initialization script that does not install with GVM entries for which there are already variables, e.g. GROOVY_HOME. Any and all other solutions would be welcome!

**Comment by marc0der** [comment]
This seems to be an outdated issue so closing.
