### ISSUE TITLE
Consistency between 'use' and 'default' when version not installed

### ISSUE THREAD

**Issue by robfletcher** [sdkman/sdkman-cli#201]
If I don't have a particular candidate version installed and I do `gvm use foo 1.0` it will offer to install it for me. If I do `gvm default foo 1.0` it will just halt saying _1.0 is not installed_.

I know that `gvm use` will offer to make it the default but it would make sense to me if `gvm default` was simply an alias for `gvm use` with automatic acceptance of the _set as default_ option at the end.

**Comment by marc0der** [comment]
Only saw this issue now, almost three years later, sorry!

The `use` and `default` commands are very distinct in that default is used for updating the `current` symlink in the candidate's folder. It results in every new terminal opening with that version of the candidate. The `use` command on the other hand only changes the path for that shell to point at a specific version. Any new shell will still return to the default version selected.

If you try to `use` a version that is not installed, it simply falls back into the install flow, which in turn offers you to make it default. This was done as per a feature request.

We could spend time retrofitting `default` to have similar behaviour, but I see it as a very rarely used command in comparison to `install` and `use`. Is it really worth the effort?

**Comment by marc0der** [comment]
After some more thought, I agree that these two should be consistent. On closer inspection, this is also not too difficult to implement.

**Comment by rgoldberg** [comment]
`use` & `default` are currently consistent, but both halt on a not-installed version instead of offering to install that version.
