### ISSUE TITLE
Add Golo as a candidate

### ISSUE THREAD

**Issue by aalmiray** [sdkman/sdkman-cli#226]
The Golo programming language (http://golo-lang.org) is available in a zip whose structure closely matches Groovy's. This makes it for an easy inclusion into GVM.

**Comment by marc0der** [comment]
This has all happened folks! Unfortunately golo has not chosen to publish their versions on SDKMAN, but I'm sure if enough people ask on their forums they will do so.

@aalmiray and since you asked so nicely, I included Scala AND Kotlin 😂😂

**Comment by aalmiray** [comment]
@marc0der: curse you for making so easy to install cool software with just one command line. My productivity level is ... over 9000!
