### ISSUE TITLE
Global install

### ISSUE THREAD

**Issue by robfletcher** [sdkman/sdkman-cli#23]
It would be nice to have the option to share installations between all users of a machine (maybe with a user-specific symlink to the active version).

**Comment by fedotxxl** [comment]
+1 for this feature

**Comment by ben3000** [comment]
Try as I might, I can't get the `GVM_DIR` setting to work.

I set `export GVM_DIR=/usr/local/gvm` in `~/.bashrc`. In `~/.bash_profile`, I `source ~/.bashrc`, I delete all gvm stuff, exit the terminal, open a new one, run `curl -s get.gvmtool.net | bash` and it still writes everything to `$HOME/.gvm`.

`GVM_DIR` is hard-coded into the script that `curl` downloads, so the value I exported [isn't used at all](https://stackoverflow.com/a/4609727/2495717).

**Comment by marcoVermeulen** [comment]
Working on it. Should have something out by tomorrow.

**Comment by marc0der** [comment]
This has been successfully implemented.
