### ISSUE TITLE
Groovy state is weird in 1.3.11

### ISSUE THREAD

**Issue by russel** [sdkman/sdkman-cli#235]
I upgraded to 1.3.11 and then got the following. I have no idea if this was the case previously.

|> gvm current
Using:
gradle: 1.8
grails: 2.3.1
griffon: 1.4.0
groovy: /home/users/russel/.gvm/vertx/current/bin:/home/users/russel/.gvm/springboot/current/bin:/home/users/russel/.gvm/lazybones/current/bin:/home/users/russel/.gvm/groovyserv/current/bin:/home/users/russel/.gvm/griffon/current/bin:/home/users/russel/.gvm/grails/current/bin:/home/users/russel/.gvm/gradle/current/bin:/home/users/russel/.gvm/gaiden/current/bin:.:/home/users/russel/bin.Linux.x86_64:/home/users/russel/lib/Go/bin.Linux.x86_64:/home/users/russel/lib.Linux.x86_64/Clay/bin:/home/users/russel/lib.Linux.x86_64/LDC/bin:/home/users/russel/bin:/home/users/russel/lib/Java/groovy/bin:/home/users/russel/lib/Java/scala/bin:/home/users/russel/lib/Java/fantom/bin:/home/users/russel/lib.Linux.x86_64/Rust/bin:/home/Checkouts/Mercurial/Fortress/bin:/home/users/russel/lib.Linux.x86_64/X10/bin:/home/users/russel/lib.Linux.x86_64/Dart-SDK/bin:/home/users/russel/lib.Linux.ix86/AndroidSDK/platform-tools:/home/users/russel/bin.Linux.ix86:/home/users/russel/lib/Chapel/bin/linux64:/home/users/russel/lib.Linux.x86_64/Eiffel/studio/spec/linux-x86-64/bin:/home/users/russel/lib.Linux.x86_64/JDK/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
groovyserv: 0.13
vertx: 2.0.2.final

**Comment by marc0der** [comment]
No report back since Nov 2013 so can we close this issue?
