### ISSUE TITLE
error running "gvm c" in screen

### ISSUE THREAD

**Issue by joterway** [sdkman/sdkman-cli#242]
I'm running Ubuntu 12.04.3 and gvm mostly works fine. I set a default groovy and grails version and can run "gvm c" just fine from bash. However, when I run the same command within screen it seems to fail with a recently reported error:

  bash: ((: i <= : syntax error: operand expected (error token is "<= ")
  No candidates are in use

This is my screen version:

  Screen version 4.00.03jw4 (FAU) 2-May-06

**Comment by marc0der** [comment]
Is this still broken or can we close the issue?

**Comment by marc0der** [comment]
Tested this on screen and tmux. Working perfectly in sdkman 5.0.0+51.
