### ISSUE TITLE
Way to install candidates for all users on Mac

### ISSUE THREAD

**Issue by WarFox** [sdkman/sdkman-cli#261]
Is there a way to install candidates for all users on Mac?
It would be great if we could download once into a shared library location like /Library
and then use soft links on each user profile.
Is it possible?

**Comment by marc0der** [comment]
This work was completed sometime last year. It is now possible to do a global install, please see the our [installation page](http://sdkman.io/install.html) for more details.

**Comment by WarFox** [comment]
Thank you! Sorry, I had completely forgotten about this issue

**Comment by marc0der** [comment]
No worries!
