### ISSUE TITLE
gvm failed to install new versions - Permission denied

### ISSUE THREAD

**Issue by fkorssjoen** [sdkman/sdkman-cli#262]
Hi, i'm having troubles when trying to install new versions of grails.

gvm install grails 2.3.6

Downloading: grails 2.3.6

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  129M  100  129M    0     0   229k      0  0:09:35  0:09:35 --:--:--  248k

Installing: grails 2.3.6
__gvmtool_install_candidate_version:9: permission denied: mv
Done installing!
- Tried reinstalling gvm
- After running the gvm command, I can no longer run any other OS commands in the shell.
- Before running the gvm command, everything is normal.
- I used gvm frequently installing and switching grails versions.
- I'm using MacOs 

Please give me any hints!

Thanks.

**Comment by biniama** [comment]
[SOLUTION] It was for sure a problem caused by Trend Micro Security anti-virus software installed by my company on MacOS.

I trashed the antivirus and able to install grails with sdkman. 

Then, put back the deleted anti-virus.

**Comment by mashimom** [comment]
Hello,
I am on a company machine on WSL behind proxy (downloads work) but most installations fail on the mv command. I got java 8.0.232-open working while gradle 6.0.1 and others fail.

**Comment by marc0der** [comment]
Hi @mashimom, if you hop onto slack I can help you there: https://slack.sdkman.io
