### ISSUE TITLE
Add GVM to Homebrew

### ISSUE THREAD

**Issue by mullen3** [sdkman/sdkman-cli#266]
There currently aren't any formulas for installing GVM via homebrew. Looking into adding a formula for it.

**Comment by diroussel** [comment]
Shame, once I heard about sdkman, the first thing I tried was to see if I could install it via homebrew.

**Comment by marc0der** [comment]
This doesn't really make much sense as sdkman is a package manager, like
homebrew. However, we are different in that we install everything within
the user's home directory. Also, we have our own selfupdate mechanism which
would clash with updates from other package managers.

Installation is simple through the use of our install script piped through
bash and we do intend to keep it that way.
