### ISSUE TITLE
will gvm support maven?

### ISSUE THREAD

**Issue by dongwq** [sdkman/sdkman-cli#275]

**Comment by msgilligan** [comment]
Hasn't gvm already started supporting some tech that is not (strictly) Groovy? I just noticed (after some months haha) that I no longer have Maven on my system. (Yes, I've been using Gradle almost exclusively!) 

There would be no better way to install Maven than with GVM. It would even allow me to easily switch Maven versions if I need to. It seems like a great "trojan" to get more Java developers over to gvm and eventually Gradle, too.

**Comment by msgilligan** [comment]
For reference here is the Jira Issue I created for Maven:
http://jira.codehaus.org/browse/MNG-5749

**Comment by wimdeblauwe** [comment]
+1 for this. Would be very nice to support Maven as well.
