### ISSUE TITLE
Implement post install hooks

### ISSUE THREAD

**Issue by nobeans** [sdkman/sdkman-cli#276]
I'm developing a new version of GroovyServ. It might be required to run a script just after installing it. Can I do that? Or, must I consider alternative way for that?

**Comment by marc0der** [comment]
This has now been completed so closing.

**Comment by lucastheisen** [comment]
@muja , FWIW, you can implement something akin to a post install hook by creating an extension script (ie: `${}/ext/sdkman-install-with-post-function.sh`):

```bash
#!/bin/bash

source <(sed 's/__sdk_install/__sdk_builtin_install/g' "${SDKMAN_DIR}/src/sdkman-install.sh")

function __sdk_install() {
  __sdk_builtin_install "$@"
  local exit_code=$?

  if ((exit_code==0)); then
    local java_home
    java_home="$(__sdk_home "${1}" "${2}")"
    >&2 echo "install certificates into ${java_home}"
    
    <insert_code_to_update_cacerts_here>
  fi

  return "${exit_code}"
}
```

**Comment by muja** [comment]
> [@muja](https://github.com/muja) , FWIW, you can implement something akin to a post install hook by creating an extension script (ie: `${SDKMAN_DIR}/ext/sdkman-install-with-post-function.sh`):
> 
> #!/bin/bash
> 
> source <(sed 's/__sdk_install/__sdk_builtin_install/g' "${SDKMAN_DIR}/src/sdkman-install.sh")
> 
> function __sdk_install() {
>   __sdk_builtin_install "$@"
>   local exit_code=$?
> 
>   if ((exit_code==0)); then
>     local java_home
>     java_home="$(__sdk_home "${1}" "${2}")"
>     >&2 echo "install certificates into ${java_home}"
>     
>     <insert_code_to_update_cacerts_here>
>   fi
> 
>   return "${exit_code}"
> }

Very nice and clever, thank you. This is a much more robust version than the one using `starship`, however it was a bit trickier to get working correctly. You want to check for `$1 == java` to not invoke this post-install for other candidates, for example. Also, `sdkman` has started to print some warnings to `stdout` when you use `__sdk_home` so you have to use `sdk home`

The code I ultimately ended up with:

```bash
#!/bin/bash

eval "$(sed 's/__sdk_install/__sdk_builtin_install/g' "$SDKMAN_DIR/src/sdkman-install.sh")"

function __sdk_install() {
  __sdk_builtin_install "$@"
  local exit_code=$?

  if [[ $exit_code == 0 && "$1" == java ]]; then
    local java_home="$(sdk home "$1" "$2")"
    local cacerts="$(find "$java_home" -name cacerts -type f)"
    if [[ -n "$cacerts" ]]; then
      echo
      echo "symlinking cacerts"
      mv "$cacerts" "$cacerts.original"
      ln -s "/etc/ssl/certs/java/cacerts" "$cacerts"
    fi
  fi

  return $exit_code
}
```
