### ISSUE TITLE
use version switch continues after corrupt download/install

### ISSUE THREAD

**Issue by zacechola** [sdkman/sdkman-cli#281]
Somewhat related to #53, but also not really.

When a `Stop! The archive was corrupt and has been removed! Please try installing again.` error is thrown, gvm continues to switch the shell over to the version requested, even though it was corrupt and not installed.

The program should exit before switching to a version not downloaded/installed.

Obviously the simple way out here is to try again, but I just wanted to point this out.

**Comment by marc0der** [comment]
This is no longer relevant as `use` no longer attempts to install anything if the version is not present.
