### ISSUE TITLE
Rename main function to 'sdk' and make configurable 

### ISSUE THREAD

**Issue by marcoVermeulen** [sdkman/sdkman-cli#286]
The main function needs to be renamed to 'sdk' instead of 'gvm', and should allow other aliases to be configured. The default configuration should include an alias for 'gvm', which can be changed for users of the Go Version Manager.

**Comment by jesperronn** [comment]
@marcoVermeulen since SdkMan is now released, can this issue be closed?

**Comment by marcoVermeulen** [comment]
For sure!
