### ISSUE TITLE
Allow binary / source / documentation for Groovy (and other candidates) 

### ISSUE THREAD

**Issue by anodynos** [sdkman/sdkman-cli#290]
Currently gvm installs *only* the binary release of Groovy.

I usually end up downloading the [Combined binary / source / documentation bundle: Distribution bundle](http://dl.bintray.com/groovy/maven/groovy-sdk-2.4.0-beta-3.zip) and unziping it on top of `~/.gvm/groovy/2.x` cause I want my IDE to have the sources & docs in one neat place. 

Could that become an option ?

**Comment by danieldbower** [comment]
I agree that this is a good idea.  Perhaps a config option (config file, or command line switch) would be a good compromise.  

To further dream, I can envision a command:  
gvm docs grails 2.2.4
This could be a simple link to have the system open the directory for the downloaded docs.  On my Ubuntu system, to open a location from the command line, I use:
gnome-open /path/to/directory

**Comment by jglapa** [comment]
Yes! Including the sources would also allow to create a groovy _library_ in IntelliJ IDEA that can be used to support groovy only projects. Right now if you point to **~/.sdkman/candidates/groovy/x.y.z** you get this error
_Looks like Groovy distribution in specified path is broken. Cannot determine version._ . 
Copying the src/ directory into the sdkman distribution solves the problem.

**Comment by marc0der** [comment]
@jglapa You would need to raise this with the groovy team, as they are responsible for their own releases on sdkman. You could raise this on their [mailing list](http://www.groovy-lang.org/mailing-lists.html) if you like.
