### ISSUE TITLE
I think gvm should use local archives first.

### ISSUE THREAD

**Issue by abcfy2** [sdkman/sdkman-cli#291]
Because I can't access to ``gvmtool.net`` from here usually.

So I think every command are all connect to ``gvmtool.net`` is terrible. It's so slow and often failed.

I think ``use``,``default``,``install`` and so on should check local version first, if it has, just use local file(s), I think it's graceful. No need to connect to ``gvmtool.net`` always.

And I think ``selfupdate`` should not delete local file first. Because if connect or download failed(often connected time out here), I can't retry any more. I think download the new version archive first, and override the old files is better.

Best regards.

**Comment by marc0der** [comment]
SDKMAN is far less chatty now, but will still requires an internet connection to function (much like a browser requires the internet). A lot of work has gone into optimising this, so closing this issue.
