### ISSUE TITLE
offer ant, sbt also for installation from gvmtool 

### ISSUE THREAD

**Issue by zaxebo1** [sdkman/sdkman-cli#297]
let me only have a system with jdk and gvmtool .
Now using gvmtool i can install groovy,grails,gradle etc
Only, if you also offer sbt then we can bootstrap scala too from the same gvmtool
offering ant also will be a great addon

about sbt
http://chapeau.freevariable.com/2013/08/making-fedora-a-better-place-for-scala.html         
http://stackoverflow.com/a/23871207                 

more relevant urls for managing multiple versions of scala
https://github.com/toolbear/svm
https://github.com/kaiinkinen/pvm
http://stackoverflow.com/questions/13422189/how-can-i-manage-multiple-versions-of-scala-sbt-in-my-dev-environment

=============

so, gvmtool will become single tool for bootstrapping any system with latest essential jdk libraries,groovy libraries,scala libraries.

**Comment by stavytskyi** [comment]
I would be great if you can add 'ant' and 'maven' too for convenience.

**Comment by marcoVermeulen** [comment]
GVM is about to undergo a HUGE metamorphosis. It's going to be renamed SDKenv. We will introduce a notion of Candidate Groups. At the moment, GVM only caters for Groovy Candidates. Soon we will have a Scala Group too, where we will be acting as broker for all things Scala too.

**Comment by zaxebo1** [comment]
Thats a good news.
I will request to kindly settle on a name which is **google friendly**, that is if people have discussed/mentioned about it on some lone forum or some another discussion group then it will be easy to be searchd

**Comment by marcoVermeulen** [comment]
Don't worry, it will be very well publicised when it's ready, combined with
blog posts etc. I've already acquired sdkenv.io too.

**Comment by zaxebo1** [comment]
also , currently it is written as **bash script** . If you are planning to rewrite from scratch, then may be writing it in **python** may be good option.

- Python is included in default installation of all the linux, because it is requirement in LSB(Linux standard Base) standard. 

- Putting it in python will give advantage, of better portability of running python scripts directly on MS-Windows too, without any emulation layer.

- many bash script files are deployed as separate files, whereas many individual python scripts can be bundled together as single zipped .pyz file, and executed directly. So even though "sdkenv" may be implemented by multiple python script files, but all those can be zipped together as a single executable file .pyz  
see https://blogs.gnome.org/jamesh/2012/05/21/python-zip-files/

**Comment by marcoVermeulen** [comment]
Nope, no rewriting needed, only some renaming is involved. Bash was
selected because it is the best tool for the job. We want people to get
going with the least possible dependencies on their machines. Everyone has
bash.

Nothing is stopping you from writing a python implementation and making it
publicly available though! Who knows, it might end up being more popular
than the bash version! PoshGVM was also written in this spirit and has
become very popular among windows users.

**Comment by zaxebo1** [comment]
i didn't knew about poshgvm , thanks for the tip.  :-)

**Comment by RaviH** [comment]
+1 for scala and sbt

**Comment by bond-** [comment]
+1 for ant, maven

**Comment by abelsromero** [comment]
I think this can be closed now. All tools are already integrated (yay!).
You made my day when I saw that ant was also in.

**Comment by marc0der** [comment]
Awesome, and many more coming soon!

**Comment by bond-** [comment]
@marc0der Just a FYI.

`sdk list ant` gives the following message which I think is incorrect. While `sdk list` does show ant as a candidate.

```
Stop! ant is not a valid candidate.
```

**Comment by abelsromero** [comment]
It work fine on my machine. It shows ant candidate 1.9.6.
Running sdkman version 3.3.1

**Comment by marc0der** [comment]
@bond- you would probably need to flush your local candidate cache to see new candidates like ant.

    $ sdk flush candidates
