### ISSUE TITLE
Add Gremlin to GVM

### ISSUE THREAD

**Issue by mattyb149** [sdkman/sdkman-cli#298]
Gremlin is a Groovy-based DSL for graph traversal/operations.  It was created and is maintained by Tinkerpop:

http://www.tinkerpop.com/

They have a 2.x line where Gremlin is a part of the Tinkerpop stack:

https://github.com/tinkerpop/gremlin/wiki

And they are about to release (Q1 2015 I believe) the 3.0 stack, called Gremlin, containing all the modules previously considered separate in the Tinkerpop stack

https://github.com/tinkerpop/tinkerpop3

As the project makes heavy use of Groovy, it would be great to have the ability to manage installations, versions, etc. with GVM.

Thanks in advance for your consideration!

**Comment by mattyb149** [comment]
Now that Tinkerpop is in the Apach Incubator, can the Gremlin Console and/or server be added to sdkman?

**Comment by marc0der** [comment]
Sure, it seems to be fully compliant. However, it would require one of the Tinkerpop team to integrate with us through our vendor API. They would be responsible for pushing their own versions onto our platform. I suggest you raise an issue on their github project asking for integration with sdkman.

**Comment by marc0der** [comment]
Not heard anything so closing this issue.
