### ISSUE TITLE
Ubuntu 14.10, lightdm, .profile and gvm-init.sh not compatible

### ISSUE THREAD

**Issue by monetschemist** [sdkman/sdkman-cli#308]
The line added to the end of .profile by gvm:

[[ -s "/home/clh/.gvm/bin/gvm-init.sh" ]] && source "/home/clh/.gvm/bin/gvm-init.sh"

is not interpretable by sh, only by bash (due to the [[ and also the "source").

Lightdm on Ubuntu (at least in current 14.10) uses sh to interpret .profile and therefore kacks (popup during login complains of "[[" not found) on that line. changing the [[ ... ]] to "test" and changing "source" to "." makes lightdm really kack (login fails with no diagnostic and returns to the lightm greeter)... so my current workaround is

    #THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
    if [ -n "$BASH_VERSION" ]; then
        [[ -s "/home/clh/.gvm/bin/gvm-init.sh" ]] && source "/home/clh/.gvm/bin/gvm-init.sh"
    fi

which of course means gvm-init.sh is not invoked...  at least not by lightdm, if that was indeed the intention.

I guess another possibility might be to put the line in .bash_profile rather than .profile... to me this seems a reasonable thing to do since it is clear that only bash is meant to invoke .bashrc.

Notes:

1) I originally posted this in the wrong spot, thanks for the correction Marco;
2) there is considerable dispute as to whether lightdm is meant to interpret .profile or not.  for what it's worth, after having thought about it for awhile, I don't think it should; I think that terminal windows are meant to interpret .profile (or of course an RS232 console).  but anyway there is some doubt about this over on launchpad.net and plenty of folk are arguing that it should be disabled in lightdm.

**Comment by marc0der** [comment]
Revisiting this old issue. I really don't think it's SDKMAN's responsibility to create a .bash_profile if it doesn't exist. We will only update a file if it is already present on a system.

Are you still experiencing an issue or can we close this?

**Comment by monetschemist** [comment]
Good morning, Marco,

I changed from gvm to SDKMAN awhile back and I don't believe the .profile
change occurred again.

I may be recalling the situation incorrectly, but I think the problem arose
because the gvm stuff was appended to .profile which is read by sh as well
as bash and the code was not suitable for sh.  Also maybe this was true of
other system components that read .profile.

If there isn't a .bash_profile, or .bashrc, that probably indicates the
lack of .bash use by that user and so creating one would seem to have
little utility.

Why not close it?

On Tue, Jul 5, 2016 at 8:19 AM, Marco Vermeulen <notifications@github.com>
wrote:

> Revisiting this old issue. I really don't think it's SDKMAN's
> responsibility to create a .bash_profile if it doesn't exist. We will only
> update a file if it is already present on a system.
>
> Are you still experiencing an issue or can we close this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sdkman/sdkman-cli/issues/308#issuecomment-230510019>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHgAntpD5SHFupOv-6NXu0JypHUQW70wks5qSnYMgaJpZM4C_WH7>
> .
>



-- 
Chris Hermansen · clhermansen "at" gmail "dot" com

C'est ma façon de parler.

**Comment by marc0der** [comment]
Okay, sorry but didn't really understand the last bit :-)

Al I really wanted to know was are you still having an issue or can I close
this?

**Comment by monetschemist** [comment]
Sure, I think it's safe to close the bug.  I don't seem to have the issue
anymore, anyway.

On Tue, Jul 5, 2016 at 11:12 AM, Marco Vermeulen <notifications@github.com>
wrote:

> Okay, sorry but didn't really understand the last bit :-)
>
> Al I really wanted to know was are you still having an issue or can I close
> this?
> On Tue, 5 Jul 2016 at 19:00, monetschemist <notifications@github.com>
> wrote:
>
> > Good morning, Marco,
> >
> > I changed from gvm to SDKMAN awhile back and I don't believe the .profile
> > change occurred again.
> >
> > I may be recalling the situation incorrectly, but I think the problem
> arose
> > because the gvm stuff was appended to .profile which is read by sh as
> well
> > as bash and the code was not suitable for sh. Also maybe this was true of
> > other system components that read .profile.
> >
> > If there isn't a .bash_profile, or .bashrc, that probably indicates the
> > lack of .bash use by that user and so creating one would seem to have
> > little utility.
> >
> > Why not close it?
> >
> > On Tue, Jul 5, 2016 at 8:19 AM, Marco Vermeulen <
> notifications@github.com>
> > wrote:
> >
> > > Revisiting this old issue. I really don't think it's SDKMAN's
> > > responsibility to create a .bash_profile if it doesn't exist. We will
> > only
> > > update a file if it is already present on a system.
> > >
> > > Are you still experiencing an issue or can we close this?
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/sdkman/sdkman-cli/issues/308#issuecomment-230510019
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AHgAntpD5SHFupOv-6NXu0JypHUQW70wks5qSnYMgaJpZM4C_WH7
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Chris Hermansen · clhermansen "at" gmail "dot" com
> >
> > C'est ma façon de parler.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/sdkman/sdkman-cli/issues/308#issuecomment-230554280
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAI0BgifWnUtZIk2KTkKiCkPqm56b7YYks5qSpu8gaJpZM4C_WH7
> >
> > .
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sdkman/sdkman-cli/issues/308#issuecomment-230557637>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHgAnnR_KKmTFyrOM7dvEWONVsGcDGQ-ks5qSp6egaJpZM4C_WH7>
> .
>



-- 
Chris Hermansen · clhermansen "at" gmail "dot" com

C'est ma façon de parler.

**Comment by marc0der** [comment]
Great, thanks.
