### ISSUE TITLE
Rename GVM to avoid conflict with Golang GVM

### ISSUE THREAD

**Issue by knacht** [sdkman/sdkman-cli#312]
I recently stumpled upon golang and they are using a similar tool with the exact name (gvm)

Therefore it is not possible to use Golang GVM and Groovy GVM since both have the exact same name. 

The Developers of GVM closed an issure regarding the problem, stating golang gvm has existed before grovvy gvm.

https://github.com/moovweb/gvm/issues/82

**Comment by marcoVermeulen** [comment]
It will probably be renamed to `sdk` in the near future, with configurable aliases per deployment. (this will allow us to spin up a _scalaenv_ service for instance)

**Comment by zaxebo1** [comment]
sdk is generally expanded to **"software development kit".**
will the proposed sdk be expanded to the same, or something else.

**Comment by marcoVermeulen** [comment]
@zaxebo1 really don't understand what you're asking. The new name is SDKman, short for Software Development Kit Manager.

**Comment by zaxebo1** [comment]
in your comment (which is just above my comment) dated 6 Jan at https://github.com/gvmtool/gvm-cli/issues/312#issuecomment-68897089 , you had said that

> It will probably be renamed to sdk in the near future, 

Thats why I just asked - what is the fulll form of just  "sdk" name (as said in your 6 Jan comment)?

****

But as you just now said that now it is named SDKman , then my question is now not applicable.

**Comment by mojavelinux** [comment]
> The new name is SDKman, short for Software Development Kit Manager.

I think this name could easy be misconstrued as being masculine and therefore is not a good choice.

I'd like to offer some other suggestions:

* sum (SDK Update Manager)
* sup (Software Updater)
* up (Updater)
* um (Update Manager)
* sdkr (SDK-r)
* summon

I'm really digging the last one, summon. You can see where (Software/SDK Update Manager) fits in the name, but the name itself also means to call for something.

```
$ summon install groovy
```

The name "um" also reads in a pretty humorous way:

```
$ um install groovy
```

**Comment by ctkdev** [comment]
+1 for summon

**Comment by marcoVermeulen** [comment]
A lot has already gone into developing SDKman (inlcuding graphic design,
acquisition of domain plus lots more including complete refactor of
codebase). This was opened to the community by way of a vote, and SDKman
came out popular above all others.

Unfortunately we are way past changing tack again.

BTW, the CLI will read:

    sdk install groovy 2.4.4

**Comment by mojavelinux** [comment]
> This was opened to the community by way of a vote

I follow Twitter and GitHub very closely and I never remember seeing an announcement. I also don't see a reference to it on the forums, so I'm not sure where this vote was held.

**Comment by marcoVermeulen** [comment]
You could try here:
https://twitter.com/sdkmanager/status/603123176315424768

here:
https://twitter.com/sdkmanager/status/604002646530342912

and all tweets in between if you don't believe me.

**Comment by mojavelinux** [comment]
My point is that this issue is about the renaming and yet there's no
discussion of the decision or decision process here. So unless you caught
one tweet go by, you didn't get a vote. Even the tweet thread looks
inconclusive.

**Comment by knacht** [comment]
GVM is now SDKman therefore I'll close the issue
