### ISSUE TITLE
GVM going into offline mode when trying to install groovy

### ISSUE THREAD

**Issue by neowulf33** [sdkman/sdkman-cli#314]
The issue seems to be caused because the following url is inaccessible.

```
$ curl -v http://cast.gvm.io/broadcast/latest
* Hostname was NOT found in DNS cache
*   Trying 107.23.96.64...
* Connected to cast.gvm.io (127.0.0.1) port 80 (#0)
> GET /broadcast/latest HTTP/1.1
> User-Agent: curl/7.37.1
> Host: cast.gvm.io
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Connection: Keep-Alive
< Content-Length: 652
<
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Access Denied (content_filter_denied)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your request was denied because of its content categorization: "Malicious Outbound Data/Botnets"
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">

</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
* Connection #0 to host cast.gvm.io left intact
```

**Comment by marcoVermeulen** [comment]
Maybe a network problem on your side? I haven't had any warnings on Uptime Robot regarding this service being unavailable.

**Comment by wangtengchao** [comment]
Yes, it's the network problem. I have the same problem and solve it by modify /etc/hosts like this:
54.209.85.221 cast.gvm.io

**Comment by marcoVermeulen** [comment]
Be careful though, because these services are hosted on Cloud Foundry, so the IP could change at any time.

**Comment by splix** [comment]
what is the current address?
```
~  host cast.gvm.io
Host cast.gvm.io not found: 3(NXDOMAIN)
```

**Comment by marc0der** [comment]
Broadcasts are served by http://cast.sdkman.io/broadcast/latest.

If you are still using gvm, I suggest upgrading to sdkman.

**Comment by splix** [comment]
Yeah, I realized that gvm is passed away, but it took some time. It's really hard to get it from "_This command is not available in offline mode._" message, even for _gvm selfupdate_. And there're no other information why it could happen. Googling doesn't help much.

Maybe there is a way to make old gvm to produce more informative message, like by making some special response to gvm tool? maybe make `cast.gvm.io` to produce some response (with HTTP error maybe) that will tell that you have to upgrade to sdkman now? even `gvm.io` website is down now, no way to find out that you need to update

**Comment by marc0der** [comment]
I honestly don't think many people are using gvm anymore, so no further work will be done on it. There never was a gvm.io website, and gvmtool.net is permanently redirecting to sdkman.io.

Since this is not an issue with sdkman, I'll close this issue. For usage and help you can use our gitter feed linking off from our website.

**Comment by chendeshen** [comment]
curl -s api.sdkman.io/candidates/groovy
sdk selfupdate force 
export SDKMAN_DIR="/root/.sdkman" && source "/root/.sdkman/bin/sdkman-init.sh"
sdk offline enable
sdk offline disable
sdk install groovy
groovy -v
