### ISSUE TITLE
Zsh: Install doesn't consider ZDOTDIR

### ISSUE THREAD

**Issue by datalogics-kam** [sdkman/sdkman-cli#328]
``ZDOTDIR`` specifies an alternate location for the location of dotfiles in zsh.

I happen to have ``ZDOTDIR=$HOME/.zsh.d``, so the install created a new ``$HOME/.zshrc`` instead of appending to ``ZDOTDIR/.zshrc``

Fortunately, I saw this and fixed it manually.

**Comment by marcoVermeulen** [comment]
Pull requests welcome! :-)

**Comment by marc0der** [comment]
No response for over a year so closing.
