### ISSUE TITLE
Support version files

### ISSUE THREAD

**Issue by HackAttack** [sdkman/sdkman-cli#329]
I don't see a way to set up the right versions of everything without having to remember to do so in my shell every time I change directories to a project. I would like to have some facility like rbenv does with the `.ruby-version` file such that GVM does the right thing automatically.

`gvm switch` still is a manual step, and additionally appears to only work for Grails.

This is similar to #116 except mimic the implementation of rbenv rather than rvm.

**Comment by marcoVermeulen** [comment]
I'm not in favour of having a tool hijacking the shell and changing things on the fly, so this will not become part of the standard gvm behaviour. 

Having said that, feel free to try hooking into the extensions mechanism to achieve this. Pull requests are always welcome on the extensions project.

**Comment by jesperronn** [comment]
Using Ruby and RVM on a daily basis, i find it tedious that gvm cannot automatically select correct Grails version when I'm in a folder.

I will highly recommend implementing it also in gvm. In my experience, it took less than two minutes to become addicted to that behaviour. If you think of it, it's not that magic at all: You will always want the Grails version from your `application.properties` 

A simple way (and perhaps also addressing your point about being too 'magic'), could be:

* shell looks for file named `.grails-version` when you enter a directory. 
* If file exists, read version from here (for example `2.4.2` or `3.0.0`)
* fire `gvm use grails <version>` 

I recall at an earlier stage that RVM would display a green message about the ruby version selected whenever you entered a directory with a `.ruby-version` file. I saw in my console that the message has been removed in recent versions of RVM. I guess users were satisifed with the version switching it provides and safe enough without a specific message. RVM also has other ways of selecting version but that's a longer story which is less relevant here.

For gvm users, I sincerely hope somebody is up to try implement. I highly recommend it, and could not live without it. (perhaps Ruby users are just more focused on convenience than gvm/grails users... :) )

PS. see also first discussion of this feature approx 3 years ago: https://github.com/gvmtool/gvm-cli/issues/46

**Comment by marcoVermeulen** [comment]
Feel free write an extension that does all the above. Pull requests are
welcome!

**Comment by pshirshov** [comment]
From what I can understand this functionality is still missing, right?

**Comment by marc0der** [comment]
Yes that's right, and we won't be adding language specific hacks to sdkman. It is however possible to extend sdkman through extensions which you can write yourself.

**Comment by pshirshov** [comment]
That's sad. Any custom modifications are too inconvenient to be useful for a team.

**Comment by marc0der** [comment]
They can be raised as a PR on the sdkman-extensions project, then all
benefit from these extensions.

Sdkman itself must remain agnostic of what it's serving though.
