### ISSUE TITLE
find: ‘~/.gvm/var/delay_upgrade’: No such file or directory

### ISSUE THREAD

**Issue by tukushan** [sdkman/sdkman-cli#330]
* Xubuntu 14.04
* zsh 5.0.2 (x86_64-pc-linux-gnu) 
* oh-my-zsh
* GVM 2.4.1

To replicate:

```
➜  ~  rm ~/.gvm
➜  ~  curl -s get.gvmtool.net | bash
➜  ~  source "$HOME/.gvm/bin/gvm-init.sh"
➜  ~  gvm install groovy
==== BROADCAST =================================================================
* 23/04/15: Lazybones 0.8.1 has been released on GVM. #lazybones
* 02/04/15: Grails 3.0.1 has been released on GVM. #grailsfw
* 01/04/15: Springboot 1.2.3.RELEASE has been released on GVM. #springboot
================================================================================

Downloading: groovy 2.4.3

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 30.4M  100 30.4M    0     0   125k      0  0:04:07  0:04:07 --:--:-- 37404

Installing:➜  ~  groovy 2.4.3
Done installing!

Do you want groovy 2.4.3 to be set as default? (Y/n): 

Setting groovy 2.4.3 as default.
find: ‘/home/tukushan/.gvm/var/delay_upgrade’: No such file or directory

```

groovy isn't setup on the path, but i can run it via ```~/.gvm/groovy/current/bin/groovy -v```

```gvm current groovy``` shows:
```
Using groovy version /opt/idea/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/tukushan/bin:/home/tukushan/software/mongo_current/bin:/home/tukushan/software/play_current:/bin:/home/tukushan/software/sbt/bin
find: ‘/home/tukushan/.gvm/var/delay_upgrade’: No such file or directory
```

**Comment by tukushan** [comment]
After the restart the error goes away. May be related to https://github.com/gvmtool/gvm-cli/issues/317

**Comment by ilmoralito** [comment]
Same Error label, after installing gvm 

find: `/home/sherlock/.gvm/var/delay_upgrade': No such file or directory

**Comment by ilmoralito** [comment]
After restart no more label but grails is not working

➜  ~  gvm list grails
==== BROADCAST =============================================

ONLINE MODE RE-ENABLED! All functionality now restored.

============================================================
------------------------------------------------------------
Offline Mode: only showing installed grails versions
------------------------------------------------------------
                                                            
 * 2.2.3
------------------------------------------------------------
* - installed                                               
> - currently in use                                        
------------------------------------------------------------
➜  ~  gvm use grails 2.2.3

Using grails version 2.2.3 in this shell.
➜  ~  grails
zsh: command not found: grails
➜  ~

**Comment by marcoVermeulen** [comment]
I've rolled out release 2.4.2 which should fix this. Could you please test this for me, and if fixed close the issue?

**Comment by thekalinga** [comment]
I did a fresh install on ubuntu 14.04 with oh-my-zsh & jdk8. I dont see this issue anymore, but after installing spring boot & restarting the terminal spring command does not work

**Comment by thekalinga** [comment]
If I modified `gvm-init.sh` & added the following two lines at the start

```sh
echo "GVM_INIT => $GVM_INIT"
echo "PATH => $PATH"
```

it outputs

```
GVM_INIT => true
PATH => /home/user/.nvm/versions/node/v0.12.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

which means someone is setting GVM_INIT to true much earlier in lifecycle, without populating the PATH.

Current workaround for me is to add

```sh
export GVM_INIT=false
```

to the line just before GVM initialization line in the .zshrc file

my current working .zsh lloks like

```sh
....
...

export GVM_INIT=false

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/home/user/.gvm/bin/gvm-init.sh" ]] && source "/home/user/.gvm/bin/gvm-init.sh"
```

**Comment by marcoVermeulen** [comment]
@thekalinga I just set up a fresh docker container with the entire tool chain (ubuntu + jdk8 + zsh) and it works perfectly. My suspicion is that you have an incorrectly configured system.

BTW, my machine is Arch Linux, JD8, also with zsh + ohmyzsh and everything is working perfectly.

**Comment by thekalinga** [comment]
@marcoVermeulen Thanks for letting me know..

I'm not sure who might be setting GVM_INIT without updating the PATH. May be its a residue from previous installations.

For now, I'll go ahead with this workaround. I'll wait to see if any one else is also facing the same issue.

**Comment by marcoVermeulen** [comment]
Might also be worth mentioning that I've seen some strange interaction with
RVM in the past. If you are using it, try commenting it out temporarily to
see if that does it.

**Comment by thekalinga** [comment]
Thanks for you suggestion. However, I have not used RVM till date. Only NVM (node version manager). Not sure if that can interact with GVM in anyway

**Comment by marcoVermeulen** [comment]
Any news on this? Can we close this issue?

**Comment by andreasguther** [comment]
Last night I did a brand new installation of Mint Linux. When I installed gvm I got the same error message. I do not think I have a messed up installation. I basically installed the OS, installed Oracle Java SDK (left OpenJDK installed), Groovy, curl, all with apt-get, then gvm with curl and finall using gvm to install more. I saw the same problem on another fresh installation I did about two weeks ago. I would suggest creating a clean installation using a VM player. I am confident you will be able to reproduce the problem.

**Comment by marcoVermeulen** [comment]
Would be great if we could get to the bottom of this but unfortunately I
need a lot more information.

Firstly, are you installing the oracle jdk through apt-get, and if so, are
you using a PPA? Next, why are you installing Groovy with apt? That is what
GVM is for. What version of Mint are you using?

Next the shell, are you using ZSH or bash? If you are using ZSH, is it with
ohmyzsh or prezzto? If with bash, are you running /bin/sh or /bin/bash as
your shell?

When reporting an error, please give all the information needed so we can
try making the best diagnosis possible.

BTW, I just spun up a docker instance of ubuntu (aka mint) on my machine. I
installed openjdk 8, then curl and unzip. I installed gvm with curl, then
groovy with gvm and all worked fine as usual.

**Comment by rbauduin** [comment]
I just had this problem on a CentOS 7.
When I log out then back in, I don't have the problem anymore.
I saw bin/sdkman-init.sh does a `touch "${SDKMAN_DIR}/var/delay_upgrade"`. Maybe this is not done in the install procedure but only when logging in?

**Comment by marc0der** [comment]
A question: after the install procedure, did you source this file as instructed? This should have created the file.
