### ISSUE TITLE
Proposal for GVM cache 

### ISSUE THREAD

**Issue by corneil** [sdkman/sdkman-cli#337]
I would like to propose a GVM cache facility.
In enterprise environments you invariably run into issues around proxy servers or network usage for large teams.
By provide a cache mechanism on the network user can configure gvm to the location of their local cache server and only connect to the cache.
The cache could be a file tree behind a Web server or a binary repository like Archiva, Nexus or Artifactory.

This leads me to think that gvm could benefit from considering the artifacts as items in binary repository.

**Comment by marcoVermeulen** [comment]
GVM/SDKman can be installed on premises for clients. Please contact me if you would like help to have this set up in your enterprise.

It would be trivial to point GVM at any binary repository, as it merely acts as a broker. BTW, all the groovy binaries are currently hosted on Bintray, which is backed by Artifactory as far as I know.

**Comment by marc0der** [comment]
As a cache is not really a viable solution, can we close the issue?
