### ISSUE TITLE
Install Java JDKs with SDKMAN!

### ISSUE THREAD

**Issue by zaxebo1** [sdkman/sdkman-cli#338]
please offer to install "openjdk/openjre" also through gvm

**Comment by zaxebo1** [comment]
something like

* jEnv https://github.com/linux-china/jenv (bash shell) 
          http://jenv.io/

jenv-ps https://github.com/linux-china/jenv-ps   (power shell)

functionality can be implemented into gvm itself.

*****

jenv: the Java enVironment Manager  ( http://jenv.io/ )
jenv is a tool for managing parallel Versions of Java Development Kits on any system, such as Linux, Mac and Windows. It provides a convenient command line interface for installing, switching, removing and listing Candidates.

Both jEnv and gvm are written in bash. And are having separate implementations.
This jEnv functionality can well be - 'part of gvm'/'reimplemented in gvm from scratch' .  As both are complementary projects.

**Comment by marcoVermeulen** [comment]
We have explored this before, and jenv is _very_ different in nature. We do not support platform specific binaries at the moment, but will consider doing so in the future once we have migrated to SDKman.

**Comment by fmarot** [comment]
@marc0der just a remark: you should explicitly state on the front page of the website that SDKman does "not support platform specific binaries at the moment". First time I saw the project I really wondered "so how do I install the JDK ?!".
Regards.

**Comment by culmat** [comment]
:+1:

**Comment by adzubla** [comment]
Is there any plan do add JDK managment?
For a tool called sdkman! it would be good do embrace THE main sdks used by everyone...

**Comment by marc0der** [comment]
For sure it's going to happen. Only problem is that jdks are platform specific, not universal so we need to do some work to accommodate all flavours of these sdks. Another complication is that we need give an option for users to agree to the EULA associated with Java SDKs.

**Comment by marc0der** [comment]
Just to let everyone know that this is the very next thing on the roadmap. JDKs coming soon!

**Comment by shyiko** [comment]
@marc0der you might wanna check [shyiko/jabba](https://github.com/shyiko/jabba) out (it offers cross-platform JDK installation/management)

**Comment by solvingJ** [comment]
@marc0der Thanks for taking this on! Very cool feature.  Can't wait to try it. Any ETA?

**Comment by marc0der** [comment]
The first pilot will roll out on our beta channel later this week. We will release Java 8 on Linux as a first stab, then release on Mac OSX shortly afterwards. You can join the beta channel by following the instructions on the installation page of our site.

**Comment by solvingJ** [comment]
Thats awesome, thank you!
Actually, I just realized that this project is for regular sdkman and i use the posh-gvm port. What needs to happen for it to reach that project?

**Comment by marc0der** [comment]
Yes, unfortunately PoshGVM has gotten far out of date as the contributor no longer seems to have time.

That said, anyone who knows powershell would be more than welcome to update it and raise a PR 🙂
