### ISSUE TITLE
Support for old codehaus-hosted versions

### ISSUE THREAD

**Issue by mcandre** [sdkman/sdkman-cli#350]
For archival purposes, it would be good if gvm could install really old, codehaus-hosted versions of Groovy.

Archive.org maintains copies of some of these, e.g. v1.0:

http://web.archive.org/web/20150508090325/http://dist.codehaus.org/groovy/distributions/

**Comment by marcoVermeulen** [comment]
We currently only rely on binaries found in BinTray. If these libraries are ported over to BinTray, we would be happy to point to them from GVM.

**Comment by mcandre** [comment]
I haven't used BinTray before, but it sounds great!

How do we add these legacy versions to BinTray?

**Comment by marcoVermeulen** [comment]
The guys at bintray need to add them. Maybe raise a request with them
directly?

**Comment by marc0der** [comment]
Can we close this issue?
