### ISSUE TITLE
moving from .gvm to .sdkman breaks links to sdks in IDEs

### ISSUE THREAD

**Issue by pmcneil** [sdkman/sdkman-cli#356]
Very minor issue: I used GVM to install versions then point my IDE at those SDKs. The upgrade which changed the name to SDKman (which is sensible) moved the SDKs to .sdkman and broke the IDE links to SDKs...

It might be nice to create a soft link to .gvm when upgrading (not when just installing) to maintain backwards compatibility?

**Comment by marcoVermeulen** [comment]
That's been done and released as 3.0.2.
