### ISSUE TITLE
GVM -> SDKMAN issues (OSX, Travis)

### ISSUE THREAD

**Issue by robertoschwald** [sdkman/sdkman-cli#357]
Yesterday, we were hit by upgrade issues on out OSX machines. GVM suddently didn't work at all. All Grails / Groovy installations were gone and gvm call caused "no such file or directory".

gvmtool.net website causes 404, the link to the documentation as well. 
A small notice on both sites what happened and how to fix upgrade issues on those sites would have helped a lot.

Today we got similar issues in Travis.
https://travis-ci.org/robertoschwald/grails-audit-logging-plugin/builds/80973628

All in all my personal feeling is that the transition causes a lot of pain, due to the lack of upgrade documentation for people like me who do not follow GVM tool. It took a while and digging to find out that GVM tool is now SDKMAN.

**Comment by marcoVermeulen** [comment]
If you upgrade using the latest version (3.0.2 at this time) all should work. I've added a symlink to ensure backward compatibility. You might need to update your config variables to have a `sdkman_` prefix though for the auto-answer to work.

BTW, have you considered using the [bin/download.sh](https://github.com/sdkman/sdkman-cli/blob/master/bin/download.sh) script instead? It was purposefully introduced for CI environments and is a lot less error prone in your build. SDKMAN is a developer tool, not a CI tool.

**Comment by marcoVermeulen** [comment]
Closing this issue now.
