### ISSUE TITLE
Cannot Switch to Non-default Grails Version 

### ISSUE THREAD

**Issue by rdgoite** [sdkman/sdkman-cli#360]
Whenever I switch to a Grails version that's not the default set previously, I get:

    Error: Could not find or load main class org.codehaus.groovy.grails.cli.support.GrailsStarter

when I try to run any command. 

Some details about my development environment:
* Mac OS X 10.10.5
* Java 1.7.0_75
* SDKMAN 3.0.2

To reproduce the error (assuming multiple installation of Grails 2.4.4 and 2.5.1):
<ol>
<li>Open a terminal window.</li>
<li>Set Grails 2.5.1 as the default: <code>sdk d grails 2.5.1</code></li>
<li>Open another terminal window and check which version of Grails is in use: <code>grails --version</code>. If the previous step worked, it should state that Grails 2.5.1 is in use.</li>
<li>Switch to Grails 2.4.4: <code>sdk u grails 2.4.4</code></li>
<li>Check which version of Grails is now in use: <code>grails --version</code>. At this point, the error should be thrown.</li>
</ol>

**Comment by kaskelotti** [comment]
I'm having very similar issues that started to appear after GVM -> SDKMAN upgrade.

Environment is
- Cygwin running on Win 7
- JAVA 1.6.0_45
- SDKMAN 3.0.2

**Comment by rdgoite** [comment]
According to SDKMAN on Twitter:

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">If already upgraded on OSX and having issues, please try step 4 here: <a href="http://t.co/ZXXsK45Gb8">http://t.co/ZXXsK45Gb8</a></p>&mdash; SDKMAN! (@sdkmanager) <a href="https://twitter.com/sdkmanager/status/644656346407768064">September 17, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Step 4 involves updating bash config files (`.bashrc` and/or `.bash_profile`) so that the shell calls the sdkman init script correctly. I have set up my system such that in `.bash_profile`, the `.bashrc` script gets called (when it exists). I discovered that, after the installation, sdkman updated `.bashrc` with something like:

```
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
[[ -s "/Users/me/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/me/.sdkman/bin/sdkman-init.sh"
```

Since I have configured my environment such that in `.bash_profile`, `.bashrc` gets called before alsmot any other commands, I had 2 options:

* Move those init lines above to the end of `.bash_profile`.
* Update `.bash_profile` such that it calls `.bashrc` last.

I picked the first option (for now) as I'm not sure if running the sdkman script in a non-login shell makes sense to me at the moment. There's also a similar line for the previous GVM installation that I removed from `.bash_profile`. This seems to have addressed the issue for my environment.

**Comment by kaskelotti** [comment]
Thanks for the greate info @rdgoite!

In my case, the `.bashrc` file was updated by sdkman correctly, but `.bash_profile` still contained references to gvm. I manually updated the `.bash_profile` file to have same init operation as `.bashrc` and works fine.

**Comment by marcoVermeulen** [comment]
Cool, well spotted. I'm updating the selfupdate script to include this file too. I'll release it shortly as version  3.0.3.

**Comment by marcoVermeulen** [comment]
Please let me know if that solved it. If so, can I close this issue?

**Comment by rdgoite** [comment]
Well, like I said previously, updating my bash config (manually) addressed the issue for me.

**Comment by marcoVermeulen** [comment]
Cool, so please close the issue then.

**Comment by rdgoite** [comment]
Oh, I thought you were going to close it.
