### ISSUE TITLE
Setting Default Grails Version is Applied to All Open Terminals/Shells

### ISSUE THREAD

**Issue by rdgoite** [sdkman/sdkman-cli#361]
Whenever I set the default Grails version in any open shells, the default gets applied to all other shells that are open during the switch.

To reproduce the issue (assuming default is set to Grails 2.5.1):
<ol>
<li>Open two (or any number more than 1) terminal windows.</li>
<li>Set one of the open terminals (let's call it T1) to use a different Grails version, say: <code>sdk u grails 2.4.3</code>.</li>
<li>In the other (or another) window (let's call T2), set the default to a different Grails version that was set previously, say: <code>sdk d grails 2.5.0</code>.</li>
<li>Go back to T1 (or switch to any other terminal window that's not T2), and check what Grails version is currently in use. In my tests it's switched into the one in the previously set as default (e.g. Grails 2.5.0), although since <a href="https://github.com/sdkman/sdkman-cli/issues/360">there's an issue with switching among Grails versions</a>, I get an error message.</li>
</ol>

**Comment by rdgoite** [comment]
This is still problem even after <a href="https://github.com/sdkman/sdkman-cli/issues/360#issuecomment-142482631">I've worked around the issue with switching among Grails versions</a>.

**Comment by marcoVermeulen** [comment]
Very odd, mine acts completely as expected. I've tested it both on my own machine and on a unspoiled docker container running ubuntu. In both cases it works exactly as it should.

If anybody else experiences this issue, please let me know and I'll look into it.

**Comment by rdgoite** [comment]
What's your local setup? I'm using Mac OS X 10.10.5.

**Comment by marcoVermeulen** [comment]
I'm on Linux, but OS doesn't really have an effect on this. What really matters is the kind of shell. I tried the scenario using ZSH and bash, and ran this on both Linux and FreeBSD (OSX is derived from BSD) to be sure. I see no difference.

I have a hunch that you might have some weirdness going on in your local environment as nobody else seems to be having such issues. Lets keep this one open though, in case we find others that do have this problem.

**Comment by marc0der** [comment]
Is this still an issue or can we close it?

**Comment by rdgoite** [comment]
The issue seems to be fixed with the sdkman that I'm currently using, which is version 5.0.0+51.

**Comment by marc0der** [comment]
Awesome, thanks!
