### ISSUE TITLE
"use" dosn't work unless there is a default version

### ISSUE THREAD

**Issue by SparkyBluefang** [sdkman/sdkman-cli#363]
With the changes in 651bf3c746daf64f78a78571b0fb902807c10a0d, the "use" command no longer works all the time.

"use" will update PATH if the candidate is already in PATH, however it will not add it to PATH (or it silently fails).

A work around is to set a default version so that "${SDKMAN_DIR}/${CANDIDATE_NAME}/current" exists and is added to PATH when sdkman is sourced.

**Comment by oshwardo** [comment]
I also see that it doesn't work at all, even with a default set.

Have fully re-installed sdkman, but still no joy.

(Environment; CentOS & Bash )

**Comment by marcoVermeulen** [comment]
@SparkyBluefang Is this when you first install the candidate? Can you give me a a sequence of steps to replicate this?

**Comment by marcoVermeulen** [comment]
This has been deployed as 3.0.5. Can you confirm that it's fixed please?

**Comment by oshwardo** [comment]
Hi Marco, I can confirm that this is now fixed.

Many thanks
