### ISSUE TITLE
Scala is not a candidate

### ISSUE THREAD

**Issue by ace-subido** [sdkman/sdkman-cli#365]
Got a new machine and I'm trying to install scala via sdkman since this is much more convenient. Documentation states I can do `sdk install scala`:

<img width="869" alt="screen shot 2015-09-30 at 10 19 08 am" src="https://cloud.githubusercontent.com/assets/730800/10182866/07733cbc-675c-11e5-8527-14c8cfb4bbdb.png">

But based on `sdk list` Scala is not a candidate. Am I missing something?

**Comment by marcoVermeulen** [comment]
It's coming very soon!

**Comment by ace-subido** [comment]
Thanks for the reply! Any PR link? Searched `scala` on the Pull Requests, couldn't find any. I'd like to help out on whatever I can :)

**Comment by marcoVermeulen** [comment]
One of the beauties of sdkman is that it's completely agnostic of the SDKs
that it serves. It's simple an entry in the database and from there on it
will work.

We are currently making a few small improvements before opening the gates
to the Scala ecosystem. Hang in there!

**Comment by marc0der** [comment]
Scala is now available. More coming soon!
