### ISSUE TITLE
latest upgrade broke installation

### ISSUE THREAD

**Issue by danmcharness** [sdkman/sdkman-cli#366]
existing working plain-jane installation of sdkman v3.0.4 on linux where the .bashrc is updated by sdkman.

sdkman announces v3.0.5 availability, so I run 'sdk selfupdate', with normal output. However, any subsequent sdk commands no longer work even though $SDKMAN_DIR is set correctly.

now running 'sdk' from a new console reports back 'No command 'sdk' found'.

**Comment by GsusRecovery** [comment]
Forgive me in advance for the dumb question (i have just updated to 3.0.5 and all seems to work correctly): after the upgrade have you executed in a new terminal the following commands?
```bash
export SDKMAN_DIR="${HOME}/.sdkman" && source "${HOME}/.sdkman/bin/sdkman-init.sh"
```

**Comment by danmcharness** [comment]
yup - that's where I said "in a new console".

No biggie.... I just blew away the install and reinstalled.

Dan McHarness
*printed on recycled data*

**Comment by GsusRecovery** [comment]
Mine was only a blind shot, all's well that ends well.

**Comment by marcoVermeulen** [comment]
Okay, closing this one then.
