### ISSUE TITLE
Cant install due to syntax error

### ISSUE THREAD

**Issue by anixan** [sdkman/sdkman-cli#368]
Hi,

I have a new Ubuntu 14.10 LTS server and when I run the following:

    curl -s http://get.sdkman.io | bash

I get the following error:

    syntax error near unexpected token `newline'
    bash: line 1: `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">'

**Comment by GsusRecovery** [comment]
Seems like you have trouble reaching the install script. bash is showing you the first line of the input ( a doctype tag of a webpage). 

Are you beyond a proxy server? Or are you using a wifi network with a captive portal (redirect all your http request to authentication page)?

Try to open http://get.sdkman.io in the browser, in the correct behaviour you have to see a bash script (black/white text file starting with #!/bin/bash).

You can also see the full (html) output simply using more or less:

```bash
curl -s http://get.sdkman.io | less
```

**Comment by anixan** [comment]
Hi,

Thanks for the reply you are right it appears to be a firewall issue.

This can be closed.

Thanks

**Comment by marcoVermeulen** [comment]
Yes, it seems like you are being blocked by a proxy.
