### ISSUE TITLE
how to access installed candidate

### ISSUE THREAD

**Issue by dmoran-epages** [sdkman/sdkman-cli#370]
Hello.

After successfully installing sdkman (to a custom location).

`> sdk install springboot` .. fine
 `> sdk use springboot`
   `Using springboot version 1.2.6.RELEASE in this shell`

`> sdk spring `
 `...cant find spring ....`  am I missing something?

note

`> ./sdkman/springboot/current/bin/spring`
 works fine, but i dont need sdkman if im going to be manually entering paths to the installed sdks on the command line right?

**Comment by marc0der** [comment]
Please read the documentation found at http://sdkman.io before raising an issue. If you still have questions, please join the Gitter user chat where someone will help you.
