### ISSUE TITLE
grails is sourced from github, but could come from bintray, thereby bypassing corporate firewall blocking of guthub

### ISSUE THREAD

**Issue by GordonRehling** [sdkman/sdkman-cli#372]
http://grails.io says that grails releases are available on bintray as well as github.

To help those of us who are behind very un-trusting corporate firewalls, could sdkman be altered to change reference bintray rather than github for the grails candidate?

**Comment by marcoVermeulen** [comment]
This should be raised with the Grails team directly as they publish their own versions.

However, if they consent we could look at changing the existing versions to point to bintray.

**Comment by marcoVermeulen** [comment]
Copying @graemerocher into the conversation.

**Comment by marc0der** [comment]
Closing this issue as it should be raised with Grails itself. The Grails team publish their own releases, and hence are in control of what appears on sdkman.
