### ISSUE TITLE
Move candidate folders into dedicated candidates folder

### ISSUE THREAD

**Issue by marc0der** [sdkman/sdkman-cli#374]
At the moment, all candidate folders are placed in the top level `.sdkman` folder. With many new candidates about to be added, it would be preferable to place all candidates in a `candidates` folder beneath `.sdkman/` so that Groovy would be under `~/.sdkman/candidates/groovy`.

At the same time we should perform a migration of the existing folders to the new structure on selfupdate.

**Comment by flofreud** [comment]
Alternatively we could also move all non-candidate folders into a dot-folder and therefore avoid to break references to installed candidates, again. I believe there are several people using gvm to install candidates, eg grails, and reference the sdkman-paths in their IDEs. Additionally from the users point of view the relevant content inside of the `~/.sdkman` folder are the candidate folders and I believe they should be easily to reach. The dot-folder could be `~/.sdkman/.core`. 

But a change of the init-script location could also break several environments like seen after the renaming.

**Comment by marcoVermeulen** [comment]
At the moment we are mimicking something like a small Unix environment
inside the .sdkman folder, so it would be preferable to keep the main
structure as it is. As you also pointed out, moving the location of the
init scripts could break a lot of things.

I propose we create symlinks to all installed moved candidates in the top
level directory, guaranteeing backward compatibility. Although newly
installed candidates will begin their life in the candidates folder and
never get a symlink. In doing so we slowly and gracefully phase out the old
location.

**Comment by marc0der** [comment]
Completed and rolled out in version 3.2.0.
