### ISSUE TITLE
sdkman upgrade replaces symlink with file in a dotfiles configuration

### ISSUE THREAD

**Issue by taterpeel** [sdkman/sdkman-cli#379]
In a common dotfiles setup, resource files (pertinent ones here being .bashrc and .zshrc) are symbolic links pointing to a the file in another directory.  During the upgrade from gvm to sdkman, my symlink was clobbered and replaced with an actual file rather than following the link to update the file in my local dotfiles repo.

**Comment by marc0der** [comment]
Usually dotfiles are NOT set to symlinks. Nowhere have I advised that you should do so in the documentation. It is however possible to change the install location to something other than `~/.sdkman` by exporting the `SDKMAN_DIR` environment variable before installation.

Please see the [Installing to a Custom Location](http://sdkman.io/install.html) section of the install page for more details.

**Comment by taterpeel** [comment]
I'm using a standard installation for sdkman itself. What is non-standard is my shell configuration.  My .zshrc file is not in the standard location. I am using a [dotfiles](https://dotfiles.github.io/) set up so my $HOME/.zshrc is actually a symlink to $HOME/dotfiles/zsh/zshrc.  When I upgraded from gvm to sdkman, my .zshrc symlink was replaced with a regular file.  I assume that it happens at the point where ${sdkman_init_snippet} is being appended to .zshrc.  I found the code in install.sh that does a simple redirect/append (>> operator) to the file, but when I tested that operator with symlinks on the command line, it resolved symlinks to real files.  So, perhaps a different procedure is being performed when the old gvmtool snippet gets replaced with the sdkman snippet?

**Comment by marc0der** [comment]
The upgrade was performed here in the [selfupdate.sh](https://github.com/sdkman/sdkman-cli/blob/master/src/main/bash/selfupdate.sh#L105) file. This is responsible for doing a `sed` and replacing the original content of the files.

Can you confirm that it works with your dotfiles setup?

**Comment by kdabir** [comment]
I also faced the same issue. I recently realized when changes to symlinked files in dotfiles repo were not reflecting the changes. I found out that symlinks in $HOME were replaced with the files. Hopefully it was only because of GVM->SDKMAN update and would not affect regular sdkman updates.

**Comment by marc0der** [comment]
So with no further response I presume that this is no longer an issue and closing.
