### ISSUE TITLE
when installing over gvm, existing installs are not listed

### ISSUE THREAD

**Issue by gernotstarke** [sdkman/sdkman-cli#380]
I had groovy, gradle, grails etc. installed via gvm in multiple versions each.

After the proposed installation of sdkman, these (existing) versions are not "listed"
anymore, e.g.

    sdk list gradle

does NOT show ANY installed version.

Running gradle (or the other installed tools) is still possible.

when I run:

    sdk install gradle

I get:

    stop! gradle 2.8 is already installed.

**Comment by marc0der** [comment]
I would need some more specific information. If we choose a single candidate, say Gradle, what versions do you have installed and which is the current version?

You can determine this by doing an `ls -lah ~/.sdkman/candidates/gradle`

**Comment by gernotstarke** [comment]
Marco, will be back on my computer on weekend... so anser to your question will take that long... 
thx Gernot

**Comment by marc0der** [comment]
Has this subsequently been resolved? If so, can we close it?

**Comment by gernotstarke** [comment]
ok for me.

Gernot

**Comment by marc0der** [comment]
Great, thanks!
