### ISSUE TITLE
How about adding feature like jenv.

### ISSUE THREAD

**Issue by hujianxin** [sdkman/sdkman-cli#385]
Hi, today, I tried sdkman-cli and it's awesome. But, I can't find the command like `sdk local` and `sdk global`. So,  how about adding freatures like jenv.

I'm a java and groovy beginner. So, this work is beyond my ability. And, it's just a =Little advice=

**Comment by marc0der** [comment]
Please note that this is not a forum for user discussion, but for addressing development features and bugs. For usage discussion please consider using gitter.

Complete instructions on how to use sdkman can be found on our site at http://sdkman.io
