### ISSUE TITLE
vertx 3.2.0 installed failed.

### ISSUE THREAD

**Issue by abcfy2** [sdkman/sdkman-cli#395]
The ``vertx-3.2.0.zip`` is different from ``vertx-3.1.0.zip``, it has no the parent dir that named ``vert.x-3.2.0``

Wish to fix this issue.

**Comment by marc0der** [comment]
This was fixed a few hours after they published their binary. To recover do:

    sdk uninstall vertx 3.2.0
    sdk flush archives
    sdk install vertx

That should fix it for you.
