### ISSUE TITLE
Groovy is not running after install

### ISSUE THREAD

**Issue by aplatypus** [sdkman/sdkman-cli#396]
I have left a post with more details on StackExchange:

*  http://unix.stackexchange.com/questions/249814/what-other-steps-to-run-groovy-by-using-the-sdkman-install-instructions

Groovy doesn't run after install via the sdk.  I followed the steps on the installing Groovy with the sdk.  When I tried the 

      groovy -version

I'm told groovy is not installed and to use apt-get!

I think there are more steps required; or the install operation needs to do more.

**Comment by abcfy2** [comment]
Try:

    sdk u groovy

**Comment by aplatypus** [comment]
@abcfy ... I guess you didn't look tat the details on stackexchange:

*  http://unix.stackexchange.com/questions/249814/what-other-steps-to-run-groovy-by-using-the-sdkman-install-instructions

Use had no effect.  I've updated the question with same error message, for clear description what (doesn't) happen.

**Comment by abcfy2** [comment]
It might be something wrong with your ``PATH`` env.

     $ echo $PATH

Is there any ``.sdkman`` path in your ``$PATH`` ? And open a new terminal, type again.

**Comment by aplatypus** [comment]
Thanks 

abcfy2 - I was taking guidance from the install instruction steps on 
*  groovy language page
   *   http://www.groovy-lang.org/install.html

Now you mention it, the steps there are not the same as the steps on 
*   http://sdkman.io/

As you've outlined them.  I will apply the up to date procedure.

In the meantime, I just wanted to know why the simple instructions, quoted as: "nothing more to do" seemed to require more to be done.

As an experiment I logged in to a fresh session, and volia! ...

       $ groovy -version
          Groovy Version: 2.4.5 JVM: 1.8.0_66 Vendor: Oracle Corporation OS: Linux

It worked also.

Looks like there's some documentation changes needed on the Groovy-language **install**-s.

Thanks for your help with this.

**Comment by crazy4groovy** [comment]
Same issue! Wow, turns out a new ssh shell did the trick :) Thanks so much for the sdk tool, but it would be sooo helpful to see a prompt for this.

```
root@ubuntu:~# echo $JAVA_HOME
/usr/lib/jvm/java-8-oracle
root@ubuntu:~# sdk i groovy

Downloading: groovy 2.4.5

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 34.7M  100 34.7M    0     0  1004k      0  0:00:35  0:00:35 --:--:-- 1011k

Installing: groovy 2.4.5
Done installing!

Do you want groovy 2.4.5 to be set as default? (Y/n): Y

Setting groovy 2.4.5 as default.
root@ubuntu:~# groovy -e "println 1"
The program 'groovy' is currently not installed. You can install it by typing:
apt-get install groovy
```

< /confusion > 

:+1:

**Comment by marc0der** [comment]
Has this confusion been resolved yet? If so, can we close this issue?

**Comment by aplatypus** [comment]
yes it is running now.

On 5 July 2016 at 07:14, Marco Vermeulen <notifications@github.com> wrote:

> Has this confusion been resolved yet? If so, can we close this issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sdkman/sdkman-cli/issues/396#issuecomment-230354857>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEF1JVQsnTbUULvmb2oZy80qUT-9rhCks5qSXfEgaJpZM4G227K>
> .
>



-- 
aloha,
         \_w_/
 ___________________________________
    º  http://www.facebook.com/will.2016
