### ISSUE TITLE
Idea of a "local" setting?

### ISSUE THREAD

**Issue by seanleblanc** [sdkman/sdkman-cli#400]
The jenv project has an idea of "local" vs. "global" default for managing JDKs. I'm wondering if sdkman has any notion of this, or any plans of adding this.

"Local" pertains to the current directory. When bouncing around between various versions of grails, for example, this could be a killer feature.

**Comment by marc0der** [comment]
We already have this in the form of the [extensions](https://github.com/sdkman/sdkman-extensions). We have an one called `switch`, which switches to the Grails version of the containing folder on your behalf. New extensions can easily be added as required.

In future, please consider asking for help on our [gitter user-issues](https://gitter.im/sdkman/user-issues) channel before raising issues on Github.
