### ISSUE TITLE
[Improvement] Add build.properties files to grails folders

### ISSUE THREAD

**Issue by PachiNoSay** [sdkman/sdkman-cli#403]
In Groovy Grails Tools Suite GGTS (and similar Eclipse products) when add a new Grails compiler you can only set the name and select the folder but if the folder not contains a build.properties file with only one propertie (i.e: grails.version=2.4.4) then the wizard not recognize as apropiated compiler folder and not continue.
When I download a grails compiler in zip file the build.properties exists with the corresponding version.
![grails-2](https://cloud.githubusercontent.com/assets/16719806/12354536/70dbb0a4-bb75-11e5-83b5-7af1973500ec.png)

**Comment by marc0der** [comment]
This is not an sdkman problem, as we merely redirect to the zip found on the Grails download page. You would have to raise this with the Grails team, or otherwise with GGTS.
