### ISSUE TITLE
Maven command `mvn.cmd` is created without execution rights (Win 8.1 + cygwin)

### ISSUE THREAD

**Issue by abelsromero** [sdkman/sdkman-cli#404]
I checked that the maven command is created without execution permissions. None of the users get execution.
This does not happen when downlading a standard maven binary distribution and doing a manual installation.

This does not prevent the executable to be used from a shell, but causes an error from some tools that create "fork" processes like 'maven-invoker-plugin'.
This can be fixed either from Windows or just adding the execution permisions using `chmod` from cygwin shell.
I see it happens also for ant.

Could the chmod command be integrated during the installation?

**Comment by marc0der** [comment]
We do not make _any_ changes to the binary you receive on sdkman. We merely redirect curl to the original binary hosted on their respective sites. We then simply unzip it and add it to the PATH. I suggest following this up with the respective teams.

**Comment by abelsromero** [comment]
I dug further and found out it's kind of and historical issue with the unzip command in cygwin, it just "forgets" the exec permission. Really, not much can be done about unless permissions are check explicitly by sdkman.

Feel free to close the issue.

**Comment by marc0der** [comment]
Thanks for investigating.
