### ISSUE TITLE
latest lubuntu: after upgraded into sdkman: some missing installations

### ISSUE THREAD

**Issue by tkassila** [sdkman/sdkman-cli#405]
Hi,
after upgrading into sdkman after gvm, later I noteced, that some installations are either missing or can be executed, but not listed by list command. Not corrected after reinstallation (not listed) an upgraded version by a software. By removing the content of .sdkman and reinstall sdkman, normal function returned into installed softwares.

**Comment by marc0der** [comment]
Silly question, but did you manage to re-source sdman-init.sh?

**Comment by tkassila** [comment]
None re-executing or like that of SD...init.sh or manual editing the script
or another SDK files, or installed apps.
22.1.2016 3.15 ip. "Marco Vermeulen" <notifications@github.com> kirjoitti:

**Comment by marc0der** [comment]
Sorry, didn't understand that. Has this been resolved?

**Comment by tkassila** [comment]
Yes, it has been resolved by me at the first try

**Comment by tkassila** [comment]
Hi, I have resolved this issue. And I marked this closed and resolved on
github. Thanks, Tuomas

2016-07-04 23:04 GMT+03:00 Marco Vermeulen <notifications@github.com>:

> Sorry, didn't understand that. Has this been resolved?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sdkman/sdkman-cli/issues/405#issuecomment-230348478>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAF0AwbO-7mG9RZsvZ5kUlpQ0yrCTTBCks5qSWdqgaJpZM4HKSgg>
> .
>



-- 
Tuomas Kassila
tuomas.kassila@gmail.com
