### ISSUE TITLE
Leaves out colon when prepending to PATH

### ISSUE THREAD

**Issue by asuraphel** [sdkman/sdkman-cli#412]
I went further to figure out this issue and run the comand: 
`which gradle` which gave me `/usr/lib/gradle`

Then I echoed my env var `PATH` which gave me: 
`/home/asuraphel/.sdkman/candidates/groovy/current:/home/asuraphel/.sdkman/candidates/grails/current:/home/asuraphel/.sdkman/candidates/gradle/2.7/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/asuraphel/packer`

Went to see /etc/environment and found out the `PATH` variable is set to: 

`PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"`

It appears that sdkman forgets the last trailing `:` when prepending to the `PATH` variable. 

Looks like the issue is around the area ...kman/candidates/gradle/2.7/usr/local/sbin:/usr/loc..

**Comment by marc0der** [comment]
I've tried replicating this issue on several machines (including a fresh docker container) but can't seem to get the same results. Are you still experiencing this problem?

In addition, looking at [this line](https://github.com/sdkman/sdkman-cli/blob/731b28c7bd5bcdc542e8b83d8a681bf1222e3ba1/src/main/bash/sdkman-path-helpers.sh#L38), I can't see how we could ever omit a `:` when prepending the `PATH`.

**Comment by asuraphel** [comment]
It's been a which since I used SDKMAN on this machine. I tried it again and it seems to work fine! I have no idea how it went away but thanks for trying to investigate.

**Comment by marc0der** [comment]
No probs! Closing this issue for now.
