### ISSUE TITLE
`sdkman disable` for disabling candidates

### ISSUE THREAD

**Issue by quintesse** [sdkman/sdkman-cli#413]
Right now when I have sdkman installed I can't access any other previously available versions, the sdkman version always takes precedence.

It would be nice to have a `sdkman disable` which for the current terminal would disable the resolving for the given candidate. NB: `sdkman remove` is not what I'm looking for, I don't want to remove the candidate and all its versions.

As an extension to that it would be nice to be able to do this by default, for example `sdkman default <candidate> none` would disable the candidate by default and you'd have to do `sdkman use` first.

And if you ask *why* I have other versions not installed by sdkman in my path: it's for when I'm working on the new version of candidate that's also available in sdkman (we maintain the `ceylon` candidate). So the new version is the one I already have in my path but I'd like to use sdkman to install/manage all the older versions.

**Comment by marc0der** [comment]
An sdk disable command is not really needed, since sdkman allows you to manage local candidate versions using the local install feature. For more information, please see the following docs:
http://sdkman.io/usage.html#localversion

For some examples of how to use it, please see the cukes:
https://github.com/sdkman/sdkman-cli/blob/master/src/test/cucumber/local_developement_versions.feature

Hope this helps!

**Comment by marc0der** [comment]
No response received so closing this issue.

**Comment by quintesse** [comment]
Sorry I didn't respond to this before. Having read your response back in March I always wanted to try it out but Real Life intervened.

The indicated solution using a local candidate version does indeed seem to work. Thanks!

**Comment by marc0der** [comment]
No probs! Glad it worked.

**Comment by alexp1917** [comment]
seeing a 404 for both those links mentioned above.

my specific use case: a package provides a binary, and sometimes i need to actually see the real version of the binary its overriding. my solution was to uninstall. this didnt actually delete anything, and reinstalling only made sdkman unzip (ran for about half a minute).

the only thing i wish it would have also done is unset the JAVA_HOME variable. but thats pretty simple to do yourself.
