### ISSUE TITLE
'use' doesn't work (until a default version is set?)

### ISSUE THREAD

**Issue by chris-reeves** [sdkman/sdkman-cli#414]
Fresh install of sdkman today (12th of March). Version 3.3.2. Installed as follows:
```
$ curl -sS http://get.sdkman.io | bash -s stable --ignore-dotfiles
$ echo '[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"' >> ~/.bashrc
```

Opened a fresh xterm, installed grails 2.4.5 and tried to use, but current grails is not set:
```
$ sdk install grails 2.4.5
...
$ sdk use grails 2.4.5

Using grails version 2.4.5 in this shell.
$ sdk current grails
Not using any version of grails
$ grails
bash: grails: command not found
```

The same problem exists when trying to use another fresh xterm after installing grails.

After setting a default version, things don't improve for the current terminal session:
```
$ sdk default grails 2.4.5

Default grails version set to 2.4.5
$ sdk current grails
Not using any version of grails
$ sdk use grails 2.4.5

Using grails version 2.4.5 in this shell.
$ sdk current grails
Not using any version of grails
$ grails
bash: grails: command not found
```
however after opening yet another fresh terminal session things appear to work fine:
```
$ sdk current grails
Using grails version 2.4.5
```

**Comment by marc0der** [comment]
I think you left out one crucial bit. After installing grails, you have `...`, which actually asks you a (vital) question:

    Do you want grails 2.4.5 to be set as default? (Y/n): 

By hitting enter, here, it automatically makes 2.4.5 the default version. After this, you are free to `use` any version you like. I just tested this in a fresh docker container and it all works exactly as expected. Full documentation to how candidate installation works can be found in the [cukes](https://github.com/sdkman/sdkman-cli/blob/master/src/test/cucumber/install_candidate.feature).

**Comment by chris-reeves** [comment]
Correct, it did ask me that question. I answered 'no', as I do not want to make that my default. (I didn't deliberately miss that text out - I had already closed the xterm in which I performed the installation in the course of troubleshooting).

If you answer no, then the behaviour is as I described. The expected behaviour would be to not have a default set, but to be able to 'use' an installed version.

If a default version must be set in order for things to work, then the user shouldn't be given a choice here.

I would, of course, argue that the user should be given a choice, and that sdkman should work without a default being set.

**Comment by marc0der** [comment]
No, the default behaviour is to set a default on first installation of a candidate (that is why it is denoted with a capital *Y*, and _enter_ defaults to yes).

The `use` command is only for if you want to deviate from the default already set when using multiple terminals.

However, I agree that we probably shouldn't provide a choice when installing the first candidate version, and always make it the default. I'll look at implementing this in the near future. For now, simply use the default as suggested and it should all work as expected.

**Comment by chris-reeves** [comment]
I did have a quick look at fixing things at the weekend, but the current test suite in master didn't pass for me (non-docker) and I needed to complete the project work for which I was installing grails. Those tests for install_candidate look fairly thorough and all pass, but don't make any assertions about whether it is possible to use the installed candidate once it is installed.

**Comment by chris-reeves** [comment]
Indeed, everything worked once I set 2.4.5 as a default (and I opened another new terminal).

Not providing an option when installing the first candidate would resolve this for me.

Would you be interested in a PR to not require a default to be set, if I was to find the time to work this up?

Thanks for your efforts on this. Much appreciated.

**Comment by marc0der** [comment]
Good to hear that it's working.

For sure, contributions are always greatly appreciated!
