### ISSUE TITLE
sdkman to be working on windows

### ISSUE THREAD

**Issue by wholenewstrain** [sdkman/sdkman-cli#417]
I use git bash on windows and just modified sdkman-use script to work correctly.
I just changed one script but I see sdkman could be modified to easily work on windows if the current folder was to be dropped and swapped for current file that would hold current version.

$echo '2.2.2' > current
and then all the other scripts would just read the current file to set environment variables

I also added jdk as supported candidate by copying own jdk versions under .sdkman/candidates/jdk
Now I just run:
$sdk use jdk 1.7

Since we are already detecting existing jdk we could copy the ones we find and ask user for a path to any additional jdks they want to be managed.
Also instead copying entire jdk we could use a file with path, that is more portable.

$echo 'path to jdk home' > candidates/jdk/1.8.0_77

**Comment by marc0der** [comment]
It would be handy to see this in code, perhaps you could raise a small PR so I could see exactly what it was that you had in mind?

Regarding JDKs, a full blown implementation of this is on it's way.

**Comment by marc0der** [comment]
No further response so closing this issue.

**Comment by wholenewstrain** [comment]
OK let me prepare something

**Comment by marc0der** [comment]
Again nothing for a month so closing permanently.
