### ISSUE TITLE
Install is failing.  `curl -s get.sdkman.io | bash` does not work--your nginx server is not providing correct content.

### ISSUE THREAD

**Issue by dkelsey** [sdkman/sdkman-cli#418]
`curl -s get.sdkman.io | bash`  returns:

> bash: line 1: syntax error near unexpected token 'newline'
> bash: line 1: '<!DOCTYPE html>'

the request to [http://get.sdkman.io](http://get.sdkman.io) is returning the generic **nginx** welcome page

**Comment by marc0der** [comment]
It was a temporary issue due to DNS while cutting over to our new infrastructure.

**Comment by dkelsey** [comment]
Just checked this morning and yes, it's resolved.  Thanks!
