### ISSUE TITLE
Ant archive is corrupt

### ISSUE THREAD

**Issue by jramoyo** [sdkman/sdkman-cli#421]
$ sdk install ant

Downloading: ant 1.9.6

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   353  100   353    0     0    245      0  0:00:01  0:00:01 --:--:--   245
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/tpadmin/.sdkman/archives/ant-1.9.6.zip or
        /home/tpadmin/.sdkman/archives/ant-1.9.6.zip.zip, and cannot find /home/tpadmin/.sdkman/archives/ant-1.9.6.zip.ZIP, period.

Stop! The archive was corrupt and has been removed! Please try installing again.`

**Comment by marc0der** [comment]
They removed version 1.9.6 when they released 1.9.7. So much for an immutable build process 😜. This has now been rectified on our side now.
