### ISSUE TITLE
Provide list of packages on website

### ISSUE THREAD

**Issue by ieugen** [sdkman/sdkman-cli#423]
It would be nice to have a list of packages or search on sdkman.io.

**Comment by NoUsername** [comment]
i also second this, it was really confusing for me at first when I recommended the tool to a colleague and said "hey, use this to install gradle" and then "oh wait, gradle istn't listed on the frontpage." followed by "oh wait it is listed in the examples, hm, what else does it support, where's the list??"
i don't want to have to install it to find out. Even if the list is slightly outdated (it could say 'this list may be out of date' or sth), it is better than no online overview at all.

**Comment by marc0der** [comment]
Issue moved to [sdkman/sdkman-website #6](https://github.com/sdkman/sdkman-website/issues/6) via [**ZenHub**](https://www.zenhub.com/)
