### ISSUE TITLE
Install command fails

### ISSUE THREAD

**Issue by chromial** [sdkman/sdkman-cli#424]
Right on the home page it says: 

_Get started now!
Go on, paste and run the following in a terminal: 
$ curl -s "https://get.sdkman.io" | bash"_

If you actually run that command it will not only fail but also give no indication that it has failed.
Curl won't download the script because of a redirect but you will not see the error message because the 's' flag makes it fail silently. Following is the error without it.

curl: (51) SSL: certificate subject name 'api.sdkman.io' does not match target 
host name 'get.sdkman.io'

**Comment by marc0der** [comment]
Very curious indeed. I just ran this on a clean docker container, and it worked without any issues. You are right that the `-s` makes it silent, but the actual problem is somehow with your certs.

**Comment by chromial** [comment]
-k does much better:

[~] curl -k "https://get.sdkman.io" | he
ad
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11015  100 11015    0     0   123k      0 --:--:-- --:--:-- --:--:--     0
#!/bin/bash
#
#   Copyright 2012 Marco Vermeulen
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#

**Comment by marc0der** [comment]
I think we will see this happen from time to time when cert store issues are experienced. The simplest fallback is actually to simply go to http, as this still works too.

The `-k` simply runs curl in 'insecure' mode.

**Comment by marc0der** [comment]
No response so closing this issue.
