### ISSUE TITLE
sdkman grails on imac executes but does nothing except resets/clears terminal

### ISSUE THREAD

**Issue by pimpedoutgeek** [sdkman/sdkman-cli#428]
Howdy, I have been using sdkman on my Ubuntu laptop w/o issues but a recent forced migration to iMac grails -version for example does nothing except clears and resets the terminal screen. sdk -l grails returns as expected. After initial install sdk worked as expected but recent iMac upgrades may have done some damage. Complete re-install needed?

**Comment by marc0der** [comment]
Very strange indeed. Could you try installing from scratch on your Mac?

**Comment by marc0der** [comment]
Any progress on this? If so, can we close this issue?

**Comment by marc0der** [comment]
No further response so closing.

**Comment by battaglr** [comment]
Just in case someone find this in the future, I had the same problem and was because Java wasn't properly configured. After configuring the JAVA_HOME and PATH, all worked as expected. Hope it helps.

**Comment by marc0der** [comment]
This should be automatically handled by sdkman though. It also helps of you installed java with sdkman.

**Comment by battaglr** [comment]
Sadly, in this case it failed to do so —I even reinstalled sdkman 2 times and the whole Groovy/Grails environment.

I'll take your advice and install Java with sdkman —didn't know it was available already.

Thanks!

**Comment by bmaupin** [comment]
Same thing for me on Ubuntu; I'd installed Grails via sdkman but wanted to use my system's java. This worked:

    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    grails

**Comment by marc0der** [comment]
@bmaupin I suggest you do _not_ do this as you will break things. Rather consider letting sdkman manage your system JDK(s) by using [local versions](http://sdkman.io/usage.html#localversion). You can do the following:

    sdk install java openjdk-8 /usr/lib/jvm/java-8-openjdk-amd64

This new version will now become available for you to use from within sdkman.

**Comment by bmaupin** [comment]
@marc0der I was hesitant to use sdkman to install Java because I didn't want a duplicate Java install somewhere, and that's exactly what I needed. Thanks!
