### ISSUE TITLE
Investigate DMG extraction on Mac

### ISSUE THREAD

**Issue by marc0der** [sdkman/sdkman-cli#440]

**Comment by xasx** [comment]
Sorry, but I need to mention that 7-zip could also help out here, refer to [Wikipedia's list of supported formats](https://en.wikipedia.org/wiki/7-Zip#Others).

[p7zip] would be a thing to be after in the case you are interested.

[p7zip]: http://p7zip.sourceforge.net/

**Comment by marc0der** [comment]
Despite 7-zip being a very convenient tool, the same issue applies here as
on windows. We want to steer clear of adding additional dependencies so
that we keep the barrier of entry as low as possible.

OSX has all the native CLI tooling available to perform this task, even if
it requires a few more steps to do it than with using such tools as 7-zip.

**Comment by xasx** [comment]
Never mind, just wanted to give another argument. Wouldn't the integration of a third-party tool with a platform-independent CLI-ish API also help development of more streamlined scripts?

Don't get me wrong, I fully understand and respect your idea as the owner to only rely on platform tools.
 My rule of thumb for introducing another dependency is 
* if it comes in handy in a second place
* does not break existing stuff
* is easy to integrate
* and lightweight
then go and include the dependency. However I see the difficulty here to ship certain binaries bundled with sdkman itself that are already coupled to the OS. Remembers me on times where I needed to ship various binaries with Java Service Wrapper dependent Java services.

**Comment by marc0der** [comment]
User experience trumps everything else, especially  having more 'streamlined scripts' for the developers to work with. Our users aren't concerned about what the scripts look like, just that it works and works well.

As for the other points, these are all true if you have a dependency resolution mechanism in place, which bash doesn't. We need to make every effort in keeping sdkman as light as possible, and sometimes need to make small sacrifices in the process.

**Comment by marc0der** [comment]
Preliminary stab at JDK installation from the command line can be found in [this Gist](https://gist.github.com/marc0der/c5e1e6b8be9d00f57cbb99e92000b948).

To see if it actually works:

    $ export JAVA_HOME="$HOME/.sdkman/candidates/java/1.8.0u101"
    $ export PATH="$JAVA_HOME/bin:$PATH"

*This is not official JDK support but a spike! However, it does performs the entire JDK installation from CLI.*
