### ISSUE TITLE
Investigate EXE extraction on Windoze

### ISSUE THREAD

**Issue by marc0der** [sdkman/sdkman-cli#441]

**Comment by marc0der** [comment]
It is possible to extract an MSI .exe file from within a bash script using the following syntax:

    #!/bin/bash
    /cygdrive/c/Users/vagrant/Downloads/jdk-8u91-windows-x64.exe /s INSTALLDIR=C:\\temp\\jdk

Some observations:
* perform `chmod +x` on `.exe` file before executing
* specify the fully qualified path to the `.exe` file when executing
* `/s` instructs a silent installation
* `INSTALLDIR` must be specified as a windows path with escaped backslashes.
* any nested installation folders will be created on demand by the command, no need for `mkdir -p`

**Comment by xasx** [comment]
IIRC I was able to get some older JDK's content without invoking the installer with the help of [7-zip](http://www.7-zip.org/). Depends on how you want to deal with possibly interfering registry settings or whether you completely want to take over the management of them.

**Comment by marc0der** [comment]
It would be preferable to completely manage them like we do with all our candidates. I've actually managed to get it working on a vm with the above syntax.

I would prefer not to use 7-zip because of the dependency introduced. If MSI can do it out of the box, we get the extraction for free in a light weight manner.

**Comment by xasx** [comment]
> I would prefer not to use 7-zip because of the dependency introduced. 

I already thought this would be an issue.

My main point why suggesting 7-zip was that you never know what the installer does in addition to extracting the JDK files. I think one thing to cope with is the installer setting the installed JDK as the default. That will make the handling of a 'no' for the default question after the JDK installation a bit more difficult.

One thing: does the installer immediately return after call? If so, how will you know the installation has finished? (just curious)

**Comment by marc0der** [comment]
AFAIK, when running the command as described, it doesn't do anything
besides extract the contents. The installer blocks the shell until
extraction is complete. We will then take the extracted folder and deal
with it as usual by placing it under `~.sdkman/candidates/java`.

Important to note that we care only about the availability of the JDK on
the PATH in Cygwin terminals, and not about global Windows
installation/integration here.

**Comment by xasx** [comment]
Not sure about the installer not doing other stuff:

https://www.java.com/en/download/help/silent_install.xml

It's somehow unclear what Oracle means with

> * Have all features of the JRE installed

You could probably easily find out by creating the mentioned log, using `/L <path-to>setup.log`

**Comment by marc0der** [comment]
Good point, will give that a try.
