### ISSUE TITLE
The command something like `refresh-paths` required

### ISSUE THREAD

**Issue by wwarlock** [sdkman/sdkman-cli#444]
Didn't find how to make candidates visible in the system after copying sdkman.
Though candidates are visible by `sdk ls`.
I've tried to use `sdk use`, `sdk default`, `sdk install`.
The message like `"Using sbt version 0.13.11 in this shell."` (and `"Stop! sbt 0.13.11 is already installed."` after `sdk install`) appeared but no changes maked to the system.
The only way to reactivate candidate `sdk rm && sdk install` and sometimes that is not good.

**Comment by marc0der** [comment]
I don't think this is a bug but rather a usage issue. Please use our Gitter chat for advise before raising an issue.
