### ISSUE TITLE
Version ordering algorithm has 'issues'

### ISSUE THREAD

**Issue by russel** [sdkman/sdkman-cli#449]
It seems that 3.0-rc-1 is order before 2.14.1 in the sdkman ordering algorithm.

```
|> sdk outdated
Outdated:
gradle (3.0-rc-1 < 2.14.1)
|> 
```

**Comment by mnellemann** [comment]
I'm also seeing funny version comparison - grails 4.0.1 < grails 3.3.11 :)

````
$ sdk upgrade                                                                                             [0]

Upgrade:
gradle (5.6.3 < 6.0)
grails (4.0.1 < 3.3.11)
java (8.0.202-zulufx < 11.0.5.hs-adpt)

Upgrade candidate(s) and set latest version(s) as default? (Y/n): n
````

**Comment by marc0der** [comment]
There is no version ordering algorithm really, so this message is a bit misleading. That said, I've just updated the default version of Grails to be `4.0.1`. /cc @graemerocher
