### ISSUE TITLE
Stop! grails is not a valid candidate. SDKMAN 4.0.35

### ISSUE THREAD

**Issue by shikhar459** [sdkman/sdkman-cli#450]
I have added few files in .m2 for dependencies. Earlier sdk was working file with grails. Now it is showing error `Stop! grails is not a valid candidate.`

**Comment by marc0der** [comment]
SDKMAN, has nothing to do with the local maven repository. Something else must have happened on your system.

In future, please raise usage questions on our [Gitter User Issues](https://gitter.im/sdkman/user-issues) before opening an issue.
