### ISSUE TITLE
unsafe bash executions

### ISSUE THREAD

**Issue by childnode** [sdkman/sdkman-cli#451]
e.g. [sdkman-install.sh](https://github.com/sdkman/sdkman-cli/blob/master/src/main/bash/sdkman-install.sh) uses mkdir that is not a more or less secure bash function but might be overloaded by a simple user function. So, you should update any calls to `mkdir` to s.th. like `/usr/bin/env mkdir` to not execute the user function if it exist but the real mkdir binary.

This expands to many others like: `rm`, etc. too!

**Comment by marc0der** [comment]
Pull requests welcome!

**Comment by childnode** [comment]
#lock /me is working on that
