### ISSUE TITLE
disable auto upgrade check

### ISSUE THREAD

**Issue by junho85** [sdkman/sdkman-cli#455]
#453 I think it's better to have "disable auto upgrade check" option.

ex)
.sdkman/etc/config
```
sdkman_disable_auto_upgrade_check=false
```

because my company servers have firewall. .sdkman/bin/sdkman-init.sh script is hang until timeout configured when I use remote connection (ex ssh).

add.
add timeout error message when sdkman-init.sh has failed. it was not easy to find the reason why login bash prompt is slow.

**Comment by marc0der** [comment]
If you have a look on our [site under Usage](http://sdkman.io/usage.html#config), you will see that we already have such a configuration:

    # perform automatic selfupdates
    sdkman_auto_selfupdate=true|false

Hope this helps!

**Comment by oussamabadr** [comment]
Here is the new documentation link:  https://sdkman.io/usage#config

And by the way, the config file is under: `~/.sdkman/etc/config`

**Comment by jacktang** [comment]
I set 
```
sdkman_auto_selfupdate=false
sdkman_selfupdate_enable=false
```

to make my zsh work fine.

**Comment by marc0der** [comment]
Hi @jacktang, the `sdkman_auto_selfupdate` flag is [no longer used](https://github.com/sdkman/sdkman-cli/releases/tag/5.12.0) so you can remove it from your config altogether. You should only be using `sdkman_selfupdate_enable` only with the latest versions of sdkman.
