### ISSUE TITLE
.sdkrc to store versions for specific directory

### ISSUE THREAD

**Issue by musketyr** [sdkman/sdkman-cli#463]
I would be great if there is alternative to `.nvmrc` file in [NVM](https://github.com/creationix/nvm).

Given `.sdkrc` file in current directory with following content

```
grails=3.2.0.M2
```

When I run `sdk use`
Then `grails` version `3.2.0.M2` is downloaded if not present yet
And `grails` version `3.2.0.M2` is used in current shell

**Comment by marc0der** [comment]
This is already mostly supported in the [sdkman-extensions](https://github.com/sdkman/sdkman-extensions) project by way of the `sdk switch` command. Feel free to give it a try and/or raise any PRs on this to improve it.

**Comment by musketyr** [comment]
this looks it's doing way too much magic and does not work for every candidate supported. I would prefer having separate file. let's keep this option open.

**Comment by marc0der** [comment]
For sure, it's not in a great state.
Is that you volunteering to write a new extension? :-)

**Comment by marc0der** [comment]
Moving this issue over to the sdkman-extensions project, as this will not be implemented in the CLI.

**Comment by marc0der** [comment]
Issue moved to [sdkman/sdkman-extensions #9](https://github.com/sdkman/sdkman-extensions/issues/9) via [**ZenHub**](https://www.zenhub.com/)

**Comment by musketyr** [comment]
@marc0der I would love to, but out of time at the moment 😿

**Comment by musketyr** [comment]
also my bash skills are not that deep :-(

**Comment by marc0der** [comment]
Sad to hear, but will be waiting here for when you are skilled up in bash! :smile:
