### ISSUE TITLE
List installed sdk

### ISSUE THREAD

**Issue by Tsuki** [sdkman/sdkman-cli#464]
hopefully sdk can create list-local cmd for list the installed sdk and their version.

**Comment by marc0der** [comment]
Not really sure what you mean by this. Could you explain exactly what it is you're after?

**Comment by Tsuki** [comment]
just like brew ls, it will show all installed formular.

in sdkman, sdk list only show the manual of all sdk instead of installed list

**Comment by marc0der** [comment]
Right, so what you are actually after is the `sdk current` command. It might be worth heading over to our site and reading the [usage page](http://sdkman.io/usage.html) to see all the commands available.

In future, please consider using our Gitter User Issues chat to ask usage questions before raising an issue.

**Comment by nicolaiparlog** [comment]
I'm pretty sure @Tsuki asked for a way to list all installed candidates/versions, e.g.

```
Installed:

java: 11.0.5-open
      8.0.232.hs-adpt
maven: 3.6.2
```

`sdk current` only lists those currently used:

```
Using:

java: 11.0.5-open
maven: 3.6.2
```
