### ISSUE TITLE
sdk list [candidate] doesn't list all versions

### ISSUE THREAD

**Issue by KevinGreene** [sdkman/sdkman-cli#465]
Currently, `sdk list grails` produces the following output for me:

```
================================================================================
Available Grails Versions
================================================================================
     3.2.0.RC1            3.1.0.RC1            3.0.15               2.4.5
     3.2.0.M2             3.1.0.M3             3.0.14               2.4.4
     3.2.0.M1             3.1.0.M2             3.0.13               2.4.3
 > * 3.1.9                3.1.0.M1             3.0.12               2.4.2
     3.1.8                3.1.0                3.0.11               2.4.1
   * 3.1.7                3.0.9                3.0.10               2.4.0
     3.1.6                3.0.8                3.0.1                2.3.9
     3.1.5                3.0.7                3.0.0                2.3.8
     3.1.4                3.0.6                2.5.5.BUILD-SNA    * 2.3.7
     3.1.3                3.0.5                2.5.5                2.3.6
     3.1.2                3.0.4                2.5.4                2.3.5
     3.1.11               3.0.3                2.5.3                2.3.4
     3.1.10               3.0.2                2.5.2                2.3.3
     3.1.1                3.0.17               2.5.1                2.3.2
     3.1.0.RC2            3.0.16               2.5.0                2.3.11

================================================================================
```

However, I need to use grails 2.2.x. After finding the latest version of 2.2.x from the grails website, I was able to install it with `sdk install grails 2.2.5`.

**Comment by marc0der** [comment]
I've opened up some space in the list view by removing obsolete versions for now. I'll keep this ticket open to make some changes to the list view allowing for more versions.

**Comment by eprozium** [comment]
Also the order of the candidates is alphanumeric not semver :(.

**Comment by marc0der** [comment]
Yes, that's a know issue and will be addressed in the rewrite of the candidates service.

**Comment by ColinHarrington** [comment]
What determines that a candidate is obsolete?  It would be nice to have more visibility into the candiates & versions.  Seems like #489 is related

**Comment by marc0der** [comment]
This is on my list of things to do shortly. I'll be rewriting the rendering
of the list in our new candidates api application. As part of that I'll
also address all these deficiencies.

Right now, the list view simply truncates the older versions, even though
they are still all available for download. At the time I did the simplest
thing possible, but clearly it is no longer fit for purpose.

I'll update this issue soon with the progress I make on this rewrite.

**Comment by emorgado** [comment]
I'm having problem with this too.
sdk version 
    5.5.13+272
sdk list grails
================================================================================
Available Grails Versions
================================================================================
     3.3.1                3.2.1                3.1.11               3.0.14         
     3.3.0.RC1            3.2.0                3.1.10               3.0.13         
     3.3.0.M2             3.1.9              * 3.1.1                3.0.12         
     3.3.0.M1             3.1.8                3.1.0                3.0.11         
     3.3.0                3.1.7                3.0.9                3.0.10         
     3.2.9                3.1.6                3.0.8                3.0.1          
     3.2.8                3.1.5                3.0.7                3.0.0          
     3.2.7                3.1.4                3.0.6                2.5.6          
     3.2.6                3.1.3                3.0.5                2.5.5          
     3.2.5                3.1.2                3.0.4                2.5.4          
     3.2.4                3.1.16               3.0.3                2.5.3          
     3.2.3                3.1.15               3.0.2                2.5.2          
     3.2.2                3.1.14               3.0.17               2.5.1          
     3.2.11               3.1.13               3.0.16               2.5.0          
     3.2.10               3.1.12               3.0.15               2.4.5          

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
I need grails 2.4.3, it cam be set as default, but when i run grails it simply fail without any messages.

I'm Using ubuntu 16.04.

Any suggestion how to solve?

**Comment by marc0der** [comment]
This is now resolved with the rewrite of the list view in our sdkman-candidates app. The list view now not only orders version lists correctly, but also expands to an arbitrary size.
