### ISSUE TITLE
Add Lein as sdk!

### ISSUE THREAD

**Issue by eprozium** [sdkman/sdkman-cli#470]
Please add Lein http://leiningen.org/ as SDK too.

Thank you.

**Comment by marc0der** [comment]
This needs to be done by their team. We encourage teams to publish their own candidates on sdkman using our vendor APIs.

It is probably best for you to raise an issue on their project, then to mention me. I'll support and advise on how they could get started.

**Comment by eprozium** [comment]
> This needs to be done by their team. 

Well, than most probably nothing will happen :) . They already support ```brew``` :) .

**Comment by russel** [comment]
If they only support brew then they have a real problem: they are missing out on the entire Linux community and probably the entire Windows community, hot to mention those OSX users who are with MacPorts.

Of course lein is a short shell script that loads everything so installation is not that big a deal.

**Comment by eprozium** [comment]
> If they only support brew then they have a real problem

I haven't said that they **only** support brew :) .

> Of course lein is a short shell script that loads everything so installation is not that big a deal.

It's not. That shell script (with it's equivalent for Windows) is only the entry point. It will download the rest, so it can selfupdate and upgrade  and stuff. It's also a complete build system for Clojure :) .

The only aspect is missing is the ease to switch to different versions quickly like sdkman allows.

**Comment by marc0der** [comment]
@eprozium You would probably surprised how willing they are to help. It's a bit early to give up, no?

I suggest opening the github issue as I suggested, _then_ seeing what the outcome is.

Most teams are more than happy to have another distribution channel for their software.

**Comment by eprozium** [comment]
https://github.com/technomancy/leiningen/issues/2204

**Comment by marc0der** [comment]
Closing this issue as it is now with the Lein team.
