### ISSUE TITLE
Make a candidates (wiki) page.

### ISSUE THREAD

**Issue by eprozium** [sdkman/sdkman-cli#472]
It seems that many projects don't know about sdkman (maybe because of recent name and scope change?), or do not offer integration with it.

Make a "potential candidates" page to collect projects that might be very well suited for sdkman.

**Comment by aadrian** [comment]
> Make a "potential candidates" page to collect projects that might be very well suited for sdkman.

https://github.com/sdkman/sdkman-cli/wiki/Potential-Candidates
