### ISSUE TITLE
How to uninstall sdkman on mac osx?

### ISSUE THREAD

**Issue by LichFaker** [sdkman/sdkman-cli#481]
Today, I use `sdkman 5.1.3+69` to install `gradle`, when download almost 50% it suddenly stop without any information. Then no matter what command I typed, it always hint `is not available while offline` even if I enable the offline.

So I want to uninstall the `sdkman`, but I found nothing in doc.

**Comment by marc0der** [comment]
Was that 50% download of Gradle? In that case it sounds like your internet went down.

Uninstalling sdkman is not the right solution here, but if you _really_ wanted to, simply `rm -rf ~/.sdkman`.

In future, please consider using our [Gitter user-issues](https://gitter.im/sdkman/user-issues) account for usage questions before opening an issue on github.
