### ISSUE TITLE
jbakery install fails

### ISSUE THREAD

**Issue by d-subrahmanyam** [sdkman/sdkman-cli#483]
Team,

Thanks a lot for the awesome job. 

I was trying to install jbakery through skdman and everytime I was encountering the below error. 

Downloading: jbakery 0.0.4

In progress...

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/subbu/.sdkman/archives/jbakery-0.0.4.zip or
        /Users/subbu/.sdkman/archives/jbakery-0.0.4.zip.zip, and cannot find /Users/subbu/.sdkman/archives/jbakery-0.0.4.zip.ZIP, period.

After some investigation I found that sdkman expects the zip file names to be as per the candidates name. Then I tried picking up the jbakery-bin-0.0.4.zip from bintray and place it in archives folder and run the install without any success. Then I tried renaming it to jbakery-0.0.4.zip  and installed successfully.  

If the install scripts can be tweaked to learn about the install binary file and then pick them up.

**Comment by marc0der** [comment]
Thanks for the headsup. I'll remove jbakery as it is no longer supported on sdkman by the author.

**Comment by marc0der** [comment]
BTW, you will need to do an `sdk flush candidates` and open a new terminal for this to fully take effect.
