### ISSUE TITLE
Groovy installation and groovy-all jar

### ISSUE THREAD

**Issue by mikessh** [sdkman/sdkman-cli#485]
Hello!

It appears that groovy install for v 2.4.7 is not going to fetch ``groovy-all-*.jar``, so 
```
groovy -e "println 'Hello world'
```
immediately throws
```
Caught: groovy.lang.MissingPropertyException: No such property: println for class: script_from_command_line
```
which is fixed if ``groovy-all-2.4.7.jar`` from maven is put to ``candidates/groovy/current/lib/
``. Perhaps this was done on purpose, yet it seems quite strange as for example running 
```
scala -e "print('Hello world\n')"
```
after installing Scala with SDKMAN runs OK.

**Comment by marc0der** [comment]
We simply download and extract the official sdk that is available for download on the Groovy download page. Feel free to query this with the Groovy team.
