### ISSUE TITLE
No installation, download fails due to invalid certificate

### ISSUE THREAD

**Issue by Patterner** [sdkman/sdkman-cli#486]
I tried the script from https://get.sdkman.io and it failed.
```
curl -L 'https://api.sdkman.io/1/res?platform=Linux&purpose=install'
```
curl: (60) SSL certificate problem: self signed certificate in certificate chain

The 'downloaded' file is 0 bytes.

**Comment by tbarnier** [comment]
try out with disabling certificate checking (-k option)
``
curl -L 'https://api.sdkman.io/1/res?platform=Linux&purpose=install'
``
should work....

**Comment by guillaume-tessier-cbp** [comment]
- First, get the sdkman install script file : `curl -s --insecure "https://get.sdkman.io`
- Edit this file and under the `echo "Download script archive..."`, add `-k` (insecure) to the curl command just below.
- exécute the sdkman script file you just edited : `./sdkman`

It should be able to fetch what it needs without throwing SSL/TLS errors and successfully install.

**Comment by marc0der** [comment]
Even better, make sure that your key chain is up to date so you don't need to resort to such hackery. SDKMAN has a valid SSL certificate.
