### ISSUE TITLE
Stop! maven is not a valid candidate.

### ISSUE THREAD

**Issue by zidom** [sdkman/sdkman-cli#488]
![image](https://cloud.githubusercontent.com/assets/635265/20333434/76f72cb6-abed-11e6-9d0d-4c31a5b54859.png)

**Comment by marc0der** [comment]
Due to the service not being reachable you must have corrupted your candidate cache. Can you try doing a flush, then opening a new terminal?

`$ sdk flush candidates`

**Comment by Wanimal** [comment]
@marc0der that's great

**Comment by marc0der** [comment]
Closing this issue as it's not really a bug but usage related.

**Comment by Hillkorn** [comment]
That should be somewhere in the doc. Had that problem too

**Comment by marc0der** [comment]
I was thinking about this and wondering if we need a new command to refresh the candidate cache.

We could do something like a refresh command that simply fetches and resets the candidates.

WDYT?

**Comment by Hillkorn** [comment]
Sounds good to me. With an addidional hint to the command in the error
message would be perfect i think.

Marco Vermeulen <notifications@github.com> schrieb am So., 20. Nov. 2016 um
08:54 Uhr:

**Comment by marc0der** [comment]
This has now all been fixed, and refresh of candidate cache now happens automatically.

**Comment by stanisfun** [comment]
Still happend with last version

**Comment by stanisfun** [comment]
stanislav@strifan:~/workspace$ sdk selfupdate force

Updating SDKMAN...
######################################################################## 100,0%


Successfully upgraded SDKMAN!

Open a new terminal to start using SDKMAN 5.1.18+191.

To join our BETA channel, simply follow the instructions on:

   http://sdkman.io/install.html

Enjoy!!!

stanislav@strifan:~/workspace$ sdk install maven

Stop! maven is not a valid candidate.

**Comment by prodigy4440** [comment]
In my case i have to force selfupdate to getbit to work.
sdk selfupdate force

**Comment by Hillkorn** [comment]
I also have that problem quite often and think that the slow dns resolution of my isp could be the problem of it.

**Comment by marc0der** [comment]
Could you try adjusting your curl configurations in the config file?

**Comment by scarenci** [comment]
Hi, people

I am having the same problem: "Stop! java is not a valid candidate" 

I updated my version to 5.16.1 and got this problem =( Before that my installation was working fine. 

I tried execute this command "sdk flush candidates", but nothing different happened and I removed my old version to install again from zero and the problem persists. 

Can you check if the main still working? or I need to delete something else to work?

@marc0der I saw that you collaborated with the software and you were the last one to updated, can you help me to understand what is happening? I appreciate any help

**Comment by scarenci** [comment]
I had to restart the machine for the new version to work, even applying the "source" in the file the problem continued.

But now I think is working normal again, I will do some tests

**Comment by philurlaub** [comment]
Same here!

**Comment by philurlaub** [comment]
Yes, seems to be down again

**Comment by marc0der** [comment]
@philurlaub service is definitely restored. Please join our community slack uptime-robot channel for live updates, or chat with us on user-issues if you still have problems.

**Comment by dmytroKarataiev** [comment]
I started having the same issue yesterday in GitHub Actions.
