### ISSUE TITLE
Leiningen not working after installing sdkman

### ISSUE THREAD

**Issue by abhi18av** [sdkman/sdkman-cli#490]
Hi sdkman team:)

I wanted to tryout goovy and due to some path issues I switched to `sdkman` from `brew` but now I'm unable to import my clojure libraries i.e. `./m2` has been removed from the classpath - or atleast that's what I've found out so far.

Could you please tell me how to configure the changes made my sdkman to the path?

**Comment by marc0der** [comment]
This seems like a usage issue, not a bug. Can we close this issue and take this to the Gitter user-issues chat room where we can help resolve this effectively?

**Comment by abhi18av** [comment]
Oh sure) 

But, I guess I've pretty much resolved it myself by *something* with the class path. But, is there a way I can add the system `./m2` repo to `groovy conf` file?

I know it's not `sdkman` issue anymore so I'll close it. Nice job btw :+1:
