### ISSUE TITLE
sdkman stops working frequently

### ISSUE THREAD

**Issue by snimavat** [sdkman/sdkman-cli#492]
I have sdk man installed, and grails and gradle candidates installed.

But frequently, i will get error, grails command not found, or gradle not found
when i do, sdk use grails 2.5.5, it will give error

==== INTERNET NOT REACHABLE! ===============================

 Some functionality is disabled or only partially available.
 If this persists, please enable the offline mode:

   $ sdk offline

============================================================

Even though my internet is working properly.

i can not do sdk ls either, or sdk selfupdate force.. nothing works

**Comment by marc0der** [comment]
Could this be due to curl timing out due to a slow network connection? We provide a configuration to increase the timeouts in cases where network latency is too high.

If you are still having issue, please head over to the user-issues channel on Gitter where I can help finding your problem.

**Comment by snimavat** [comment]
ok, it works right now, if it comes again, i will try the Gitter.

Thanks
