### ISSUE TITLE
sdk list command is broken, version 5.1.7+91

### ISSUE THREAD

**Issue by halyph** [sdkman/sdkman-cli#493]
Mac OS 10.11.6
Bash

```
$ sdk v
SDKMAN 5.1.7+91

$ sdk list
-bash: less is /usr/bin/less: No such file or directory
-bash: echo: write error: Broken pipe
```

But it worked before this update

I've just checked and found that this issue is related to #411 /CC @SamirTalwar

**Comment by SamirTalwar** [comment]
Looks like Bash is behaving differently on your machine; perhaps it's Bash v3 rather than Bash v4.

In * src/main/bash/sdkman-utils.sh*, can you try changing `which less` to `command -v less` and see if that fixes it? If it does, I'll test it on mine when I get home tonight and send a pull request.

**Comment by halyph** [comment]
- bash version
```
$ sh --version
sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

- `less` command
```
$ which less
less is /usr/bin/less
```

**Comment by halyph** [comment]
Hot fix fix in `sdkman-utils.sh`
```
function __sdkman_page {
    # local PAGER="${PAGER-$(which less)}"
    local PAGER="/usr/bin/less"

    if [[ -n "$PAGER" ]]; then
        "$@" | "$PAGER"
    else
        "$@"
    fi
}
```

I.e. `which less` command output should be handled properly

Also, there might be `alias`es and in this case `which less` will return more then one line

**Comment by SamirTalwar** [comment]
@halyph: Yes, exactly. Could you try using `command -v` instead? It's much more standard. `which` was my mistake.

**Comment by SamirTalwar** [comment]
I have tested it (had five minutes) and it works fine here.

**Comment by halyph** [comment]
1. Without `alias`
```bash
$ command -v less
/usr/bin/less
```

2. With `alias`
```bash
[~]
$ alias less='my-super-less'

[~]
$ command -v less
alias less='my-super-less'
```

**Comment by SamirTalwar** [comment]
OK, let's not use the result of `command -v less`. Too unstable. We can still use the exit code though.

```sh
function __sdkman_page {
    if [[ -n "$PAGER" ]]; then
        "$@" | $PAGER
    elif command -v less >& /dev/null; then
        "$@" | less
    else
        "$@"
    fi
}
```

Mind giving it a crack?

**Comment by halyph** [comment]
Tested - it works on my side
