### ISSUE TITLE
End-of-central-directory signature not found.

### ISSUE THREAD

**Issue by louis813** [sdkman/sdkman-cli#495]
When I installed by following:

`$ curl -s https://get.sdkman.io | bash`

Error happen:

`End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.`

Then I check the download script, 

`curl -L "${SDKMAN_SERVICE}/res?platform=${sdkman_platform}&purpose=install" > "$sdkman_zip_file"`

Just found the resonse was as following:

[https://bintray.com/artifact/download/sdkman/generic/sdkman-cli-5.2.0%2B125.zip](https://bintray.com/artifact/download/sdkman/generic/sdkman-cli-5.2.0%2B125.zip)

> 
> HTTP Status 404 - Could not find entity
> 
> **type** Status report
> 
> **message** Could not find entity
> 
> **description** The requested resource is not available.
> 
> Apache Tomcat/8.0.33
> 

I am located in China. I wonder whether is was the problem of bintray.com or my network issue.

**Comment by mingfai** [comment]
i think the script is broken. try download manually for now:
https://bintray.com/sdkman/generic/sdkman-cli#files

**Comment by marc0der** [comment]
It was a blip with publishing of binaries.

**Comment by louis813** [comment]
@mingfai 

Thx man.

@marc0der 

Yes, now it works.

> curl -s https://get.sdkman.io | bash
> ...
> ...
> ...
> Download script archive...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
> 100 20074  100 20074    0     0    664      0  0:00:30  0:00:30 --:--:--  4844
> Extract script archive...
> Install scripts...
> Set version to 5.2.1+136 ...
