### ISSUE TITLE
Incorrect Version Number Displayed

### ISSUE THREAD

**Issue by restagner** [sdkman/sdkman-cli#503]
I've uninstalled sdkman, following the instructions at http://sdkman.io/install.html.  Then, I re-installed sdkman.  During the installation, the process noted

```text
Extract script archive...
Install scripts...
Set version to 5.2.1+136 ...
Attempt update of bash profiles...
Updated existing /home/restagner/.bashrc
```

After installation, I issued the command `sdk version`.  It returned `SDKMAN 5.1.4+78`.  I thought is should return `5.2.1+136`

**Comment by marc0der** [comment]
Sorry, incorrect issue number quoted in that commit :-)

Closing this as this was due to a login shell sourcing the init script. Restarting the X session fixed it.

Will need to review how bash profile(s) are updated at installation time going forward.
