### ISSUE TITLE
The confirmation prompt for the upgrade command is not being correctly displayed

### ISSUE THREAD

**Issue by EPadronU** [sdkman/sdkman-cli#508]
Screenshot

![2016-12-24-211936_696x112_scrot](https://cloud.githubusercontent.com/assets/829947/21469376/7c504572-ca1e-11e6-9648-d56efb5831e9.png)

Version: `SDKMAN 5.5.0+174`

uname -a: `Linux sophy 4.8.7-1 #1 SMP Fri Nov 25 22:10:42 VET 2016 x86_64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz GenuineIntel GNU/Linux`

**Comment by mdaloia** [comment]
Also it happens with the `sdk install` command:


```
$ sdk install java 7u79

[...]

Done installing!

\033[1;33mDo you want java 7u79 to be set as default? (Y/n): \033[0m
```

**Comment by marc0der** [comment]
@EPadronU @mdaloia Could you both please confirm that the bug is fixed in 5.5.1+179?

**Comment by mdaloia** [comment]
@marc0der Yep, fixed. Thanks.

**Comment by marc0der** [comment]
No probs, thanks for letting me know!
