### ISSUE TITLE
Make colorized output optional

### ISSUE THREAD

**Issue by pstric** [sdkman/sdkman-cli#510]
In a terminal with an inverted color scheme, the colorized output can be very hard to read.
Please make it either optional or configurable.

**Comment by marc0der** [comment]
It already is, simply set the `sdkman_colour_enable=false` in the `.sdkman/etc/config`.

**Comment by lfmunoz** [comment]
@marc0der  anyway to get this to work with environment variables? Want color normally but in certain instances when running with automation don't want color.
