### ISSUE TITLE
Sdkman can't install ant again

### ISSUE THREAD

**Issue by rgordeev** [sdkman/sdkman-cli#513]
Could you please fix problem with ant new version releases?

Downloading: ant 1.9.7

In progress...

######################################################################## 100,0%
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ~/.sdkman/archives/ant-1.9.7.zip or
        ~/.sdkman/archives/ant-1.9.7.zip.zip, and cannot find ~/.sdkman/archives/ant-1.9.7.zip.ZIP, period.

Stop! The archive was corrupt and has been removed! Please try installing again.

**Comment by marc0der** [comment]
This has now been fixed, and ant 1.9.8 and 1.10.0 have also been added.
