### ISSUE TITLE
Recent version of sdkman prevents GUI login on (K)Ubuntu 16.10

### ISSUE THREAD

**Issue by jarl-dk** [sdkman/sdkman-cli#514]
When updating to a recent version of sdkman, say 5.3.0+159 on Ubuntu 16.10 then after log-out you can not login on the GUI any more.

This is confirmed on Ubuntu 16.10 and Kubuntu 16.10 on SDK version 5.3.0+159

A known workaround is to remove/uncomment the sdkman line(s) in `~/.profile` (you can still keep it in `~/.bashrc`).

A known working earlier version of sdkman is 5.1.4+78

To reproduce:
Create a virtual machine with Ubuntu 16.10 and install sdkman. Then logout and try to login again via the GUI.

**Comment by marc0der** [comment]
AFAIK this is fixed in the latest release. Can you please confirm that your problem has been resolved?

**Comment by jarl-dk** [comment]
Yes. Confirmed with `SDKMAN 5.1.18+191`
