### ISSUE TITLE
Install jdk7 failed on OSX

### ISSUE THREAD

**Issue by wuranbo** [sdkman/sdkman-cli#516]
~/yottafrontendnew (ttl_conf_key_more_desc ✔) ᐅ sdk install java 7u79
tr: Illegal byte sequence

Oracle requires that you agree with the Oracle Binary Code License Agreement
prior to installation. The license agreement can be found at:

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

Do you agree to the terms of this agreement? (Y/n): Y

Downloading: java 7u79

In progress...

######################################################################## 100.0%
Binary validation passed...
We will be needing super powers...

Repackaging java 7u79...
Attaching to the DMG...
Mounting DMG as Volume...
One or more volume(s) failed to mount
Installing PKG inside DMG...
installer: Error the package path specified was invalid: '/Volumes/JDK 7 Update 79/JDK 7 Update 79.pkg'.
Copy JDK Home to temp folder...
cp: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home: No such file or directory
Preparing archive...

zip error: Nothing to do! (try: zip -qr /Users/wrb/.sdkman/tmp/.zip . -i .)
Unmounting volume...
hdiutil: unmount: "/Volumes/JDK 7 Update 79" failed to unmount due to error 2.
hdiutil: unmount failed - No such file or directory
Done repackaging...
Cleaning up cookie...
mv: rename /Users/wrb/.sdkman/tmp/.zip to /Users/wrb/.sdkman/archives/java-7u79.zip: No such file or directory
unzip:  cannot find or open /Users/wrb/.sdkman/archives/java-7u79.zip, /Users/wrb/.sdkman/archives/java-7u79.zip.zip or /Users/wrb/.sdkman/archives/java-7u79.zip.ZIP.
rm: /Users/wrb/.sdkman/archives/java-7u79.zip: No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.

**Comment by marc0der** [comment]
The clue lies in the following line:
One or more volume(s) failed to mount

I suggest unmounting all volumes on your machine and trying again.

**Comment by marc0der** [comment]
@wuranbo please confirm that this solves the problem before I close this issue.

**Comment by wuranbo** [comment]
Please close, it's OK when I following your instruction.
@marc0der   sorry, in my vacation. Thanks your sdkman.
