### ISSUE TITLE
while installing java, error comes as java installation was not detected

### ISSUE THREAD

**Issue by patelkunal** [sdkman/sdkman-cli#527]
It looks like chicken-and-egg problem here.

I got my new mac-machine and started with sdkman installation.

```bash
sdk install java
```
gives following error 
```
No java installations was detected.
Please go to http://www.java.com/getjava/ and download
```

Please provide the solution - I really don't want to install other way - I prefer managing java installation using sdkman.

Thanks,
Kunal

**Comment by marc0der** [comment]
sdkman don't emit such a message, so my guess would be that sdkman was not properly installed or initialised.

In future, please consider asking usage questions on Gitter before opening a github issue.
