### ISSUE TITLE
Stop! The archive was corrupt and has been removed! Please try installing again. on ubuntu 16.04 ? 

### ISSUE THREAD

**Issue by a-eid** [sdkman/sdkman-cli#530]
I'm trying to install kotlin on ubuntu 16.04 with no luck !! 
i get the following error 

[](http://imgur.com/LtUUVXH) 

http://imgur.com/LtUUVXH

**Comment by danielbraun89** [comment]
issue still exists

**Comment by helpermethod** [comment]
> issue still exists 

Hi @danielbraun89! Which version did you try to install?

**Comment by marc0der** [comment]
Hi @a-eid and @danielbraun89, 
Please chat to us on our community slack where we will gladly help you get this problem resolved. I closed this issue because it isn't a CLI bug as per the contributing guidelines.
