### ISSUE TITLE
sdk is not getting installed and reporting success message even though its not installed (ubunutu 16.04 )

### ISSUE THREAD

**Issue by patelkunal** [sdkman/sdkman-cli#532]
I am seeing wired errors while installing sdkman on my new ubuntu 16.04 setup.

following is the log message for installation command.

```
                                                 Now attempting installation...
                                                                               
Looking for a previous installation of SDKMAN...
Looking for unzip...
Looking for zip...
Looking for curl...
Looking for sed...
Installing SDKMAN scripts...
Create distribution directories...
Getting available candidates...
Prime the config file...
Download script archive...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
Extract script archive...
[/home/kunal/.sdkman/tmp/res-5.1.18+191.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/kunal/.sdkman/tmp/res-5.1.18+191.zip or
        /home/kunal/.sdkman/tmp/res-5.1.18+191.zip.zip, and cannot find /home/kunal/.sdkman/tmp/res-5.1.18+191.zip.ZIP, period.
Install scripts...
mv: cannot stat '/home/kunal/.sdkman/tmp/stage/sdkman-init.sh': No such file or directory
mv: cannot stat '/home/kunal/.sdkman/tmp/stage/sdkman-*': No such file or directory
Set version to 5.1.18+191 ...
Attempt update of bash profiles...
Attempt update of zsh profiles...



All done!


Please open a new terminal, or run the following in the existing one:

    source "/home/kunal/.sdkman/bin/sdkman-init.sh"

Then issue the following command:

    sdk help

Enjoy!!!
```

Here it gives success message but when I run sdk command - it says command not found. And $HOME/.sdkman is just skeleton there is nothing inside all subfolders.

I am happiely using sdkman in macbook. but here it downloads corrupt file and nothing happens afterwards.

Thanks in advance,
/kp

**Comment by marc0der** [comment]
Granted that we should not be displaying the success message on failures, the real clue to what is wrong here is all in the log you pasted above.

For starters, we see an error when trying to curl down the zip, due to ca cert problems:

    curl: (77) error setting certificate verify locations:
      CAfile: /etc/pki/tls/certs/ca-bundle.crt
      CApath: none

Because of curl failing, we write an empty zip file which then fails because this is not a valid zip:

    Extract script archive...
    [/home/kunal/.sdkman/tmp/res-5.1.18+191.zip]
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of /home/kunal/.sdkman/tmp/res-5.1.18+191.zip or
        /home/kunal/.sdkman/tmp/res-5.1.18+191.zip.zip, and cannot find /home/kunal/.sdkman/tmp/res-5.1.18+191.zip.ZIP, period.

The right way to fix this is to address the problem on your machine with CA certs. If you are willing to live with an insecure system, we can relax this on sdkman by using the `sdkman_insecure_ssl=true` in the _~/.sdkman/etc/config_.
