### ISSUE TITLE
Adding local candidates

### ISSUE THREAD

**Issue by maor121** [sdkman/sdkman-cli#535]
Hi,

There are so many sdks that are not included, let's say: Spark or R.
Is there a possibility to just unpack the package into the candidates folder. And it will be added to the PATH?

**Comment by marc0der** [comment]
Not yet no. At the moment we only allow local versions. However, this is something we could potentially consider going forward.

Spark in particular has come up before and is very viable as a candidate now that we support multiplatform binaries. First prize would be if the Spark team published their own versions. It might be worth raising this with them to get the ball rolling.

**Comment by marc0der** [comment]
Spark has been added sometime ago, so please check it out to see if it's working for you. As for R, it does not come in an SDK package, and is also not really related to the JVM. I recommend installing R through your native package manager.

Lastly, we now have a cool new [db-migrations](https://github.com/sdkman/sdkman-db-migrations) app where new Candidates and Versions can be added on a PR based mode. Give it a try in future if you see something missing on SDKMAN.

**Comment by marc0der** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The upgrade command should have it's default set to N for sdkman_auto_answer](https://trello.com/c/lBmsBqrI/31-the-upgrade-command-should-have-its-default-set-to-n-for-sdkmanautoanswer)
