### ISSUE TITLE
-bash: /Users/.../.sdkman/bin/sdkman-init.sh: No such file or directory

### ISSUE THREAD

**Issue by boybeak** [sdkman/sdkman-cli#536]
After executing ```curl -s "https://get.sdkman.io" | bash``` success. I executed ```/Users/.../.sdkman/bin/sdkman-init.sh```, but the resust is 
```-bash: /Users/.../.sdkman/bin/sdkman-init.sh: No such file or directory```

**Comment by marc0der** [comment]
Did you source or execute? The sdkman init script is not executable so can't be executed. It must always be sourced.

**Comment by marc0der** [comment]
Closing this as it's a user issue. In future, please try our Gitter user-issues channel first.

**Comment by jeremylbq** [comment]
I have the same problem , and  i really don't know how to solve it .

**Comment by demon101** [comment]
same for me,

scripts fails on gitlab ci 

> source ~/.sdkman/bin/sdkman-init.sh

/root/.sdkman/bin/sdkman-init.sh: No such file or directory

**Comment by LiJiye** [comment]
I also have the same problem, and how can i solve it please.

**Comment by BabyMelvin** [comment]
Have solved?  help....

**Comment by Mehran-Abghari** [comment]
+1 I have same problem

**Comment by marc0der** [comment]
Please give more details about the environment you are running in. Also the OS, shell and anything else that might help so we can try to replicate this. Without information and context we can't do much.

**Comment by Mehran-Abghari** [comment]
Hello @marc0der ,
I'm using **Ubuntu Budgie 17.10** and use **Tilix** as my terminal.
I live in **Iran** and you know some websites are blocked **BUT sdkman.io IS NOT BLOCKED** and i can access it by my browser.
I try to install SDKMAN! by `curl -s "https://get.sdkman.io" | bash`
After that, i saw message **`Enjoy!`**
Then i use command `source "$HOME/.sdkman/bin/sdkman-init.sh"`
but get this error:
`.../.sdkman/bin/sdkman-init.sh: No such file or directory`

**Comment by marc0der** [comment]
Hi @Mehran-Abghari, your problem is almost certainly down to blocked IPs. The script you are calling in turn pulls a binary down from bintray. From what I can see, you are getting the script successfully but can't proceed because the zip wasn't successfully downloaded.

That said, the installer should guard against this and give a more descriptive error message.

**Comment by Mehran-Abghari** [comment]
Hello @marc0der ,
Yes, Bintray is blocked in IRAN (Bintray blocked IRAN IP actually).
Is there other repository to download zip file manually or a mirror ?
about this `"the installer should guard against this and give a more descriptive error message"`: Installer should say some error message, not "Enjoy!" :laughing: and if can, download from other source.
Thanks for help

**Comment by mark5566** [comment]
same problem

**Comment by mark5566** [comment]
![image](https://user-images.githubusercontent.com/11515695/73611680-295b4800-461f-11ea-9479-f4ed47726605.png)

same problem

**Comment by wissnusetiawan** [comment]
How to install -> https://sdkman.io/install

**Comment by wissnusetiawan** [comment]
Using root

**Comment by marc0der** [comment]
@wissnusetiawan _Never_ use root to install SDKMAN.

**Comment by crusy** [comment]
Same here

**Comment by aqude** [comment]
ty

**Comment by wonderdev007** [comment]
same here

**Comment by ultravires** [comment]
If you don't see:

```
❯ curl -s "https://get.sdkman.io" | bash

                                -+syyyyyyys:
                            `/yho:`       -yd.
                         `/yh/`             +m.
                       .oho.                 hy                          .`
                     .sh/`                   :N`                `-/o`  `+dyyo:.
                   .yh:`                     `M-          `-/osysoym  :hs` `-+sys:      hhyssssssssy+
                 .sh:`                       `N:          ms/-``  yy.yh-      -hy.    `.N-````````+N.
               `od/`                         `N-       -/oM-      ddd+`     `sd:     hNNm        -N:
              :do`                           .M.       dMMM-     `ms.      /d+`     `NMMs       `do
            .yy-                             :N`    ```mMMM.      -      -hy.       /MMM:       yh
          `+d+`           `:/oo/`       `-/osyh/ossssssdNMM`           .sh:         yMMN`      /m.
         -dh-           :ymNMMMMy  `-/shmNm-`:N/-.``   `.sN            /N-         `NMMy      .m/
       `oNs`          -hysosmMMMMydmNmds+-.:ohm           :             sd`        :MMM/      yy
      .hN+           /d:    -MMMmhs/-.`   .MMMh   .ss+-                 `yy`       sMMN`     :N.
     :mN/           `N/     `o/-`         :MMMo   +MMMN-         .`      `ds       mMMh      do
    /NN/            `N+....--:/+oooosooo+:sMMM:   hMMMM:        `my       .m+     -MMM+     :N.
   /NMo              -+ooooo+/:-....`...:+hNMN.  `NMMMd`        .MM/       -m:    oMMN.     hs
  -NMd`                                    :mm   -MMMm- .s/     -MMm.       /m-   mMMd     -N.
 `mMM/                                      .-   /MMh. -dMo     -MMMy        od. .MMMs..---yh
 +MMM.                                           sNo`.sNMM+     :MMMM/        sh`+MMMNmNm+++-
 mMMM-                                           /--ohmMMM+     :MMMMm.       `hyymmmdddo
 MMMMh.                  ````                  `-+yy/`yMMM/     :MMMMMy       -sm:.``..-:-.`
 dMMMMmo-.``````..-:/osyhddddho.           `+shdh+.   hMMM:     :MmMMMM/   ./yy/` `:sys+/+sh/
 .dMMMMMMmdddddmmNMMMNNNNNMMMMMs           sNdo-      dMMM-  `-/yd/MMMMm-:sy+.   :hs-      /N`
  `/ymNNNNNNNmmdys+/::----/dMMm:          +m-         mMMM+ohmo/.` sMMMMdo-    .om:       `sh
     `.-----+/.`       `.-+hh/`         `od.          NMMNmds/     `mmy:`     +mMy      `:yy.
           /moyso+//+ossso:.           .yy`          `dy+:`         ..       :MMMN+---/oys:
         /+m:  `.-:::-`               /d+                                    +MMMMMMMNh:`
        +MN/                        -yh.                                     `+hddhy+.
       /MM+                       .sh:
      :NMo                      -sh/
     -NMs                    `/yy:
    .NMy                  `:sh+.
   `mMm`               ./yds-
  `dMMMmyo:-.````.-:oymNy:`
  +NMMMMMMMMMMMMMMMMms:`
    -+shmNMMMNmdy+:`


                                                                 Now attempting installation...


Looking for a previous installation of SDKMAN...
Looking for unzip...
Looking for zip...
Looking for curl...
Looking for sed...
Installing SDKMAN scripts...
Create distribution directories...
Getting available candidates...
Prime platform file...
Prime the config file...
Installing script cli archive...
* Downloading...
######################################################################## 100.0%
* Checking archive integrity...
* Extracting archive...
* Copying archive contents...
* Cleaning up...

Installing script cli archive...
* Downloading...
######################################################################## 100.0%
* Checking archive integrity...
* Extracting archive...
* Copying archive contents...
* Cleaning up...

Set version to 5.18.2 ...
Set native version to 0.4.6 ...
Attempt update of interactive bash profile on regular UNIX...
Added sdkman init snippet to /root/.bashrc
Attempt update of zsh profile...
Updated existing /root/.zshrc



All done!


You are subscribed to the STABLE channel.

Please open a new terminal, or run the following in the existing one:

    source "/root/.sdkman/bin/sdkman-init.sh"

Then issue the following command:

    sdk help

Enjoy!!!
```

You need `rm -rf ~/.sdkman/`，then reinstall it. May you need `export https_proxy="http://127.0.0.1:10809"`

**Comment by wrthissell** [comment]
I am using Windows 10 with Bash for Windows V 2.47.1, the latest version of curl as of this writing.  I created the https_proxy="https://127.0.0.1:10809" and http_proxy="http://127.0.0.1:10809" environment variables.  I get the following error:


thissell@wrtntbk2 MINGW64 ~
$ curl -v "https://get sdkman.io" | bash
* URL rejected: Malformed input to a URL function
* closing connection #-1
curl: (3) URL rejected: Malformed input to a URL function

The following webpage: https://knowledge.broadcom.com/external/article/371676/seeing-url-rejected-malformed-input-to-a.html explains that spaces in a url are no longer allowed in recent versions of curl.  May the sdkman installation program be revised to replace spaces with %20 so I may be able to install it?
