### ISSUE TITLE
installation options for linux users

### ISSUE THREAD

**Issue by rogerwelin** [sdkman/sdkman-cli#540]
A deb & rpm package would be nice as a linux user instead of the curl | bash option

**Comment by marc0der** [comment]
This is not feasible, as we install sdkman into the user's directory. sdkman is built to manipulate the `PATH` on a per user basis, so it makes more sense to keep it at the user home level. Also, sdkman is responsible for it's own updates which would clash with package managers. Lastly, sdkman's installation candidates would clash with the package managers equivalent packages.

In future, please feel free to discuss on our [gitter channel](https://gitter.im/sdkman/user-issues) prior to opening a github issue as per our guidelines found [here](https://github.com/sdkman/sdkman-cli/blob/master/README.md).
