### ISSUE TITLE
sdk use gradle 3.4.1 - not works, not works sdk commands

### ISSUE THREAD

**Issue by boyfox** [sdkman/sdkman-cli#544]
I don't understand why sdk tools says "done" but, not works when checking:

![screen shot 2017-03-09 at 3 33 44 pm](https://cloud.githubusercontent.com/assets/3168694/23746470/cf8f8014-04dd-11e7-9b92-f8b3eafff998.png)

How to fix this problem? 

I'm using Mac : 

![screen shot 2017-03-09 at 3 34 24 pm](https://cloud.githubusercontent.com/assets/3168694/23746495/eb28bfb6-04dd-11e7-8952-610549215133.png)

**Comment by marc0der** [comment]
Can you try opening a new terminal? If that doesn't work, try sdk default gradle.

In future, please raise usage questions on our gitter channel before opening an issue.

**Comment by boyfox** [comment]
I tried sdk default gradle, not works, this is not a question

**Comment by marc0der** [comment]
This is most certainly a usage issue or something down to your local environment. If you ping me directly on gitter I can try running through some options to help you get it working.
