### ISSUE TITLE
Provide option to install documentation folders

### ISSUE THREAD

**Issue by aplatypus** [sdkman/sdkman-cli#545]
As stated, I would be useful to include documentation folders with packages as an option a secondary install or something like that.

For example my IDE wants to point to the Docs folder.  After a recent update to Groovy, I found the iDE was loading the documentation for the version I had installed way before I started using SDK MAN.

Many thanks for consider ing ths request.

**Comment by marc0der** [comment]
This is up to the individual vendors whether they want to distribute the lite binary or a full binary including docs and samples on sdkman. @paulk-asert would probably be the right person to speak to about this, since he performs the publishing for the Groovy binaries.

**Comment by aplatypus** [comment]
Hi again, OK ... I will follow that up.  It also occurred to me to add a suggestion for the library source code.  Given your response, I guess what we are talking about under this regime would be "package configurations".  Is that allowed for?  Just checking so I mention the most appropriate thing.

**Comment by marc0der** [comment]
Sdkman is totally agnostic of the content of the binaries that it distributes. In other words, we can distribute whatever the vendor wishes to distribute as it's binary, which may include docs, samples or the source code.

**Comment by paulk-asert** [comment]
From 2.4.10 we now include the doco when you install. Hopefully everyone is happy with the slightly fatter download.

**Comment by marc0der** [comment]
Thanks for the update Paul! Closing this issue...

**Comment by aplatypus** [comment]
That's good news.  Personally I would have preferred a CLI based solution so those on diets could go fat-free.  For example;
-  sdk install groovy-doc
-  sdk install groovy-src

Giving users the choice about what they load.  Neverthe less it's a good result.
