### ISSUE TITLE
use makes the candidate default if no default was set

### ISSUE THREAD

**Issue by dovchinnikov** [sdkman/sdkman-cli#555]
Steps: 
```
~$ sdk install <candidate> <version>
~$ rm .sdkman/candidates/<candidate>/current
~$ sdk use <candidate> <version>
```

Result: 
`<candidate>` of `<version>` is default again

Expected result:
no defaults are set when `use` is used

**Comment by marc0der** [comment]
I don't understand why you are manually removing the current link. This is not recommended at any time.

Simply put, this is not a bug as you shouldn't be tampering with symlinks that sdkman creates for its internal use.

Lastly, every candidate _must_ have a default at all times, else it leads to inconsistent state.

**Comment by dovchinnikov** [comment]
I was expecting `use` to modify only current environment. 

I'm removing `current` so my scripts relying on some predefined variables will effectively fail unless they don't execute appropriate `sdk use` command.

I'm working with multiple versions of gradle, groovy and grails, and each time I open new terminal I'm setting the version of desired candidate with `use`.

> every candidate must have a default at all times, else it leads to inconsistent state

Please clarify why.

**Comment by marc0der** [comment]
I suggest that you read the [documentation](https://github.com/sdkman/sdkman-cli/blob/master/src/test/cucumber/use_version.feature) that describes how the `use` command works. 

Deleting the `current` symlink is _not_ a valid use case, and any effects that it may cause is most certainly not a bug.

**Comment by dovchinnikov** [comment]
I'm sorry if this is wrong place to ask, but I still don't understand inconsistent state when there is no default set. If there is no way to unset the default version, I think there should be one.

BTW [documentation](http://sdkman.io/usage.html#use)  explicitly states that `use` modifies state **for the current shell only**.

**Comment by marc0der** [comment]
It is definitely an inconsistent state because when opening a new shell,
the candidate will appear not to be there. This is not sensible from a user
experience perspective. This is why we make the assumption that if a
candidate is first installed, that version is the default.

Subsequently, you can then install other version(s) and then get the option
to make those default.

If no current link is present (ie no default set), it won't be added to the
path and it appears that the candidate is not installed. This in turn
causes much confusion.

I hope this clarifies it for you.

**Comment by dovchinnikov** [comment]
> when opening a new shell, the candidate will appear not to be there

That is my point. I expect the candidate not to be there.

> it appears that the candidate is not installed

IMO deciding whether candidate is installed or not by existence of `current` link is not a good design...

I'm asking for a way to unset a default, and not setting default unless user answers _Yes_ (like when installing a new version with another default already set). Should I create a new issue?

**Comment by marc0der** [comment]
No, this is not a bug and will not be changed. Period.

**Comment by dovchinnikov** [comment]
I have several versions of Groovy (~25) and another bunch of Grails (~15) installed. I'm getting tired of searching how some version got into classpath, via some environment variable or some symbolic link.
Example: there was a user of IntelliJ, and I couldn't reproduce his issue. Turned out default Gradle was set to 2.1, and Grails was picking it up via `current`. So I prefer to keep globals as clean as possible.

At the same time sdkman is very convenient for downloading distributions. I install a candidate, point to it from IntelliJ and I'm ready to go. 

Since you don't want to change how `use` or `default` behave, could you please introduce a new option, something like `sdk set`, which will behave like `use` without messing with `current`?

**Comment by marc0der** [comment]
Nope, sdkman works perfectly fine as it is. It is meant to manage environment variables, not just download binaries. This is by design.

A `set` command is not required, read the manual and understand how `use` and `default` really  work and you will see that it isn't required.

If you really don't like how sdkman works, feel free to fork the code and run your own version.

**Comment by dovchinnikov** [comment]
Basically the same issue: ability to revert to system state for all subsequent shells (remove `current` symlink). https://github.com/sdkman/sdkman-cli/issues/673

**Comment by sysmat** [comment]
$ sdk default gradle 6.0.1
rm: cannot remove '/c/Users/tomaz/.sdkman/candidates/gradle/current': Is a directory
ln: failed to create symbolic link '/c/Users/tomaz/.sdkman/candidates/gradle/current/6.0.1': File exists
