### ISSUE TITLE
ug command claims no candidates are in use

### ISSUE THREAD

**Issue by kousen** [sdkman/sdkman-cli#561]
```
$ sdk v

SDKMAN 5.5.8+227
```

Running on OS X El Capitan, 10.11.6
Running zsh (oh_my_zsh, to be specific)

```
$ sdk c

Using:

asciidoctorj: 1.5.5
gradle: 3.5
grails: 3.2.8
griffon: 1.5.0
groovy: 2.4.10
java: 8u121
kotlin: 1.1.1
lazybones: 0.8.3
springboot: 1.5.2.RELEASE
sshoogr: 0.9.25
```

```
$ sdk ug

No candidates are in use
```

Always worked before. Any advice would be appreciated.

**Comment by marc0der** [comment]
This is a know issue and was addressed in a pull request by @pbassiner. https://github.com/sdkman/sdkman-cli/pull/559

I'll be releasing this shortly.
