### ISSUE TITLE
Shebang assumes bash to be in /bin which will never be true for *BSD

### ISSUE THREAD

**Issue by michael-o** [sdkman/sdkman-cli#562]
Shebang says `#!/bin/bash`. It will never work on *BSD because it is installed from ports to `/usr/local/bin/bash`. Frontpage claims FreeBSD compat.

Change shebang to `#!/usr/bin/env bash` which is the common standard these days and a portable approach.

**Comment by marc0der** [comment]
Sounds sensible. Of course PRs are always welcome :-)
