### ISSUE TITLE
sdkman inconsistiency(-ies)

### ISSUE THREAD

**Issue by aplatypus** [sdkman/sdkman-cli#565]
When I list sdk -- I can see "`sdk install kotlin` as a sensible command to install kotlin.

```
sdk install kotlin
sdk list
sdk install kotlin

Stop! kotlin is not a valid candidate.
```
A week back I installed/upgraded gradle 3.5; at that time I also had similar troubles.  Tonight for instance I have this result:
```
gradle -version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Linux 4.4.0-72-generic amd64

 ~ $ sdk current

No candidates are in use
```
* _huh_?!

According to the SDKMAN usage page, that should list the programs installed and the version I'm using.
*  http://sdkman.io/usage.html#current

The network is working, evidenced by me writing-up this issue.  Yet it can often report that something can't be done without the network.  I have found that enabling offline and then disabling offline sometime helps with that for a short time.

At the end of this, I feel there's some built-in limitations with the scripts assumptions and probably some muddling of the "internal state".

A few months ago I just renamed the .sdkman folder and reinstalled the product.  That actually saw me _right_ until recently.  At least I could update groovy and gradle even if it took (like) 10 attempts.  Or so between the two.

It is unclear for me how sdkman could get "mixed-up" in this way.  More to the point:
```
$ ls -lt ~/sdkman/candidates/kotlin
total 8
lrwxrwxrwx 1 aa aa   45 Apr 13 06:56 current -> /home/aaa/.sdkman/candidates/kotlin/1.1.1
drwxr-xr-x 5 aa aa 4096 Mar 13 12:07 1.1.1
drwxr-xr-x 5 aa aa 4096 Feb 16 19:43 1.1-RC
```
and while  ...
```
$ kotlin -version
kotlin: command not found
```
doesn't work, the kotlin command is available:
```
~/.sdkman/candidates/kotlin/current/bin/kotlin -version
Kotlin version 1.1.1 (JRE 1.8.0_121-b13)
```
I think I'd like to see some diagnostic commands or options to clean-up  in the sdkman data-store.  A few ideas:
1.  `sdk cleanup`
   - inspired by the svn cleanup command
1.  `sdk reset` or `rebuild`
   -  The reason for this is that the raw stuff sdkman needs is available as folder-tree paths and it might be more straightforward for sdkman to just rebuild it's status database and metadata from what is actually there on disk.  
  - In the process it might also log the inconsistencies it finds along the way
  - a `reinstall` option might be useful too -- Essentially repeating what I did when I remove things and reinstalled sdkman.
1.  `sdk status` ... just report on whatever state matters compared with the actual state of the folder tree.
1.  `sdk show_log [date]` ... list the current log (default) or for the specified date

From what I've seen something is mixed-up, sometimes and reinstalling looks like the most reliable way to deal with stuff.  I don't see the SDKMAN procedure as bing that complicated that it can't keep the books in-order.   If things are becoming messy, it is probably a basic flaw in the process model -- Like may be some download was incomplete?  Are we checking completeness, etc.

I hope someone has some helpful information or options to try.  I used the flush command, that doesn't appear to have helped or improved this weird stuff.

**Comment by marc0der** [comment]
Sounds like you have intermittent or slow network access. You can try increasing the curl timeouts in the config file which usually solves the problem.

Nobody else is experiencing these issues at this time, which makes me think that this local to your environment. Also, all this functionality is extensively tested with automated tests on CI which proves that our scripts are probably not at fault here.

**Comment by marc0der** [comment]
Did you try the suggestion to adjust timeouts? Can I close this issue now?

**Comment by aplatypus** [comment]
yes OK

**Comment by marc0der** [comment]
Then closing this issue.
