### ISSUE TITLE
Maven 3.0.1

### ISSUE THREAD

**Issue by fouvry** [sdkman/sdkman-cli#570]
Hi,

It would be helpful if I could install maven 3.0.1 using sdkman.

In any case, thanks for the tool!

**Comment by McPringle** [comment]
@fouvry, do you still need Maven 3.0.1? As of today, Maven 3.3.9, 3.5.0 and 3.5.2 are available in SDKMAN.

**Comment by marc0der** [comment]
@fouvry if you really do need it, it can now be installed via a simple PR on our db migrations project:
https://github.com/sdkman/sdkman-db-migrations

**Comment by fouvry** [comment]
I got the suggestion to download it manually, store it in the archives directory, and then run the installation command (I think). That worked, and was sufficient for me.

@marc0der, Thanks for the pointers to the new possibility!

**Comment by marc0der** [comment]
Great pleasure!
