### ISSUE TITLE
Installation of Java fails on Cygwin

### ISSUE THREAD

**Issue by fouvry** [sdkman/sdkman-cli#571]
Hi,

I tried to install Java (through bash from CygWin), but I get the following error message

```
-bash: /cygdrive/c/Users/thisuser/.sdkman/tmp/g22MTLT714qgj87zDVSwR8qkGIy7Znvg.bin: Permission denied
mv: cannot stat '/cygdrive/c/temp/jdk': No such file or directory

zip error: Nothing to do! (try: zip -qr /cygdrive/c/Users/thisuser/.sdkman/tmp/g22MTLT714qgj87zDVSwR8qkGIy7Znvg.zip . -i .)

Done repackaging...
mv: cannot stat '/cygdrive/c/Users/thisuser/.sdkman/tmp/g22MTLT714qgj87zDVSwR8qkGIy7Znvg.zip': No such file or directory
unzip:  cannot find or open /cygdrive/c/Users/thisuser/.sdkman/archives/java-8u131.zip, /cygdrive/c/Users/thisuser/.sdkman/archives/java-8u131.zip.zip or /cygdrive/c/Users/thisuser/.sdkman/archives/java-8u131.zip.ZIP.
rm: cannot remove '/cygdrive/c/Users/thisuser/.sdkman/archives/java-8u131.zip': No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.
```

Any idea what might be going on? (Environment variable, permissions?)

Thanks!

**Comment by psramkumar** [comment]
run your Cygwin in Administrator Mode and give a try.

Note: still it may not work because above stated Path`'/cygdrive/c/temp/jdk'` is not correct  
looking for the way to change this path to `.sdkman/tmp` instead

**Comment by psramkumar** [comment]
Please follow the other thread.
https://github.com/sdkman/sdkman-cli/issues/520

it is better to close this one

**Comment by fouvry** [comment]
Running the CygWin bash shell in Administrator mode installed the package.

**Comment by psramkumar** [comment]
Found one alternative for Time being, 
zip JDK7 home folder as `java-7u80.zip` copy inside "SDKMAN_HOME/achives"
then run `sdk install java 7u80`

this time the installation will be success, since the binary is already downloaded in right place.

Similarly you can do the same for 8 and 9 

hope this helps for now.

**Comment by marc0der** [comment]
Mark as duplicate #520
