### ISSUE TITLE
Java 9 ea167 missing java.lang.reflect.Module and Layer

### ISSUE THREAD

**Issue by renatoathaydes** [sdkman/sdkman-cli#573]
Looks like Java 9 ea167 is missing some new Java 9 classes like `java.lang.reflect.Module` and `java.lang.reflect.Layer`.

When I upgraded, my code that uses those classes no longer compiled. Setting the JDK in IntelliJ also shows those classes are missing.

Downgrading  to Java 9 ea163 makes the problem go away.

Please report to Oracle if the problem is actually with their distribution of Java 9EA167.

**Comment by marc0der** [comment]
We don't really have any contact with Oracle, we merely distribute the binaries on their site.

Perhaps you could try feeding this issue back to them yourself on their JDK 9 forums?

**Comment by renatoathaydes** [comment]
I thought you might want to remove this version from the  repository as it is obviously broken... and I have tried to report the bug but they don't make it easy to do it at all...

I also noticed that the version printed with `java- version` is not the one reported by SDKMAN.

So, I am not sure I should file the bug with Oracle instead of SDKMAN:

```
sdk use java 9ea163

Using java version 9ea163 in this shell.
➜  test-modules git:(master) ✗ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+157)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+157, mixed mode)
```

**Comment by renatoathaydes** [comment]
Oh, my previous comment obviously refers to the previous java version in SDKMAN, `9ea163` (which reports itself to be 9ea157). The latest one, `9ea167` reports the expected version.

**Comment by marc0der** [comment]
Very odd, I'm not really seeing that on my side:

```
$ sdk u java 9ea163
$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+163)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+163, mixed mode)
```

Could there be something else wrong here?
