### ISSUE TITLE
7z and RAR support!

### ISSUE THREAD

**Issue by aadrian** [sdkman/sdkman-cli#576]
Please add 7z and RAR also as accepted pack/unpack solutions, especially since Windows systems don't come with zip/unzip.

Thank you.

**Comment by marc0der** [comment]
Windows systems do not come with 7z or RAR support. Windows however does come with zip/unzip when you use cygwin, and this has always worked from day 1.

**Comment by aadrian** [comment]
> Windows systems do not come with 7z or RAR support. 

No, but they're free and are installed in most corporate environments. 

> Windows however does come with zip/unzip when you use cygwin, 

If users are allowed to use Cygwin, they can also use PowerShell most of the time :).

Bash (from Git) is a different story :) . WinZip however is not that common.
