### ISSUE TITLE
use command broken in cygwin

### ISSUE THREAD

**Issue by sparsick** [sdkman/sdkman-cli#579]
Using `sdk use` on cygwin, I get following error:
```
__sdk_use:export:35: not valid in this context: Files/TortoiseGit/bin:/cygdrive/c/Program
```

I think the reason is that I have blank spaces in my PATH variable. It seems the problem is similar to #378 .

**Comment by marc0der** [comment]
Thanks for your contribution. I will be releasing this in the very near future.
