### ISSUE TITLE
Use real Vertx server for Cucumber tests

### ISSUE THREAD

**Issue by pledbrook** [sdkman/sdkman-cli#58]
The Cucumber tests should verify that both the client and server are working as expected. At the moment, they're using a stub server implementation. Since I want to add a test for checking the behaviour of out-of-date versions of gvm and the implementation of that feature requires code changes on the server, we really need to be running against the server code.

I guess the issue here is the dependency on MongoDB, but I wonder whether it's possible to run the server app with a dummy mongo-persister busmod that we can initialise with duff data. Or we can have the Cuke tests require a running MongoDB instance, but that's probably a non-starter.

**Comment by marc0der** [comment]
We have since cut over the acceptance tests to use wiremock instead. This was done because acceptance tests should test the behaviour of the CLI, not be an end-to-end suite.

Having said that, I plan to write some end-to-end multi-platform smoke tests using spock soon.
