### ISSUE TITLE
Oracle JDK - Ability to Download Your Own File?

### ISSUE THREAD

**Issue by EarthCitizen** [sdkman/sdkman-cli#585]
I recently read the (sdkman) blog post about the download link issues for Oracle JDK. Unfortunately, OpenJDK is not an option for our organization, but still, we desperately need the version management features of sdkman.

This may be somewhat wonky, but what if the user could download their own file and provide the file locally to sdkman?

**Comment by tpraxl** [comment]
I would very much appreciate that. Currently – only for one project – I absolutely need the Oracle SDK. So what I needed to do was: 

* http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
* vim ~/.bashrc
* comment out the sdkman initialization

Next time, I need to use the sdks installed via sdkman, I need to uncomment that section. This is annoying.

**Comment by EarthCitizen** [comment]
Closing this as I was made aware of the local install feature of sdkman:

http://sdkman.io/usage.html#localversion

**Comment by tpraxl** [comment]
Example for using a preinstalled (local) version of the oracle jdk with sdkman on Ubuntu 14.04:

```
sdk install java 8u131-oracle-local /usr/lib/jvm/java-8-oracle
sdk default java 8u131-oracle-local
```
