### ISSUE TITLE
When are new JDK 9 ea builds updated?

### ISSUE THREAD

**Issue by eljobe** [sdkman/sdkman-cli#588]
I'm curious to understand what has to happen after a new JDK 9 ea build version is released, and when it shows up in `sdk list java`'s output? Version 174 is out, but Sdkman's latest version is 170. Is there something I can do to help get the latest release out on Sdkman?

**Comment by eljobe** [comment]
@marc0der any hints on this?

**Comment by marc0der** [comment]
I'm currently in talks with Azul to start releasing their JDKs in much the
same way as Gradle publishes their releases. Hopefully this will include
9ea releases too. I'll keep updating the progress here.

**Comment by marc0der** [comment]
@eljobe great news is that Azul have started publishing JDK 8 on SDKMAN and will soon start publishing 9 EA releases too. Will close this issue when the first 9 EA release is available.

**Comment by mpschuetze** [comment]
Hi guys. Azul pushed  Zulu 9ea13 tonight. Binaries should work on Intel x64 for Linux, Windows, and MacOS. Please let me know if you see any glitches. Thanks. Matt

**Comment by marc0der** [comment]
Thanks @mpschuetze! Closing this issue now.
