### ISSUE TITLE
$HOME/.sdkman/bin empty after installing

### ISSUE THREAD

**Issue by mquilzini-daitan** [sdkman/sdkman-cli#590]
When I run the command:
curl -s "https://get.sdkman.io" | zsh
it fails to populate $HOME/.sdkman/bin folder but prompts as successfully installed.

**Comment by xiejinpeng007** [comment]
I have the same problem , it's an empty folder.
and a download the sdkman-init.sh and execute,
another problem came out :
"__sdkman_echo_debug: command not found"

**Comment by marc0der** [comment]
We will need a lot more information than this. Please provide console output, platform, shell as well as all relevant versions.

**Comment by mauricioborges** [comment]
@marc0der I may be able to help. Having the same issue here. The console output you may find relevant is the following:
```
Download script archive...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  717k  100  717k    0     0   225k      0  0:00:03  0:00:03 --:--:--  392k
Extract script archive...
[/home/mauricio/.sdkman/tmp/res-5.5.9+231.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/mauricio/.sdkman/tmp/res-5.5.9+231.zip or
        /home/mauricio/.sdkman/tmp/res-5.5.9+231.zip.zip, and cannot find /home/mauricio/.sdkman/tmp/res-5.5.9+231.zip.ZIP, period.
```
It fails from there as it's not able to unzip it.

I'm running arch-linux x86-64 and I've tried against bash 4.4.12 and zsh 5.3.1

**Comment by Keidrych** [comment]
Install is failing as the file isn't able to be located, hosting service 'BinTray' doesn't seem to contain the current release file anymore

**Comment by mauricioborges** [comment]
@Keidrych just saw that Bintray itself is experiencing issues :/

**Comment by Keidrych** [comment]
Okay got this working... get.sdkman.io is specifying a release that doesn't exist in BinTray.. SDKMAN_VERSION="5.5.9+231"

If you update this to 5.5.9+239 (latest) then it will install.

**Comment by marc0der** [comment]
@mauricioborges Just looked now and it seems like the binary is available again. @Keidrych there is no version `5.5.9+239` available on Bintray, so not sure where you're getting that from. The only artifact produced by build 239 was `master+239` which is available on our beta channel.

Just tested everything and it all seems to be fine now. Let me know on Gitter if you have any further issues.
