### ISSUE TITLE
sdk list is broken for PAGER containing arguments

### ISSUE THREAD

**Issue by alexeiz** [sdkman/sdkman-cli#594]
The error is like this:
```
% sdk list
__sdkman_page:2: command not found: less -R -M --shift 5 -F -X
```

From the `man 1 man` page:
```
MANPAGER, PAGER
...
    The  value  may  be a simple command name or a command with arguments.
```

You need to do `eval $PAGER` in `__sdkman_page`.

**Comment by marc0der** [comment]
This currently works in all our test environments (Cygwin, OSX, Ubuntu, Centos), so I would need to know a lot more detail than what was given above. Please provide your OS, your shell and other contextual details that might shed light on your issue.

**Comment by alexeiz** [comment]
The issue is environment independent.  You need to `export PAGER="less -R -M --shift 5 -F -X"` to reproduce it.

**Comment by marc0der** [comment]
That's not standard shell behaviour though, which means that this is not a valid issue. We depend on the pager environment variable being set to a sensible value. Could you try setting to `less` and tell us if it works?

**Comment by marc0der** [comment]
Fair enough, I've had a closer look at your PR and see your point. Will merge shortly.
