### ISSUE TITLE
Mismatch for Gradle and current Groovy

### ISSUE THREAD

**Issue by aplatypus** [sdkman/sdkman-cli#595]
I noticed something unexpected.  I think it could be something in the Gradle configuration.  I am reporting it here as the first step to tracking down the root cause.   In a nut shell the Gradle installation is NOT using the current version for Groovy.

The current version of Groovy is **v2.4.12**

I used the `sdk install gradle` tonight to upgrade Gradle.  When I checked the upgrade I found that the Gradle is Not using the current Groovy.  i also have a `GROOVY_HOME` path set,

````
platypus ~ $ echo $GROOVY_HOME
/home/william/.sdkman/candidates/groovy/current
````
As you see the latest Gradle **v4.1** installed under this regime show Groovy v2.4.**_11_** ... _wtf!_

A key reason for using SDKMAN is to ensure the selected choice of versions for software are the active and executed versions.  So (for instance) I may swap to Groovy 2.2 for some reason -- Like checking a regression test to make sure the test wasn't broken by the Groovy version... But if dependents tools like Gradle ignore the current state settings and options, at best results for that use-case will be unreliable.

I can accept that  Gradle might report that it needs a specific version of Groovy when I run Gradle.  So Gradle 4.1 may _barf_ if I try to run with Groovy 2.2 (say).  If Groovy 2.2 is the **_current_** setting I definitely expect Groovy to run with Groovy (_current_) 2.2 and not 2.4.11.

I trust you see the point.  SDKMAN is very useful as a command-and-control system for SDK-s.  If it won't do that, or if packages undermine that capability, then I need to know that so tasks like the regression checking I mentioned are carried out with fidelity.

For instance does SDKMAN have something to configure an installation?  Say an option that can let me tell Gradle to use the _current_ Groovy _run-time!??_

Or is this a Gradle SDKMAN problem?

````
platypus ~ $ sdk default groovy
Default groovy version set to 2.4.12

platypus  ~ $ sdk current groovy
  Using groovy version 2.4.12

platypus  ~ $ gradle -version
-----------------------------------------------------------
Gradle 4.1
------------------------------------------------------------
Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11   #  <---
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.4.0-87-generic amd64
````

**Comment by marc0der** [comment]
This is not a bug. Gradle is a completely standalone SDK that comes with
its own bundled groovy jar. Grails functions in the same way.

It is also worth noting that SDKMAN is not a package manager in the
traditional sense. We don't handle dependencies between SDKs, but expect
each SDK to provide all it's own. My definition of an SDK is that it is a
completely standalone distribution.
