### ISSUE TITLE
feature: silent sdk install

### ISSUE THREAD

**Issue by koooge** [sdkman/sdkman-cli#596]
Hello.
`sdk install` shows always progress bar by `curl --progress-bar`.
But, it's bothering in case like provisioning.
So, I want options suppress progress-bar like `curl -s` or `curl -sS`.
For example `sdk install --silent`
How about it?
Thank you

**Comment by marc0der** [comment]
Sure, PRs are always welcome but let's first talk about it in our Gitter [cli-dev](https://gitter.im/sdkman/cli-dev) chat room so we can agree on an approach.

**Comment by koooge** [comment]
I looked `npm` , but I didn't see any similar command.  I reconsidered this and I think this is fine as it is `> /dev/null`. Thank you.
