### ISSUE TITLE
Deprecated/obsolete candidate support!

### ISSUE THREAD

**Issue by aadrian** [sdkman/sdkman-cli#601]
Some of the candidates in the list are "deprecated/obsolete". e.g. the case of `activator`. Removing them would  break the usage for some existing users, but it would be nice if it were visible that hose candidates are deprecated for new users. e.g. when `sdk ls`.

Thank you.

**Comment by marc0der** [comment]
I think the effort involved would be too high for the small benefit we would gain. Candidates are hardly ever removed; so far activator is the only one.

Please follow our new guidelines in future before opening an issues.
