### ISSUE TITLE
For MacOS 10.12, It did't add "sdkman_init_snippet" to .bash_profile

### ISSUE THREAD

**Issue by chinaPD** [sdkman/sdkman-cli#606]
I'm using macOS, and i installed sdkman with **curl -s "https://get.sdkman.io" | bash**. Everytime i open a terminal, it needs to run **source "$HOME/.sdkman/bin/sdkman-init.sh"**. I saw the file downloaded from https://get.sdkman.io and found sdkman_bash_profile of mac profile path is declared but not used. and sdkman_init_snippet is writed to ${HOME}/.bashrc, but it is not used by macOS.

**Comment by marc0der** [comment]
Please follow our guidelines before raising issues.
