### ISSUE TITLE
alias to gvm should not be default

### ISSUE THREAD

**Issue by techgaun** [sdkman/sdkman-cli#607]
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [x] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

Right now, we can disable the gvm alias for sdk by setting `sdkman_disable_gvm_alias` to `true` in the `$SDKMAN_DIR/etc/config` but now that its been quite a time that gvm name was removed, I think it makes more sense to have that as a configurable option. Also, it conflicts with [gvm](https://github.com/moovweb/gvm/) so it would be great if we could have these two great version managers co-exist together without conflicts in user's system. I've posted my thoughts on https://gitter.im/sdkman/user-issues as well.

**Comment by marc0der** [comment]
My suggestion would be to remove that alias all together. One of the main reasons we changed the name was to get rid of the ambiguity and name-clash. The only reason we kept the alias around was to appease a few.
