### ISSUE TITLE
IDE support

### ISSUE THREAD

**Issue by THUFIR** [sdkman/sdkman-cli#609]
Feature request.

Here is the discussion:

(04:06:59 AM) The topic for #sdkman/cli-dev is: New Feautures or Enhancements
(04:07:23 AM) THUFIR: will you be adding netbeans?
(05:08:14 AM) THUFIR: anyone there?

really says it all.  Two overlapping tools (umake and sdkman) not optimal for this user.  Would preferably use just one of those.  Please add IDE support.

**Comment by marc0der** [comment]
We've recently introduced database migrations that allow users to contribute their own candidates and versions. The migrations project can be found here:
https://github.com/sdkman/sdkman-db-migrations

Feel free to raise a PR to get netbeans onto sdkman.

**Comment by marc0der** [comment]
@THUFIR shout of anything is unclear or if you need any help with this. Examples have been provided to help you get going.
