### ISSUE TITLE
Consider adding support for VisualVM

### ISSUE THREAD

**Issue by vpavic** [sdkman/sdkman-cli#612]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [X] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

It would be nice to have VisualVM available as a candidate in SDKMAN.

Even though VisualVM is distributed as a part of Oracle JDK, providing first class support would be highly beneficial to OpenJDK users, and would also ensure the users are able to run the same version of VisualVM regardless of the currently used JDK version.

The standalone VisualVM project is available at https://visualvm.github.io/.

**Comment by marc0der** [comment]
VisualVM 1.3.9 has now been added. Please feel free to raise a PR on our [DB Migrations](https://github.com/sdkman/sdkman-db-migrations) if you want to use other versions (or if newer versions are released).
