### ISSUE TITLE
In ZSH show zsh: command not found: sdk

### ISSUE THREAD

**Issue by zhouhuacong** [sdkman/sdkman-cli#613]
In my Macbook pro, on zsh type "sdk" show zsh: command not found: sdk

then i enter :curl -s "https://get.sdkman.io" | bash   it will work again.

but when i close this terminal and start a new one , it's show command not found: sdk again.

how to solve this ?

**Comment by meltzerpete** [comment]
For bash, sdkman appends the following to your ~/.bashrc
`
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/USER/.sdkman"
[[ -s "/home/USER/.sdkman/bin/sdkman-init.sh" ]] && source "/home/USER/.sdkman/bin/sdkman-init.sh"
`
(where USER is your username)

Just copy this on to the end of the ~/.zshrc and it should work just fine.

**Comment by marc0der** [comment]
Can you confirm that you have this snippet? This should have been appended automatically to the `.zshrc` file when you installed sdkman.

**Comment by aadrian** [comment]
@marc0der it happens quite often with oh-my-zsh that an update is reverting that file to some old backup, and those lines need to be manually added back.

**Comment by meltzerpete** [comment]
Ah no, I copied it manually since I also had the same problem.

**Comment by marc0der** [comment]
I also use oh-my-zsh but have never had it reverting my changes to .zshrc.
Let me know if you see this happening again.

**Comment by Jiiiiiin** [comment]
✘ jiiiiiin@jiiiiiins-MacBook-Pro  ~/.oh-my-zsh/custom/plugins   master  source ~/.zshrc
/Users/jiiiiiin/.zshrc:120: parse error near `[['
 ✘ jiiiiiin@jiiiiiins-MacBook-Pro  ~/.oh-my-zsh/custom/plugins   master 

why?

**Comment by Jiiiiiin** [comment]
.zshrc add:
```cmd
SDKMAN_DIR="/home/jiiiiiin/.sdkman" [[ -s "/home/jiiiiiin/.sdkman/bin/sdkman-init.sh" ]] && source "/home/jiiiiiin/.sdkman/bin/sdkman-init.sh"
```
jiiiiiin is my mac username

**Comment by marc0der** [comment]
What happens when you source the `~/.sdkman/bin/sdkman-init.sh`?

Another experiment, what happens when you manually source your `.zshrc`.

**Comment by do-adams** [comment]
For some reason, I was having the same problem on my MacBook Pro when doing a clean install of sdkman.

I ended up manually adding the snippet that @meltzerpete posted at the end of both my .bashrc and .bash_profile files. 

That took care of it 🍻

**Comment by cresharper** [comment]
This does not work for me despite following suggestions. See below:

![screen shot 2017-12-20 at 11 55 01 am](https://user-images.githubusercontent.com/9372848/34218638-b724a8ee-e57c-11e7-93b6-55cc643746e2.png)

Full .zshrc below:


```
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[ -s "/Users/charper/.jabba/jabba.sh" ] && source "/Users/charper/.jabba/jabba.sh"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/charper/.sdkman"
[[ -s "/Users/charper/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/charper/.sdkman/bin/sdkman-init.sh"

```

**Comment by marc0der** [comment]
The clue is in the title bar of your shell: it's a bash shell, not zsh. On
Linux we use the chsh command to permanently switch to a different shell.
Not sure if the same is true for OSX.

**Comment by cresharper** [comment]
I needed to include this in my `.bash_profile` - looks like it's working good now

**Comment by marc0der** [comment]
Excellent news! Closing this issue.

**Comment by cepix** [comment]
> For bash, sdkman appends the following to your ~/.bashrc
> `#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!! export SDKMAN_DIR="/home/USER/.sdkman" [[ -s "/home/USER/.sdkman/bin/sdkman-init.sh" ]] && source "/home/USER/.sdkman/bin/sdkman-init.sh"`
> (where USER is your username)
> 
> Just copy this on to the end of the ~/.zshrc and it should work just fine.

`#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!! 
export SDKMAN_DIR="$HOME/.sdkman" 
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"`

**Comment by edilson14** [comment]
i belive that you was using sdk on bash, you just have to copy the line in the .bash_profile , that export sdk , and past on the .zshrc, and refresh

**Comment by rafambbr** [comment]
Just execute this line: works fine for me Ubuntu 19.04

`echo 'source "$HOME/.sdkman/bin/sdkman-init.sh"' >> ~/.zshrc`

**Comment by xadimousalih** [comment]
Very simple

step 1: 

    vim ~/.zshrc

step 2:(Add at the end of the file)

    source ~/.bash_profile;

step 3:(Execution shell)

    > source ~/.bash_profile

You can use sdkman :
➜  sdk

We periodically need to update the local cache. Please run:

  $ sdk update

==== BROADCAST =================================================================
* 2020-09-21: jbang 0.47.1 now available for download.
* 2020-09-20: jbang 0.46.1 @jbangdev https://git.io/JUEb5
* 2020-09-20: jbang 0.46.0 @jbangdev https://git.io/JUEHD
================================================================================

Usage: sdk <command> [candidate] [version]
       sdk offline <enable|disable>

   commands:
       install   or i    <candidate> [version] [local-path]
       uninstall or rm   <candidate> <version>
       list      or ls   [candidate]
       use       or u    <candidate> <version>
       default   or d    <candidate> [version]
       home      or h    <candidate> <version>
       env       or e    [init]
       current   or c    [candidate]
       upgrade   or ug   [candidate]
       version   or v
       broadcast or b
       help
       offline           [enable|disable]
       selfupdate        [force]
       update
       flush             <broadcast|archives|temp>

   candidate  :  the SDK to install: groovy, scala, grails, gradle, kotlin, etc.
                 use list command for comprehensive list of candidates
                 eg: $ sdk list
   version    :  where optional, defaults to latest stable if not provided
                 eg: $ sdk install groovy
   local-path :  optional path to an existing local installation
                 eg: $ sdk install groovy 2.4.13-local /opt/groovy-2.4.13

**Comment by marc0der** [comment]
@xadimousalih I really wouldn't recommend sourcing your bash profile from your zsh profile. Rather just add the following snippet to the end of `.zshrc`:

```
# SDKMAN!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
```

**Comment by itsraghz** [comment]
> @xadimousalih I really wouldn't recommend sourcing your bash profile from your zsh profile. Rather just add the following snippet to the end of `.zshrc`:
> 
> ```
> # SDKMAN!
> export SDKMAN_DIR="$HOME/.sdkman"
> [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
> ```
> 
> Make sure this is at the very end.

+1 for making it in three separate lines, as I had it in 2 lines - first comment and the rest of the lines together which gave me an error as follows.

`
➜  h2 source ~/.zshrc
/Users/raghavan.muthu/.zshrc:106: bad pattern: [[
`

**Comment by raveendrabikkina-metcash** [comment]
just do this and that should resolve your issue
source ~/.bash_profile;
