### ISSUE TITLE
URL created by install script does't work

### ISSUE THREAD

**Issue by windyboy** [sdkman/sdkman-cli#618]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [*] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

Try to install by : 
curl -s https://get.sdkman.io | bash

 The url "https://bintray.com/artifact/download/sdkman/generic/sdkman-cli-5.6.0+287.zip" generated by script seems not work.

**Comment by marc0der** [comment]
No conversation was held on the gitter channel as stipulated, so closing. There is also no problem with the URL that I can see.
