### ISSUE TITLE
SDKMAN truncates the version number on list output

### ISSUE THREAD

**Issue by McPringle** [sdkman/sdkman-cli#619]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [X] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

I can reproduce this issue mentioned by @johnnybaloney in the [Gitter User Issues Room](https://gitter.im/sdkman/user-issues) chat with the actual version of SDKMAN. As you can see in the directory listing, there is a version `kop-jdk1.8.0_151`. In the `sdk list java` outout the version number is truncated, the last character is missing: `kop-jdk1.8.0_151` -> `kop-jdk1.8.0_15`

```
$ sdk version
SDKMAN 5.5.15+284

$ ls -l ~/.sdkman/candidates/java/
total 0
drwxr-xr-x  18 mcpringle  staff  576 18 Okt 17:39 8u152-zulu
drwxr-xr-x  14 mcpringle  staff  448  4 Nov 16:12 9.0.1-zulu
lrwxr-xr-x   1 mcpringle  staff   51 12 Dez 18:56 current -> /Users/mcpringle/.sdkman/candidates/java/8u152-zulu
drwxr-xr-x   2 mcpringle  staff   64 31 Dez 11:29 kop-jdk1.8.0_151

$ sdk list java
================================================================================
Available Java Versions
================================================================================
   + kop-jdk1.8.0_15                                                               
   * 9.0.1-zulu                                                                    
     9.0.1-oracle                                                                  
     9.0.0-zulu                                                                    
 > * 8u152-zulu                                                                    
     8u151-oracle                                                                  
     8u144-zulu                                                                    
     8u131-zulu                                                                    
     7u141-zulu                                                                    
     6u65-apple
================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
```

**Comment by marc0der** [comment]
@McPringle @johnnybaloney The reason why you are seeing this long version name truncated is that the table actually holds 4 columns of versions, each column with a max width of 15 chars. An example of this would be the listing for Groovy:
```
================================================================================
Available Groovy Versions
================================================================================
     3.0.0-alpha-1      * 2.4.12               2.3.1                2.0.8          
     2.6.0-alpha-2        2.4.11               2.3.0                2.0.7          
     2.6.0-alpha-1        2.4.10               2.2.2                2.0.6          
     2.5.0-beta-2         2.4.1                2.2.1                2.0.5          
     2.5.0-beta-1         2.4.0                2.2.0                2.0.4          
     2.5.0-alpha-1        2.3.9                2.1.9                2.0.3          
     2.4.9                2.3.8                2.1.8                2.0.2          
     2.4.8                2.3.7                2.1.7                2.0.1          
     2.4.7                2.3.6                2.1.6                2.0.0          
     2.4.6                2.3.5                2.1.5                1.8.9          
     2.4.5                2.3.4                2.1.4                1.8.8          
     2.4.4                2.3.3                2.1.3                1.8.7          
     2.4.3                2.3.2                2.1.2                1.8.6          
     2.4.2                2.3.11               2.1.1                1.8.5          
 > * 2.4.13               2.3.10               2.1.0                1.8.4          

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
```
The publish API actually does not allow publishing of versions longer than 15 characters, so perhaps we should enforce this restrictions too when adding local versions to sdkman. Either way, I don't think that this is a bug, but rather enforcement of a constraint. WDYT?

**Comment by McPringle** [comment]
At the [Hackergarten](http://hackergarten.net) in Lucerne today, we discussed this issue. Our idea is to modify the logic which generates the column output. We want to check the width of all entries of each column and make each column as wide or narrow as needed with a small gap between. The number of columns could be dynamic, too (based on the with of the columns). What do you think about this idea, @marc0der?

We had some problems, after we cloned this repo a lot of the tests failed. We'll start a discussion about it in the [Gitter chat](https://gitter.im/sdkman/cli-dev) and try to continue our investigation (and probalby improve the README file).

**Comment by johnnybaloney** [comment]
Why the limit of 15 characters?

**Comment by McPringle** [comment]
@johnnybaloney Because the columns have a with of 20 characters with a gap of 5 characters. That's why we have the idea of a dynamic column width and dynamic column count.

**Comment by johnnybaloney** [comment]
So the view holds the model hostage. Dynamic columns sounds a better approach indeed, they way `ls -C` lists files.

**Comment by marc0der** [comment]
@McPringle @johnnybaloney I'll be honest to say that versions larger than 15 characters have never been encountered before until now. The only time this could happen is if an unnaturally wide version identifier is entered for a local version (read extreme edge case). I suggest rather than introducing dynamic column widths (which will look very untidy to my OCD mind haha), can we add a constraint to the command that adds the local version instead?

Another point: the list view is generated serverside by the *sdkman-candidates-legacy* service. In fact, it is the last endpoint that needs to be ported to the new *sdkman-candidates* service. The code will be re-written from scratch in Scala, so changing this code now would probably be a waste.

**Comment by beckje01** [comment]
I ran into this while adding custom builds of jdk 11, I think the solution to add a constraint on the add command is best as the list view truncates but the version is still actually there.

**Comment by marc0der** [comment]
I am currently rewriting the new (long awaited) list view. So far I've implemented it with 4 columns again, but can easily change it to have 3 columns. This will yield 5 characters for status and 21 for the version. Does it sound better?

Anyway @beckje01, I think putting a validation in place is a great idea.

**Comment by beckje01** [comment]
I'm actually fine with any length as long as we have the validation.

**Comment by marc0der** [comment]
Cool, I'll keep it at 14 chars across 4 columns then.
