### ISSUE TITLE
on 80-chars wide terminal looks terribly 

### ISSUE THREAD

**Issue by le93us** [sdkman/sdkman-cli#620]
demo
https://asciinema.org/a/bR4fagPUhaiALQ1YvqcIOjUIq

IMHO, it's better do not use asci-style decorating and output in, for example, `apt` style.

**Comment by marc0der** [comment]
Please adhere to the [contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md) before opening a new issue.
