### ISSUE TITLE
gvm collides with sdk

### ISSUE THREAD

**Issue by fedepia** [sdkman/sdkman-cli#621]
I have installed SDK and used it to install grails in Mac High Sierra, however after rebooting I noticed that both sdk and grails were not found in the path anymore when issuing both commands in the terminal.

I followed the instruction to install sdk again and seems that everything is ok, however sdk is not in the path. The only way to get sdk in the path is by executing manually:
```source "$HOME/.sdkman/bin/sdkman-init.sh"```

After checking at my `~/.bashrc` file I found:

```
#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/Users/federicop/.gvm/bin/gvm-init.sh" ]] && source "/Users/federicop/.gvm/bin/gvm-init.sh"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/federicop/.sdkman"
[[ -s "/Users/federicop/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/federicop/.sdkman/bin/sdkman-init.sh"
```

Therefore I checked if gvm is working and it is, but not the case with sdk. It looks like sdk has problems if gvm is also installed. Any idea to fix this?

**Comment by marc0der** [comment]
Not sure why you have both SDKMAN _and_ GVM installed. GVM is has been discontinued for several years and SDKMAN supersedes it.

I suggest removing all traces of GVM from your machine. Also, these days SDKMAN will add the init snippet to the login profile (`.bash_profile`) not to the interactive profile (`.bashrc`).

In future, please follow our contributor guidelines before opening issues here on Github.
