### ISSUE TITLE
sdkman-init.sh optimization and cleanup

### ISSUE THREAD

**Issue by jjlin** [sdkman/sdkman-cli#624]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [x] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

`sdkman-init.sh` has some inefficiencies and unnecessary hacks that should be fairly easy to correct. It's relatively worthwhile to optimize this file because it's run every time a new interactive shell is spawned.

**Comment by marc0der** [comment]
Thanks for the improvements!
