### ISSUE TITLE
running grails just clear/resets the terminal and does nothing MacOS

### ISSUE THREAD

**Issue by ppazos** [sdkman/sdkman-cli#626]
Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [x] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

running grails just clears/resets the terminal and does nothing MacOS after installing grails 2.5.6, was working OK with grails 3.2.9, any ideas?

this issue recommends to set JAVA_HOME env, I did set it but didn't work, Java is NOT installed from SDKMAN!

sdkman/sdkman-cli#428

going back to grails 3.2.9, grails works OK

**Comment by marc0der** [comment]
This sounds like an issue with Grails, not SDKMAN. In particular, we have no control over `JAVA_HOME` if we're not managing it. The rest is up Grails itself to resolve the environment variables.

FWIW, I tried installing Grails 2.5.6 on my local machine alongside Java (also installed by SDKMAN) and all works fine.

If the problem persists I would suggest following this up with the Grails team.

**Comment by ppazos** [comment]
@marc0der I have configured the JAVA_HOME env and it doesn't seem to affect the issue. Running Grails 2.5.6 not installed from SDKMAN! seems to work OK. Not sure what the issue is with the version installed by SDKMAN!.

**Comment by ppazos** [comment]
@marc0der just installed SDKMAN on another machine, JDK8 and Grails 2.5.6 and got the same result, the issue might come from SDKMAN  not setting env vars correctly for Grails. 1. SDKMAN is not setting JAVA_HOME, 2. executing Grails installed from SDKMAN just cleans the console, nothing gets executed.

**Comment by marc0der** [comment]
@ppazos another thing to check: ensure that you aren't working in a login shell.

**Comment by CarlosPinedaT** [comment]
@ppazos how has the problem solved ? ... the same thing happens to me !!!

**Comment by ppazos** [comment]
@marc0der @CarlosPinedaT today I setup a new environment, installed Grails 2.5.6 and got the same issue: the terminal just cleans up without any feedback, this is a new env, did not configure anything, just installed sdkman and grails using sdkman, then just grails run-app and I get nothing. This is linuix mint 19.
