### ISSUE TITLE
Download script archive fails...

### ISSUE THREAD

**Issue by oniseijin** [sdkman/sdkman-cli#627]
Please explain the Issue / Feature Request here:

Running 
` curl -s "https://get.sdkman.io" | bash`

Results in 
<pre>
Installing SDKMAN scripts...
Create distribution directories...
Getting available candidates...
Prime the config file...
Download script archive...

curl: (56) Received HTTP code 403 from proxy after CONNECT
Extract script archive...
[/home/tkctsejd/.sdkman/tmp/sdkman-5.6.1+290.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/tkctsejd/.sdkman/tmp/sdkman-5.6.1+290.zip or
        /home/tkctsejd/.sdkman/tmp/sdkman-5.6.1+290.zip.zip, and cannot find /home/tkctsejd/.sdkman/tmp/sdkman-5.6.1+290.zip.ZIP, period.
</pre>

**Comment by marc0der** [comment]
Please follow the contributor guidelines before opening a github issue. Also, cannot replicate this issue.
