### ISSUE TITLE
Bug: Flushing candidates remove vital directories

### ISSUE THREAD

**Issue by rbatllet** [sdkman/sdkman-cli#628]
The way to reproduce it is:

1. Open a terminal and install the last version
```
curl -s "https://get.sdkman.io" | bash
exit
```

2. Open a terminal and type:
```
sdk install grails
exit
```

3. Then, open a terminal and type:
```
sdk flush candidates
exit
```

4. And finally, when I open a terminal an error message is showed:
```
-bash: /Users/user/.sdkman/var/candidates: No such file or directory
```

**Comment by rbatllet** [comment]
The same bug was solved a couple of years ago. 
See: https://github.com/sdkman/sdkman-cli/issues/425

**Comment by marc0der** [comment]
We recently had to rework that code so this must have slipped through. A quick fix in the interim would be to run the following snippet in a new terminal:

    $ curl -s https://api.sdkman.io/2/candidates/all > ~/.sdkman/var/candidates

**Comment by marc0der** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove candidate flush feature](https://trello.com/c/4NNqPny9/18-remove-candidate-flush-feature)
