### ISSUE TITLE
Support binary builds of Adoptopenjdk

### ISSUE THREAD

**Issue by MaSven** [sdkman/sdkman-cli#629]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [x] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

Support the binary builds of [Adoptopenjdk](https://adoptopenjdk.net/).

Adoptopendjk is a new website that hosts the nightly and stable builds of openjdk and openj9. Also added with features for upcoming releases. You can read more about it here [about Adoptopenjdk](https://adoptopenjdk.net/about.html)

**Comment by MaSven** [comment]
I would try to make an PR for this.

**Comment by marc0der** [comment]
Excellent, that would be greatly appreciated. Since this is a new category of jdk, and we already have `*-zulu` and `*-oracle`, I suggest we name all of these `*-openjdk`. wdyt?

Also the platforms we need to support are MacOSX, Windows 64 and Linux 64.

**Comment by MaSven** [comment]
Yes i think also *-openjdk would be a good option.
They support the following system.
* Windows x64
* Linux x64
* MacOSX x64
* Linux s390x
* Linux ppc64le
* Linux aarch64
* AIX ppc64

So this should be no problem.

**Comment by MaSven** [comment]
this can be used to retrieve the binarys 
https://api.adoptopenjdk.net/README

**Comment by marc0der** [comment]
We don't really have facility to call APIs inline right now. We store URLs of where the binaries are located in our database so unfortunately the only way for you to add adoptopenjdk is by doing a PR on sdkman-db-migrations like we discussed before.

**Comment by MaSven** [comment]
Maybe it is the time to write the cli so that it can invoke api itself? I could do a pr for this but i dont want to write something like this in bash. Maybe we could use java for this. Since java9 it could also be deployed with java itself so the user does not need to download it before. Also aot compilation could improve the startup. Or in java 10 openjdk supports AppCDS for improved startup [AppCDS](https://blog.codefx.org/java/application-class-data-sharing/)

**Comment by marc0der** [comment]
Thanks for going to the trouble of preparing this PR. As I've said before, your help is much appreciated.

Just a quick bit of background regarding SDKMAN, as well as addressing your previous comment:
I'd prefer not to call any remote APIs inline. Also, sdkman was written in bash for a purpose: the idea is that it can run anywhere with almost no dependencies (besides curl, unzip and zip). Java is a very heavyweight dependency and IMO not the right tool for the job.

Further to that, remember that the bash CLI is only the tip of the iceberg. All the real work is done by APIs on the backend. SDKMAN is actually backed by 5 microservices for all client API calls. These services are also responsible for serving up small segments of dynamic bash that are executed inline on the client. In addition to these services, we have 4 microservices that serve all vendor API calls. Most of the backend API is written in Scala.

One last thing to mention is that SDKMAN follows a _push_ model, as opposed to a _pull_ crawler based model. Crawlers are brittle, error prone and a nightmare to maintain. The following two methods are provided for performing new sdk version releases:

a) for vendors, we provide a REST API that can be called to release new versions. Azul followed this method for Java until recently, but have subsequently stopped releasing their own versions.
b) community members can now raise PRs on the db migrations project to supplement any versions that they might require. This is the route that I'm encouraging in this instance.

Lastly, I suggest that we use the fully resolved URLs for the versions that we want published on SDKMAN. We also want to have real version numbers, not some latest/snapshot tag as this would be very unstable going forward. I'll leave some more pointers on the PR itself.

Hope this all makes sense now!

**Comment by MaSven** [comment]
Yes thank you. Sorry for bothering. Also i will close this issue since the pull request https://github.com/sdkman/sdkman-db-migrations/pull/3 is merged. I will keep an eye on the project for further releases and make new pull requests.

**Comment by marc0der** [comment]
Looking forward to those PRs. And thanks again for contributing!

**Comment by QIvan** [comment]
sorry guys. How can I find the AdoptOpenJdk in SDKMAN! ? 
now i see 
```
$ sdk ls java
================================================================================
Available Java Versions
================================================================================
     12.ea.12-open
     11.0.0-open
     10.0.2-zulu
     10.0.2-open
     10.0.2-oracle
     9.0.7-zulu
     9.0.4-open
     8.0.181-zulu
     8.0.181-oracle
     7.0.191-zulu
     6.0.113-zulu
     1.0.0-rc7-graal
```

i use 
```
$ sdk v

SDKMAN 5.7.3+337
```

**Comment by koppor** [comment]
For the googlers landing here:

```terminal
$ sdk ls java
================================================================================
Available Java Versions
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
 AdoptOpenJDK  |     | 15.0.1.j9    | adpt    |            | 15.0.1.j9-adpt
               |     | 15.0.1.hs    | adpt    |            | 15.0.1.hs-adpt
               |     | 14.0.2.j9    | adpt    |            | 14.0.2.j9-adpt
               |     | 14.0.2.hs    | adpt    |            | 14.0.2.hs-adpt
               |     | 13.0.2.j9    | adpt    |            | 13.0.2.j9-adpt
               |     | 13.0.2.hs    | adpt    |            | 13.0.2.hs-adpt
               |     | 12.0.2.j9    | adpt    |            | 12.0.2.j9-adpt
               |     | 12.0.2.hs    | adpt    |            | 12.0.2.hs-adpt
               |     | 11.0.9.open  | adpt    |            | 11.0.9.open-adpt
               |     | 11.0.9.j9    | adpt    |            | 11.0.9.j9-adpt
               |     | 11.0.9.hs    | adpt    |            | 11.0.9.hs-adpt
               |     | 8.0.275.open | adpt    |            | 8.0.275.open-adpt
               |     | 8.0.275.j9   | adpt    |            | 8.0.275.j9-adpt
               |     | 8.0.275.hs   | adpt    |            | 8.0.275.hs-adpt
...
$ sdk v

SDKMAN 5.9.1+575
```

`j9` denotes [Eclipse OpenJ9](https://www.eclipse.org/openj9/). Thus OpenJ9 is fully supported.
