### ISSUE TITLE
when execute upgrade, it seems judged java 9 version little than java 8 by mistake

### ISSUE THREAD

**Issue by yetangye** [sdkman/sdkman-cli#630]
Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [X] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

`bash-3.2$ sdk upgrade

Upgrade:
java (9.0.4-oracle < 8u152-zulu)
springboot (1.5.8.RELEASE, 1.5.9.RELEASE < 2.0.0.RELEASE)

Upgrade candidate(s) and set latest version(s) as default? (Y/n):`

**Comment by marc0der** [comment]
Please follow the contributor guidelines before opening a new issue. We can reopen this once we've discussed on Gitter.
