### ISSUE TITLE
Wrong internal package structure for openjdk 10.0.0

### ISSUE THREAD

**Issue by viartemev** [sdkman/sdkman-cli#633]
I set up Java 10 as default java version and this config doesn't work.
```  
sdk list java | grep 10
     10u23-openjdk
 > * 10.0.0-openjdk
```

```
java --version
Unable to locate an executable at "/Users/vartemyev/.sdkman/candidates/java/current/bin/java" (-1)
```

OS: Mac OS Sierra 10.13.3
Java: 10.0.0-openjdk

**Comment by wreulicke** [comment]
I also encoutered this issue.

**Comment by marc0der** [comment]
Okay, just checked the internal structure of the package and it has a non-standard package structure. Thanks Oracle. Will have to deal with this in the backend. Pulling that version for mac temporarily...

**Comment by marc0der** [comment]
OpenJDK 9.0.4 is also affected so pulled both.

**Comment by viartemev** [comment]
@marc0der thanks for fixing

**Comment by marc0der** [comment]
Pleasure 😀
