### ISSUE TITLE
Update sdkman version not works on macOS High Sierra 10.13.4

### ISSUE THREAD

**Issue by boyfox** [sdkman/sdkman-cli#635]
I always will update sdkman when will publishing new release version. Updating process always successfully but version is not changed.

OS: macOS High Sierra 10.13.4

Look to screenshot:

![screenshot at apr 17 10-45-05_sdkman](https://user-images.githubusercontent.com/3168694/38850898-e1301bc0-422c-11e8-8c8b-ba1ba3735b38.png)

I tried to completely close all the terminal instances and start the new terminal, but still not changed. Upgrade not works.

**Comment by marc0der** [comment]
Please follow our contributor guidelines as stated before prior to opening an issue.
