### ISSUE TITLE
How to install Java 6 for legacy projects?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [sdkman/sdkman-cli#636]
How can we install Java 6 using SDKMAN!?

Because Java 6 is kind of deprecated I think it was dropped, but we will still need this to maintain legacy projects.

I've found a solution using brew cask, but because I like to use SDKMAN! I was wondering if we can still install Java 6. Maybe using the archive files or something like that.

**Comment by marc0der** [comment]
Yes, you can install JDK 6 as a local version for your platform. Instructions for this are on the usage page of our site. Also, depending on your platform, you can still install JDK 6.0 Zulu, for instance if you are on linux or cygwin.

Another thing to try: why not use JDK 8? It is fully backward compatible with JDK 6 source code.

Closing this issue for now but feel free to drop in on our Gitter chat if you require more assistance. I'd be glad to help.

**Comment by autonomousapps** [comment]
I looked at the [usage page](https://sdkman.io/usage), but I don't see anything about installing JDK 6 or any older version of an SDK.
