### ISSUE TITLE
The site, gvmtool.net, is hacked

### ISSUE THREAD

**Issue by jlbrewster** [sdkman/sdkman-cli#641]
Trying to visit the site, http://gvmtool.net getting redirected to malicious sites..

**Comment by marc0der** [comment]
We are no longer called gvm, the domain has long since been orphaned. 

Please follow the contributor guidelines (the stuff you deleted) prior to opening a new issue.

**Comment by jlbrewster** [comment]
Whoa, whoa...why are you accusing me of deleting stuff and "not following
guidelines"?  I was trying to report an outage, that's all (if you had
guidelines for that, I would have followed them). If you want to teach me
(a person trying to help) a lesson, don't jump to conclusions, and try not
being condescending.  (The rest of the world may be stupider than you, but
still deserves respect).

If the tool was 'long since orphaned'...why doesn't it state that
anywhere?? (Something like "SDKman, formerly GDK" anywhere would have saved
me so much time!)(There are several third party sites that still have your
old link; you should ask them to update it).
