### ISSUE TITLE
Add gradle-completion (bash / zsh) in sdk man

### ISSUE THREAD

**Issue by alexandrenavarro** [sdkman/sdkman-cli#646]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [X ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

Add gradle-completion  (bash / zsh, https://github.com/gradle/gradle-completion) in sdk man notably if you install gradle

**Comment by marc0der** [comment]
We only provide what's in the official gradle bin distribution. If you want to see this included please take it up with the Gradle team.
