### ISSUE TITLE
GraalVM downloads a bad archive

### ISSUE THREAD

**Issue by dsyer** [sdkman/sdkman-cli#651]
It's probably a bug in the distro (sdkman only downloads the archive), but the symptom is that graal is unusable from sdkman:

```
$ sdk use java 1.0.0-rc1-graal
$ native-image --help
Error: Unable to use jar-files from directory /home/dsyer/.sdkman/candidates/java/1.0.0-rc1-graal/lib/svm/builder
Caused by: java.nio.file.NoSuchFileException: /home/dsyer/.sdkman/candidates/java/1.0.0-rc1-graal/lib/svm/builder
```

The problem is that the .zip archive downloaded by sdkman is not valid. The tarball (.tar.gz) distributed by the Graal project works fine because it contains symlinks and some of the commands rely on that. Probably still broken on Windows?

The downloads page for graal doesn't have a zip archive for 1.0.0-rc1 (https://github.com/oracle/graal/releases), so wherever sdkman is getting it from is the source of the bug.

**Comment by marc0der** [comment]
We are using the only archive available on the download page which is the tarball.

@dsyer on gitter you mentioned something about comparing the tarball to a zip. Where did you get hold of this zip archive?

**Comment by marc0der** [comment]
Just making @shelajev aware of this too. Should we raise an issue on Graal itself about this?

**Comment by dsyer** [comment]
If sdkman downloads the tarball then I think it must get screwed up somewhere in the toolchain somewhere. When I do `sdk install java 1.0.0-rc1-graal` I get a zip file at `~/.sdkman/archives` that has all the problems that the installation does (no symlinks) - that's the one I compared to the tarball.

**Comment by marc0der** [comment]
That makes total sense now. We repackage tarballs into zips for caching purposes; that's most certainly where things go wrong.

**Comment by marc0der** [comment]
I've just released a [fix on sdkman-hooks](https://github.com/sdkman/sdkman-hooks/commit/243bdbe507765bccdb79dbe972ed756c74f5a644) which addresses this issue. @dsyer could I please ask you to test if this is working for you now? You would need to do the following:

    $ sdk flush archives
    $ sdk use java {some-other-installed-version}
    $ sdk rm java 1.0.0-rc1-graal
    $ sdk install java 1.0.0-rc1-graal

This should re-download the binary, repackage it (using the hooks) and finally install it in place.
I've tried using the native-packager at it now seems to work for me.

**Comment by marc0der** [comment]
Not heard anything back and have tested this successfully so closing the issue.
