### ISSUE TITLE
Setting noclobber prevents writing status files in var/

### ISSUE THREAD

**Issue by kwbr** [sdkman/sdkman-cli#669]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [x] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

To prevent accidential overwriting of files in my shell (bash) I use "set -o noclobber". Because sdkman is sourced this setting causes an error everytime sdkman writes by redirecting the output to a file. I replaced all places by using tee: `echo "$broadcast_live_id" | tee "$broadcast_id_file" > /dev/null`
Currently those three files are affected:
```
var/version
var/broadcast_id
var/broadcast
```

**Comment by marc0der** [comment]
Resolved by #668
