### ISSUE TITLE
How we can update all installed packages at once?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [sdkman/sdkman-cli#672]
I'm searching for a way to update all installed packages at once, using just one command line.

How can we do that?

**Comment by marc0der** [comment]
Usage questions can be asked on [Gitter](https://gitter.im/sdkman/user-issues), and full instructions how to use the tool on our [website](https://sdkman.io/usage).

In future, please observe our [Contributor Guidelines](https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md) before opening an issue here.
