### ISSUE TITLE
Stop! The archive was corrupt and has been removed! Please try installing again.

### ISSUE THREAD

**Issue by adarsh1195** [sdkman/sdkman-cli#674]
Hi. Iam trying to install groovy using sdkman on CentOS. I use the following command.

sdk install groovy. 

I get the following response. 
Downloading: groovy 2.4.15

In progress...

######################################################################## 100.0%
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/master/.sdkman/archives/groovy-2.4.15.zip or
        /home/master/.sdkman/archives/groovy-2.4.15.zip.zip, and cannot find /home/master/.sdkman/archives/groovy-2.4.15.zip.ZIP, period.

Stop! The archive was corrupt and has been removed! Please try installing again.

I tried it multiple times but still getting the same. Need a solution.

**Comment by marc0der** [comment]
Please follow the contributor guidelines prior to opening an issue.
