### ISSUE TITLE
sdk install javafx

### ISSUE THREAD

**Issue by axiopisty** [sdkman/sdkman-cli#675]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ x] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

As of JDK 11, JavaFX is no longer packaged/shipped with the JDK. I would like to request `sdk install javafx` within sdkman. See also: https://gluonhq.com/products/javafx/

**Comment by marc0der** [comment]
Closing this as it isn't actually a new feature. Comments can be found in the Gitter chat.

**Comment by ehmkah** [comment]
For me it helped to use a version of java which has a -fx in it. For example: 11.0.1-zulufx :-) or the corresponding command
sdk install java 11.0.1-zulufx.

**Comment by philgebhardt** [comment]
To continue from @ehmkah post above, the JavaFX suffix appears to have changed to `fx-zulu`, e.g.

```shell
sdk install java 17.0.6.fx-zulu
```
