### ISSUE TITLE
get.sdkman.io ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by Blackspaceta** [sdkman/sdkman-cli#678]
Hello, I can not install sdkman.
1) ping: unknown host https://get.sdkman.io.
2) In the browser at https://get.sdkman.io I get the answer ERR_CONNECTION_TIMED_OUT.
3) Test results for Russian providers http://ping-admin.ru/free_test/result/15408550375pehnv196cy10cuhgw762b.html
4) I asked my provider - he did not block https://get.sdkman.io
5) I live in Russia in the Kaliningrad region, I use two different providers.

**Comment by marc0der** [comment]
The blocking is not done by ISPs but by the authorities. I can guarantee you that the our servers are not down.

Please follow our guidelines before an issue here.
