### ISSUE TITLE
Stop! The archive was corrupt and has been removed! Please try installing again.

### ISSUE THREAD

**Issue by berinle** [sdkman/sdkman-cli#68]
I keep getting this error, no matter what module I try to install. I am running on a windows 7 machine (64-bit).

Downloading: groovy 2.0.5

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.0M  100 27.0M    0     0  4733k      0  0:00:05  0:00:05 --:--:-- 5190k

Stop! The archive was corrupt and has been removed! Please try installing again.

It does seems it finished downloading, but why it is flagged as corrupt is beyond me.

Please help!

**Comment by justnull** [comment]
Thank you

**Comment by justnull** [comment]
Thank you!

**Comment by maephisto666** [comment]
I can confirm the comment written by @gordolio .

I had installed zip package, but I also found out I had another unzip in my path. Fixing that did the trick.
