### ISSUE TITLE
SDKMAN sets the wrong JAVA_HOME for GraalVM on MAC

### ISSUE THREAD

**Issue by Vad1mo** [sdkman/sdkman-cli#680]
When installing graalvm on mac `sdk i java 1.0.0-rc-10-grl` then the  `JAVA_HOME` env variable which is set by sdkman points to a wrong directory.

**Is:**
```sh
>echo $JAVA_HOME
/Users/me/.sdkman/candidates/java/current
>ls -la
current -> /Users/me/.sdkman/candidates/java/1.0.0-rc-10-grl
```

**Should be for GraalVM**:

```sh
>echo $JAVA_HOME
/Users/me/.sdkman/candidates/java/current/Contents/Home/
>ls -la
current -> /Users/me/.sdkman/candidates/java/1.0.0-rc-10-grl/Contents/Home
```

**Comment by marc0der** [comment]
Please follow the contributor guidelines as clearly stipulated before opening an issue.

**Comment by Vad1mo** [comment]
It seems to be more important to follow processes than solving problems. I tried to kickoff a discussion on https://gitter.im/sdkman/user-issues but nobody cares. Apparently it isn't important that there is bug.

**Comment by McPringle** [comment]
@Vad1mo Gitter is not a real time communication system. On Gitter, you got an answer on the same day in the afternoon. In my opinion this is very good, because this is an open source project where all contributors spend their free time on.
