### ISSUE TITLE
SDKMAN warns about update while there is none

### ISSUE THREAD

**Issue by mhogerheijde** [sdkman/sdkman-cli#681]
Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [x] this is a new Bug Report or Issue, a conversation was started on [Twitter](https://twitter.com/mhogerheijde/status/1072868313846312964).

Please explain the Issue / Feature Request here:

SDKMAN warned me that there was an update, while there actually wasn't:

```
ATTENTION: A new version of SDKMAN is available...

The current version is 5.7.3+337, but you have 5.7.3+337

Would you like to upgrade now? (Y/n): Y
No update available at this time.
```

I don't know how to reproduce the issue, using the `sdk update` command immediately tells me there are no updates.

![screenshot from 2018-12-12 15-52-08](https://user-images.githubusercontent.com/1466140/49922600-7cb98680-feb1-11e8-83bb-3cd0b0daefeb.png)

See also discussion on twitter: https://twitter.com/mhogerheijde/status/1072868313846312964

Details about my system:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
$ zsh --version
zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
$ xfce4-terminal --version
xfce4-terminal 0.8.7.4 (Xfce 4.12)
$ tmux -V
tmux 2.7
```

**Comment by marc0der** [comment]
Hi @mhogerheijde 

I see two things that might be the cause of what you're seeing here. Firstly, please check to see that your xfce terminal isn't set to use a login shell. This often causes problems with the state update of the shell. The other thing that might be causing issues is the use of tmux, which could be causing some state bleeding between shells.

And of course, there is the possibility that there might be an interaction between both of these, which might explain the very odd message we are seeing. Shell environment are very fragile, so writing tooling that works across all combinations and permutations is very tricky indeed.

**Comment by mhogerheijde** [comment]
```
$ echo $0
-zsh
```

I think that means that I do use a login-shell? Although i have this option disabled

![screenshot from 2018-12-14 12-07-38](https://user-images.githubusercontent.com/1466140/50000148-f24c5200-ff98-11e8-8b0f-e945b8531e39.png)

Should `sdk update` trigger the same process? I.e. can I try to reproduce this by doing some cross-terminal interaction with SKDMAN?

**Comment by marc0der** [comment]
Very strange indeed. When I issue that command (I'm also on Linux with ZSH) I get:

```

**Comment by mhogerheijde** [comment]
It seems really hard to reproduce. I've had `/bin/zsh` as command for a while at my home machine and it didn't pop up. But at my work-machine, I used `tmux` all the time and it didn't pop up either.

I started using `tmux` at home again and just now got a similar message, albeit a bit different:
```
$ sdk ls gradle
WARNING: SDKMAN is out-of-date and requires an update. Please run:

  $ sdk update
[SNIP]

$ sdk update
No new candidates found at this time.
```

**Comment by marc0der** [comment]
@mhogerheijde I think what you are seeing is expected behaviour (although perhaps the language we used here is a bit confusing). Sdkman requires you to run an `update` periodically to pull down any potentially new candidates. If no new candidates were added since your last update, this message will be shown. You can read the [specification](https://github.com/sdkman/sdkman-cli/blob/master/src/test/cucumber/update.feature) for this feature using some real examples.

**Comment by gzsombor** [comment]
I have similar problem, it somehow fails to detect the current version, and always tries to update:

```
$  sdk update
==== BROADCAST =================================================================
* 29/01/19: Micronaut 1.0.4 released on SDKMAN! #micronautfw
* 28/01/19: Gradle 5.2-rc-1 released on SDKMAN! #gradle
* 27/01/19: Jbake 2.6.4 released on SDKMAN! #JBake
================================================================================
No new candidates found at this time.


ATTENTION: A new version of SDKMAN is available...

The current version is , but you have 5.7.3+337.

```

**Comment by marc0der** [comment]
@gzsombor can you confirm that you are not running a login shell but an interactive shell?

**Comment by marc0der** [comment]
Sdkman works with bash and zsh but not fish. You can read about login vs interactive shells here:
https://unix.stackexchange.com/questions/50665/what-is-the-difference-between-interactive-shells-login-shells-non-login-shell

**Comment by freiit** [comment]
If I run this in a byobu/screen session (started from a login terminal) I get the same issue. If I run without byobu/screen, it works fine.

**Comment by matthewadams** [comment]
Same here just now.  Latest macOS, but upgraded with Bash 5.  Here's my session (prompt is result of bash-it, https://github.com/Bash-it/bash-it):
```
 matthewadams  ⎇ add-test-project  ~/dev/yaktor/yaktor-dsl-xtext   sdk help
WARNING: SDKMAN is out-of-date and requires an update. Please run:

  $ sdk update


Usage: sdk <command> [candidate] [version]
       sdk offline <enable|disable>

   commands:
       install   or i    <candidate> [version]
       uninstall or rm   <candidate> <version>
       list      or ls   [candidate]
       use       or u    <candidate> [version]
       default   or d    <candidate> [version]
       current   or c    [candidate]
       upgrade   or ug   [candidate]
       version   or v
       broadcast or b
       help      or h
       offline           [enable|disable]
       selfupdate        [force]
       update
       flush             <broadcast|archives|temp>

   candidate  :  the SDK to install: groovy, scala, grails, gradle, kotlin, etc.
                 use list command for comprehensive list of candidates
                 eg: $ sdk list

   version    :  where optional, defaults to latest stable if not provided
                 eg: $ sdk install groovy

 matthewadams  ⎇ add-test-project  ~/dev/yaktor/yaktor-dsl-xtext   sdk update
No new candidates found at this time.
 matthewadams  ⎇ add-test-project  ~/dev/yaktor/yaktor-dsl-xtext   sdk version

SDKMAN 5.7.3+337
 matthewadams  ⎇ add-test-project  ~/dev/yaktor/yaktor-dsl-xtext   echo $0
-bash
 matthewadams  ⎇ add-test-project  ~/dev/yaktor/yaktor-dsl-xtext   env|grep -i bash
SHELL=/usr/local/bin/bash
BASH_IT=/Users/matthewadams/.bash_it
BASH_IT_THEME=powerline-plain
 matthewadams  ⎇ add-test-project  ~/dev/yaktor/yaktor-dsl-xtext   /usr/local/bin/bash --version
GNU bash, version 5.0.9(1)-release (x86_64-apple-darwin18.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by reitzig** [comment]
I'm seeing this in both fish _and_ bash.

Not sure what you are getting at with the login shell business. I for one use sdk only locally in my regular terminal emulator.

> Sdkman requires you to run an update periodically to pull down any potentially new candidates.

I can confirm that running `sdk update` once removes the spurious warning in both shells. Since candidate lists should not have anything to do with the version of sdk, I still see a bug here.

**Comment by reitzig** [comment]
>  This issue is about something completely different than the candidate refresh

Aye. And yet you write:

>  something that everyone needs to do periodically and ensure that you can see any new candidates

I still haven't understood why sdk would complain about an outdated version when all it can know is that it hasn't checked for a while. In which case I for one don't want it to complain at all; it should just check, or leave it to me to frequently run `sdk update`.
(Which, FWIW, I never do: for candidates I use `sdk upgrade`.)

**Comment by marc0der** [comment]
Welcome to chat about this on Slack, but it remains a different issue all together.

**Comment by jest** [comment]
I can confirm that running `sdk update` in *new* shell causes the *unset* value of `$SDKMAN_REMOTE_VERSION` passed to `__sdkman_auto_update`

https://github.com/sdkman/sdkman-cli/blob/fb820f2f8b401d7b1115f694fae01faf103d9e69/src/main/bash/sdkman-main.sh#L128-L131

and versions comparison to fail

https://github.com/sdkman/sdkman-cli/blob/4a5ca28f87eeb36e7f2e9351c883fd9b51401c9f/src/main/bash/sdkman-selfupdate.sh#L44-L53

resulting in message:

```
ATTENTION: A new version of SDKMAN is available...

The current version is , but you have 5.7.4+362.
```

The value of `$SDKMAN_REMOTE_VERSION` is only ever set in function `___sdkman_check_version_cache`:

https://github.com/sdkman/sdkman-cli/blob/9c03510d3cfbeadee2cf17ff16cc613396532b74/src/main/bash/sdkman-cache.sh#L39-L45

However, the function is not called for the specific `update` command:

https://github.com/sdkman/sdkman-cli/blob/fb820f2f8b401d7b1115f694fae01faf103d9e69/src/main/bash/sdkman-main.sh#L53-L57

It is hard to observe, as running any `sdk` command in the shell prior to `update` causes the value of `$SDKMAN_REMOTE_VERSION` to be set for further `update` and the message not to be shown.

@marc0der I'd prepare the PR, but I'm not sure what the correct fix is here... Setting `SDKMAN_REMOTE_VERSION="$SDKMAN_VERSION"` as the `else` part for

https://github.com/sdkman/sdkman-cli/blob/fb820f2f8b401d7b1115f694fae01faf103d9e69/src/main/bash/sdkman-main.sh#L53-L57

would work, but that would be a lie :)

Maybe adding `&& -n "$SDKMAN_REMOTE_VERSION` to the condition?

https://github.com/sdkman/sdkman-cli/blob/fb820f2f8b401d7b1115f694fae01faf103d9e69/src/main/bash/sdkman-main.sh#L128-L131

**Comment by reitzig** [comment]
@jest Can't reproduce with 5.8 :partying_face: 

![image](https://user-images.githubusercontent.com/4246780/82544911-234d9080-9b56-11ea-977e-633aa9bf7f35.png)

**Comment by marc0der** [comment]
@reitzig this is normal and happens once a month if I remember right. It merely refreshes the candidate cache and other metadata.

This is similar to apt-get update or git fetch.

**Comment by felipecrs** [comment]
I also have this issue, I run `sdk selfupdate` every day, and it always "update" to the same version it is (once by day, further calls says that it's up-to-date).

```sh-session
$ sdk selfupdate
ATTENTION: A new version of SDKMAN is available...

The current version is , but you have 5.9.0+555.
```

**Comment by felipecrs** [comment]
Any chance this can get fixed? It's still happening as of today. 

```
ATTENTION: A new version of SDKMAN is available...

The current version is , but you have 5.11.0+644.
```

**Comment by marc0der** [comment]
Hi @felipecrs, this is due to an environment issue and not a bug in sdkman. You need to ensure that you are using an interactive, not a login shell. Login shells hold on to their state, which causes this issue to occur.

**Comment by felipecrs** [comment]
It would be good if we could switch sdkman's mechanism to use something not dependent on this. I'm on WSL2, and I'm did not enable the login shell explicitly here.

**Comment by gzsombor** [comment]
The problem is that sdkman takes the version number from an environmental variable (from SDKMAN_VERSION), which I think is a bit strange decision, instead of getting this value from ~/.sdkman/var/version. And overriding that environment variable is shell specific.

**Comment by markoong** [comment]
I'd just add that @gzsombor has hit the probably cause of some strange "issues" still persisting after having updated sdk to a new version (tested with 5.9.0).
After being invited to "Open a new terminal to start using SDKMAN v...", sdk update won't proceed with another update, but `sdk version` still reports the old version number.

This is probably due to this lines inside /home/user/.sdkman/bin/sdkman-init.sh:

```
# set env vars if not set
if [ -z "$SDKMAN_VERSION" ]; then
        export SDKMAN_VERSION="5.11.0+644"
fi
```

`SDKMAN_VERSION` is not exported in this case.

**Comment by jest** [comment]
The problem that @felipecrs describes is the same that I showed in comment https://github.com/sdkman/sdkman-cli/issues/681#issuecomment-597659521, although the command he describes is different.

It has nothing to do with old version "stuck" in environment variable, but rather with unset `$SDKMAN_REMOTE_VERSION` when the **first** command is issued in new shell.

To try out:

1. `touch -t 197101010000 "$SDKMAN_DIR/var/*` to make sdkman think it wasn't updated for a looong time
2. close the terminal
3. open the terminal
4. `sdk update`

Result (as of now):
```
No new candidates found at this time.


ATTENTION: A new version of SDKMAN is available...

The current version is , but you have 5.11.0+644.

Would you like to upgrade now? (Y/n): 
```

If you issue some other `sdk` command between 3. and 4. (e.g. `sdk ls`), the version check in 4. does not propose to upgrade.

**Comment by felipecrs** [comment]
I pushed a PR to fix this.
