### ISSUE TITLE
install several candidates in one line

### ISSUE THREAD

**Issue by lx-931203** [sdkman/sdkman-cli#686]
Hi.

There is no way to install several things in one line.

But,
this way
```
parallel sdk install ::: maven gradle ant
```

and this
```
declare -a arr=("maven" "gradle" "ant")

for i in "${arr[@]}"
do
  sdk install "${arr[$i]}"
done
```

also don't work.

Why isn't possible easy
```
sdk install maven gradle ant
```

?

**Comment by marc0der** [comment]
Please follow the contributor guidelines before opening an issue.
