### ISSUE TITLE
sdk man execute use command,but not change current link

### ISSUE THREAD

**Issue by simonjhy** [sdkman/sdkman-cli#687]
when I use sdk install two different version java sdk, I use sdk use command to switch version, the path has been successfully changed, but the current link not changed. I checked sdk-use.sh and found there is a line like this "if [[ ! ( -h "${SDKMAN_CANDIDATES_DIR}/${candidate}/current" || -d "${SDKMAN_CANDIDATES_DIR}/${candidate}/current" ) ]];. I think it should not add "!".

**Comment by marc0der** [comment]
SDKMAN behaves exactly as expected, all tests verify that it works as it should:
https://github.com/sdkman/sdkman-cli/blob/master/src/test/cucumber/use_version.feature

In future, please follow the guidelines that you deleted prior to opening an issue.
