### ISSUE TITLE
Can't install 8.0.201-oracle

### ISSUE THREAD

**Issue by Israphel** [sdkman/sdkman-cli#692]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [x] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:
Starting today at aprox 1700 hours UTC, Sdkman fails to get 8.0.201-oracle:

```
Downloading: java 8.0.201-oracle

In progress...

######################################################################## 100.0%
Download has failed, aborting!

Can not install java 8.0.201-oracle at this time...

Instead of the tarbal, we get an html file
```
Instead of the tarball, we get an html file:

```
<title>Error Page 404</title>
<base href="http://download.oracle.com/index.html" />
```

Is it possible that Oracle changed something?

**Comment by marc0der** [comment]
@Israphel simply went to the download page and was greeted by [this spectacle](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html), dated today.

This means we are finally going to pull our last Oracle JDK from SDKMAN :tada:

**Comment by Israphel** [comment]
so... it won't be possible anymore to get oracle jdk 8 from sdkman?

**Comment by marc0der** [comment]
No, this is the end of the road I'm afraid.

Besides, openjdks are the preferred target these days. If you really need Java 8, try using a Zulu JDK. It is more secure than the Oracle JDK as patchsets are kept up to date.

**Comment by Israphel** [comment]
:( ok, we will try Zulu or something. Thanks man!

**Comment by marc0der** [comment]
You'll see that the other OpenJDK variants are actually _exactly_ the same as the Oracle JDK. You won't notice any difference, except that you **don't need to pay for it**! :laughing:

**Comment by joeminicucci** [comment]
> @Israphel simply went to the download page and was greeted by [this spectacle](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html), dated today.
> 
> This means we are finally going to pull our last Oracle JDK from SDKMAN 🎉

I understand your hatred for Oracle but I don't see how these licensing terms lead you to pull out the Oracle SDKs. We actually used SDKMan specifically to switch between Oracle 8 and OpenJDK. Can you explain your thinking?

**Comment by marc0der** [comment]
It's not really hatred, rather an absolute disagreement with their terms and licensing agreement. By distributing their software, we put ourselves at risk of being shut down by these corporate trolls. With so many good open source alternatives, there really is no reason to be using this restrictive proprietary software.
