### ISSUE TITLE
get.sdkman.io is blocked in Russia by IP

### ISSUE THREAD

**Issue by burtsevyg** [sdkman/sdkman-cli#694]
# host get.sdkman.io
    get.sdkman.io has address 159.89.187.78

IP 159.89.187.78 is blocked in Russia
You can check it:

https://blocklist.rkn.gov.ru/

Change or add new IP, please.

**Comment by marc0der** [comment]
Follow the guidelines please. Also, read the FAQ before opening an issue.

**Comment by burtsevyg** [comment]
Thank you! It helps.
