### ISSUE TITLE
Installation is not working curl -s "https://get.sdkman.io" | bash !!!!

### ISSUE THREAD

**Issue by planesweep** [sdkman/sdkman-cli#695]
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [x] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:
curl -s "https://get.sdkman.io" | bash is not working!!!

**Comment by planesweep** [comment]
Looking for a previous installation of SDKMAN...
Looking for unzip...
Looking for zip...
Not found.
======================================================================================================
 Please install zip on your system using your favourite package manager.

 Restart after installing zip.
======================================================================================================

**Comment by marc0der** [comment]
Please follow the guidelines above before opening an issue :point_up:
