### ISSUE TITLE
11.0.3.j9-adpt fails on MacOS

### ISSUE THREAD

**Issue by EugenMayer** [sdkman/sdkman-cli#698]
Installing `11.0.3.j9-adpt` on macos fails with 

```
__sdkman_post_installation_hook:15: no matches found: /Users/em/.sdkman/tmp/out/*/Contents`
```
 .. command used : `sdk install java 11.0.3.j9-adpt` 

Installing `sdk install java 11.0.2-open` works without issues though.

MacOS: High Sierra

**Comment by marc0der** [comment]
Thanks for the heads up. Could I ask you to try the hotspot variant too? Does this give the same error result?

**Comment by EugenMayer** [comment]
It seems like the hotspot variant works without issues:

`sdk install java 11.0.3.hs-adpt`

```
Downloading: java 11.0.3.hs-adpt

In progress...

######################################################################## 100.0%

Repackaging Java 11.0.3.hs-adpt...

Done repackaging...
Cleaning up residual files...

Installing: java 11.0.3.hs-adpt
Done installing!
```

**Comment by EugenMayer** [comment]
Fixed, thank you!
