### ISSUE TITLE
gradle cant be installed on mac

### ISSUE THREAD

**Issue by hajaryasin26** [sdkman/sdkman-cli#700]
i tried to install gradle but it wont work. why?

Downloading: gradle 5.4.1

In progress...

########################                                                  33.9%
curl: (18) transfer closed with 57535346 bytes remaining to read
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/hajar/.sdkman/archives/gradle-5.4.1.zip or
        /Users/hajar/.sdkman/archives/gradle-5.4.1.zip.zip, and cannot find /Users/hajar/.sdkman/archives/gradle-5.4.1.zip.ZIP, period.

Stop! The archive was corrupt and has been removed! Please try installing again.

**Comment by marc0der** [comment]
Please follow the [contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md) (the stuff you deleted without reading) before opening an issue here.
