### ISSUE TITLE
sdk uninstall will fail if username contains "_"

### ISSUE THREAD

**Issue by yujiorama** [sdkman/sdkman-cli#706]
- [ ] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [x] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

I found a problem that the `sdk uninstall xxx` does not work for some people.
The sed command will fail if the username contains "_".
https://github.com/sdkman/sdkman-cli/blob/master/src/main/bash/sdkman-uninstall.sh#L27

Sdkman should expect to username will be following the restriction of linux convention "[a-z_][a-z0-9_-]*[$]".

**Comment by rgoldberg** [comment]
Does anything need to be done to accept PR #707 to fix this?

**Comment by rgoldberg** [comment]
This was fixed by #707, so can probably be closed.
