### ISSUE TITLE
Why doesn't "sdk  list --installed" doesn't work in Ubuntu 19.04? And why its not mentioned in "sdk --help" section?

### ISSUE THREAD

**Issue by PranavBhattarai** [sdkman/sdkman-cli#710]
![Screenshot from 2019-08-19 13-10-11](https://user-images.githubusercontent.com/32763112/63246576-b7669080-c282-11e9-9ebc-8a858938ff27.png)

**Comment by marc0der** [comment]
Usage questions should be asked on Slack (as is clearly stipulated in our contributor guidelines, you know the stuff you deleted before you opened this issue?).
