### ISSUE TITLE
latest osx: update bash

### ISSUE THREAD

**Issue by cekvenich** [sdkman/sdkman-cli#711]
When I run sdk update on OSX it says I need to update my bash to 4. But I have bash 5.
Help?

iMac:~ code$ sdk update
An outdated version of bash was detected on your system!
We recommend upgrading to bash 4.x, you have:
  3.2.57(1)-release
Need to use brute force to replace candidates...
iMac:~ code$ bash --version
GNU bash, version 5.0.9(1)-release (x86_64-apple-darwin18.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by marc0der** [comment]
Please follow the contributor guidelines as stated prior to opening an issue.

**Comment by marc0der** [comment]
BTW, check out the FAQ describing this issue:
https://github.com/sdkman/sdkman-cli/wiki/FAQ#when-i-run-sdk-update-on-osx-it-says-i-need-to-update-my-bash-to-4-but-i-have-bash-5-whats-up-with-that
