### ISSUE TITLE
Ubuntu and Linux curl command has no output option (--output)

### ISSUE THREAD

**Issue by sivaswami** [sdkman/sdkman-cli#712]
We require a conversation to take place in the appropriate [SDKMAN Slack](https://slack.sdkman.io) channel before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [* ] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

Please explain the Issue / Feature Request here:
The sdkman_install.sh script has --output flag which doesn't works with Linux machines like "ubuntu".

• • • curl --help | grep -i output
 -f, --fail          Fail silently (no output at all) on HTTP errors
 -i, --include       Include protocol response headers in the output
 -N, --no-buffer     Disable buffering of the output stream
 -o, --output <file> Write to file instead of stdout
 -O, --remote-name   Write output to a file named as the remote file
 -R, --remote-time   Set the remote file's time on the local output
     --trace-ascii <file> Like --trace, but without hex output
     --trace-time    Add time stamps to trace/verbose output
 -w, --write-out <format> Use output FORMAT after completion

#download binary
		__sdkman_secure_curl_download "${download_url}" --output "${binary_input}"
		__sdkman_echo_debug "Downloaded binary to: ${binary_input}"

**Comment by marc0der** [comment]
Read the dump you posted very carefully...

Sdkman was developed on Linux (it is all I use), and the CI build on Travis actually runs in Ubuntu in Docker.

Let's head on over to slack to discuss this issue.

**Comment by sivaswami** [comment]
I am not sure about slack connectivity. can you please help me with the slack link ?

**Comment by marc0der** [comment]
Simply follow the links on our website, it's very simple.
