### ISSUE TITLE
Protect against bash alias of `rm`

### ISSUE THREAD

**Issue by paxperscientiam** [sdkman/sdkman-cli#713]
We require a conversation to take place in the appropriate [SDKMAN Slack](https://slack.sdkman.io) channel before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [x] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

There is a chance that `rm` may be aliased. As sdkman are sourced functions, there is the chance that previously defined aliases in shell config may clash. To avoid this, "escape" commands with `rm` in source.

EG: `rm path/to/something` to `\rm path/to/something`

PS: This is an important issue. Since no one has responded on Slack for a month, I'm putting this here anyway and submitting a PR.

**Comment by marc0der** [comment]
Mind pointing me to the conversation on Slack first? Sorry, it must have slipped my attention.

**Comment by paxperscientiam** [comment]
Hi @marc0der . Yes, here is my slack comment: https://sdkman.slack.com/archives/C0AUXKDK5/p1565378051002400
