### ISSUE TITLE
in alpine how to use sdkman?

### ISSUE THREAD

**Issue by hetianxing668** [sdkman/sdkman-cli#715]
this is alpine linux home site https://www.alpinelinux.org/,
i want to use sdkman in alpine but , i don't know how to use.
install follow step by step but failed
![image](https://user-images.githubusercontent.com/3139772/66726531-85317380-ee6c-11e9-9941-65171dcb93eb.png)

**Comment by marc0der** [comment]
Please follow the contributor guidelines as stipulated.
