### ISSUE TITLE
Install a custom DMG package to ~/.sdk

### ISSUE THREAD

**Issue by warden** [sdkman/sdkman-cli#720]
Usecase:
As we know JDKs are now behind a curtain. I'd like SDKMan to be able to automatically install a manually downloaded DMG file to `~/.sdk` folder. 
Does it make sense to you?
I'm happy to try to contribute if you direct me to the modules that would need to be changed.

```
hdiutil attach ./jdk-8u221-macosx-x64.dmg
pkgutil --expand /Volumes/JDK\ 8\ Update\ 221/JDK\ 8\ Update\ 221.pkg ./jdk
cpio -i < ./jdk180221.pkg/Payload
mv Contents/Home/ ~/.sdkman/candidates/java/oraclejdk-8u221
sdk default java oraclejdk-8u222 oraclejdk-8u221
hdiutil eject /Volumes/JDK\ 8\ Update\ 221/
```

**Comment by marc0der** [comment]
Please follow the contributor guidelines as stipulated. Please feel free to chat on [slack](https://slack.sdkman.io/) before we reopen this one. This discussion should probably be on the #cli-development channel. Closing this issue until discussed further.
