### ISSUE TITLE
Provide a way to get the home directory of an installed sdk candidate version

### ISSUE THREAD

**Issue by bes** [sdkman/sdkman-cli#722]
Please tick one:
- [x] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

Please explain the Issue / Feature Request here:

Expose a new command `sdk home <candidate> <version>` to be able to get e.g. a `JAVA_HOME` path to be able to execute one-off command line commands. 

Example

```
# Need Java 11 to build something
sdk use java 11.0.5.hs-adpt
# But there is this one tool that requires Java 8,
# and now you can run it like this without switching sdk
JAVA_HOME=`sdk home java 8.0.232.hs-adpt` my_java_8_command
```

Thank you for considering my feature request.

**Comment by marc0der** [comment]
I'm not opposed to adding this command as I can see that it could be useful.

I do have one silly question though: why not run this other tool in another terminal that `use`s Java 8?

**Comment by bes** [comment]
Good question. My use case for this is I have an alias for a java command that I would like to run interactively from time to time. Maybe it can be solved with a script and a subshell just as well.

**Comment by cwensel** [comment]
fwiw, it's quite common in the Java ecosystem for wrapper shell scripts to rely on a $JAVA_HOME env var, for good or bad (Gradle, Hadoop, Jetty, etc).

The Java SDK analog to this is `/usr/libexec/java_home` which simplifies swapping JDK versions during testing and development. But it only works with Oracle supplied SDKs from what I can tell. 

Leveraging sdkman to be the source of truth of installed versions and paths would be very handy.

**Comment by rgoldberg** [comment]
Should this issue be closed, since a PR was merged for it?
