### ISSUE TITLE
Kotlin/Native

### ISSUE THREAD

**Issue by cup** [sdkman/sdkman-cli#723]
https://github.com/JetBrains/kotlin-native

**Comment by cup** [comment]
why did you close

**Comment by marc0der** [comment]
Please follow the contributor guidelines as stipulated (all the stuff you deleted). We first discuss on slack to determine viability.

**Comment by cup** [comment]
Suit yourself. Kotin/Native is a perfectly valid and popular SDK, regardless of what boilerplate I did or didnt fill out.

**Comment by marc0der** [comment]
Actually it's not, as I would have told you on slack prior to opening this issue.

**Comment by cup** [comment]
From your attitude, its clear that you are a person that I *dont* want to talk to on Slack, or anywhere else; let alone go through the trouble of getting a Slack invite.

Cheers

**Comment by marc0der** [comment]
No attitude really, I've had to put this process in place to prevent having to trawl through zillions of issues (that aren't actually valid issues) in my spare time every week.

The reason I would have given you on slack is that kotlin native does not have a binary distributable, so it isn't a valid candidate.

From their github:

> The best way to use the Kotlin/Native compiler is with a build system. It helps by downloading and caching the Kotlin/Native compiler binaries and libraries with transitive dependencies, and running the compiler and tests. It caches the compilation results too. A build system can also be used by an IDE to understand the project layout.

**Comment by cup** [comment]
Yeah, it does:

https://github.com/JetBrains/kotlin/releases/latest

**Comment by marc0der** [comment]
Okay, thanks for letting me know. So the right place to report this issue is probably with the kotlin native folks themselves. Jetbrains are responsible for publishing their own releases of kotlin to sdkman via the vendor API. I'd expect they would want to do the same for kotlin-native.

**Comment by cup** [comment]
Yeah, Im not doing that.

**Comment by marc0der** [comment]
Also, feel free to mention me and I'll chime in too to help that process along.

**Comment by marc0der** [comment]
Ah right, well bye then.

**Comment by leaf-node** [comment]
Just FYI, this is the status of the request upstream: <https://youtrack.jetbrains.com/issue/KT-44288/Make-Kotlin-Native-binaries-available-via-SDKMAN>. It sounds like the preferred way to install Kotlin Native is via Gradle. The following tutorial downloads the native executable (but for some reason, the project doesn't compile): <https://kotlinlang.org/docs/native-gradle.html>
