### ISSUE TITLE
Add `sdk status` as an alternative to `sdk current`

### ISSUE THREAD

**Issue by iemejia** [sdkman/sdkman-cli#726]
We require a conversation to take place in the appropriate [SDKMAN Slack](https://slack.sdkman.io) channel before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [x] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

Please explain the Issue / Feature Request here:

Most cli tools include a status of the tool state e.g. `git status`. In the case of sdkman the default status arg is called `sdk current`. This is less intuitive and by offering a default status keyword we can make sdkman use more familiar for cli users.

**Comment by marc0der** [comment]
See above:

> Please note that issues will be closed immediately if prior discussion did not take place.

**Comment by marc0der** [comment]
Happy to discuss this on slack and can reopen afterwards.
