### ISSUE TITLE
404 on 'sdk list'

### ISSUE THREAD

**Issue by christophehenry** [sdkman/sdkman-cli#727]
We require a conversation to take place in the appropriate [SDKMAN Slack](https://slack.sdkman.io) channel before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [X] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

Please explain the Issue / Feature Request here:

`sdk list` return 404 HTML page:

```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.15.12</center>
</body>
</html>
```

**Comment by marc0der** [comment]
> Please note that issues will be closed immediately if prior discussion did not take place.

No discussion took place so closing this issue. There is [no outage](http://status.sdkman.io/) reported on any of our services and all our APIs are responding as expected. I'd be happy to discuss the problem you are experiencing on our slack user-issues channel.

**Comment by christophehenry** [comment]
Well then your script has a bug becaus I can find the lines:

```
if [ -z "$SDKMAN_CANDIDATES_API" ]; then
        export SDKMAN_CANDIDATES_API="https://api.sdkman.io/2"
fi
```

And https://api.sdkman.io/2 returns 404. So this bug is actually valid.
Just sayin... :roll_eyes:

**Comment by marc0der** [comment]
Erm, no. That is the base url of the API.

**Comment by C06A** [comment]
The list command without candidate works fine, but if I run `sdk list java` I also get 404.
If you follow REST API then the URL would be [https://api.sdkman.io/2/candidates/list/java](url) and it returns 404.

**Comment by marc0der** [comment]
The restful API for this call is working just fine, always has been. Your assumption about what the API endpoint is isn't correct, hence the 404. I suggest upgrading sdkman or checking your proxy settings. Again, feel free to reach out on slack.
