### ISSUE TITLE
Is this normal or a glich?

### ISSUE THREAD

**Issue by PranavBhattarai** [sdkman/sdkman-cli#728]
I am using Ubuntu 19.10.
`sdkman version: 5.7.4+362`

![Screenshot from 2020-02-18 15-05-18](https://user-images.githubusercontent.com/32763112/74722104-7ca8d980-5260-11ea-9011-e3007df362d3.png)
![Screenshot from 2020-02-18 15-05-06](https://user-images.githubusercontent.com/32763112/74722121-82062400-5260-11ea-8a57-6f4be7d23bd5.png)

**Comment by marc0der** [comment]
Please read the [contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md) (the stuff you deleted) prior to opening an issue.
