### ISSUE TITLE
Helidon Support ?

### ISSUE THREAD

**Issue by sivaswami** [sdkman/sdkman-cli#733]
We require a conversation to take place in the appropriate [SDKMAN Slack](https://slack.sdkman.io) channel before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ *] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

Please explain the Issue / Feature Request here:
Can SDKMAN help in downloading Helidon SE and MP automatically ?
https://helidon.io/#/

**Comment by marc0der** [comment]
AFAIK, Hellidon is a set of libraries and not an SDK. From what I've seen it works through a Maven archetype. If there is an SDK, could you point me to it?

**Comment by marc0der** [comment]
Since there was no further response on this issue, and that Helidon is only a collection of libraries with not SDK, I'm going to close this issue.

Happy to reopen if the Helidon team ever decides to ship an SDK with a CLI.
