### ISSUE TITLE
sdk upgrade should respect sdkman_auto_answer setting

### ISSUE THREAD

**Issue by idegtiarenko** [sdkman/sdkman-cli#746]
At the moment `sdk upgrade` will trigger prompt to the user when there are upgrades found.
This operation should respect `sdkman_auto_answer` setting so that prompt could be suppressed.
It might be useful when executing sdk operations as part of other scripts (for example batch update: update deb packages and sdk candidates)

**Comment by marc0der** [comment]
This has now been merged so closing this issue.
