### ISSUE TITLE
Incorrect handling of architecture identifier

### ISSUE THREAD

**Issue by hexvalid** [sdkman/sdkman-cli#752]
We require a conversation to take place in the appropriate [SDKMAN Slack](https://slack.sdkman.io) channel before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [x] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

Please explain the Issue / Feature Request here:

Hi,

I installed sdkman on my aarch64 linux machine.
When i install a jdk `(sdk install java 8.0.252.fx-zulu)` this tool download and installing jdk for x86_64 arch. Ignoring my CPU Arch.

uname -a
`Linux alarm 5.6.5-1-ARCH #1 SMP Mon Apr 20 18:49:23 MDT 2020 aarch64 GNU/Linux`

**Comment by marc0der** [comment]
This tool support both Linux x86, x83 as well as Windows (Cygwin, MinGW) and OSX.

At this time we don't hold any binaries for Arm architectures. That said, we should probably tighten up our validation when receiving request for unsupported architectures.
