### ISSUE TITLE
Run `sdk env` automatically when entering a directory with an `.sdkmanrc`

### ISSUE THREAD

**Issue by helpermethod** [sdkman/sdkman-cli#756]
We require a conversation to take place in the appropriate [SDKMAN Slack](https://slack.sdkman.io) channel before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [x] this is a new Feature Request, a conversation was started in the [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).

Please explain the Issue / Feature Request here:
With the `env` command in place, there should be some hook which runs `sdk env` automatically whenever a directory is entered which contains an `.sdkmanrc`.

**Comment by marc0der** [comment]
As discussed in slack, this should be configurable through the use of a new config flag. For now it should probably be disabled by default.

**Comment by rgoldberg** [comment]
Should probably recourse up the directory tree to find the closest `.sdkmanrc`, not just one in the current directory. This would make each `.sdkmanrc` apply to its directory and to all its subdirectories, until another `.sdkmanrc` overrides it for a sub tree.

**Comment by helpermethod** [comment]
That would mean it would recurse on every directory change and probably re-executing the one found in `$HOME` multiple times when traversing directories. Adds additional complexity and slows down the shell for very little benefit IMHO.

**Comment by marc0der** [comment]
I don't think we should go down that road. Let's keep it simple...

**Comment by goerge** [comment]
With #757 being merged and released as part of `5.8.0` this issue can be closed, right?
