### ISSUE TITLE
Question: Where do find a changelog?

### ISSUE THREAD

**Issue by reitzig** [sdkman/sdkman-cli#761]
As a maintainer of [depending software](https://github.com/reitzig/sdkman-for-fish), it's highly relevant to me to know what changed in SDKMAN!.

Can you please publish a changelog in an easily accessible way?

Places I looked:

 - https://github.com/sdkman/sdkman-cli/releases
 - https://sdkman.io/
 - sdkman "changelog"

**Comment by marc0der** [comment]
Hi @reitzig, as you can see we don't currently have an explicit changelog. The closest thing is to look at the git commit history for now. That said, it should be possible to automate this and I'm happy to accept pull requests for enabling this. The current release script is very primitive and can be found in the _bin_ folder of this project.

**Comment by reitzig** [comment]
I don't think this can be automated in a reasonable way, at least not without very different input from the contributers.

 - There are dozens of commits in the 5.8 release. Not many of them have expressive, high level comments as would be needed for a meaningful changelog.
 - The same is true for the PR titles.

Without going through every PR in detail and cross-comparing the changes, I don't see a way to come up with a meaningful changelog.

There are many ways to curate one (e.g. CHANGELOG file that each PR needs to make a meaningful addition to), and prepared ways to have notes end up in GitHub Releases (IIRC, annotated tags work wonderfully). _If_ something like a CHANGELOG file existed, creating the tag annotation would be simple and I'd happy to help. But I'm not in the position to summarize the work being done.

(FWIW, I _think_ if you use GitHub Projects with Milestones or somesuch, _and_ have appropriately cut stories in them, you could automatically generate a changelog from that as well. Just as an option, doesn't apply here.)

**Comment by reitzig** [comment]
There are changelogs now -- thank you! :tada:
