### ISSUE TITLE
Micronaut CLI directory not set correctly in $PATH

### ISSUE THREAD

**Issue by mlk5060** [sdkman/sdkman-cli#768]
Hi there!

I just followed the installation instructions for Micronaut using SDKMAN listed [here](https://guides.micronaut.io/micronaut-cli/guide/index.html) however, it appears that Micronaut's `bin` directory isn't referenced in the fragment added to my PATH by SDKMAN. With a vanilla `sdk install micronaut`, my PATH starts with `/home/my_home_dir/.sdkman/candidates/micronaut/current`, whereas the `mn` executable is located in `/home/my_home_dir/.sdkman/candidates/micronaut/current/bin`. I am using ZSH, so adding `export PATH="$SDKMAN_DIR/candidates/micronaut/current/bin` to the end of my `.zshrc` allows me to use `mn` in a shell session, but this seems wrong?

Many thanks for SDKMAN, by the way!

**Comment by marc0der** [comment]
Hi @mlk5060, this does sound like something specific to your system. I installed several versions of micronaut yesterday and had no issues, which makes me think it might be an issue on your side.

However, without all the details I probably won't be able to help you here. 

Please replace the template text above with all details filled in, or even better, if you hop onto slack I can try to give you a hand over there.

**Comment by mlk5060** [comment]
Hi @marc0der :) Many thanks for getting back to me, it does seem like something on my side, and I hope its not something that will cause you too much of a headache (hopefully it is literally just my machine that suffers from this!).

I can't see any template text, unfortunately, I did look for some since it is annoying getting issues that don't give you all the information you need (first hand experience), apologies for that! If I get some free time I'll message you on Slack but I don't have much at the moment :( I'll soldier on regardless, but wanted to give you a heads up just in case something were wrong and it would affect others.

Many thanks again for your response, please feel free to close the issue! I don't want to since you follow a particular procedure for resolving tickets, and I don't want to mess it up!

**Comment by marc0der** [comment]
No worries, and really do feel free to drop in on slack where I can try help you get it sorted. We can then always update this issue later to help others with the same issue.

**Comment by marc0der** [comment]
If all is well, I'm closing this issue for now.

**Comment by mlk5060** [comment]
No problem @marc0der Thanks again for your help with this :+1:
