### ISSUE TITLE
sdk uninstall error: bad flag in substitute command

### ISSUE THREAD

**Issue by asarkar** [sdkman/sdkman-cli#771]
```
$ sdk version

SDKMAN 5.7.3+337

$ sdk list java
|     | 11.0.3       | zulu    | local only | 11.0.3-zulu
| >>> | 8.0.212      | zulu    | local only | 8.0.212-zulu

$ sdk uninstall java 11.0.3-zulu
sed: 1: "s_/Users/johndoe ...": bad flag in substitute command: '_'

Uninstalling java 11.0.3-zulu...

$ sdk uninstall java 11.0.3-zulu
sed: 1: "s_/Users/johndoe ...": bad flag in substitute command: '_'

java 11.0.3-zulu is not installed. 
```

**Comment by marc0der** [comment]
@asarkar please use the provided template when opening an issue as per the [contributing guidelines](https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md).

**Comment by asarkar** [comment]
@marc0der I'm not seeing any templates in the contributing guidelines you referred to, neither am I seeing any particular pattern among the open issues. I reported a legitimate problem with pertinent information, if your approach is to closing it due to lack of formatting, that's your prerogative. I'm not going to spend more time spit and polishing it.
