### ISSUE TITLE
Bug: OSX /usr/libexec/java_home is not seeing SDKMan JVMs

### ISSUE THREAD

**Issue by jottinger** [sdkman/sdkman-cli#773]
**Bug report**
Installed Java SDK with SDKMan.
Apps that use the /usr/libexec/java_home command to find the JVM do not succeed:

```
> /usr/libexec/java_home -V
Unable to find any JVMs matching version "(null)".
Matching Java Virtual Machines (0):

Default Java Virtual Machines (0):

No Java runtime present, try --request to install.
>
```

**To reproduce**
Install a JVM via SDKMan on Catalina.
Run `/usr/libexec/java_home -V` and verify SDKMan JVM is reported.

**System info**

OSX, Catalina, most recent
zsh 5.8 (x86_64-apple-darwin19.3.0)
SDKMAN 5.8.3+506

**Comment by marc0der** [comment]
Hi @jottinger, this really isn't a bug, but rather a flaw in the OSX `java_home` proprietary tool. Of course we have no control over what that tool does. I suggest raising this issue with Apple to make their tool more open and extensible.
