### ISSUE TITLE
Feature: Replace invocations of $(cat file) with $(< file)

### ISSUE THREAD

**Issue by helpermethod** [sdkman/sdkman-cli#774]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

Because SDKMAN takes aliases into account, it may happen that users have aliased `cat` to its popular replacement [bat](https://github.com/sharkdp/bat).

While `bat` is functionally equivalent to `cat`, it is also slower than `cat` by a measurable margin. This especially poses a problem in the context of `sdk env`, where the use of `bat` adds a whooping 300ms to its execution (about 1/3 of its total execution time).

This PR replaces every every invocation of `$(cat file)` in the context of the `sdk env` command by the equivalent substitution `$(< file)` (a special form of command substitution supported by Bash and Zsh).

In the case that users don't have that alias set, the change still improves `sdk env`'s performance, though only by a very small margin.

**Comment by marc0der** [comment]
Thanks for contributing again @helpermethod.
