### ISSUE TITLE
Feature: Bash Completion for SDKMAN

### ISSUE THREAD

**Issue by helpermethod** [sdkman/sdkman-cli#781]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

The ergonomics of SDKMAN could be greatly improved by providing autocompletion for commands, subcommands, candidates and versions.

**Comment by helpermethod** [comment]
Hi @marc0der, I've just linked the `sdkman-hooks` PR to this issue. Is this enough, or should I create an additional feature request for the `sdkman-hooks` repository?

**Comment by marc0der** [comment]
Don't worry about creating an issue, linking it here is perfect 👍
