### ISSUE TITLE
Question: [how to unninstall sdkman]

### ISSUE THREAD

**Issue by misbagas** [sdkman/sdkman-cli#783]
so i want to unninstall SDKMAN on my macos , i was follow this step for SDKMAN unninstalation instruction , rm -rf ~/.sdkman , but it's doesnt work for my mac

    

> rm -rf ~/.sdkman

and when i type sdk version on my macos console my uninstalation step is not work , this is the result when i type sdk version.

https://i.stack.imgur.com/hfAf1.png

i use macos operating system , version catalina

**Comment by marc0der** [comment]
@misbagas to uninstall SDKMAN completely, you need to remove that folder completely. Optionally, also remove the snippet from your bash or zsh profile responsible for sourcing `sdkman-init.sh`. Lastly, close the current terminal and open a new one to ensure that everything is removed.

It is also worth noting that the `sdk` command is not an executable, but a function that gets sourced into the shell. This is why you are possibly still seeing the command available in your old shell.

Please let met know if that worked!

**Comment by misbagas** [comment]
i not follow you step , i just type this on my terminal macos :

> 

    sudo mv ~/.sdkman

or is not work

    sudo mv /Users/yourname/sdkman/

**Comment by misbagas** [comment]
just that , and is work for me

**Comment by misbagas** [comment]
and thank you @marc0der  for you answer

**Comment by misbagas** [comment]
so i close
