### ISSUE TITLE
Feature: Add `sdk env install` subcommand

### ISSUE THREAD

**Issue by helpermethod** [sdkman/sdkman-cli#784]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
As discussed some time ago in the Slack `cli-development` channel, it would be nice to have an additional subcommand for `sdk env` which installs the candidates contained in `.sdkmanrc`.

**Comment by marc0der** [comment]
Sounds great, and highly useful.
