### ISSUE TITLE
Bug: curl 7.71.1 reports "SSL certificate problem: self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by christopher-johnson** [sdkman/sdkman-cli#787]
output from curl -V 
```
curl 7.71.1 (x86_64-apple-darwin19.5.0) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 c-ares/1.16.1 libssh2/1.9.0 nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```
This is a "custom" build of curl to be able to support TLS 1.3 (see installation [guide](https://learnings.bolmaster2.com/posts/curl-openssl-tlsv1.3-on-macos.html) for details)

any sdkman operation that depends on curl subsequently fails.

**Comment by marc0der** [comment]
I can confirm that our API doesn't support TLS 1.3 yet. I will wait for Debian 10 (which has openssl 1.1.1) to be released before I roll it out to our nginx nodes. For now, I am changing the label to enhancement as I don't feel this is a bug.

**Comment by marc0der** [comment]
I _think_ I've managed to get this working in nginx now. Could I ask you to try testing this again please @christopher-johnson? It should all work as expected now. Feel free to close this issue if it all checks out.

**Comment by christopher-johnson** [comment]
I now suspect that this particular PKIX exception is a consequence of our corporate TLS proxy that overwrites the root CA for non-whitelisted sites (have had a similar situation in the past).  What is odd is that it did not occur with the previous version of curl.  I can close this issue as invalid.  Thanks for your quick response!
