### ISSUE TITLE
Bug: cannot install http4k

### ISSUE THREAD

**Issue by jmfayard** [sdkman/sdkman-cli#789]
**Bug report**

Cannot install http4k 

**To reproduce**

`$ sdk install http4k` produces an error

**Stop! http4k is not a valid candidate.**

But it is listed in `$ sdk list`

```
http4k (0.20.0)                                               http://http4k.org/

http4k is the Functional toolkit for building HTTP applications in Kotlin

                                                            $ sdk install http4k
```

**System info**

macOS 10.15 zsh

**Comment by marc0der** [comment]
Have you tried performing and `sdk update` prior to installation?

**Comment by jmfayard** [comment]
I did but I somehow miss the part `Please open a new terminal now...`

Problem solved
