### ISSUE TITLE
Feature: Ballerina support

### ISSUE THREAD

**Issue by bassmake** [sdkman/sdkman-cli#791]
- [x ] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
[Ballerina](https://ballerina.io/) is an open source programming language and platform for cloud-era application programmers to easily write software that just works.
Default implementation is in java, it would be great if SKDMAN provided support for this language.

**Comment by helpermethod** [comment]
Hi @bassmake!

Had a quick look at the binary format and the ZIP structure and Ballerina looks like a good candidate to be added to SDKMAN!.

Do you want to give it a try?

All that is needed is a PR on this project.

https://github.com/sdkman/sdkman-db-migrations

If you need any help, feel free to ask!
