### ISSUE TITLE
Feature: Redhat Mandrel JDK support

### ISSUE THREAD

**Issue by AlexKovynev** [sdkman/sdkman-cli#794]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
Cause it's already have stable release (20.1.0.2), it will be nice to add support as an GraalVM analog.

**Comment by helpermethod** [comment]
Hi @AlexKovynev,

looks doable from a quick look. Do you want to give this a try?

**Comment by marc0der** [comment]
Yep, agreed. We just need to do a sanity check on the binary format, as well as the internal structure. I would also need to do something on the backend in the sdkman-hooks service to accommodate a new JDK vendor.

**Comment by AlexKovynev** [comment]
sorry guys i don't an redhat employer or some, i only write project on quarkus and want to use your sdkman. Hope someone can do it.

**Comment by marc0der** [comment]
@AlexKovynev the great news is that sdkman is a community driven project and anyone can add it. All that is required is a pull request on this project:
https://github.com/sdkman/sdkman-db-migrations

**Comment by zakkak** [comment]
It looks like Mandrel is now available :)
https://github.com/sdkman/sdkman-db-migrations/pull/324#issuecomment-725331770

Thank you all who were involved in making this happen!
