### ISSUE TITLE
Feature: homewbrew formula

### ISSUE THREAD

**Issue by pshirshov** [sdkman/sdkman-cli#799]
- [X] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

Hi!

It would be very nice to have a homebrew formula, current way with shell script installation is very inconvenient for automatic provisioning.

**Comment by helpermethod** [comment]
Hi @pshirshov!

Using brew for installing SDKMAN! sounds like a good idea in theory but seems to pose a few problems in practice:

* brew discourages tools that update itself (like SDKMAN! does)
* brew by design never modifies files outside HOMEBREW_PREFIX, so you would have to manually modify your `.bash_profile` to source SDKMAN's init script

**Comment by pshirshov** [comment]
> brew discourages tools that update itself (like SDKMAN! does)

Though many packages do that.

> brew by design never modifies files outside HOMEBREW_PREFIX, so you would have to manually modify your `.bash_profile` to source SDKMAN's init script

It's possible to add a post-install message to a homebrew package. E.g. try to install JDK on Catalina - and `brew` will tell you what steps you must take in order to get it working.

**Comment by asmaier** [comment]
Why not simply add sdkman as brew cask ? https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by marc0der** [comment]
The main problem here is what @helpermethod stated above. SDKMAN updates itself, we would first have to do some development to disable this behaviour for brew installations. Also, sdkman has all it's files in user space (home folder), so it will probably be a problem for brew to manage these.

**Comment by asmaier** [comment]
But I can install for example the Google Chrome browser as cask. It also updates itself and does all kinds of things. I don't think the self-update feature is a blocker for implementing sdkman for brew cask.

**Comment by felipecrs** [comment]
References https://github.com/Homebrew/brew/issues/10167.

**Comment by jayvdb** [comment]
Perhaps someone can create a custom tap for this in their own repo?  It doesnt need to be perfect to be useful.

**Comment by benkeil** [comment]
Any news on this?

**Comment by helpermethod** [comment]
I guess now that SDKMAN! is distributed as an SDK itself, that should be doable. Wdyt @marc0der?

**Comment by marc0der** [comment]
Sure. SDKMAN still updates itself once installed, so we probably need a config to turn that off. Also, during installation, we do a bunch of stuff like populating the `/var` folder and other initialisation tasks.

**Comment by benkeil** [comment]
You can write a cask.

**Comment by marc0der** [comment]
@benkeil Nope, not me. But maybe _you_ can write that cask 😄

**Comment by helpermethod** [comment]
@benkeil Work on an initial Brew tap has [started](https://github.com/sdkman/homebrew-tap) but requires some minor changes in sdkman-cli itself.

**Comment by ironfish** [comment]
What happened to this tap. I used it to install SDKMAN and now it's gone?

**Comment by helpermethod** [comment]
Hi @iron,

we are currently moving the tap over to the official repository, and in the process I've made the repository private. I'll make it public until the migration is finished.

Sorry for the inconvenience!

**Comment by ironfish** [comment]
Thank you, very much appreciated.

**Comment by helpermethod** [comment]
There is now an official Homebrew Tap for SDKMAN! updated automatically with every release.

Installation instructions can be found here:

https://github.com/sdkman/homebrew-tap

**Comment by marc0der** [comment]
@helpermethod Thanks for all your effort. Fantastic work!
