### ISSUE TITLE
PowerShell Core support

### ISSUE THREAD

**Issue by pshirshov** [sdkman/sdkman-cli#803]
PowerShell Core is cross-platform and it's a very nice shell.

Unfortunately, SDKMAN relies on a `bash`y launcher script which cannot be interpreted by `pwsh`.

Could you please implement a separate launcher for `pwsh`?

**Comment by marc0der** [comment]
Unfortunately, we won't be implementing a power shell version at any point. In fact, the idea is to move away from bash too and write a native version for all popular platforms.

**Comment by pshirshov** [comment]
For those who may experience the same problem: I made an alternative dependency manager: https://github.com/7mind/binlink

**Comment by marc0der** [comment]
@pshirshov It's probably more constructive to join us and help make SDKMAN better than creating yet another tool that does exactly the same.

**Comment by pshirshov** [comment]
I just made the future happen now to solve my own issues - that's exactly a native version which would work for all popular platforms (apart of windows but that should be solvable too). 

I would be happy if you reuse/improve my code though. Also I may explain my approach (it's really simple).
