### ISSUE TITLE
Question: Is there a short description how to install SDKMan on Windows based on WLS2? 

### ISSUE THREAD

**Issue by uwieske** [sdkman/sdkman-cli#808]
Hi 

I am on Windows 10 and want to install SDKMan on Windows based on WLS2. I ve read the "Install" documentation on the website of SDKMan, but unfortunately I am not able to continue based on the limited WLS 2 install description given in this page,

I would like to read a comprehensive installation instruction of SDKMan on Windows 10 with WLS2 support, please.

Thank you

**Comment by marc0der** [comment]
Hi @uwieske, since WLS2 is just Linux under the hood, you can simply follow the standard installation instructions on https://sdkman.io/install.

This will allow you to use Java on the CLI within WSL2.
