### ISSUE TITLE
Question: mvnd about to provide a mvn executable

### ISSUE THREAD

**Issue by ppalaga** [sdkman/sdkman-cli#809]
related: https://github.com/mvndaemon/mvnd/pull/89

We are about to add `mvn` script into the `bin` folder of `mvnd` distro. A simple test shows that our `mvn` will "shade" the `mvn` from the stock Maven:

```
$ sdk install mvnd # using the distro from https://github.com/mvndaemon/mvnd/pull/89
$ sdk install maven

# open a new console
$ echo $PATH
/home/ppalaga/.sdkman/candidates/mvnd/current/bin:/home/ppalaga/.sdkman/candidates/maven/current/bin:/home/ppalaga/.sdkman/candidates/jbang/current/bin:/home/ppalaga/.sdkman/candidates/java/current/bin:...

$ which mvn
~/.sdkman/candidates/mvnd/current/bin/mvn
```

We admit this has some potential to break expectations of many sdkman users.
We actually do not insist on our `mvn` script taking the precedence, but we need it in our bin and we need it having executable permissions. 

So the question is, what can we do solve the situation in such a way that the stock Maven's `mvn` is picked even if `mvnd` is installed and even if `mvn` exists in `mvnd` 's `bin` folder?

We are thinking about making `mvnd` a Maven distro so that it is not possible (at least with sdkman) to have both stock Maven and mvnd active at the same time. Maybe there are other options we could consider?

**Comment by marc0der** [comment]
We could introduce a post-install hook that removes executable rights from your `mvn` executable. It would require a PR on our `sdkman-hooks` service if you are up for some scala and play fun :smile:

**Comment by ppalaga** [comment]
Thanks for the suggestion, @marc0der , but we have found another good solution. We basically moved the embedded Maven to `mvn` subdir of our distro. The `mvn` executable`s full path is thus `mvn/bin/mvn` rather than `bin/mvn`. SDKMAN does not add `mvn/bin` to PATH and thus our `mvn/bin/mvn` executable is not found by the shell.
