### ISSUE TITLE
Bug: SDKMAN 5.9.1+575 cannot install Amazon JDK 11 (candidate version 11.0.9-amzn)

### ISSUE THREAD

**Issue by ikysil** [sdkman/sdkman-cli#812]
**Bug report**
SDKMAN 5.9.1+575 cannot install Amazon JDK 11 (candidate version 11.0.9-amzn)

**To reproduce**
```
$ sdk flush force
$ sdk i java 11.0.9-amzn

Downloading: java 11.0.9-amzn

In progress...

################################################################################################## 100.0%

Repackaging Java 11.0.9-amzn...

Done repackaging...

Installing: java 11.0.9-amzn
mv: target '/home/ikysil/.sdkman/candidates/java/11.0.9-amzn' is not a directory
Done installing!

Do you want java 11.0.9-amzn to be set as default? (Y/n): n

```

**System info**
- OS: Ubuntu 20.04
- Shell and version
```
$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
```
- The output of `sdk version`
```
$ sdk version

SDKMAN 5.9.1+575
```

**Comment by ikysil** [comment]
It looks like the packaging was changed between previous 11.0.8-amzn and new 11.0.9-amzn candidates

Here is the line in `sdkman-install.sh` which generates that error message:
https://github.com/sdkman/sdkman-cli/blob/ec96fe835c2029cbe401ba751e0b725ec8c5137c/src/main/bash/sdkman-install.sh#L74

**Comment by ikysil** [comment]
Here is the full expansion of the `mv` command:
```
+ mv /home/ikysil/.sdkman/tmp/out/ADDITIONAL_LICENSE_INFO /home/ikysil/.sdkman/tmp/out/amazon-corretto-11.0.9.11.1-linux-x64 /home/ikysil/.sdkman/tmp/out/ASSEMBLY_EXCEPTION /home/ikysil/.sdkman/tmp/out/LICENSE /home/ikysil/.sdkman/tmp/out/README.md /home/ikysil/.sdkman/tmp/out/version.txt /home/ikysil/.sdkman/candidates/java/11.0.9-amzn
mv: target '/home/ikysil/.sdkman/candidates/java/11.0.9-amzn' is not a directory
```

**Comment by marc0der** [comment]
Thanks for reporting this @ikysil, we'll look into this as soon as possible.

**Comment by santhosh34** [comment]
Happening the same on amazon EC2 centos as well.

**Comment by marc0der** [comment]
I can confirm that the new version published fixes the problem.

**Comment by ikysil** [comment]
Confirmed on my side as well.

I'm closing the issue.
