### ISSUE TITLE
Bug: Getting 403 Forbidden when trying to get_url 'https://get.sdkman.io'

### ISSUE THREAD

**Issue by seanwang-okta** [sdkman/sdkman-cli#813]
**Bug report**
Hi, I'm running an ansible role to install sdkman in a docker container on an us-east-1 ec2 instance, and i'm getting 403 forbidden when doing a get_url with 'https://get.sdkman.io' as the url. I tried doing a curl as well and got the same error 403. This was working fine a week ago, so not sure what changed.

2020-10-23 20:04:20 TASK [okta.sdkman : Download SDKMAN] *******************************************
2020-10-23 20:04:20 fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/sdkman_script", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 403: Forbidden", "status_code": 403, "url": "https://get.sdkman.io"}

The ansible role we're running is based off of this one, and this is the line where it fails: https://github.com/Comcast/ansible-sdkman/blob/3773085be50f5bb3fe8a1030cf3275ee93d9e62a/tasks/install.yml#L63
**To reproduce**
curl https://get.sdkman.io from us-east-1 ec2 instance.

**System info**
(unable to even download it)

**Comment by helpermethod** [comment]
Hi @seanwang-okta!

Could you do a `curl -v https://get.sdkman.io` to get a little bit more context?

**Comment by seanwang-okta** [comment]
`
[ec2-user@ip-10-15-50-230 ~]$ curl -v https://get.sdkman.io
* Rebuilt URL to: https://get.sdkman.io/
*   Trying 45.55.42.78...
* TCP_NODELAY set
* Connected to get.sdkman.io (45.55.42.78) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.sdkman.io
*  start date: May 30 00:00:00 2020 GMT
*  expire date: Apr 28 23:59:59 2022 GMT
*  subjectAltName: host "get.sdkman.io" matched cert's "*.sdkman.io"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: get.sdkman.io
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Server: nginx/1.19.1
< Date: Fri, 23 Oct 2020 22:52:33 GMT
< Content-Type: text/html
< Content-Length: 153
< Connection: keep-alive
< 
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.19.1</center>
</body>
</html>
* Connection #0 to host get.sdkman.io left intact`

**Comment by marc0der** [comment]
Hi @seanwang-okta, could you please DM me your external IP address on Slack? I've had to blacklist a number of IP addresses recently due to overuse of our API. I just want to rule out that yours isn't one of those.

**Comment by seanwang-okta** [comment]
hi @marc0der, i've messaged you in the sdkman slack.

**Comment by marc0der** [comment]
Closing this issue for now.
