### ISSUE TITLE
Bug: Offline can't get back online

### ISSUE THREAD

**Issue by khmarbaise** [sdkman/sdkman-cli#817]
Currently I get always:
```
~$ sdk list java
==== INTERNET NOT REACHABLE! ===================================================

 Some functionality is disabled or only partially available.
 If this persists, please enable the offline mode:

   $ sdk offline

================================================================================

--------------------------------------------------------------------------------
Offline: only showing installed java versions
--------------------------------------------------------------------------------
 * 8.0.272.hs-adpt
 * 7.0.262-zulu
 * 16.ea.21-open
 * 15.0.1.hs-adpt
 * 11.0.9.hs-adpt
 > 11.0.8.hs-adpt
--------------------------------------------------------------------------------
* - installed                                                                   
> - currently in use                                                            
-----------------------------------------
```

I tried already to bring online back...via:
```
~$ sdk offline disable
Online mode re-enabled!
~$ sdk list java
==== INTERNET NOT REACHABLE! ===================================================

 Some functionality is disabled or only partially available.
 If this persists, please enable the offline mode:

   $ sdk offline

================================================================================

--------------------------------------------------------------------------------
Offline: only showing installed java versions
--------------------------------------------------------------------------------
 * 8.0.272.hs-adpt
 * 7.0.262-zulu
 * 16.ea.21-open
 * 15.0.1.hs-adpt
 * 11.0.9.hs-adpt
 > 11.0.8.hs-adpt
--------------------------------------------------------------------------------
* - installed                                                                   
> - currently in use                                                            
-----------------------------------------
```

Currently it seemed not possible via command line options to bring it back working.

**To reproduce**

**System info**
OS: Mac OS Mojava (Version: 10.14.6)
```
~$ sdk version
==== INTERNET NOT REACHABLE! ===================================================

 Some functionality is disabled or only partially available.
 If this persists, please enable the offline mode:

   $ sdk offline

================================================================================


SDKMAN 5.9.1+575
```

**Comment by marc0der** [comment]
I don't think this is a bug with SDKMAN, as all servers are [fully operational](http://status.sdkman.io/). Please ensure that the internet is reachable and that you aren't being blocked by a proxy. If problems persist, please feel free to contact us on the [SDKMAN Slack](https://slack.sdkman.io/) #user-issues channel where we can help you resolve your issue.

**Comment by khmarbaise** [comment]
No proxy, nothing is blocked; Browser works perfectly (three different ones) builds with Maven, Docker etc. getting everything they need; IDE makes Updates without any issue. ...everything else is working without any issue...

The question is: Where is configured being online / offline? Cause that can't be changed in contradiction to the printed out message...

**Comment by marc0der** [comment]
@khmarbaise I've answered all your questions on slack. Happy to pick up and help you resolve your issues there.

**Comment by sothawo** [comment]
I just git the same problem. Answering an GitHub issue on slack does not help others that have the same issue.

**Comment by marc0der** [comment]
@sothawo this could be caused by so many issues, not just a single cause. That's why we are happy helping you on a case by case basis. In short, SDKMAN currently uses curl to make all it's API calls. If curl does not succeed for whatever reason then SDKMAN goes into the offline mode. This is less than ideal, but for now it is what it is until we roll out a better solution.

**Comment by EricJim08** [comment]
The same problem is happening on me.I always get the same "bug"-"offline"，if I can't sovle it ,maybe I will change to use anothor tool.

**Comment by marc0der** [comment]
@EricJim08 I will be removing the offline mode very soon as it is known to have lots of problems. In the meanwhile, you might want to have a play with the curl timeout settings to see if that resolves the issue.

Feel free to try out those other tools if you think that will solve your problems.
