### ISSUE TITLE
Bug: SDKman not able to install JDK in Cygwin in Windows 10

### ISSUE THREAD

**Issue by aymanapatel** [sdkman/sdkman-cli#821]
**Bug report**

SDKMan gives following error when installing JDK:

```
Stop! java 11.0.5-zulu is not available. Possible causes:
 * 11.0.5-zulu is an invalid version
 * java binaries are incompatible with CYGWIN_NT-10.0
 * java has not been released yet
```

**To reproduce**

- Install Cygwin with zip, unzip, Python, etc.

- Install SDK version with the following command: `curl -s "https://get.sdkman.io" | bash`
- SDKMan gets successfully installed. But after running `sdk install java 11.0.5-zulu`, get the above-mentioned error:

**System info**

- OS: Windows 10 Build 20251.fe_release.20130-1438
- `bash --version`: GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
- SDK Version: `SDKMAN 5.9.1+575`

**Comment by marc0der** [comment]
This is not a bug as `11.0.5-zulu` is not a currently supported version. The currently supported Zulu version is `11.0.9-zulu`.

In the future, please ask usage questions on our Slack user-issues channel before opening a bug report.
