### ISSUE TITLE
Feature: Add `sdk env clear` subcommand

### ISSUE THREAD

**Issue by mperezi** [sdkman/sdkman-cli#824]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
When you are done with a project that uses a custom environment (bootstrapped by `sdk env`) and you walk out of that directory there must be a way of restoring the versions overridden by the environment. This is specially the case when you switch to another project that relies on default versions.

**Comment by helpermethod** [comment]
Hi @mperezi!

This sounds like a useful addition.

`direnv` has a similar feature so I guess it should also be possible for SDKMAN!.
