### ISSUE TITLE
Feature: Install JDK to "standard" location

### ISSUE THREAD

**Issue by ColtonIdle** [sdkman/sdkman-cli#826]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
Apparently sdkman doesn't install to standard location as per this tweet. Any reason why not to do this? https://twitter.com/JakeWharton/status/1263656692643921920

**Comment by marc0der** [comment]
Please follow the contributor guidelines in future.

Feel free to ask usage questions on the [SDKMAN Slack](https://slack.sdkman.io).
