### ISSUE TITLE
Feature: SDKMAN to offer the possibility to install Native JDK for Apple Silicon

### ISSUE THREAD

**Issue by imrabti** [sdkman/sdkman-cli#830]
Now that Apple Silicon computers are publicly available, and there is the first native JDK for this CPU architecture from Azul https://www.azul.com/downloads/zulu-community/?package=jdk, it would awesome that I could install it using SDKMAN.

**Comment by marc0der** [comment]
@imrabti I totally agree, it will be fantastic to have this platform covered. Some work needs to be done on the CLI to accommodate this. We use the output of `uname` and `uname -m` to infer the architecture of a platform on SDKMAN. If you perhaps have such a machine available, please help us by providing the output of those two commands.

**Comment by imrabti** [comment]
@marc0der I have a MBP with M1 I tried the two commands and here is the output :
For `uname` I get `Darwin`
And for `uname -m` I get `arm64`

**Comment by marc0der** [comment]
Does anyone know what a normal Mac reports for `uname -m`? I'm guessing that `uname` also returns `Darwin`. Apologies, I'm a Linux user :smile:

**Comment by azusa** [comment]
Hi @marc0der ,
On normal(Intel) mac, `uname` returns `Darwin` and `uname -m` returns `x86_64` .

**Comment by pr1metine** [comment]
Hi all!
Is there an update on this?

**Comment by mecca831** [comment]
Should be doable by adding a similar check for `DarwinARM64` here: https://github.com/sdkman/sdkman-cli/blob/b8b856f4a589e2447dae8c7ce7fe234a982a5d26/src/main/bash/sdkman-init.sh#L34

However, with Rosetta 2, the x86_64 JDKs will run just fine. From a design point of view, if `DarwinARM64` is added, should it be possible to also list/install x86_64 candidates?

The available candidates would be,

* Darwin -> x86_64 jdks
* DarwinARM64 -> x86_64 AND arm64 jdks

Or maybe just ask the user to set `SDKMAN_PLATFORM="Darwin"` specifically to install x86_64 JDKs?

**Comment by mecca831** [comment]
If it helps, this is the output from macOS Arm64 Zulu JDK by Azul:

```
System.out.println(System.getProperty("os.name") + " " + System.getProperty("os.arch"));
```

```
Mac OS X aarch64
```

**Comment by lptr** [comment]
IIUC this issue now is about choosing the `aarch64` variant of the JDK automatically on Apple silicon. I think the matter is somewhat more complicated than that.

At least during the current transitional period for you might want to install the `x86` for some applications that don't yet support Apple silicon natively, while you'd want to use the `aarch64` variant for the ones that do. The ability to switch between the two architectures is exactly what I'd love to use SDKMAN for.

**Comment by marc0der** [comment]
Hi @lptr!

We were just having the same [discussion on Slack](https://sdkman.slack.com/archives/CJK9DMV6V/p1610709359003300?thread_ts=1608701825.041500&cid=CJK9DMV6V), but I'll repeat what we said here:

I suggested that we introduce a feature toggle by way of a config variable in `.sdkman/etc/config` to enable this compatibility. I was thinking of a new variable called `sdkman_rosetta2_compat` that will propagate the `x86_64` arch to the backend. This will allow that you can install `x86_64` JDK variants in the time being until vendors have caught up with publishing the arm64 variants. It will be an exclusive switch thouth.

**Comment by lptr** [comment]
@marc0der I can't access Slack, but what you write here it seems that it will be an either/or choice the user has to make whether they want `x86` or `aarch64` variants installed. I think it would be better if it was possible to install both variants, and let the user choose between them. Sorry if I missed something, and this is already the plan.

**Comment by marc0der** [comment]
@lptr, to enable this scenario where both variants are supported will be a lot of work and have a great impact on our backend. The either/or scenario is fairly simple to roll out with only changes to the CLI.

My thinking is that all vendors will be bringing out `aarch64` variants in the near future, which means it isn't a situation that we will need to live with for very long. In the meanwhile, this "exclusive" compatibility mode that I'm suggesting will unblock those who still want to use many different flavours of JDK. However, most users are just interested in having the latest greatest available JDK.

**Comment by marc0der** [comment]
This feature has been released on the stable channel as [5.10.0](https://github.com/sdkman/sdkman-cli/releases/tag/5.10.0).

**Comment by nicodewet** [comment]
Gotcha alert: remember, on Apple Silicon Mac, to have a **Rosetta Terminal** and a **Terminal** 

You may have, at some stage, Rosetta enabled your terminal app and forgotten about it (as I did). This will mean that uname -m will NOT return arm64 so you'll think sdkman is not working when limiting SDKs to native ones.

So use the native terminal with sdkman if you only want to ever see native JDKs.

It was this article that helped me remember that I failed to create 2 terminals and probably Rosetta enabled my sole terminal when installing homebrew months ago: https://osxdaily.com/2020/11/18/how-run-homebrew-x86-terminal-apple-silicon-mac/

**Comment by sbrannen** [comment]
Another gotcha alert: on Apple Silicon Mac... you have to ensure that your shell is ARM64 if you want SDKMAN to install ARM variants.

After a migration from an older MacBook Pro to new one with Apple Silicon, I lost several hours trying to figure out how to get SDKMAN to install ARM-based JDKs.

See https://github.com/Homebrew/discussions/discussions/2486 for details regarding shell (e.g., `bash`) installation with home brew.
