### ISSUE TITLE
Feature: Support Loom enhanced JDKs ?

### ISSUE THREAD

**Issue by paul-hammant** [sdkman/sdkman-cli#834]
http://jdk.java.net/loom/ currently lists a modified Java-16 that includes "project loom" features.

It would be great to see that as a 'ls' and install choice for `sdk`  Over the next year, Loom gets closer and closer to being mainstream and ultimately merged back into standard Java. Thus, this gets developer interest increasingly going forward

**Comment by marc0der** [comment]
Loom is already available under SDKMAN and can be installed with `sdk i java 16.ea.7.lm-open`. We also keep this up to date when new versions come out.

**Comment by paul-hammant** [comment]
Didn't realize `loom` was shortened to `lm`, sorry.
