### ISSUE TITLE
Bug:  Can not install java 11.0.9-librca at this time...

### ISSUE THREAD

**Issue by a-trusov** [sdkman/sdkman-cli#837]
**Bug report**
~ >>> sdk install java 11.0.9-librca                                                                                            

Downloading: java 11.0.9-librca

In progress...

########################################################################################################################## 100,0%########################################################################################################################## 100,0%
Download has failed, aborting!

Can not install java 11.0.9-librca at this time...

**System info**
Manjaro
SDKMAN 5.9.1+575

**Comment by helpermethod** [comment]
Hi @a-trusov!

Does the problem still persist?

Tested the installation on both MacOSX and Ubuntu and both seem to work fine.

**Comment by marc0der** [comment]
Hi @a-trusov, I too use Manjaro and just managed to install it without a hitch. Please feel free to chat with us on slack if your issue persists.
