### ISSUE TITLE
Feature: Set GRAALVM_HOME environment variable

### ISSUE THREAD

**Issue by michael-schnell** [sdkman/sdkman-cli#838]
Currently using Java GraalVM does not set the "GRAALVM_HOME" environment variable. It would be nice if it could be set along with "JAVA_HOME". This would avoid manual setup after switching between Java / GraalVM versions.

**Comment by marc0der** [comment]
SDKMAN does not currently distinguish between GraalVM or Java, treating them both as Java. And so it isn't possible to tell if the current version in use is a classic or graal installation. For this reason, it isn't possible to set the GRAALVM_HOME. This can only ever change if we make GraalVM a candidate apart from Java, but this will cause a path clash as they both provide Java. Hope the explanation makes sense!

**Comment by michael-schnell** [comment]
OK, I thought there is some kind of "post processing" that could be added for different Java flavours.
