### ISSUE TITLE
[LinuxARM64][Java] bash: No such file or directory

### ISSUE THREAD

**Issue by unknowpe** [sdkman/sdkman-cli#840]
![IMG_20201211_141045_639](https://user-images.githubusercontent.com/33694084/101874085-c4676b80-3bba-11eb-811d-542e8625e580.jpg)
I just found SDKMAN! Recently, it really save my day .. All Installation has been successfully completed.. Although I had some errors and I got no lead from searching related issues .. Please help

**Comment by helpermethod** [comment]
Hi @unknowpe!

Are you using termux?

**Comment by unknowpe** [comment]
> Hi @unknowpe!
> 
> Are you using termux?

Yes

**Comment by helpermethod** [comment]
Interestingly, the executable exists

    test -f  /data/data/com.termux/files/home/.sdkman/candidates/java/current/bin/java
    echo $? # 0, so the file exists

**Comment by unknowpe** [comment]
the executable file exists .. but idk why it say "no such file" could this be my file is corrupted ??

**Comment by helpermethod** [comment]
The file exists, and if you do a `file $JAVA_HOME/bin/java` it shows the correct type. I need to test this with different installations, but if I remember correctly this worked at some point.

**Comment by unknowpe** [comment]
![IMG_20201211_192631_484](https://user-images.githubusercontent.com/33694084/101903543-03abb180-3be7-11eb-836d-208a43e76c0f.jpg)
UUgh .. @helpermethod  , I just realize it was my fault to begin .. I failed to notice the difference mechanisms between android and PC . Thank you for your time.

**Comment by helpermethod** [comment]
@unknowpe Very interesting, thanks for sharing!
