### ISSUE TITLE
Question: How to install openjdk-8

### ISSUE THREAD

**Issue by cmoulliard** [sdkman/sdkman-cli#841]
## Question

Is it still possible to install old openjdk (e.g. openjdk-8) versions as `sdk list java` dont show it anymore ?
```
 Java.net      |     | 17.ea.1      | open    |            | 17.ea.1-open
               |     | 16.ea.28     | open    |            | 16.ea.28-open
               |     | 16.ea.9.lm   | open    |            | 16.ea.9.lm-open
               |     | 16.ea.3.pma  | open    |            | 16.ea.3.pma-open
               |     | 15.0.1       | open    |            | 15.0.1-open
               |     | 14.0.2       | open    |            | 14.0.2-open
               |     | 13.0.2       | open    |            | 13.0.2-open
               |     | 12.0.2       | open    |            | 12.0.2-open
               | >>> | 11.0.2       | open    | installed  | 11.0.2-open
               |     | 10.0.2       | open    |            | 10.0.2-open
               |     | 9.0.4        | open    | installed  | 9.0.4-open
```

**Comment by helpermethod** [comment]
On Windows and 64-Bit Linux it should still be possible by issuing the following command

    sdk install java 8.0.265-open

There is an ongoing task to make older versions available [indefinitely](https://github.com/sdkman/sdkman-db-migrations/issues/170).

**Comment by cmoulliard** [comment]
In the meantime I installed the AdoptOpenJDK release `sdk install java 8.0.275.hs-adpt`

**Comment by marc0der** [comment]
It is recommended to use AdoptOpenJDK for Open JDK, as the Java.net releases are more focused on bleeding edge releases and don't give much attention to updating their older builds.

**Comment by LexxFade** [comment]
if you're on arch linux, type `sudo pacman -S jdk8-openjdk`

**Comment by sagarpanchal** [comment]
> if you're on arch linux, type `sudo pacman -S jdk8-openjdk` on your terminal

BTW
