### ISSUE TITLE
Bug: SDKMAN considers Grails 3.3.12 newer than 4.0.6

### ISSUE THREAD

**Issue by 0branch** [sdkman/sdkman-cli#843]
**Bug report**

Versioning issue: SDKMAN considers Grails 3.3.12 newer than 4.0.6:

	$ sdk c grails
	Using grails version 4.0.6

but

	$ sdk ug
	Upgrade:
	grails (4.0.6 < 3.3.12)
	Upgrade candidate(s) and set latest version(s) as default? (Y/n): _

Offering to upgrade to a previous (major) version and set it as the default is the wrong behaviour.

**To reproduce**

Install Grails 4.0.6, then run `sdk ug`.

**System info**

macOS 10.14.6; GNU bash, version 3.2.57(1)-release; SDKMAN 5.9.1+575.

**Comment by marc0der** [comment]
Hi @0branch, this isn't really a bug, but rather a publishing issue by the Grails team. Most vendors are responsible for publishing (and setting the default version) of their own candidates. You should probably take this up with one of their engineers. Perhaps @ilopmar can point you to the right person.

**Comment by ilopmar** [comment]
Yeah, that's a bug on our side. Last week we released both Grails 4.0.6 and 3.3.12 in that order, so 3.3.12 became the "latest" one.
This is something @puneetbehl would be able to fix :)
