### ISSUE TITLE
Issues with compiling kotlin scripts.

### ISSUE THREAD

**Issue by LexxFade** [sdkman/sdkman-cli#848]
Not sure whats causing this; just installed SDKMAN to configure kotlin cli-compiler ([followed these steps](https://kotlinlang.org/docs/tutorials/command-line.html))
```
[Running] cd "/home/lexx/Documents/Code/kotlin/" && kotlinc main.kt -include-runtime -d main.jar && java -jar main.jar
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
main.kt:1:10: warning: parameter 'args' is never used
fun main(args: Array<String>){  
         ^
```
got these errors when I tried to compile a kotlin script using the command: `kotlinc main.kt -include-runtime -d main.jar` on my arch linux system.

**PS: it did compile the kotlin-script, just dunno why its throwing this error before doing that.

**Comment by marc0der** [comment]
Hi @LexxFade, this isn't really a bug with SDKMAN.

Please feel free to ask usage questions in the Kotlin Slack, or if it has to do with the installation of Kotlin via SDKMAN, in our Slack.
