### ISSUE TITLE
Feature: zsh/_sdk isn't left on disk in the install

### ISSUE THREAD

**Issue by xenoterracide** [sdkman/sdkman-cli#852]
been trying to install or use completions via `zinit` but it would appear that this isn't left on disk in anyway during installation if it was in the right location zinit itself might detect it.

```sh
zinit wait lucid as"command" \
  dl"https://get.sdkman.io?rcupdate=false" \
  atclone"zsh get.sdkman.io" \
  atpull"%atclone" \
  src"$SDKMAN_DIR/bin/sdkman-init.sh" \
  atinit"sdk install java" \
  atload"zicompinit" \
  blockf \
  for zdharma/null
```
sdkman actually works here, but the completions aren't installed with `zicompinit` if they were in the stage after install ran, I could simply move them to the right location, because zicompinit runs after atclone and src

**Comment by marc0der** [comment]
Hi @xenoterracide, I'm really not sure what you are asking here. I have no clue how `zinit` works.

If you are asking about where the `sdk` executable lives, then the answer is that it doesn't live anywhere on the file system. `sdk` is actually a top-level function that is sourced into the shell. The same goes for all the helper functions that `sdk` uses to perform its tasks.

**Comment by xenoterracide** [comment]
I'm talking about the zsh completions

**Comment by marc0der** [comment]
I'm still unclear as to what you would like us to do to make this happen. Please feel free to reach out to us on slack where we are more than happy to help.

**Comment by marc0der** [comment]
I just realised what you were referring to, sorry 😄

This file was contributed by someone very long ago and is not maintained at all.

I suggest you use the oh-my-zsh plugin for sdkman, which is maintained and comes bundled with oh-my-zsh.

I'll make a not of removing that file soon.
