### ISSUE TITLE
Bug: [sdk list java don't working]

### ISSUE THREAD

**Issue by Duduxs** [sdkman/sdkman-cli#853]
**Bug report**
When i use this follow command -> sdk list java <- i get an error, all of the others commands seems to work, but this not

**To reproduce**

**System info**

- OS Linux mint and version 20.0 Ulyana
- Shell zsh and version 5.8
- SDKMAN 5.9.2+613

** Screenshot **
[https://ik.imagekit.io/27ewoxssse/image__1__fesREhvVd.png](url)

**Comment by ehv1** [comment]
I have the same issue. Seems like the URL that CURL connects to is down.
Beta channel doesn't seem te function also.
Only the command sdk list java is failing....

Pengwin Linux, WSL2, latest SDKMAN

**Comment by marc0der** [comment]
Thanks for reporting this! This was a problem with some dodgy data in the backend database causing our candidates service to blow up on the Java list view. This has been fixed now and we are locating/fixing the code that inserted the bad data in the first place.

In future, please consider dropping us a note in our Slack where we are able to respond a lot faster.
