### ISSUE TITLE
Bug: Could not uninstall sdkman

### ISSUE THREAD

**Issue by sindhuvahinis** [sdkman/sdkman-cli#854]
**Bug report**
sdkman-uninstall.sh: 19: sdkman-uninstall.sh: Syntax error: "(" unexpected

**To reproduce**
run sdkman-uninstall.sh

**System info**
Linux - Ubuntu

**Comment by marc0der** [comment]
Hi @sindhuvahinis,
Perhaps you have misunderstood what the `sdkman-uninstall.sh` is for. This file contains functions that are used by the `sdk` top-level function for uninstalling candidate versions. Please read the [documentation](https://sdkman.io/install) on our website for uninstalling SDKMAN from your system.
