### ISSUE TITLE
Add CONTRIBUTING section on how to add new candidate versions

### ISSUE THREAD

**Issue by schrepfler** [sdkman/sdkman-cli#855]
It's not quite clear how to add new versions of application candidates, if this is clarified we could potentially get more contributions and have the list updated more frequently.

**Comment by marc0der** [comment]
Hi @schrepfler, you can find all the details in [sdkman-db-migrations](https://github.com/sdkman/sdkman-db-migrations) project. It has an extensive [README.md](https://github.com/sdkman/sdkman-db-migrations/blob/master/README.md) file that explains the entire process.

Please consider chatting to us first on Slack before opening issues here as per the contributor guidelines.

**Comment by schrepfler** [comment]
@marc0der Apologies! I only now saw that there's a separate project/repository that deals with the versionsm, sorry!
