### ISSUE TITLE
Bug: [Classifiers for JDK (trava, adpt) distinction]

### ISSUE THREAD

**Issue by soberich** [sdkman/sdkman-cli#856]
**Bug report**
on `sdk upgrade`

```
Upgrade:
java (11.0.9-trava < 11.0.9.hs-adpt)

Upgrade candidate(s) and set latest version(s) as default? (Y/n): n
```

**To reproduce**

```
sdk install java 11.0.9-trava
sdk upgrade
```

**System info**
```
zsh 5.8 (x86_64-apple-darwin20.1.0)
```

**Comment by soberich** [comment]
Any news here? Thanks in advance.

**Comment by marc0der** [comment]
@soberich I'd say this is a duplicate of #869.

In future, please do consider asking usage questions on Slack before opening a bug report here as stipulated in the [contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/f6ee7927c77f351cbe6765e886099b286a841103/CONTRIBUTING.md). We are always available and ready to help clarify things if anything is unclear, and will then open a feature or bug based on those conversations.

**Comment by marc0der** [comment]
The wording has now been improved so as not to cause further confusion.

**Comment by soberich** [comment]
> In future, please do consider asking usage questions on Slack before opening a bug report
NP, alright, Marko.
