### ISSUE TITLE
Bug: auto env in Bash works only once

### ISSUE THREAD

**Issue by pioorg** [sdkman/sdkman-cli#863]
**Bug report**
It seems that if a directory contains `.sdkmanrc` then in Bash it works only once (to be precise the version is changed once when entering the dir and then reset when leaving it). Subsequent `cd` doesn't set the version as set in `.sdkmanrc`.

**To reproduce**
In Bash `cd` into directory having `.sdkmanrc`, then `cd -`. The changes of e.g. JDK happen as expected.
Then repeat, nothing happens in Bash.

This is different from zsh, zsh changes the JDK every time when 'visited'.

Expected flow in zsh:

```
krypa% cat /tmp/envTest/.sdkmanrc 
# Enable auto-env through the sdkman_auto_env config
# Add key=value pairs of SDKs to use below
java=15.0.2.hs-adpt
krypa% pwd
/tmp
krypa% cd envTest 

Using java version 15.0.2.hs-adpt in this shell.
krypa% cd -
/tmp
Restored java version to 11.0.9.hs-adpt (default)
krypa% cd -
/tmp/envTest

Using java version 15.0.2.hs-adpt in this shell.
krypa% cd -
/tmp
Restored java version to 11.0.9.hs-adpt (default)
```
Perhaps fault flow with Bash?

```
piotr@krypa:/tmp$ cd envTest/

Using java version 15.0.2.hs-adpt in this shell.
piotr@krypa:/tmp/envTest$ cd -
/tmp
Restored java version to 11.0.9.hs-adpt (default)
piotr@krypa:/tmp$ cd -
/tmp/envTest
piotr@krypa:/tmp/envTest$ cd -
/tmp
piotr@krypa:/tmp$
```

**System info**
- Ubuntu 18.04
- Shell and version (`GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu`))
- The output of `sdk version`: `SDKMAN 5.10.0+617`

**Comment by pioorg** [comment]
Hi!
It seems to work if after going to the default version (that is the first `cd -` from the example above) I manually clean the env variable: `unset SDKMAN_OLD_PWD`.

**Comment by helpermethod** [comment]
It's a regression I've introduced when fixing another bug. I'll fix it ASAP.

**Comment by helpermethod** [comment]
Unsetting `SDKMAN_OLD_PWD` was a great pointer, I could fix the bug within minutes. I've also recognized that the `auto env` could be improved, in that the `.sdkmanrc` should not be re-read for folders beneath the folder where the `.sdkmanrc` is located.

**Comment by pioorg** [comment]
Thanks for prompt fix, @helpermethod . I was trying to fix it locally, so even without much luck, I shared the findings. Saves time for maintainers ;-)
