### ISSUE TITLE
Feature: Add a new  command to simplify editing SDKMAN!'s configuration

### ISSUE THREAD

**Issue by helpermethod** [sdkman/sdkman-cli#868]
- [ x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
Changing SDKMAN!'s configuration currently means:

- remembering where the configuration file is located, consulting the online documentation in the worst case
- opening the file in your editor of choice

This feels clunky at best, thus I propose to add an `edit` command which opens the configuration file in the standard editor, or if not configured, falls back to open the file in `vi`.

**Comment by marc0der** [comment]
I love it. I would suggest one final fallback that prints an error message to the likes of:
```
No default editor configured.
You can set the default editor with the EDITOR environment variable.
```
