### ISSUE TITLE
Java version not swapping

### ISSUE THREAD

**Issue by carrollsa** [sdkman/sdkman-cli#877]
Hi all. Currently trying sdkman for the first time. I'm fairly new to programming and am bouncing between projects for some courses on Coursera and some tutorials on YouTube. I've run into a couple of problems with Java versions, so sdkman seemed the best solution. However, it's seeming like it isn't actually swapping the version. I feel like I may be missing something fundamental. I'll paste below what's been happening. I installed Java 8.0.282 and 11.0.10. Typing `sdk use java 8.0.282-open` prompts it to tell me that version is being used. `sdk current` confirms. `java -version` tells me I'm using my 1.8.0_271. Can anyone shed some light on what's going on? Thanks for your help!

`Steph@MSI MINGW64 ~`
`$ sdk use java 8.0.282-open`

`Using java version 8.0.282-open in this shell.`

`Steph@MSI MINGW64 ~`
`$ sdk current`

`No candidates are in use`

`Steph@MSI MINGW64 ~`
`$ java -version`
`java version "1.8.0_271"`
`Java(TM) SE Runtime Environment (build 1.8.0_271-b09)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)`

`Steph@MSI MINGW64 ~`
`$ sdk use java 11.0.10-open`

`Using java version 11.0.10-open in this shell.`

`Steph@MSI MINGW64 ~`
`$ sdk current`

`No candidates are in use`

`java version "1.8.0_271"`
`Java(TM) SE Runtime Environment (build 1.8.0_271-b09)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)`

**Comment by marc0der** [comment]
@carrollsa I just tried replicating this locally, but I do not see the same results.

Could it be that you are using a login shell (as opposed to an interactive shell)? I've seen this sort of thing often happen when login shells are used, as they don't allow on-the-fly changes to shell state, something that we rely heavily on to change environment variable.

**Comment by carrollsa** [comment]
> @carrollsa I just tried replicating this locally, but I do not see the same results.
> 
> Could it be that you are using a login shell (as opposed to an interactive shell)? I've seen this sort of thing often happen when login shells are used, as they don't allow on-the-fly changes to shell state, something that we rely heavily on to change environment variable.

Thanks for the fast response! Using the command `[[ $- == *i* ]] && echo 'Interactive' || echo 'Not interactive'`, it says it is interactive.

**Comment by helpermethod** [comment]
Hi @carrollsa,

which Windows version are you using?

**Comment by carrollsa** [comment]
Hi @helpermethod, 

I am running Windows 10 Version 10.0.19041 Build 19041.

**Comment by helpermethod** [comment]
@carrollsa what is your output when issuing the following command

    ls -l ${SDKMAN_CANDIDATES_DIR}/java

**Comment by carrollsa** [comment]
@helpermethod my output is:

`total 12`
`drwxr-xr-x 1 Steph 197609 0 Jan 11 17:03 11.0.10-open/`
`drwxr-xr-x 1 Steph 197609 0 Jan 11 15:32 8.0.282-open/`
`drwxr-xr-x 1 Steph 197609 0 Feb 22 10:16 current/`

**Comment by mlplace** [comment]
I am using Ubuntu 18 LTS and I just installed SDKman.   Then I installed a verison of java using :  sdk install java 11.0.10.9.1-amzn
tried:  sdk use 11.0.10.9.1-amzn

I get this error message:  Stop! 11.0.10.9.1-amzn is not a valid candidate.
running:
ls -l ${SDKMAN_CANDIDATES_DIR}/java
produces:
drwxr-xr-x 9 mplace mplace 4096 Jan 12 16:25 11.0.10.9.1-amzn
lrwxrwxrwx 1 mplace mplace   16 Mar 12 10:45 current -> 11.0.10.9.1-amzn

 java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

sdk list java  shows I my java install:
Amazon                       |     | 11.0.10.9.1  | amzn    | installed  | 11.0.10.9.1-amzn    

Not sure what is happening?

**Comment by mlplace** [comment]
I had the same issue and just needed to restart the terminal.

**Comment by carrollsa** [comment]
@mlplace @helpermethod @marc0der 

I couldn't tell you why, but sdkman is now working great. In the process of all of this, I restarted multiple times, tried different windows, and nothing was changing. It now works.

The only thing I can think of that may have changed is that my brother, who is a programmer and is far more experienced than I am, was helping me with some other stuff and did some cleaning up of my comp, cache, registry, etc. I don't know enough to know exactly what he did, but everything works now. Thanks for sticking with me on this! Looking forward to putting sdkman to good use.

**Comment by marc0der** [comment]
@carrollsa glad to hear that you got it working :tada: 

If you run into any more issues, please feel free to reach out to us on the [SDKMAN Slack](https://slack.sdkman.io).

**Comment by davelet** [comment]
> I had the same issue and just needed to restart the terminal.

Did as you and fixed. Thx!

**Comment by marstio** [comment]
> I had the same issue and just needed to restart the terminal.

a bit late but this fixed it for git bash but when i run "java - version" in command prompt and vscode it still shows the previous version, not sure what to do
