### ISSUE TITLE
Bug: error: Found argument '-r' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by kaushalyap** [sdkman/sdkman-cli#880]
**Bug report**

I am getting following error when trying to install `Java 15.0.2-open` but installation continues after the error, I have installed 
`Java 11.0.10-open` without any issues

```
❯ sdk install java 15.0.2-open
error: Found argument '-r' which wasn't expected, or isn't valid in this context

USAGE:
    sd [OPTIONS] <find> <replace-with> [files]...

For more information try --help
error: Found argument '-r' which wasn't expected, or isn't valid in this context

USAGE:
    sd [OPTIONS] <find> <replace-with> [files]...

For more information try --help

Downloading: java 15.0.2-open

In progress...

###############   
```
**To reproduce**
 sdk install java 15.0.2-open

**System info**

- OS : Fedora 33, 5.10.19-200.fc33.x86_64  x86_64 x86_64 x86_64 GNU/Linux
- Shell and version : GNU bash, version 5.0.17(1)-release (x86_64-redhat-linux-gnu)
- The output of `sdk version` : SDKMAN 5.11.0+644

**Comment by marc0der** [comment]
Hey @kaushalyap, thanks for reporting.

Not sure why it's complaining about a command called `sd` since we don't use such a command anywhere. Are you sure that you don't have an alias set up for `sed` pointing to `sd` somewhere in your bash profile?

**Comment by kaushalyap** [comment]
@marc0der thanks for quick reply

You are correct I have an alias for `sed` as [sd](https://github.com/chmln/sd). But I am wondering why installing java 8 work without issue but not 15?

**Comment by marc0der** [comment]
Really not sure, but that alias would certainly break things as we make extensive use of `sed`.
