### ISSUE TITLE
Bug: java 16.0.0.hs-adpt < 11.0.10.hs-adpt

### ISSUE THREAD

**Issue by scholnicks** [sdkman/sdkman-cli#892]
11.0.10.hs-adpt is being reported as an upgrade to 16.0.0.hs-adpt

I only have AdoptJDK 16.0.0.hs-adpt installed.
```
~ ❯ sdk list java | grep -i installed
               | >>> | 16.0.0.hs    | adpt    | installed  | 16.0.0.hs-adpt

```

But sdk upgrade java wants me to downgrade to 11.0.10.hs-adpt
```
~ ❯ sdk upgrade java

Upgrade:
java (16.0.0.hs-adpt < 11.0.10.hs-adpt)

Upgrade candidate(s) and set latest version(s) as default? (Y/n): n

```

**Comment by marc0der** [comment]
This is not a bug, just an unfortunate naming choice by the folks who contributed the upgrade feature. We have the notion of a default version, and this version always gets preference over all others. We currently have 11.0.10 set as default for Java. Hope the explanation makes sense.

In future, please fill in the template and consider following the contributor guidelines before opening an issue here.
