### ISSUE TITLE
Bug: `use` command no longer working as expected with zsh

### ISSUE THREAD

**Issue by jdaugherty** [sdkman/sdkman-cli#893]
**Bug report**
With 5.11.1, setting the default for a candidate (i.e. grails) works.  However, if you change the version using 'sdk use', then the candidate can't be found.  I confirmed this on a fresh install with 5.11.1 and on an upgrade.

**To reproduce**
* curl -s https://get.sdkman.io | bash
* open new terminal
* sdk install grails 4.0.9
* which grails <-- the default will succeed / grails can be found until sdk use is called
* sdk use grails 4.0.9
* which grails <-- this will fail

**System info**
* Mac OS Catalina, latest patches
* zsh - zsh 5.7.1 (x86_64-apple-darwin19.0)
* ohmyzsh shell customization with plugins = (git screen mvn jira github gitfast git-flow docker docker-compose kubectl)
* sdk version => SDKMAN 5.11.1+690

**Comment by marc0der** [comment]
@jdaugherty thank you for reporting this. One question I have, are you using the new auto-completion that shipped with SDKMAN recently?

**Comment by helpermethod** [comment]
Hey @marc0der that sounds related to the changes I've made to remove some platform-specific code. Because the tests seem to work, I suppose the bug is zsh-specific.

**Comment by jdaugherty** [comment]
@marc0der  I have not setup auto-completion, so unless ohmyzsh does (it does for some applications), it's not enabled.

**Comment by jdaugherty** [comment]
Thanks @helpermethod 

I discovered if I use `setopt BASH_REMATCH` in my zshrc or if I change sdkman-use.sh to set it local for that function `    setopt local_options BASH_REMATCH` then it works.  

Looks like https://github.com/sdkman/sdkman-cli/commit/7547946d94fcb9dc4221e2f8bc088082beba884a is the commit that causes this problem - BASH_REMATCH doesn't work in zsh without these emulation options.

**Comment by marc0der** [comment]
@helpermethod would you be comfortable reverting those changes? I'd revert the commit, but it seems like there is a bit more going on here.

**Comment by helpermethod** [comment]
I've used BASH_REMATCH in two critical code places. Reverting those changes will break the tests again :/. Easiest fix would be to check for shell type and use BASH_REMATCH[1] for Bash and match[1].

(I'm currently not near my Laptop :/).

**Comment by rgoldberg** [comment]
I already have removed all platform specific-code in my repo based on the old `master` (and it also fixes many other issues), and passed all tests in both bash & zsh.

**Comment by dcheung2** [comment]
Same here.

The latest version messed up the path
new shell
`$HOME/.sdkman/candidates/maven/current/bin`

after `sdk use` or `sdk env`
`$HOME/.sdkman/candidates/maven/3.8.1current/bin` (actual)

`$HOME/.sdkman/candidates/maven/3.8.1/bin` (expected)

**Comment by dcheung2** [comment]
working patch (for me)

I patch the file `~/.sdkman/src/sdkman-use.sh`

add `setopt local_options BASH_REMATCH` on line 21 
and change `BASH_REMATCH[1]` to `BASH_REMATCH[2]` on line 41,

**Comment by marc0der** [comment]
I've now rolled back to 5.11.0. Performing an `sdk selfupdate force` will bring you back to the earlier version if you are on the stable channel. We will release a fix in version `5.11.2` when @helpermethod is back in circulation.

The beta channel will continue to have the bug, for now, so feel free to use whatever workaround works if you are a beta user.
