### ISSUE TITLE
Feature: Add the new Microsoft JDK distribution

### ISSUE THREAD

**Issue by micrump** [sdkman/sdkman-cli#896]
- [ x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**

Microsoft moves away Azul Zulu as the Azure JDK because the contract with Azul expires on the 30th of June 2021.
Instead they decided to package their own OpenJDK distribution as announced here: https://devblogs.microsoft.com/java/announcing-preview-of-microsoft-build-of-openjdk/#frequently-asked-questions

The packages can be found here: https://www.microsoft.com/openjdk

**Comment by marc0der** [comment]
These were already supported shortly after their release. Running `sdk ls java` will show you all available options.

Please do follow the contributing guidelines before opening an issue here.
