### ISSUE TITLE
Bug: `sdk env install` does not also set the current shell versions

### ISSUE THREAD

**Issue by joehorsnell** [sdkman/sdkman-cli#905]
**Bug report**
The very useful `sdk env install` command added in #839 does not also set the versions in your shell (ie do an `sdk env`). Looking in the code for the [`env` command](https://github.com/sdkman/sdkman-cli/blob/afccde0db167c7661f8177e9aa57619f13598de4/src/main/bash/sdkman-env.sh#L26) confirms this.

I was initially confused by this - having run `sdk env install`, I assumed that I would have the installed versions set in my shell. Do you consider this a bug and if so, would you accept a fix to make `__sdkman_setup_env` also call `__sdkman_load_env`?

Edit: see discussion below - this behaviour might be better controlled through a command-line agument?

**To reproduce**
```
$ echo 'gradle=7.0' > .sdkmanrc
$ sdk env install
$ gradle --version
```

**System info**
- macOS 10.15.7
- zsh 5.8 (x86_64-apple-darwin19.6.0)
- SDKMAN 5.11.0+644

**Comment by helpermethod** [comment]
Hi @joehorsnell!

This was done on purpose, so that each command invocation does a single thing. Now, when thinking about it, I probably never use `sdk env install` without intending to use the installed SDKs after that, so you may have a point 😄 .

@marc0der What do you think about it?

**Comment by joehorsnell** [comment]
> Hi @joehorsnell!
> 
> This was done on purpose, so that each command invocation does a single thing. Now, when thinking about it, I probably never use `sdk env install` without intending to use the installed SDKs after that, so you may have a point 😄 .
> 
> @marc0der What do you think about it?

Hi @helpermethod - thanks for the quick response.

Yep, _personally_ I think you invariably would want to also _use_ the versions you've just installed, at least when running interactively. Perhaps for offline installation you'd either not care, or prefer to have the versions not set.

Maybe allowing the behaviour to be controlled via a command line arg, either `--set-versions` (current behaviour, opt-in to setting versions as well), or `--no-set-versions` (set versions by default, but opt-in in to current behaviour)?

Then the question is just, what should the default be - current behaviour with opt-in, or vice versa?

**Comment by marc0der** [comment]
I totally agree with this. It makes perfect sense to install and set the versions in one go.

@joehorsnell, we have adopted a command style syntax, so you will notice that we don't have any `--` arguments/switches in SDKMAN, but we could have it as config in `~/.sdkman/etc/config` instead. However, IMO I don't think this is even necessary.

**Comment by joehorsnell** [comment]
I took the liberty of opening a PR to try and fix this. I _think_ it's pretty straightforward, not sure if any other specs rely on the existing behaviour. I'll see what CI says!
