### ISSUE TITLE
Add missing bash completions

### ISSUE THREAD

**Issue by liviu-vasut** [sdkman/sdkman-cli#909]
**Feature request**
I'd like to add a few more completions for bash. The change is very small and I have the code ready for a PR.

**Comment by helpermethod** [comment]
Hi @liviu-vasut,

the Bash Completion is indeed missing a few completions, I'll have a look at your PR later.

**Comment by helpermethod** [comment]
The additional completions look great! Thank you for your contribution!

**Comment by liviu-vasut** [comment]
Glad I could help! Thanks for your time.
