### ISSUE TITLE
Feature: Print fully-qualified path for current (or specific version) of a candidate

### ISSUE THREAD

**Issue by KlausUnger** [sdkman/sdkman-cli#917]
**Feature request**

Sometimes it is necessary to provide the file system paths for a specific candidate version in some development tools!

E.g. If one want to use a newer maven version in Intellij then the bundled one, one needs to point to the location

** Suggested syntax** 

sdk path maven ... prints the fully qualified path name of maven/current
sdk path maven 3.6.3 ... prints the fully qualified path name of maven version 3.6.3

We need sdk a lot in teaching and most commonly students have troubles to access hidden folders on lab equipment!

**Comment by helpermethod** [comment]
Hi @KlausUnger!

This is already possible with the home subcommand, e.g.

    sdk home maven 3.8.1

**Comment by KlausUnger** [comment]
Thanks for the hint - sorry for the noise
