### ISSUE TITLE
Add Support For Spring Cloud Cli

### ISSUE THREAD

**Issue by ankurpathak** [sdkman/sdkman-cli#918]
Sdkman supports Spring Boot Cli.
Please add support for Spring Cloud Cli. 
https://docs.spring.io/spring-cloud-cli/docs/current/reference/html/

**Comment by helpermethod** [comment]
Hi @ankurpathak! Spring Boot CLI is already supported

    sdk install springboot 2.2.3.RELEASE

or

    sdk install springboot

**Comment by ankurpathak** [comment]
@helpermethod I knew Sdk Man Supports Spring Boot Cli. But I have raised ticked to support Spring Cloud Cli.

**Comment by helpermethod** [comment]
Had a quick look at the installation instructions and it seems the Spring Cloud CLI is just a plugin for the Spring Boot CLI. 

So from my point of view it doesn't make much sense to offer this as an additional candidate, as installing the Cloud CLI is already taken care of the Spring Boot CLI.

/cc @marc0der

**Comment by marc0der** [comment]
Based on @helpermethod's feedback and further inactivity, I'm closing this issue.
