### ISSUE TITLE
Bug: command not found: compdef

### ISSUE THREAD

**Issue by chrisseaton** [sdkman/sdkman-cli#922]
**Bug report**

Every time I open my terminal I see

```
/Users/chrisseaton/.sdkman/contrib/completion/zsh/sdk:58: command not found: compdef
```

**To reproduce**

Open my terminal.

**System info**

macOS 11.4

```
% zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)

% sdk version  

SDKMAN 5.11.5+713
```

**Comment by marc0der** [comment]
If you aren't using a framework like oh-my-zsh or similar, you probably need to set the following in your ZSH profile:

```
autoload -Uz compinit
compinit
```

Alternatively, you can set `sdkman_auto_complete` to `false` in the SDKMAN config file to turn auto-completion off all together.

**Comment by chrisseaton** [comment]
> If you aren't using a framework like oh-my-zsh or similar

Thanks - was I supposed to install that as part of installation? I didn't see anything saying that.

**Comment by chrisseaton** [comment]
> Alternatively, you can set `sdkman_auto_complete` to `false`

Thanks that worked around the issue - I'll do this. Should this be the default then?

**Comment by marc0der** [comment]
The use of something like oh-my-zsh makes ZSH far more useful to the user. I would highly recommend trying it.

I'd suggest _not_ turning the auto-completion off as this feature greatly helps you use SDKMAN.

**Comment by marc0der** [comment]
I'm actually thinking of adding the above few lines to the header of the zsh completion script. I'll release that soon.

**Comment by chrisseaton** [comment]
Thanks for doing that! But I get this now

```
Last login: Tue Jun 22 03:34:43 on ttys002
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? ncompinit: initialization aborted
/Users/chrisseaton/.sdkman/contrib/completion/zsh/sdk:58: command not found: compdef
% sdk version

SDKMAN 5.11.6
```

**Comment by marc0der** [comment]
Hi @chrisseaton, I'm not sure what the interaction with your system is. I just installed it on a vanilla alpine docker environment with ZSH, and it works perfectly. Here is how I tested it:

```
$ docker run -it --rm alpine:latest /bin/sh
# apk add zsh curl zip unzip
# zsh
# curl -s https://get.sdkman.io | zsh
# sdk list [tab]
```
This works perfectly with the auto-completion enabled by default. If your problem persists, feel free to drop in at the user-issues channel on our SDKMAN Slack to help you get it sorted.

**Comment by mmjmanders** [comment]
> Thanks for doing that! But I get this now
> 
> ```
> Last login: Tue Jun 22 03:34:43 on ttys002
> zsh compinit: insecure directories, run compaudit for list.
> Ignore insecure directories and continue [y] or abort compinit [n]? ncompinit: initialization aborted
> /Users/chrisseaton/.sdkman/contrib/completion/zsh/sdk:58: command not found: compdef
> % sdk version
> 
> SDKMAN 5.11.6
> ```

I have the same issues after the latest sdk update

**Comment by chrisseaton** [comment]
I've tried this this morning on a new clean macOS install - it's not a personal setup issue.

I think `compinit` is now right - it's just being aborted by the directory permissions.

```
% compaudit
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/share/zsh
```

**Comment by chrisseaton** [comment]
Fixed with

```
% compaudit | xargs chmod g-w,o-w
```

But I don't really know how these files got the wrong permissions.

**Comment by marc0der** [comment]
The `/usr/local` directory is a shared directory. Could it be that zsh was installed as the root user?

Also, was this the default version of zsh that was installed as part of OSX?

**Comment by chrisseaton** [comment]
I think possible Homebrew creates these directories for its autocomplete, and sets the wrong permissions.

So probably not your issue to fix.

**Comment by marc0der** [comment]
If you are happy with this resolution, please feel free to close this issue.
