### ISSUE TITLE
syntax error near unexpected token '<'

### ISSUE THREAD

**Issue by ssiwek-dxc** [sdkman/sdkman-cli#923]
Executing command "source /root/.sdkman/bin/sdkman-init.sh" fails with:

source /root/.sdkman/contrib/completion/bash/sdk
/root/.sdkman/contrib/completion/bash/sdk: line 37: syntax error near unexpected token `<'
/root/.sdkman/contrib/completion/bash/sdk: line 37: `			done < <(curl --silent "${SDKMAN_CANDIDATES_API}/candidates/all")'

I believe that it's caused by using old bash (from centos-7) which don't support process substitution:

$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

I encountered this bug in sdkman-5.11.5+713. I believe that previous versions were OK.

**Comment by ssiwek-dxc** [comment]
I think that such commit could fix this issue https://github.com/ssiwek-dxc/sdkman-cli/commit/136d19a9bf5790ee32a6871a7019537b895f3ab0

Not tested.

**Comment by marc0der** [comment]
You can stop this from occurring by disabling the auto-completion.
Set `sdkman_auto_complete=false` in the _.sdkman/etc/config_ file.

**Comment by ssiwek-dxc** [comment]
Yeah, I thought about such thing - but truncating completion script was my first idea

**Comment by jjkoehorst** [comment]
Luckily it is only a single line that needs to be added to the docker build file

    RUN echo "sdkman_auto_complete=false" >> "$HOME/.sdkman/etc/config"

**Comment by marc0der** [comment]
It's an acceptable workaround, but maybe @helpermethod could come up with a solution for this that also works with older versions of `bash` and `sh`.

**Comment by helpermethod** [comment]
@marc0der Will have a look at it!

**Comment by pavan-onkar-exa** [comment]
Wow even I noticed it.
@jjkoehorst Your solution worked smoothly for me !!

**Comment by helpermethod** [comment]
Hi @ssiwek-dxc, your proposal looks good to me. Would you like to submit this as a PR?

**Comment by kenyee** [comment]
Bit me too :-(
Any idea when the PR will be merged?  Looks like it's failing CI though...
Wondering if I should add the workaround...

**Comment by kenyee** [comment]
Also, is there a way to version lock SDK man installs?
This broke on our CI...never expected installing SDK man would fail because we have Centos7 images...

**Comment by marc0der** [comment]
@ssiwek-dxc if you can rebase against master and get your build green I'd be happy to merge it asap.

@kenyee some others have asked the same so we can certainly look at this.

**Comment by ssiwek-dxc** [comment]
I rebased yesterday, build were not green.
I gonna check this.

**Comment by ssiwek-dxc** [comment]
@marc0der - seems build fails on your change in bin/release-binary.sh ( 'return' -> 'exit').

**Comment by edgarmariorivera** [comment]
Hi all, this still happening, can anybody please make sure this BUG is fixed, so I can install SDK following the instructions? Any work around?
