### ISSUE TITLE
Can't remove sdk from zsh

### ISSUE THREAD

**Issue by rcarrillodev** [sdkman/sdkman-cli#929]
Hi!
I updated my mac to BigSur and the OS messed the jdk path, so I tried to reinstall jdk using sdk command. But I'm getting the following message:

`zsh: permission denied: sdk`

Then I removed .sdkman directory and all the snippets for sdkman in the following files: 

- .bashrc
- .bash_profile 
- .profile
- .zshrc

But I'm still getting this error, even reinstalling sdk.

**Comment by marc0der** [comment]
Please feel free to ask usage questions on the user-issues channel on the SDKMAN Slack as per the contributing guidelines.
