### ISSUE TITLE
Bug: Lazybones is no longer available

### ISSUE THREAD

**Issue by jest** [sdkman/sdkman-cli#936]
**Bug report**

Lazybones is no longer possible to install. It is also not possible to use an already installed one.

**To reproduce**

```
$ sdk ls lazybones

Stop! lazybones is not a valid candidate.

$ sdk install lazybones

Stop! lazybones is not a valid candidate.

$ ls ~/.sdkman/candidates/lazybones/

0.8.3  current

$ ~/.sdkman/candidates/lazybones/current/bin/lazybones

Lazybones is a command-line based tool for creating basic software projects from templates.
...                                                                              
```

**System info**

SDKMAN 5.11.6 on Linux

**Comment by marc0der** [comment]
Hi @jest, please follow the contributing guidelines before opening a bug report here. This is not a bug. Please chat to us on Slack first.

**Comment by jest** [comment]
@marc0der Well, I consider disappearing programs to be a bug of software manager.

Can you please point me to a commit or some announcement to watch for? I can find no mention in sdkman repos (GitHub search) or on a webpage on such a change.

I'm sorry, I will not create another Slack account just to ask a useless question - if it's not a bug then I see no prospect of a corresponding change in SDKMan and I just have to use other means to obtain lazybones.

Thank you for the otherwise great product, anyway!
