### ISSUE TITLE
Feature: Skip security check of the Zsh completion system like OMZ does

### ISSUE THREAD

**Issue by borrible13th** [sdkman/sdkman-cli#938]
- [x ] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
In a multiuser environment, e.g. macOS Big Sur, Zsh's security check by `compinit` warns about insecure directories and files. As a current user, you are often not either root or the owner of these directories and files. No chance to silence the warning and to use all insecure files and directories without asking.

Please introduce a variable to disable the security check by calling `compinit -u -C` instead. For example Oh-My-Zsh uses `ZSH_DISABLE_COMPFIX="true"`.

**Comment by marc0der** [comment]
Hi @borrible13th, feel free to raise a PR to disable this check. I'd be happy to merge it.

**Comment by rcousens** [comment]
In reference to this: https://zsh.sourceforge.io/Doc/Release/Completion-System.html

Are you okay with compinit being launched with -C by default (to skip the security checks) or do you want it controlled by a variable?

I went in and modified sdkman-init.sh to "compinit -C" for zsh to get rid of the annoying prompts.

**Comment by danieldietrich** [comment]
+1 `compinit -C`

**Comment by marc0der** [comment]
As before, the onus is on you. I'll happily accept a PR for this @danieldietrich @rcousens.

**Comment by danieldietrich** [comment]
@marc0der 

> I'll happily accept a PR for this @danieldietrich

Thanks! PR ready for review

**Comment by marc0der** [comment]
This has been deployed to stable so closing the issue. Thanks again for contributing!
