### ISSUE TITLE
Bug: "You already have SDKMAN installed" when installing into an empty directory

### ISSUE THREAD

**Issue by t9t** [sdkman/sdkman-cli#940]
**Bug report**
SDKMAN! does not install into an existing but empty directory.

I was trying to install SDKMAN! into `/opt` to not pollute my homedir. My user account does not have access to create anything in `/opt` so I first created a directory, gave myself access, and then tried to install SDKMAN!. That failed with the error message "You already have SDKMAN installed".

For the bug all that matters is that when the installation directory exists (but is empty), SDKMAN! fails to install.

**To reproduce**

```
$ mkdir -p sdkmantest
$ export SDKMAN_DIR="$(pwd)/sdkmantest"
$ curl -s "https://get.sdkman.io" | bash

(...)
                                                                 Now attempting installation...


Looking for a previous installation of SDKMAN...
SDKMAN found.

======================================================================================================
 You already have SDKMAN installed.
 SDKMAN was found at:

    /home/you/sdkmantest
```

**System info**

- Windows 10 + WSL2
- `zsh 5.8 (x86_64-ubuntu-linux-gnu)`
- `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`

**Comment by t9t** [comment]
On [the installation page](https://sdkman.io/install) it says:

> For this to work it is vital that your user has full access rights to this folder.It is also important that the folder does not exist as SDKMAN! will attempt to create it. 

This seems like a contradiction to me: that a user should have full access rights to a folder that does not exist. What is meant probably is that the user has the rights to create folders in the parent directory for the `SDKMAN_DIR`.

I would opt that the installer checks the directory and if it exists but is empty, it will treat it as a valid installation directory.

**Comment by marc0der** [comment]
Hi @t9t, this really isn't a bug and wasn't discussed on the user-issues channel on slack as per the contributing guidelines. Feel free to drop in there to ask any such questions.

**Comment by t9t** [comment]
Thank you very much for taking the time to look at the issue @marc0der.

I see that the "Feature" Github issue template has a note about reading the contribution guidelines, but the "Bug" template does not. So it might be a good idea to add a similar remark to that template as well, to reduce the risk of ignorant people opening an issue on Github when encountering a bug (I don't want to join a Slack group, which is why I chose to point it out here rather than there).

Apologies for opening a bug report issue for something that you don't consider to be a bug.

**Comment by marc0der** [comment]
Apologies mine, I'll make sure the template is updated. But seriously, please hop onto slack. We'd love to help you get the problem solved, and if necessary improve the functionality.

**Comment by David00154** [comment]
$ export SDKMAN_DIR="$(pwd)/sdkmantest"
$ curl -s "https://get.sdkman.io" | zsh
