### ISSUE TITLE
Feature: use variable $HOME in bashrc or zshrc files

### ISSUE THREAD

**Issue by acsdev** [sdkman/sdkman-cli#943]
Hello everyone, 

First, I would like to say that SDKMAN is awesome.

Here is just a small idea.

When a finish SDKMAN installation I get this in my .zshrc file.

> export SDKMAN_DIR="/home/<MY_USER>/.sdkman"
> [[ -s "/home/<MY_USER>/.sdkman/bin/sdkman-init.sh" ]] && source "/home/<MY_USER>/.sdkman/bin/sdkman-init.sh"

But, my .zshrc file is shared between computers. So, I always have manually change the code for this:

> export SDKMAN_DIR="$HOME/.sdkman"
> [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

Would be nice, if the value were added like the example above, after each update.

Best regards,
Allan Santos

**Comment by marc0der** [comment]
@acsdev I merged the change but unfortunately it broke installation completely so I had to roll back.
To test, I took the following steps. You might try the same before submitting a subsequent PR:

```
$ docker run --rm -it ubuntu:latest /bin/bash
# apt update && apt install -y curl zip unzip vim
# curl -s https://get.sdkman.io > /tmp/install.sh
# chmod +x /tmp/install.sh
# vim /tmp/install.sh (make your edits here)
# . /tmp/install.sh
# source /root/.sdkman/bin/sdkman-init.sh
# sdk
```

I found that it was not longer installing under the `/root` folder as it should.
If you get it working, I'd be happy to give it another try.

**Comment by acsdev** [comment]
Hi @marc0der 

I did it after the installation process. 

if you include that change as a last step after the installation is done, maybe it will be simpler.

**Comment by AzimMuradov** [comment]
> @acsdev I merged the change but unfortunately it broke installation completely so I had to roll back.
> To test, I took the following steps. You might try the same before submitting a subsequent PR:
> 
> ```
> $ docker run --rm -it ubuntu:latest /bin/bash
> # apt update && apt install -y curl zip unzip vim
> # curl -s https://get.sdkman.io > /tmp/install.sh
> # chmod +x /tmp/install.sh
> # vim /tmp/install.sh (make your edits here)
> # . /tmp/install.sh
> # source /root/.sdkman/bin/sdkman-init.sh
> # sdk
> ```
> 
> I found that it was not longer installing under the `/root` folder as it should.
> If you get it working, I'd be happy to give it another try.

I tested [the new pr](https://github.com/sdkman/sdkman-hooks/pull/33), it is working :smiley:

**Comment by AzimMuradov** [comment]
I think this is can be closed now.
