### ISSUE TITLE
Bug: [sdkman-init.sh interferes/breaks gcp cloud/kubectl zsh completions]

### ISSUE THREAD

**Issue by andrewrembrandt** [sdkman/sdkman-cli#947]
**Bug report**
When using gcloud sdk & kubectl zsh completions, the sdkman-init.sh appears to remove or break those completions (i.e. they fail to work).
(also using the ohmyzsh sdkman & kubectl plugins)

Moving the sdkman-init.sh call to before the gcloud sdk & kubectl completion ensures completions for all works correctly.

**To reproduce**
Place the following in .zshrc:
```
<snip - ohmyzsh defaults>
plugins=(
  git
  ripgrep
  vi-mode
  zsh-sdkman
  kubectl
)
</snip>

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/******/share/gcloud/path.zsh.inc' ]; then . '/home/*******/share/gcloud/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/******/share/gcloud/completion.zsh.inc' ]; then . '/home/******/share/gcloud/completion.zsh.inc'; fi

# Completions for kubectl
(( $+commands[kubectl] )) && source <(kubectl completion zsh)


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="/home/*******/.sdkman"
[[ -s "/home/********/.sdkman/bin/sdkman-init.sh" ]] && source "/home/*******/.sdkman/bin/sdkman-init.sh"
```

**System info**
- Arch Linux (kernel 5.13.6)
- zsh 5.8.1
- zsh-completions 0.33.0-1
- oh-my-zsh r6081.5377cc37c-1
- gcloud sdk 349.0.0
- kubectl 1.18.18

**Comment by marc0der** [comment]
Hi @andrewrembrandt, the ZSH completion for sdkman is obsolete as we are now providing our own completion out of the box. Would you mind giving it a try without the SDKMAN ohmyzsh plugin?

BTW, I have the exact same setup as you and experience no problems.

**Comment by andrewrembrandt** [comment]
Hi @marc0der (Many thanks for the quick reply!)

I removed the sdkman ohmyzsh plugin and still find that the gcp / kubectl completions are broken sadly

**Comment by marc0der** [comment]
Here's another thing you could try: Set your sdkman configuration to disable auto-completion by running `sdk config` and setting `sdkman_auto_complete=false`. Then try to re-enable the oh-my-zsh sdkman plugin and see what happens. Also, try having a play with the order of the oh-my-zsh plugins.

Incidentally, the oh-my-zsh sdkman completion is quite old and out of date.

**Comment by andrewrembrandt** [comment]
Hi @marc0der , many thanks for the reminder - just found the cause & a fix.

It seems that the call to `compinit` (https://github.com/sdkman/sdkman-cli/blob/master/src/main/bash/sdkman-init.sh#L182) causes the gcloud sdk completions to disappear for me (or perhaps what ever the immediately previous loaded completions are).
I noticed that the gcloud sdk checks if compinit has already been called first (which is quite likely), so applied the same fix, which resolves the issue:
```Shell
    if ! (( $+functions[compdef] )) ; then
      autoload -Uz compinit
      compinit
    fi
```

**Comment by marc0der** [comment]
Great to hear you got it working! What I understand from this is that we need to add this check to our ZSH completion script. Is that right?

If so, would you be willing to raise a PR for this fix so that all our users can benefit?

**Comment by andrewrembrandt** [comment]
Hi @marc0der, sure thing, just created the PR above - feel free to ask for additions etc

(By the way, many thanks for a great project - big time saver for many developers!)
