### ISSUE TITLE
Bug: AdoptOpenJDK's new release is now being released on different site

### ISSUE THREAD

**Issue by ntopia** [sdkman/sdkman-cli#948]
**Bug report**
When you go into https://adoptopenjdk.net/, you can see their message in the header like this,

> 24th July 2021: AdoptOpenJDK is moving to the Eclipse Foundation and rebranding.
> Our July 2021 and future releases will come from Adoptium.net

So, they stopped publishing new releases on https://adoptopenjdk.net/, and instead they started to publish their new releases on https://adoptium.net/.  They released jdk-11.0.12+7 now.

Could you apply some patch to your product?

**To reproduce**
Type `sdk list java`, and you can see that `11.0.11.xx` version for AdoptOpenJDK.

**System info**
N/A

**Comment by ntopia** [comment]
Oh, I missed "Temurin" section in the below of the result `sdk list java`.  Sorry about that.

**Comment by ntopia** [comment]
Are they really identical, or different?

**Comment by marc0der** [comment]
Hi @ntopia. This is not a bug. Please follow the contributing guidelines before opening an issue here. We can answer any questions you might have on Slack.
