### ISSUE TITLE
Bug: Missing successor of AdoptOpenJDK OpenJ9, IBM Semeru

### ISSUE THREAD

**Issue by bmarwell** [sdkman/sdkman-cli#949]
**Bug report**

Related to https://github.com/sdkman/sdkman-cli/issues/948: 

AdoptOpenJDK's build of Eclipse OpenJ9 is now released as IBM Semeru, available from IBM and from the Adoptium Marketplace.

**To reproduce**

sdk list java only shows temurin, but not semeru.

**System info**
any

** Links **

* https://twitter.com/mstoodle/status/1422569283306020874?s=20
* https://developer.ibm.com/blogs/introducing-the-ibm-semeru-runtimes/

**Comment by marc0der** [comment]
Please follow the contributing guidelines before opening a bug.
