### ISSUE TITLE
Feature: Missing successor of AdoptOpenJDK OpenJ9, IBM Semeru

### ISSUE THREAD

**Issue by bmarwell** [sdkman/sdkman-cli#950]
- [X] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**

AdoptOpenJDK's build of Eclipse OpenJ9 is now released as IBM Semeru, available from IBM and from the Adoptium Marketplace.

Please include the same way that Eclipse Tamurin is included.

**Comment by marc0der** [comment]
Thanks to @eddumelendez, this happened today!
