### ISSUE TITLE
Unknown option: [:lower:]

### ISSUE THREAD

**Issue by OrionRandD** [sdkman/sdkman-cli#951]
I get this errors after installing sdk

source ~/.sdkman/bin/sdkman-init.sh
 
Then I get this:

sdk version 
Unknown option: [:lower:]
Unknown option: -
Unknown option: _
__sdk_: command not found

my .bashrc

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/vagner/.sdkman"
[[ -s "/home/user/.sdkman/bin/sdkman-init.sh" ]] && source "/home/user/.sdkman/bin/sdkman-init.sh"

**Comment by helpermethod** [comment]
Hi @OrionRandD,

which Bash version are you using? Which OS?

**Comment by marc0der** [comment]
Hi @OrionRandD, please use the provided template and follow the contributing guidelines before opening an issue here.

**Comment by OrionRandD** [comment]
> Hi @OrionRandD,
> 
> which Bash version are you using? Which OS?

GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
GNU/Debian

But, I already installed kotlin language without sdk
Thx.

**Comment by marc0der** [comment]
Hi @OrionRandD, you would need to give us more details as per the template. For instance, I see that you are running Debian unstable as this is the only one that has bash 5.1.8.

I just tried the following in a clean environment and I can't replicate this:

```
$ docker run -it --rm debian:unstable /bin/bash
# bash --version
GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

# apt update && apt install -y curl zip unzip
# curl -s https://get.sdkman.io | bash
# source /root/.sdkman/bin/sdkman-init.sh
# sdk version
SDKMAN 5.12.2
```

It makes me think you have something else going on in your environment. Feel free to chat with us on Slack where we can help you resolve your problem in the user-issues channel.

**Comment by OrionRandD** [comment]
> Hi @OrionRandD, you would need to give us more details as per the template. For instance, I see that you are running Debian unstable as this is the only one that has bash 5.1.8.
> 
> I just tried the following in a clean environment and I can't replicate your issue:
> 
> ```
> $ docker run -it --rm debian:unstable /bin/bash
> # bash --version
> GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
> Copyright (C) 2020 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> 
> # apt update && apt install -y curl zip unzip
> # curl -s https://get.sdkman.io | bash
> # source /root/.sdkman/bin/sdkman-init.sh
> # sdk version
> SDKMAN 5.12.2
> ```
> 
> It makes me think you have something else going on in your environment. Feel free to chat with us on Slack where we can help you resolve your problem in the user-issues channel.

My OS is Siduction and I use st - simple/suckless terminal
https://siduction.org/
https://st.suckless.org/
