### ISSUE TITLE
Bug: [Groovy binary not available after installation]

### ISSUE THREAD

**Issue by emptylambda** [sdkman/sdkman-cli#961]
**Bug report**
groovy binary not available after installation

**To reproduce**
> sdk install groovy 3.0.8
result in successful install and default to this groovy version

➜  ~ ls .sdkman/candidates/groovy/3.0.8/bin 
grape             groovyc             groovyConsole.bat         groovy.ico           java2groovy.bat
grape.bat         groovyc.bat         groovyConsole_completion  groovysh             startGroovy
grape_completion  groovyc_completion  groovydoc                 groovysh.bat         startGroovy.bat
groovy            groovy_completion   groovydoc.bat             groovysh_completion
groovy.bat        groovyConsole       groovydoc_completion      java2groovy
➜  ~ .sdkman/candidates/groovy/3.0.8/bin/groovy -version 
Groovy Version: 3.0.8 JVM: 16.0.2 Vendor: Microsoft OS: Linux
➜  ~ which groovy                                        
groovy not found
➜  ~ 

**System info**

- Ubuntu 20.04
- zsh 5.8
- sdk version 
sdk version 
sdkman_auto_answer=false
sdkman_selfupdate_enable=true
sdkman_insecure_ssl=false
sdkman_curl_connect_timeout=7
sdkman_curl_max_time=10
sdkman_beta_channel=false
sdkman_debug_mode=false
sdkman_colour_enable=true
sdkman_auto_env=false
sdkman_rosetta2_compatible=true
sdkman_auto_complete=true

SDKMAN 5.12.3

**Comment by marc0der** [comment]
@emptylambda I think this is an issue on your system. I've just run the following on a fresh Ubuntu Docker container without any issues:

```
$ docker run -it --rm ubuntu:latest /bin/bash
# apt update && apt install -y curl zip
# curl -s https://get.sdkman.io | bash
# source /root/.sdkman/bin/sdkman-init.sh
# sdk install groovy
# which groovy
/root/.sdkman/candidates/groovy/current/bin/groovy
```

Please feel free to contact us on Slack, where we can help you with such usage issues.
