### ISSUE TITLE
Feature: Using a wildcard approach to install major versions

### ISSUE THREAD

**Issue by franceme** [sdkman/sdkman-cli#967]
As a Java developer user, I would like to be able to install the latest Java JDK Version 7 from a specific vendor and am not worried about the minor version.

I create Java Jupyter Notebooks for Java code samples using MyBinder and Docker images.
Since the Docker image is created on the fly from the supplied Dockerfile, I need to specify the specific JDK version during installation.
Since the vendors deprecate the older JDK minor versions hard-coding the minor versions will break the build.

I have created a [workaround](https://github.com/franceme/Esorics_Conference/blob/1cc0172909fadc475a1d52871f2c61d383799aaf/Makefile#L8) but I would like to see if there can be some kind of wildcard approach to supporting this.
This could work similarly to `sdk install java 7*zulu`.

**Comment by marc0der** [comment]
We are in the planning phases of doing this and will be picking this up soon.

This has already been requested several times before (see #776 ) so we realise this is a priority feature.

**Comment by gkfirst8** [comment]
Any news/update on this, please?
