### ISSUE TITLE
`selfupdate` does not update current gvm version

### ISSUE THREAD

**Issue by pledbrook** [sdkman/sdkman-cli#97]
I noticed when upgrading from 0.9.1 to 0.9.2 that the upgrade broadcast message continues to be displayed. It seems that `gvm` uses the `GVM_VERSION` environment variable to determine what the current version is, but this doesn't get updated until the `gvm-init.sh` script is sourced.

What's the value in exporting the `GVM_VERSION`? I also wonder what the value of exporting `GVM_SERVICE` is. The problem is that both persist with old values in the current shell, causing odd behaviour.

I recommend not exporting them and perhaps including them in the `gvm()` function instead.

**Comment by marc0der** [comment]
This was all taken care of during the refractor last year. Variable scoping was introduced using local variables, and only the most essential variables are exposed in the shell.

Closing this issue.

**Comment by marc0der** [comment]
Sorry, accidentally closed this one.

Can you confirm that this is no longer an issue so we can close it?
