### ISSUE TITLE
Bug: sdkman download candidate tomcat

### ISSUE THREAD

**Issue by tonycody** [sdkman/sdkman-cli#974]
![image](https://user-images.githubusercontent.com/6773121/133542988-13d1f5f7-c0bc-4f19-8ae5-d4f728d42b4c.png)
![image](https://user-images.githubusercontent.com/6773121/133543013-55044dd8-f848-456e-b69d-eaa9b407a286.png)
You have to change your permissions yourself

**Comment by marc0der** [comment]
Hi @tonycody, again, please chat to us on slack before opening an issue here. This is in accordance with the contributing guidelines and the template that you deleted.

We don't do anything with the Tomcat binary besides unpack it on your machine. Consider raising this with the Tomcat team who provides this binary.
