### ISSUE TITLE
Feature: List AdoptOpenJDK Jdks for uninstallation

### ISSUE THREAD

**Issue by KevinAtSesam** [sdkman/sdkman-cli#979]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**
With the migration from AdoptOpenJDK to Eclipse Adoptium, the JDK versions from AdoptOpenJDK are no longer available for installation. So far, so good, but since they're no longer listed at all, you also can't easily see what identifier you must use to uninstall the deprecated runtime.

I tried a few things until I just used the folder name in `~/.sdkman/candidates/java/`, which lead to:
```
$ sdk uninstall java 11.0.11.hs-adpt
```

So perhaps, keep showing the installed-but-deprecated JDKs so it's easier for people the migrate.

---

Addendum; The example at the bottom of `sdk list java` still uses adpt so you better also change that.

**Comment by CXwudi** [comment]
Confirmed that AdoptiumJDK 17 is out. And AdoptOpenJDK is no longer updating

**Comment by Adriankhl** [comment]
A relevant issue: last time when I did `sdk install java` it defaults to AdoptOpenJDK, but it should now default to `Temurin`.

**Comment by marc0der** [comment]
@Adriankhl Temurin 17.0.0 was made the default version when I made the announcement last week.
