### ISSUE TITLE
Bug: Bash completion for install/list does not return all candidates

### ISSUE THREAD

**Issue by ches** [sdkman/sdkman-cli#992]
**Bug report**

For the `install` and `list` commands, candidate completions return:

- Only the first candidate, if you have entered no prefix yet
- No completions, if you enter a prefix

This is also true for version number completions of `sdk install <candidate>`, for the same root cause.

I'll have a PR with a proposed fix shortly.

**To reproduce**

Use SDKMAN! in a Bash shell with `sdkman_auto_complete=true`, and try Tab-completing as follows:

```
$ sdk install <TAB>
$ sdk install activemq
# => Should suggest all candidates

$ sdk install jav<TAB>
$ sdk install jav
# => (No suggestions). Should complete "java"

$ sdk install java <TAB>
$ sdk install java 11.0.11.hs-adpt
# => Should suggest all versions
```

**System info**

```
$ uname -msrv
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

$ bash --version | head -1
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)

$ sdk version

SDKMAN 5.12.4
```

**Comment by helpermethod** [comment]
Hi @ches,

funny enough, the current version works fine for me

![image](https://user-images.githubusercontent.com/1562019/136539745-fcbfaf3a-7664-4383-962d-36f67298ad20.png)

I'm also on Mac (x86_64) and use the exact same Bash version as you.

**Comment by marc0der** [comment]
No rush! BTW, this is a preemptive step to adding the new `libexec` folder for native binaries 😬

**Comment by helpermethod** [comment]
Thanks for contributing!
