### ISSUE TITLE
Bug: Cannot install the latest Micronaut (3.1.0)

### ISSUE THREAD

**Issue by musketyr** [sdkman/sdkman-cli#996]
**Bug report**
I want to install the latest Micronaut on my machine but when I run `sdk install micronaut` I got the following result:

```
Stop! micronaut 3.1.0 is not available. Possible causes:
 * 3.1.0 is an invalid version
 * micronaut binaries are incompatible with your platform
 * micronaut has not been released yet

Tip: see all available versions for your platform:

  $ sdk list micronaut
```

Listing the Micronaut versions only shows the 2.x and 1.x versions:

```
================================================================================
Available Micronaut Versions
================================================================================
     2.0.0.RC1           1.2.10              1.1.2               1.0.0.RC1      
     2.0.0.M2            1.2.9               1.1.1               1.0.0.M4       
     2.0.0.M1            1.2.8               1.1.0               1.0.0.M3       
     1.3.7               1.2.7               1.1.0.RC2           1.0.0.M2       
     1.3.6               1.2.6               1.1.0.RC1           1.0.0.M1       
     1.3.5               1.2.5               1.1.0.M2                           
     1.3.4               1.2.4               1.1.0.M1                           
     1.3.3               1.2.3               1.0.5                              
     1.3.2               1.2.2               1.0.4                              
     1.3.1               1.2.1               1.0.3                              
     1.3.0               1.2.0               1.0.2                              
     1.3.0.RC1           1.2.0.RC2           1.0.1                              
     1.3.0.M2            1.2.0.RC1           1.0.0                              
     1.3.0.M1            1.1.4               1.0.0.RC3                          
     1.2.11              1.1.3               1.0.0.RC2                          

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
```

My SDK config is:

```
sdkman_auto_answer=false
sdkman_auto_selfupdate=false
sdkman_insecure_ssl=false
sdkman_curl_connect_timeout=7
sdkman_curl_max_time=10
sdkman_beta_channel=false
sdkman_debug_mode=false
sdkman_colour_enable=true
sdkman_auto_env=false
sdkman_rosetta2_compatible=false
sdkman_auto_complete=false
sdkman_selfupdate_enable=true
```

**To reproduce**
Run `sdk install micronaut` with the settings above in the environment described below.

**System info**
* `Darwin mcmini 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64`
* `zsh 5.8 (x86_64-apple-darwin20.0)`
* `SDKMAN 5.12.4 `

**Comment by ilopmar** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/559192/136920130-171c30fa-2b48-4630-a8be-222e0034da48.png)


I'm on Linux, though. I'll ping the team so a Mac user can try it.

**Comment by marc0der** [comment]
> There is no information about the supported architecture in the Available Java Versions table.

Could you clarify what that means? You should be seeing all the standard Mac JDKs running through the Rosetta 2 compatibility layer.

**Comment by musketyr** [comment]
Not really for Java 8 I had to stick with for a while due Grails 4 😄 

Sadly following command does not work as expected - still not showing the latest Micronaut when the default config has the Rosseta 2 disabled.

```
sdkman_rosetta2_compatible=true sdk ls micronaut
```

**Comment by joergrech** [comment]
It looks like I have the same problem when trying to install groovy on a raspberry pi image using Docker. The following worked a week (Oct. 3rd) ago but breaks now:
```bash
# Install groovy
RUN curl -s https://get.sdkman.io | bash
RUN chmod a+x "$HOME/.sdkman/bin/sdkman-init.sh"
RUN bash -c -l "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install groovy"
```
now I get the error:
```bash
#11 4.496 Stop! groovy 3.0.9 is not available. Possible causes:
#11 4.498  * 3.0.9 is an invalid version
#11 4.499  * groovy binaries are incompatible with your platform
#11 4.500  * groovy has not been released yet
```
NOTE: `sdk list groovy` lists 3.0.9 and trying to install any version such as 3.0.1 does not work either.

Please note that this is caused when running 'docker buildx build --platform linux/arm/v7' - it works on `linux/amd64`

**Comment by timyates** [comment]
@marc0der does 👆 look sensible? I believe there's a new channel `MAC_ARM64` for arm based macs

**Comment by timyates** [comment]
It's merged, we'll see if I was right next release 🤞😁🤞

**Comment by marc0der** [comment]
Hey @timyates! Yes that's right. You can publish binaries for silicon mac to `MAC_ARM64` :+1: :grin:

**Comment by marc0der** [comment]
Closing this for now as:
1. it works using Rosetta 2 compat mode
2. new binaries will be published under `MAC_ARM64` going forward
